### ISSUE TITLE
Lord of Khorne -Monstrous Strength skill has wrong icon for an effect

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#10]
https://discord.com/channels/373745291289034763/581350140942483456/1012008339544211576

![image](https://user-images.githubusercontent.com/39225561/186760804-35edeca8-c947-426e-ab8b-901d3112139a.png)

**Comment by chadvandy** [comment]
Fixed - zzz_cbfm_effect_reverse

**Comment by Harmandodelavega** [comment]
Fixed by CA and deleted
