### ISSUE TITLE
Sister of twilight can not add ancient treemen to the office

### ISSUE THREAD

**Issue by yliu267** [chadvandy/cbfm_wh3#1001]
Hello, using this mod will make it unable to add the Ancient Treemen Lords to Court of the Mage Queen (the office) when playing sister of twilight.

Game only with this mod:
![屏幕截图(1)](https://github.com/chadvandy/cbfm_wh3/assets/133838441/21067ed4-8e20-45b9-850f-80ff3471ce67)

Game without any mod:

![屏幕截图(2)](https://github.com/chadvandy/cbfm_wh3/assets/133838441/3c87add2-60a5-4cad-88cd-9afeb49fb161)

**Comment by Bogdanov89** [comment]
This is intended, the Court of the Mage-Queen is only for the Elves.
Treesingers are only elves, Isha Kurnous Loec are Elven gods.

Same how the treemen "offices" are only for the treemen.

![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/4a2bf5f7-1dd8-421b-882f-4ce3a480d8ca)
