### ISSUE TITLE
Rites Available from Turn 1

### ISSUE THREAD

**Issue by AMJ1993** [chadvandy/cbfm_wh3#1002]
**Describe the bug**
All Rites are available from Turn 1 for use for all Factions with Rites.

**Expected behavior**
Rites have an initial cooldown and are not all available from Turn 1.

**To Reproduce**
1. Start a New Campaign as the  Lizardmen, Skaven, High Elves, Dark Elves, Tomb Kings, Vampire Coast.
2. Bring up the Rites Screen, Hit "9"
3. All rites will be available from Turn 1.

**Additional context**
Problem was introduced in 3.0 and is documented as a Known Issue in the Official Total War Forums.

**Comment by Cataph** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/923
