### ISSUE TITLE
Beastmen herdstones cause permanent debuffs/attrition in nearby provinces even after they are destroyed

### ISSUE THREAD

**Issue by ChrisThwaites92** [chadvandy/cbfm_wh3#1003]
Beastmen herdstones cause permanent debuffs/attrition in nearby provinces even after they are destroyed. One example being a herdstone was active in Castle Bastonne, and after it was destroyed all adjacent provinces continued to suffer from the negative effects of the herdstone. In one savegame I had, the effects were still present 20 turns later.

1. Play as anyone
2. Wait for the beastmen to create a herdstone with a debuff building such as 'rucking pits'
3. Destroy the herdstone
4. Notice the debuffs still affect nearby provinces

**Screenshots**
![20230522130238_1](https://github.com/chadvandy/cbfm_wh3/assets/77809512/68373d58-7e0d-44a6-81e3-fe6d63444d27)
![20230522130345_1](https://github.com/chadvandy/cbfm_wh3/assets/77809512/90558f34-ccae-40c2-8d67-1cba9a96318b)
![20230522130418_1](https://github.com/chadvandy/cbfm_wh3/assets/77809512/3b622fc2-e94d-4568-82ce-7f72124b1709)
![250282275-2155fd91-682b-43ff-8eaf-a0e9ef350284](https://github.com/chadvandy/cbfm_wh3/assets/66144788/0de0cdc8-4f22-4e56-9c49-569480d59324)
![250282300-b632b6cf-7da4-47e1-a225-d2681140030e](https://github.com/chadvandy/cbfm_wh3/assets/66144788/24cc3b8d-15af-444f-9896-e63520a14d4f)

**Additional context**
One user of TWforums suggested that razing the herdstone instead of occupying the settlement makes the problem go away, though this is unverified, and in addition the AI occupynig the herdstone settlement will also cause the issue.

I used the console command mod to abandon the settlements the AI controlled that previously had the herdstone in it, and this didn't fix the problem.

**Comment by Harmandodelavega** [comment]
supposedly fixed by CA in 4.2
