### ISSUE TITLE
Nakai can't recruit kroxigors

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1004]
https://www.reddit.com/r/totalwar/comments/13rl4bm/_/

**Comment by Bogdanov89** [comment]
I dont know is this needed, my apologies if it is not.
Info related to this Nakai issue which is affecting more than just kroxigors.

![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/47ce6713-aa1d-4c91-8d84-6f185c7d3ba7)

**Comment by Cataph** [comment]
https://discord.com/channels/373745291289034763/581350140942483456/1111545711385903125

fix adds Nakai units back to the military grouping but hides them from tooltip generation to avoid duplicates, which I can only assume was the very distant original intention.
