### ISSUE TITLE
WoC red line daemonic cavalry units get double buffs

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1005]
https://www.reddit.com/r/totalwar/comments/13rlohd/new_patch_new_bugs/

**Comment by Harmandodelavega** [comment]
@mfvreeland how exactly does this fix double dipping?

**Comment by mfvreeland** [comment]
@Harmandodelavega It removes Bloodcrushers from the unit set that gets the non-daemonic buffs. I tested this fix and it worked for me. Have you observed differently?

**Comment by Harmandodelavega** [comment]
my bad forgot you could exclude through unit sets
