### ISSUE TITLE
Bretonnia throths not progressing

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1006]
https://www.reddit.com/r/totalwar/comments/13rnmiu/damsels_vows_doesnt_progress_she_is_rank_6_took/

**Comment by Cataph** [comment]
From what I can see, those vows and pledges need to be present in `script/campaign/main_warhammer/wh_dlc07_vows.lua`. 
wh_dlc07_trait_brt_protection_troth_chivalry_pledge_agent
wh_dlc07_trait_brt_protection_troth_knowledge_pledge_agent
wh_dlc07_trait_brt_protection_troth_order_pledge_agent
are not in there.
