### ISSUE TITLE
Phoenix Guard's Voice Lines Won't Play

### ISSUE THREAD

**Issue by TheDeathby2** [chadvandy/cbfm_wh3#1012]
Whenever you click on a unit of phoenix guard, or send them to battle, their voice lines won't play.
Affects both regular and regiment of renown variant. 

**To Reproduce**
1. Play as high elf faction in skirmish v. AI
2. Choose a unit of phoenix guard
3. Load into battle
4. Click on unit of phoenix guard and notice the apparent silence

**Comment by floskan** [comment]
Phoenix Guard doesn't talk, lore thing

**Comment by mfvreeland** [comment]
As @floskan said, this is by design.
