### ISSUE TITLE
Landmark in pigbarter for Nurgle only gives regen to base rotflies, not plague drones

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1018]
"Game version 3.1.0 (latest patch on steam)

Playing as Nurgle, I own the Landmark in city "Pigbarter" in the Dark Lands. Building provides:

Passive ability: "Regeneration" for Rot Flies units (factionwide).

This works as intended for units called Rot Flies, but does not work for the more advanced versions of the same units called "Plague Drone of Nurgle". In the tooltip for this unit, it even mentions they are Rot Flies just more advanced versions. Yet building does not provide "Regeneration" for any type of Plague Drone.

It might be working as intended (if it does, in my opinion it is wrong and it should affect all units). Or it might be an oversight. I hope it is the latter.

Hope this helps! " 

I'll add a PR for this, up to you guys if it's within scope or intended

**Comment by mfvreeland** [comment]
After discussion on Discord and further review, I don't think we have enough info to say for sure whether or not this is a bug.
