### ISSUE TITLE
Kholeks lord trait doesn't give 10% missile resistance to Dragon ogres and shaggoths

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#103]
Kholeks lord trait here
![20220903202431_1](https://user-images.githubusercontent.com/34427023/188283538-4837519c-fa17-424f-bd07-8abc248528a7.jpg)

It correctly gives chaos trolls missile resistance

![20220903202438_1](https://user-images.githubusercontent.com/34427023/188283563-14aebc9f-c93f-4d89-8b7a-9e599be5dcef.jpg)

But dragon ogres just has the missile resistance from scaly skin.

![20220903202442_1](https://user-images.githubusercontent.com/34427023/188283577-347f8f82-2665-455f-a5c4-5715b8b9897d.jpg)

**Comment by floskan** [comment]
chs_dragon_ogre_shaggoths and chs_dragon_ogres needs to be added to wh3_dlc20_effect_force_stat_missile_resistance_monstrous_infantry_monsters_units

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed Kholek’s Lord trait not applying missile resistance to Dragon Ogre units."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.

**Comment by floskan** [comment]
> Confirmed fixed in 4.1.

I'll start removing fixed stuff, i appreciate these comments
