### ISSUE TITLE
Grail Knights/Guardians use large mount entity size instead of medium

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#1044]
wh_main_brt_mnt_cavalry_knights_heavy_blood is using the same entity size as rhinoxes used by crushers rather than of similar cavalry units like juggernaut-mounted stuff, which is medium.
notice, not entity type, and not rider data, which is irrelevant.

This entity size causes Grail Knights and Guardians to walk over infantry, which is both inconsistent with similar super heavy pseudo-monstrous cavalry and a major balance problem, and this was arguably not tested in the slightest since it lets them overpower their hard counters (elite halberd infantry).

https://www.reddit.com/r/totalwar/comments/13sro5s/so_it_looks_like_grail_knights_can_just_push/
https://youtu.be/LKdUUoML3BA?t=366 (note on this video: I heavily disagree that bracing stuff should be given attack orders to be effective, this goes against common sense of anvil behaviour not needing micro to face their hard-countered foe in their best situation)

I fully expect people to decry that they like it this way.

Pack is in here: https://discord.com/channels/373745291289034763/581350140942483456/1113051274447962162

**Comment by mfvreeland** [comment]
Evidently intended.
