### ISSUE TITLE
Tier-2 anti-Skaven/Corruption/Plague buildings cost more than the Tier-3 ones

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1048]
"Tier-2 anti-Skaven/Corruption/Plague buildings cost more than the Tier-3 ones. So it goes 3000-2000-3000 instead of 1000-2000-3000.

Think that’s been the case for every faction I’ve tried. "

https://www.reddit.com/r/totalwar/comments/13vnoc2/total_war_warhammer_iii_update_31_bug_thread/jm6vk4v/

**Comment by mfvreeland** [comment]
It should be consistent, at least. Given what WilliamCA said over on Discord, I believe we should change any factions that don't follow the high-mid-high cost structure to match that.

**Comment by floskan** [comment]
On it

**Comment by mfvreeland** [comment]
Marking closed since we were wrong about the original bug, but added a different fix based on CA's explanation.

**Comment by Harmandodelavega** [comment]
my bad was looking at building effects
