### ISSUE TITLE
Slaanesh leadership trait "Intoxicating Presence" doesn't work on heroes

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1050]
![Skärmbild 2023-05-19 131420](https://github.com/chadvandy/cbfm_wh3/assets/34427023/ba2c941c-de53-4eea-944a-acb456fad228)

**Comment by floskan** [comment]
> 

Only Alluress heroes can receive it but i can add it in just in case

**Comment by Cataph** [comment]
ah nah it's aight, if you're certain only they can get it.
