### ISSUE TITLE
Buried treasure Chain doesn't impact payout from vampirate money rite

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1053]
![Screenshot_2023-05-31-00-16-03-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/chadvandy/cbfm_wh3/assets/34427023/0a9441a4-9dbd-4a0c-8e15-481797f3d443)
![Screenshot_2023-05-31-00-10-38-20_82e8fffdeaf74f9acf1f7052087df811](https://github.com/chadvandy/cbfm_wh3/assets/34427023/15316aa9-f026-44b6-aef1-00df18f5a2dd)

**Comment by Harmandodelavega** [comment]
Tentigers posted screenshot saying it's working
