### ISSUE TITLE
Dark diplomacy not working for certain WoC factions 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1059]
[Screenshot_2023-06-02-13-13-38-99_572064f74bd5f9fa804b05334aa4f912](https://github.com/chadvandy/cbfm_wh3/assets/34427023/abadf9a6-40d5-40dd-abc8-246e29da2597) not sure if true

**Comment by SergeantPepper1** [comment]
I am OP, I tested in-game and if there is any relations change for this tech, it doesn't show up on the Diplomacy panel for faction. It's turn 8 in the campaign.

![BeLakor relations](https://github.com/chadvandy/cbfm_wh3/assets/123917130/58be2eff-82b0-41a0-8a5e-426f5a6c2f34)
![Dark Diplomacy achieved](https://github.com/chadvandy/cbfm_wh3/assets/123917130/2d0805e4-6f20-44dc-96aa-65725105e745)

**Comment by SergeantPepper1** [comment]
Here is a screenshot showing the undivided gift as well.
![image](https://github.com/chadvandy/cbfm_wh3/assets/123917130/54b84e3a-1240-437b-be1e-f1a7e4295fce)

**Comment by mfvreeland** [comment]
Previously fixed
