### ISSUE TITLE
Oxyotl's silent sanctums dont have structures or build options in the Chaos dwarf settlements

### ISSUE THREAD

**Issue by SteelDragony** [chadvandy/cbfm_wh3#1061]
**Describe the bug**
When placing a silent sanctum in the stonesky foothills it spawns without the unearthed sanctum and with no build options showing.
(I tested both Granite Spikes and The Volary, didnt have vision on fortress of Eyes but assume that one is also affected)

**Expected behavior**
Silent sanctum spawing with unearthed sanctum and regular build options

**To Reproduce**
1. Load provided savegame
2. place silent sanctum in Granite spikes or The Volary
3. No Build options available

**Screenshots**

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**
[Auto-save (Legendary).Ghosts of Pahuax.03062023.0056352389076576.save.zip](https://github.com/chadvandy/cbfm_wh3/files/11643299/Auto-save.Legendary.Ghosts.of.Pahuax.03062023.0056352389076576.save.zip)

**Comment by SteelDragony** [comment]
The Volary got captured by the Puppets of Misrule and now the secret sanctum can construct buildings.
I tried another chaos dwarf controlled settlement and it had the same problem, so I think it is any chaos dwarf controlled settlement that is the problem.

**Comment by MarinoBrundu** [comment]
I found what appears to be the issue and I'm working on a fix.

**Comment by mfvreeland** [comment]
@MarinoBrundu Did you find while fixing this that Chaos cultist buildings weren't working in Chorf settlements as well? Also, have you tested this fix? Thanks for submitting it.

**Comment by MarinoBrundu** [comment]
@mfvreeland Yes, I also checked the chaos cults and they also weren't linked in that table. I tested the silent sanctums and they work now. I have added the chaos cults in the table as well, but haven't been able to test them because I don't have a save file available with any of the cults in chorf territory.

**Comment by floskan** [comment]
Removed from main
