### ISSUE TITLE
Chorf warmachines don't benefit from Zhatan's defeat trait

### ISSUE THREAD

**Issue by Inquisitor-no-5** [chadvandy/cbfm_wh3#1062]
Bug:
Only Hellcannon/Hellcannon RoR benefit from +15% artillery range from Zhatan's defeat trait.

Expectation
Warmachine artillery getting +15% range as well.

1. Play as Astragoth/Drazoath
2. Defeat Zhatan the Black with a lord.
3. Check the range of a piece of warmachine artillery in that lord's army.

Screenshots:
![20230603173929_1](https://github.com/chadvandy/cbfm_wh3/assets/135509302/a6dc9b70-b45d-4fee-a7d8-5e79baf7b806)

Additional context:
Saves pre- and post obtaining the trait exist, but got rejected due to file type.

**Comment by floskan** [comment]
Did we talk on discord earlier? It does work.

**Comment by floskan** [comment]
> Nah, that would have been someone else, I don't really do Discord.
> 
> Checking in-game, if the range increase applies it doesn't show on the unit card. I'd expect a Dreadquake Mortar to have ≈67 additional range listed, which it doesn't.
> 
> And maybe it's working as intended, but I'd expect that something labeled "Siege Artillery" would count as artillery.

It's weird with when it works but it's linked to all artillery in game. When you got the trait, did you wait until you passed the turn or played a battle before you looked again if it worked ? Because some traits are slow to activate.

**Comment by Inquisitor-no-5** [comment]
> It's weird with when it works but it's linked to all artillery in game. When you got the trait, did you wait until you passed the turn or played a battle before you looked again if it worked ?

I've both fought at least one battle and passed 20-ish turns. 

If I check the ranges of Hellcannons vs War Machine artillery, it's included on the unit card for the Hellcannons (they outrange Dreadquake Mortars), but not the War Machines, so the trait seems to be applying, just not to everything it should.

Checked both Vanilla and with just CBFM enabled, range values remain the same.

>Because some traits are slow to activate.

What? That's wild.

**Comment by floskan** [comment]
Ok, it seems something's off with his trait now that i looked into it. Will drop you a pack for testing

**Comment by floskan** [comment]
[zhatandefeat.zip](https://github.com/chadvandy/cbfm_wh3/files/11668586/zhatandefeat.zip)

Try this if you could
