### ISSUE TITLE
Nakai secondary lord unit recruitment duration inconsistencies (even with CBFM)

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1064]
**Describe the bug**
There was an issue on this topic before (https://github.com/chadvandy/cbfm_wh3/issues/329) and it resulted in a bug fix from CBFM but there still seem to be glaring inconsistencies (even with CBFM) with Nakai secondary lord buildings that reduce the global recruitment duration for all LM units for secondary lords.
Screenshot provides more info but to summarize even with CBFM the secondary lord recruitment durations (with maxed out military buildings) are still all over the place, with some tier 5 units recruiting in one turn and some tier 3 units taking three turns to recruit.
Some examples of secondary lord global recruitment (with maxed secondary lord buildings):
- Cold Riders (Spears) take 2 turns to recruit (same tier as regular Cold Riders which take 1 turn to recruit).
- Feral Stegadon (tier three) takes 2 turn recruit, while the tier five Ancient Stegadon & tier four Stegadon take 1 turn.
- Bastiladon (ark of sotek) is just tier two and takes 2 turns to recruit, while the same tier Feral Bastiladon recruits in 1 turn.
- 
- Stegadon (Engine of the Gods, tier four) takes 3 turns to recruit, but Ancient Stegadon (tier five) and Stegadon (tier four) takes 1 turn.
- Feral Dread Saurian takes 3 turns to recruit but the more expensive Dread Saurian takes 2 turns to recruit.
- Kroxigors and Sacred Kroxigors (the centerpiece of nakai faction) take THREE turns to recruit, which is unheard of for a tier 3 unit.

**Expected behavior**
If we are to assume some logical design was intended then unit global recruitment duration should probably remain consistent between unit types & tiers (after the secondary lord has upgraded buildings).
Tier five units like Feral Carnosaur, Feral Troglodon & Ancient Stegadon taking just 1 turn to recruit, while much lower tier units like Kroxigors taking three times as long makes absolutely no sense.
Frankly i am not sure how it should be - _perhaps (when secondary lord is fully upgraded) tier three should take 1 turn global recruitment, tier four should take 2 turns and tier five should take 3 turns?_

**To Reproduce**
1. Play Nakai faction with CBFM enabled
2. Recruit secondary lord and max out his army recruitment duration reducing buildings
3. Check and compare how long various global recruitment on the secondary lord takes (with maxed out secondary lord army buildings)

**Screenshots**

![units with buildings maxed out](https://github.com/chadvandy/cbfm_wh3/assets/55892027/70c29e48-223a-4254-97fa-446bbee9d40e)

![buildings and unit tiers reference](https://github.com/chadvandy/cbfm_wh3/assets/55892027/3cce9c82-44cd-4dde-b6a3-9ffa23849a13)

**Additional context**
First picture shows all unit recruitments on a secondary lord with maxed out buildings and with CBFM
Second picture shows secondary lord buildings and nakai tech tree as a reference.

**Comment by Harmandodelavega** [comment]
Not bugs
- Cold Riders (Spears) take 2 turns to recruit 
- Bastiladon (ark of sotek)  takes 2 turns to recruit
- Stegadon (Engine of the Gods, tier four) takes 3 turns to recruit (for some reason they decided it should take 3 and not 2 turns)

Bugs
- Ancient Stegadon (tier five) and Stegadon (tier four) take 1 turn.
- Dread Saurian takes 2 turns to recruit.
- Kroxigors and Sacred Kroxigors  take THREE turns to recruit

**Comment by Bogdanov89** [comment]
By that logic the tier 1 recruit time Feral Carno (t5), Feral Trog (t5) & perhaps Ancient Salam (t4) should take more than 1 turn.

**Comment by Harmandodelavega** [comment]
You didn't tell me about Carno/Trog
There is no logic, those are the base recuitment times which get doubled since it's global recruitment and then reduced by the buildings
Sally is intentional
