### ISSUE TITLE
Characters getting stuck into each other 

### ISSUE THREAD

**Issue by LordOmlette** [chadvandy/cbfm_wh3#1069]
HV edit:[Heroes respawning on top of armies/settlements after their faction re-emerges prevent interaction with both indefinitely on WH2 | Trello ](https://trello.com/c/DB2qNNwd/764-heroes-respawning-on-top-of-armies-settlements-after-their-faction-re-emerges-prevent-interaction-with-both-indefinitely)

**Describe the bug**
In `script/campaign/mod/zzz_cbfm_stuck_characters_fix.lua`  the condition for whether the character should be evaluated as being stuck is catching characters who are either not on the map or in the middle of being teleported.  Empire generals spawned for the invasion dilemmas could inadvertently get caught up in the filter even though they are not stuck. This means the player can spend the gold and/or prestige to defend the settlement but doesn't get to fight the battle.

**Expected behavior**
This script should only affect stuck characters.

**To Reproduce**
1. Play as Empire
2. Keep going until at least one character somewhere gets stuck.
3. When you next trigger an invasion dilemma, choose to defend the settlement (either gold or prestige).

**Save Files**

I can't reproduce this in an unmodded (no mods except CBF) campaign.

I believe adding a single extra condition to the filter should fix this:
```
                if (
                    (characterCurrent:is_wounded() == false) and
                    (characterCurrent:character_type("colonel") == false) and
                    (characterCurrent:has_garrison_residence() == false) and
                    (characterCurrent:is_embedded_in_military_force() == false) and
                    (characterCurrent:logical_position_x() ~= 65535)
                ) then
```
This should be safe, because if a character's position is 65535 then they're not on the map and/or being teleported.  Either way, they're not stuck.

**Comment by Harmandodelavega** [comment]
@mfvreeland

**Comment by mfvreeland** [comment]
Thanks for the report. We will remove this.

**Comment by Harmandodelavega** [comment]
#993

**Comment by FiftyTifty** [comment]
Nobody reported any issues in my mod page for the standalone fix, and I've added the position check. If there are other potential cases where it causes issues, it'd be good to actually know what those are. I haven't encountered any as Cathay, Dark Elves, Beastmen, or Chaos Dwarves.

**Comment by mfvreeland** [comment]
#1086 ?

**Comment by FiftyTifty** [comment]
Ooh, that's interesting. I'll see if I can get to a Sea Lane in my campaign and test.

**Comment by FiftyTifty** [comment]
I made an update to the script which checked for sea lanes. Is there anything about those events and dilemmas that can be checked for?

**Comment by mfvreeland** [comment]
I'm not sure, but I believe this fix should stay standalone regardless. There are too many potential instances where it could cause an issue, both now and with new content drops going forward (anytime CA adds a new teleport-like mechanic for a faction, this would need to be re-evaluated).

**Comment by FiftyTifty** [comment]
On the other hand, that's true already for the bug fixes. What with even minor version updates causing crashes

**Comment by mfvreeland** [comment]
Yes, but 99% of the time those update-induced crashes are due to table format updates, which are simple to fix in RPFM; there is no investigation or script changes required.
