### ISSUE TITLE
Crone hellebron on cauldron similar damage issue as pump wagons

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1070]
https://www.reddit.com/r/totalwar/comments/1439wg8/crone_hellebron_got_the_pump_wagon_bug_too/

**Comment by allenhu0912** [comment]
Hellebron in my current campaign and in a custom battle I just ran for a test (Cauldron vs Dwarf Warriors and a Lord) seemed pretty normal.

**Comment by mfvreeland** [comment]
This was fixed by CA in 4.0
