### ISSUE TITLE
One of Cult of Sotek's sacrifices still gives +8 untainted instead of -corruption

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1071]

**Comment by Bogdanov89** [comment]
i think this is the one in question

![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/29584a41-cdfc-4191-9d37-d7e2636441f9)

**Comment by Drazhir2** [comment]
The correct effect is applied
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/6e3f32e4-13ab-45f5-8e62-cf9ffb62f056)

It's just a display issue from the loc file
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/bb6128ce-0322-4906-aaa6-e83f67dcb5f4)

**Comment by floskan** [comment]
Removed from main
