### ISSUE TITLE
Redundant hero embed effects don't always prioritize the highest rank

### ISSUE THREAD

**Issue by NormanTheNorthman** [chadvandy/cbfm_wh3#108]
If I have two heroes that provide XP per-hour, my lord's army will gain XP based on the last hero to join the army, not by whichever one has the highest value. 

I wonder if this is how it is supposed to be? And are all of the 'Hero's Army' bonuses being improperly added just because one isn't paying attention to the order that they added the Hero to the army?

**Comment by Harmandodelavega** [comment]
I think it's actually the last embedded hero that had it's items/skill tree messed with, still a bug

**Comment by mfvreeland** [comment]
Pretty sure we can't fix this.

**Comment by mfvreeland** [comment]
Can't be fixed.
