### ISSUE TITLE
Vampire Coast treasure riddlesgive you the answer/zoom in to the spot

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1080]
https://www.reddit.com/r/totalwar/comments/13v9kc2/vampire_coast_treasure_riddles_are_meaningless/

**Comment by Drazhir2** [comment]
This is a CA design choice, before you could click the magnifying glass and be taken to the exact spot, now you have an icon on the exact spot. Same functionality with one step less.

I don't think this is cbfm material.

**Comment by Harmandodelavega** [comment]
> This is a CA design choice, before you could click the magnifying glass and be taken to the exact spot, now you have an icon on the exact spot. Same functionality with one step less.
> 
> I don't think this is cbfm material.

I guess it was bugged in wh2 too then

**Comment by Drazhir2** [comment]
If someone doesn't agree with CA's choice on how it should work doesn't mean it's a bug. Thankfully there are mods for people that don't agree with CA. Doesn't mean it should be changed by cbfm.

**Comment by floskan** [comment]
Didn't it just zoom into the general area? You never knew exactly where it was.

**Comment by Harmandodelavega** [comment]
> Didn't it just zoom into the general area? You never knew exactly where it was.

I spent a good deal of time figuring these out, so I either didn't notice or you're right, anyways we could check WH2

**Comment by Drazhir2** [comment]
I tested it, it moves to the exact location in wh2 as well, put your LL center screen after pressing the zoom to location button, dig, enjoy your treasure.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/6deb2ec2-2e14-4eb0-ae7f-6ccf94adb224)
