### ISSUE TITLE
Sea lanes send armies to the middle of the map with this mod is enabled.

### ISSUE THREAD

**Issue by ihasson** [chadvandy/cbfm_wh3#1086]
**Describe the bug**
Sea lanes send armies to the middle of the map when entered with this mod is enabled.

**Expected behavior**
Entering sea lanes sends armies to the other end of the sea lane as in vanilla.

**To Reproduce**
1. I was able to get this with Cylostra's faction and Maliketh's faction.
2. The easiest sea lane to use is the one near Naggarond.
3. Send a lord or hero into the sea lane.
4. End turn. 
5. When you get the Journey complete message your army or hero will be standing next to Deff Gorge. 

![20230603192631_1](https://github.com/chadvandy/cbfm_wh3/assets/8249716/7f10a9c7-d285-4135-a74a-b46bc174cedf)

**Comment by mfvreeland** [comment]
Can you try this again since our (very recent) last update? I am assuming this was probably being caused by the stuck units fixed, which has since been removed.
