### ISSUE TITLE
Killing Fire (Lore of Hashut passive) only lasts for one second in 3.1

### ISSUE THREAD

**Issue by mfvreeland** [chadvandy/cbfm_wh3#1088]
Evidently, CA checking the box for "Update Targets Every Frame" broke this ability, but it is unclear why. The workaround is to revert this change until CA can come up with a code fix.

**Comment by Harmandodelavega** [comment]
needs testing without this fix to see if they fixed it someway else in 4.0

**Comment by Drazhir2** [comment]
tested in skirmish, killing fire still only does one tick of damage

**Comment by Drazhir2** [comment]
still not fixed in 4.1.1
