### ISSUE TITLE
Coeddil "Changing Nature" skill not working (CA confirmed bug)

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1091]
**Describe the bug**
Coeddil skill Changing Nature is bugged, it does not lower the cost of changing Aspects.
CA confirmed as bug on the forum link below.

**Expected behavior**
Skill reducing the cost of aspects.

**To Reproduce**
1. Get Coeddil (wood elf hero)
2. Skill changing nature does not reduce aspect costs.

**Screenshots**
https://forums.totalwar.com/discussion/332609/coeddil-changing-nature-not-working-coeddil-cannot-leave-an-army-and-join-an-army-on-same-turn
![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/17fcdc03-9c2e-4bb9-93bd-b329c8644fa2)

**Additional context**
Thread also mentions that the hero can not leave n join an army in the same turn but CA explained that part is intended.

**Comment by floskan** [comment]
How do we fix this one? I couldn't manage do to anything with the effect connected to the skill

**Comment by floskan** [comment]
This skill works. It's just the UI that's slow to update @Bogdanov89
