### ISSUE TITLE
Heinrich Kemmler's trait that provides 'horrible regeneration" does not work on normal hexwraiths (at least when confederated). I am using 1 button respec mod, but have not encountered any similar issues. 

### ISSUE THREAD

**Issue by Disturbed78** [chadvandy/cbfm_wh3#1094]
![Screenshot (2)](https://github.com/chadvandy/cbfm_wh3/assets/136261006/a0b7ff8c-71f6-4870-af6e-27e365a3b214)
![Screenshot (1)](https://github.com/chadvandy/cbfm_wh3/assets/136261006/53ebcd39-3028-4b3b-b4ad-aab879c16182)
**Describe the bug**

**Expected behavior**

**To Reproduce**
1. Play as XYZ
2. Attack region ABC
3. Choose QWE
4. Experience crash/bug

**Screenshots**
If applicable, add screenshots to help explain your problem. The more in-game text we can see to reference the details in question, the better.

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**

**Comment by floskan** [comment]
Look at the tooltip. It applies to rank 7 and above
