### ISSUE TITLE
Public Order/Control tooltips show unnecessary text.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1098]
**Describe the bug**
Public Order/Control tooltips show unnecessary text, such as repeating lines or 0% bonuses.
Noticed on Kroq'gar IE campaign with CBFM enabled.

**Expected behavior**
Tooltip text not repeating, and 0% bonuses not shown.

**To Reproduce**
1. Play as Krog'gar
2. Mouse over the public order/control bar for a province see the tooltips

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/6e54f06f-6013-466c-8ea1-0fe395a09279)

**Additional context**
Not sure what part of this is a vanilla issue and/or what could be caused by an existing fix from CBFM.

**Comment by Drazhir2** [comment]
Vanilla is fine, this is a CBFM issue, removing the 4 populace bundles here fixes the issue:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/8697feb5-6d1b-428e-b121-b5027b28ad2a)

The next question is which issue was warbandmerc_reccostdiscount fixing? I'd guess one of these:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/77b95ce5-0cdd-4f79-be97-a89a93611ace)

Maybe the datafile names should be added to the issues when a fix is submitted to easily make the link between the 2 ?

**Comment by allenhu0912** [comment]
Playing as Franz/Gelt, the Hochland elector count bonus also has this issue, +10% campaign movement is listed twice.

**Comment by Drazhir2** [comment]
The double movement range on Hochland is a vanilla issue, not relevant to this one.
