### ISSUE TITLE
Various Giant units have attack & animation issues.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1099]
**Describe the bug**
I encountered a mod that seems to do some fixes for the various Giant units (greenskin, beastmen, chaos etc) attacks, such as:

- Giant breath and stomp attacks happened only rarely because the maximum target size is set to a very small entity (currently only spider hatchlings).
- CoC DLC added a new breath attack effect for the Nurgle Giant, but instead made all of the Giant breath attacks invisible except for the Chaos Giant.

The first point seems particularly odd and likely a CA oversight or unintended change.
Here is the mod in question - it also adds some animations but that is not relevant to CBFM i guess.
https://steamcommunity.com/sharedfiles/filedetails/?id=2987275363

**Expected behavior**
All the Giants being able to normally use all their available attacks, just like in TWW 2.
Giant animations/effects being properly visible.

**To Reproduce**
1. Try the various Giant units in custom battle or campaign

**Comment by mfvreeland** [comment]
Got permission to incorporate the fix from Steam (sans new animations).

**Comment by mfvreeland** [comment]
Mod author doesn't want this incorporated anymore.
