### ISSUE TITLE
friendly_battle_leader_killed_or_routed invalid usage flag has an incorrect loc (opposite of what it should be)

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#11]
Fix by JvJ

https://discord.com/channels/373745291289034763/581350140942483456/1012003792729948294

**Comment by chadvandy** [comment]
zzz_cbfm_specab_invalid_usage_flags
Fix by JvJ

**Comment by Harmandodelavega** [comment]
1st and 3d line fixed

**Comment by Harmandodelavega** [comment]
seems the remaining lines aren't used anywhere, keeping it anyways

**Comment by Harmandodelavega** [comment]
doesn't seem relevant anymore so archiving it

**Comment by Harmandodelavega** [comment]
that redundant line got fixed
