### ISSUE TITLE
Drycha and beast lore tree men don't boost feral bears properly 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1101]
Will add fix soon

**Comment by floskan** [comment]
Ok, CA says it's something they're working on but the bears are in drychas monstermash set

**Comment by Harmandodelavega** [comment]
@floskan ?

**Comment by floskan** [comment]
> @floskan ?

This is the same as the queen Bess issue, probably something to do with Military groupings

**Comment by Harmandodelavega** [comment]
ok so gonna merge it under unit previews

**Comment by Harmandodelavega** [comment]
#1233
