### ISSUE TITLE
Southern Realms and Savage Orcs factions allied outposts bugged and don't ever construct

### ISSUE THREAD

**Issue by xemise** [chadvandy/cbfm_wh3#1106]
Sorry if this has been submitted already in the past but I couldn't find it. Thanks.

**Comment by xemise** [comment]
Bump. Forgot to include attachments for clarification.

![SouthernRealmsOutpost](https://github.com/chadvandy/cbfm_wh3/assets/136934737/eba5bef0-5b51-4256-8ccb-ae40c01cc48c)
![SouthernRealmsOutpost2](https://github.com/chadvandy/cbfm_wh3/assets/136934737/a06a06dd-745d-408b-a191-3310c9f31833)
![SouthernRealmsOutpost3](https://github.com/chadvandy/cbfm_wh3/assets/136934737/25252175-d6a5-4caf-9526-d9b58bb7630c)

**Comment by Harmandodelavega** [comment]
@Cataph
