### ISSUE TITLE
Bloodletter, Plaguebearer, Pink Horror and Daemonette RoR benefit twice from WoC rank 7 red line

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1113]
wh3_twa06_kho_inf_bloodletters_ror_0
wh3_twa06_nur_inf_plaguebearers_ror_0
wh3_twa06_sla_inf_daemonette_ror_0

in chaos_inf_ror and chs_daemon_infantry_rank7_ror sets

both linked to
wh3_dlc20_effect_force_stat_armour_chs_infantry_units_rank7
wh3_dlc20_effect_force_stat_melee_defence_chs_infantry_units_rank7
wh3_dlc20_effect_force_stat_spell_resistance_chs_infantry_units_rank7

---

wh3_twa06_tze_inf_pink_horrors_ror_0

in mp_cap_unit_tze_inf_pink_horrors_ror_0 and chs_daemon_ranged_rank7_ror

both linked to
wh3_dlc20_effect_force_stat_armour_chs_artillery_missile_units_rank7
wh3_dlc20_effect_force_stat_reload_time_chs_artillery_missile_units_rank7
wh3_dlc20_effect_force_stat_missile_resistance_chs_artillery_missile_units_rank7

**Comment by floskan** [comment]
What would we do here? Just add a negative effect as with chosen of tzeentch?

**Comment by Harmandodelavega** [comment]
looks like it
