### ISSUE TITLE
Gotrek and Felix not coming back

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1118]
A bug I noticed in 3.0 but forgot to report, I haven't seen mention of this anywhere so I assume it's still present in 3.1. In 3.0 I was doing a Volkmar campaign where I hired Gotrek and Felix and they eventually left. They never came back again to my faction, and I later noticed that they were working for Thorek Ironbrow's faction.

**Comment by Drazhir2** [comment]
Did you play long enough? because that's how they work:

1. 30 turns for the player
2. 10 turns cooldown
3. 20 turns in AI control (assigned to a random eligible faction)
4. 10 turns cooldown
5. Back to step 1
