### ISSUE TITLE
Shard blade ability has wrong (negative) effect indicator

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1119]
![Screenshot_2023-06-20-12-02-32-26_572064f74bd5f9fa804b05334aa4f912](https://github.com/chadvandy/cbfm_wh3/assets/34427023/e372373c-1167-406c-acf5-6da1b733c190)

**Comment by Drazhir2** [comment]
Here is the fix (rename to .pack)
[zzz_cbfm_shardblade.patch](https://github.com/chadvandy/cbfm_wh3/files/11798716/zzz_cbfm_shardblade.patch)
