### ISSUE TITLE
Alith Anar upkeep reduction for shadow warriors not working

### ISSUE THREAD

**Issue by DoctorIronic** [chadvandy/cbfm_wh3#112]
There is also a post on the total war forum about it. Maybe you guys want to look into it.

https://forums.totalwar.com/discussion/318579/alith-anar-upkeep-reduction-bug

**Comment by Harmandodelavega** [comment]
#302 more info

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2, should be removed

**Comment by chadvandy** [comment]
removed
