### ISSUE TITLE
Wood Elves technology "Wisdom of the Yew" does not affect RoR unit "Wraiths of the Frozen Heart (Dryads)"

### ISSUE THREAD

**Issue by RobotLP** [chadvandy/cbfm_wh3#1123]
You can replicate by choosing Drycha that has 1 Amber on start.

**Comment by Drazhir2** [comment]
It is on purpose. 

The technology provides poison attacks for trees and is applied to the wef_dlc05_trees_not_dryad_ror unit set. 

The Dryad RoR already has a Frostbite contact effect, So giving them Poison would remove the Frostbite as you can only have one contact effect active.
