### ISSUE TITLE
Fixed Cruel, Callous, Compulsive, Fanatical, Controlling, Unethical Chaos Dwarf traits not working on certain characters

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1129]
#966 forgot to log this at the time

**Comment by Harmandodelavega** [comment]
character_skill_level_to_effects_junctions_tables/zzz_cbfm_chd_traits_fix

Fixed:
Unethical
Callous

Partially Fixed
Controlling only death lore
Fanatical only death lore
Compulsive only death lore

Not Fixed
Cruel

**Comment by floskan** [comment]
> character_skill_level_to_effects_junctions_tables/zzz_cbfm_chd_traits_fix
> 
> Fixed: Cruel by removing it from castellan Unethical Callous
> 
> Partially Fixed Controlling only death lore Fanatical only death lore Compulsive only death lore

Should all lores have those traits or just death?

**Comment by Harmandodelavega** [comment]
all but only the death one was fixed, the first 3 should be fully removed

**Comment by chadvandy** [comment]
Fix removed in CBFM 5 batch 4.
