### ISSUE TITLE
Kill a LL from x race vow for embedded Paladin not progressing ("Beastman" LL and Skrag), worked for Lord

### ISSUE THREAD

**Issue by gmoulin** [chadvandy/cbfm_wh3#113]
Hello,

the "pledge to protect" questing vow requires to "defeat a legendary lord of ogre kingdoms, beastmen, greenskins or dark elves".
On my army lord, no problem, the vow has completed when I killed the beastmen legendary lord from Estonia.
In the same army, the paladin hero vow did not complete for the same beastmen legendary lord and later for Skrag (ogre kingdoms).

It seems bugged.

**Comment by Harmandodelavega** [comment]
#196

**Comment by mfvreeland** [comment]
@gmoulin 
Looking through the script for this, it is not clear to my why this wouldn't work. Do other Paladin vows trigger OK? If it is possible to provide a save for this situation, I'm sure I could debug it.

**Comment by Harmandodelavega** [comment]
Some mod claims a bug for paladins embedded in prophetess armies was fixed, gonna assume it was this
