### ISSUE TITLE
Global diplo bonuses from techs and Dark Elf "Envoy" Ancillary don't work with Chaos Dwarfs

### ISSUE THREAD

**Issue by Y-311** [chadvandy/cbfm_wh3#1131]
**Describe the bug**
The Ancillary does not give to normal +10 relations with the chaos dwarfs. "Ruler's tolerance to Naggarond" missing in screenshot.

**Expected behavior**
The Ancillary says "+10 relations with all factions"

**To Reproduce**
1. Play DE
2. Get Envoy Follower
3. Check Diplomacy with Chaos Dwarfs

**Screenshots**
Relations with Chaos Dwarfs with Envoy Equipped:
![image](https://github.com/chadvandy/cbfm_wh3/assets/137061314/31e98db5-26e7-4f16-91c4-d1013a9c2e6a)

Relations with another faction with Envoy Equipped:
![image](https://github.com/chadvandy/cbfm_wh3/assets/137061314/dfc549c2-3b8b-43ef-adaa-f52d78860cc1)

**Comment by Harmandodelavega** [comment]
@floskan can you add chorfs to wh_main_faction_political_diplomacy_mod_technology too while you're at it?

**Comment by Harmandodelavega** [comment]
they got the envoy but not the tech one
