### ISSUE TITLE
"Engvin" Follower for Dark Elves slave income effect does not work

### ISSUE THREAD

**Issue by Y-311** [chadvandy/cbfm_wh3#1132]
**Describe the bug**
The Special Follower for Malus Darkblade should give +5% income from slaves but it does not work. As seen in the screenshots I equipped the follower and the individual building should that apparently it is making more money but in fact the total income at the top does not change.

**To Reproduce**
1. Play Malus Darkblade
2. Get Engvin Follower
3. Check Building and Total Income

**Screenshots

Not Equipped:
![image](https://github.com/chadvandy/cbfm_wh3/assets/137061314/1a9e4043-3420-409f-bba7-9aa2a49cc4c2)
![image](https://github.com/chadvandy/cbfm_wh3/assets/137061314/0b0814c0-ae95-4578-88d6-1b175cbfca6d)

Equipped:
![image](https://github.com/chadvandy/cbfm_wh3/assets/137061314/dfaf1fa8-a21b-4af5-94ab-da6ac57727e7)
![image](https://github.com/chadvandy/cbfm_wh3/assets/137061314/6e1808cd-998d-4f8c-a725-3375b7a7741a)

**Comment by mfvreeland** [comment]
I imagine this effect is basically obsolete now with the way the slave system has changed. Probably best to just remove it from the tooltip?

**Comment by Y-311** [comment]
It is still very much relevant, it increases the income of all industry industry buildings factionwide by 5% which is very strong.

**Comment by floskan** [comment]
I vote remove the redundant effect and just keep the industry one

**Comment by Y-311** [comment]
Which effect you think is redundant? @floskan

**Comment by floskan** [comment]
> Which effect you think is redundant? @floskan

Either we change the slave income to just provide 5% to industry income or remove it since like @mfvreeland said, how slaves works have changed and we don't know if this follower is intended to work the same way it used to or even at all.

**Comment by Y-311** [comment]
I am not really sure if I understand the issue here @floskan. The "Income from slaves" is not obsolete and is still in the game. For example factions effects, slanesh corruption for Morathi, Research and long campaign victory (attached pictures below). The only issue is that it is not working for this follower and the Upgrade III technology which is supposed to give +10% income from slaves (last picture) to which I made a separate post. The bug seems to be the "all provinces" tag because all boosts without it are working but the ones that say all provinces are not.

<img width="1955" alt="Screenshot 2023-06-26 at 11 32 04" src="https://github.com/chadvandy/cbfm_wh3/assets/137061314/b4f6db64-6c14-4380-a999-fe75ef0f1b19">

<img width="762" alt="Screenshot 2023-06-26 at 11 33 21" src="https://github.com/chadvandy/cbfm_wh3/assets/137061314/87b83ae2-a822-43fe-a671-6b5496ac7142">

<img width="742" alt="Screenshot 2023-06-26 at 11 34 15" src="https://github.com/chadvandy/cbfm_wh3/assets/137061314/24346b69-a9f8-40e9-99f5-2a28387aa4bd">

<img width="682" alt="Screenshot 2023-06-26 at 11 47 31" src="https://github.com/chadvandy/cbfm_wh3/assets/137061314/a6c049af-8387-4c2f-a88a-d4cfe55ca040">

<img width="1161" alt="Screenshot 2023-06-26 at 11 53 59" src="https://github.com/chadvandy/cbfm_wh3/assets/137061314/ab6537b4-a19b-4460-ad37-7faca02e796b">

<img width="803" alt="Screenshot 2023-06-26 at 11 33 51" src="https://github.com/chadvandy/cbfm_wh3/assets/137061314/ecef3092-cdec-4a5f-9e02-d7b8a0df6811">

**Comment by floskan** [comment]
> I am not really sure if I understand the issue here @floskan. The "Income from slaves" is not obsolete and is still in the game. For example factions effects, slanesh corruption for Morathi, Research and long campaign victory (attached pictures below). The only issue is that it is not working for this follower and the Upgrade III technology which is supposed to give +10% income from slaves (last picture) to which I made a separate post. The bug seems to be the "all provinces" tag because all boosts without it are working but the ones that say all provinces are not.
> 
> <img alt="Screenshot 2023-06-26 at 11 32 04" width="1955" src="https://user-images.githubusercontent.com/137061314/248755602-b4f6db64-6c14-4380-a999-fe75ef0f1b19.png"> <img alt="Screenshot 2023-06-26 at 11 33 21" width="762" src="https://user-images.githubusercontent.com/137061314/248755769-87b83ae2-a822-43fe-a671-6b5496ac7142.png"> <img alt="Screenshot 2023-06-26 at 11 34 15" width="742" src="https://user-images.githubusercontent.com/137061314/248755806-24346b69-a9f8-40e9-99f5-2a28387aa4bd.png"> <img alt="Screenshot 2023-06-26 at 11 47 31" width="682" src="https://user-images.githubusercontent.com/137061314/248755853-a6c049af-8387-4c2f-a88a-d4cfe55ca040.png"> <img alt="Screenshot 2023-06-26 at 11 53 59" width="1161" src="https://user-images.githubusercontent.com/137061314/248756191-ab6537b4-a19b-4460-ad37-7faca02e796b.png"> <img alt="Screenshot 2023-06-26 at 11 33 51" width="803" src="https://user-images.githubusercontent.com/137061314/248756279-ecef3092-cdec-4a5f-9e02-d7b8a0df6811.png">

Great, thanks for supplying some other examples. I'll just submit a fix with the correct scope for the ancillary. Does any of your other examples above not work as well?

**Comment by Y-311** [comment]
I think it's just those 2 because of the tag. I have tested all except the long campaign victory bonus and those were working correctly.

**Comment by floskan** [comment]
@Y-311 Is it possible that you can give me a save with Engvin unlocked? Or can you test this pack out for both Upgrade 3 and Engvin?
[DEslaveincome.zip](https://github.com/chadvandy/cbfm_wh3/files/11871151/DEslaveincome.zip)

**Comment by floskan** [comment]
Oops, the Engvin one might not work.

**Comment by Y-311** [comment]
Sadly I am playing through GeForce Now on a Mac, so I cant download or edit game files.

**Comment by floskan** [comment]
> 

I'm looking through your pictures and tried giving myself Engvin.. He does give income from slaves? Look at the increase in % in the bottom part of the building.

**Comment by floskan** [comment]
Without Engvin: 
![Skärmbild 2023-06-26 202543](https://github.com/chadvandy/cbfm_wh3/assets/34427023/57b181cc-9fa6-4a86-b7db-645efb357560)

With Engvin:
![Skärmbild 2023-06-26 202557](https://github.com/chadvandy/cbfm_wh3/assets/34427023/e0d3e60e-e811-4f53-b0ed-d73ff5439afb)

**Comment by Y-311** [comment]
For the technology I didn't see any change at all. Not in the building itself nor total income at the top. For the Follower it was a bit weird, I saw the building income change in the info but the total income at the top didn't change at all.

**Comment by Y-311** [comment]
By default or after your fix? 

Did you see the income at the top change? For me it didn't when I equipped / unequipped the Follower on the same turn.

**Comment by floskan** [comment]
> By default or after your fix?
> 
> Did you see the income at the top change? For me it didn't when I equipped / unequipped the Follower on the same turn.


Just with the console on so i could give Malus the follower:


Without follower
![Skärmbild 2023-06-26 231143](https://github.com/chadvandy/cbfm_wh3/assets/34427023/e1c2a1ff-ee87-46f7-88e1-8a706ed3ee33)
With follower
![Skärmbild 2023-06-26 231134](https://github.com/chadvandy/cbfm_wh3/assets/34427023/0e1738d8-df6f-43b0-9eed-b10080cfc0f9)

**Comment by Y-311** [comment]
Yeah that seems to be working correctly. Weird that it was not working for me, not sure what it could have been. Sadly I don't have the safe stored anymore so I can't check again. Thank you for checking it out!
