### ISSUE TITLE
Cult of Sotek gets a redundant "Kill and Eat" post battle option, inferior to the sacrifice option

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1133]
![20230622125351_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/deb037af-774c-423f-9d16-4060acddc26b)

**Comment by mfvreeland** [comment]
Does anyone remember what this was like in WH2? It would be trivial to have sacrifice option overwrite the default "Kill and Eat" option for Cult of Sotek, but I seem to remember there being four choices in WH2, and all of them had a potential upside. I want to say the right fix is to remove the replenishment factor for Mark for Sacrifice, but only if it was like that in WH2.

**Comment by Harmandodelavega** [comment]
I played tehenhauin a lot in WH2 and remember some choices being underwhelming but not redundant, whould check just to be sure though

**Comment by floskan** [comment]
![20240315174211_1](https://github.com/chadvandy/cbfm_wh3/assets/34427023/9c7a24d9-676f-4165-bed4-6926b43666bc)

**Comment by floskan** [comment]
Money, exp and sacrifice was his options

**Comment by mfvreeland** [comment]
Unless anyone opposes, I am going to restore it to WH2 style.
