### ISSUE TITLE
cannot exchange city when my land nearby Sartosa

### ISSUE THREAD

**Issue by shinasuka6268** [chadvandy/cbfm_wh3#1135]
as the picture shows, my land is nearby Sartosa, which is belong to Aranessa, vampire coast. 
i want to give her my city Luccini, but i cannot.

![change](https://github.com/chadvandy/cbfm_wh3/assets/137533744/72026781-0114-4147-9c9d-8416ff198214)
![change2](https://github.com/chadvandy/cbfm_wh3/assets/137533744/25afb327-eaa7-49cc-a15f-d356e64d9281)

**Comment by Harmandodelavega** [comment]
bridge does not count
