### ISSUE TITLE
Warriors of Chaos doesn't get souls from fighting Chorfs (From post battle option and settlement razing)

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1138]
![Skärmbild 2023-06-24 180455](https://github.com/chadvandy/cbfm_wh3/assets/34427023/4f36f64d-c31b-4b60-a42c-978176c89e37)

**To add to this @mfvreeland , there's also no souls rewarded for razing chorf settlements.**

**Comment by Harmandodelavega** [comment]
@mfvreeland fixed?

**Comment by mfvreeland** [comment]
I'm not sure if CA fixed it, but this fix still works

**Comment by Drazhir2** [comment]
this was not fixed by CA

**Comment by Drazhir2** [comment]
Fixed in 4.2.0
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/0960a07b-4a4e-4ede-977e-75086806dbe8)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/4cc0a647-29b0-448a-8efb-c6e13467d9f0)
