### ISSUE TITLE
Gifted Daemons not benefitting from god mark gifts.

### ISSUE THREAD

**Issue by CRUNKULON** [chadvandy/cbfm_wh3#114]
I am fairly certain that this is an oversight on CA's part, but due to the fact that gifted Daemon units lack the actual mark of their specific god, they gain no benefit from the gifts such as the Khornate one that gives Blood-Greed to all Khorne units or the Slaaneshi one that grants Vanguard deployment.

**Comment by Harmandodelavega** [comment]
I remember in 40k Gladius you could either be "marked" or have the "daemonic" trait, gonna guess it's the same here
