### ISSUE TITLE
Chaos Dwarf items cannot drop from battles plus few other item drop corrections (CatholicAlcoholic)

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1149]
https://github.com/chadvandy/cbfm_wh3/issues/1146

wh3_campaign_magic_items.lua

- Chorf ancs not hooked up
- Rapier of ecstasy typo
- WoC  "Festering Shroud" displays as Rare, but is distributed as uncommon
- wh3_dlc20_anc_weapon_axe_of_khorne does not exist (likely a duplicate of the "Axe of Khorne")
- "Talisman of Loec" listed as both a Common Talisman and a Common Enchanted Item  (should only be a Common Enchanted Item),
- 
https://discord.com/channels/373745291289034763/581350140942483456/1133447699962794105

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Chaos Dwarf specific magic items will now also drop after battle victories, not just via the Tower of Zharr mechanic."
