### ISSUE TITLE
Frost Maiden has model bugs

### ISSUE THREAD

**Issue by BarryCMC** [chadvandy/cbfm_wh3#115]
![0f16d6096b63f624ab9ad2dec244ebf81b4ca337](https://user-images.githubusercontent.com/112805267/188309260-e9cc1456-6cde-4e7b-996b-e18b5a1a0eaa.jpg)

**Comment by BarryCMC** [comment]
The sword held in his hand disappears, the sword is behind him

**Comment by Cataph** [comment]
Needs to be checked if it also happens in battle (vmd issue) or it's a campaign anim issue, which may not be worth fixing.
