### ISSUE TITLE
Road warden/Chracian scout/Warlock/Prize Hunter followers can be awarded also on ambush lost

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1153]
return context:pending_battle():ambush_battle();
 
instead of

return context:character():won_battle() and context:pending_battle():ambush_battle();

could change the loc instead

**Comment by Drazhir2** [comment]
Issue fixed in #1203

**Comment by Drazhir2** [comment]
Fixed in 4.1, they changed the loc descriptions to just say ambush battle so we need to remove the cbfm followers fix for these.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d4f5b390-9d0b-49fb-99a9-8589c330dbea)
