### ISSUE TITLE
Kroq-Gar (or Gor-Rok) not getting the per-level Weapon strength (1% WS per level) buffs he gives his Old Bloods

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#116]
Kroq-Gar does not get 1% WS per rank as other kinds of old bloods get. Just weird that the faction leader will turn out much weaker then the heroes in his army.
https://steamcommunity.com/sharedfiles/filedetails/?id=2858251286

**Comment by Cataph** [comment]
please have more descriptive issue titles.

**Comment by Aatxe360** [comment]
Kroq-Gar is a Saurus Old-Blood so technically he should get the bonuses he gives to the other Old-Bloods as well.  It is listed in his description in game that he's one of the last Saurus Old-Bloods from Xhotl.

**Comment by Cataph** [comment]
Letting him get a dynamic 1-50% dmg boost is a pretty drastic thing. I suggest not touching it unless CA confirms it's not intended.

**Comment by Harmandodelavega** [comment]
Would be cool but we can't be very sure it's intended
