### ISSUE TITLE
Exalted Hero of Khorne/Nurgle Spread Control bug

### ISSUE THREAD

**Issue by 7h3bub1** [chadvandy/cbfm_wh3#1161]
Something went wrong when copying the Exalted Hero from Warriors of Chaos to Demon factions.
In the Demon factions, Heroes have trait "Spread Control", but it seems to me somebody copied it wrong, because it has "Modifies control in the local province by -1."
![image](https://github.com/chadvandy/cbfm_wh3/assets/137820223/661964ae-4467-4746-97e5-1e31afb53ba5)

On the other hand, Bloodreapers have the same trait, but their text is "Increases control in the local province by 1 (reduces in enemy provinces).

![image](https://github.com/chadvandy/cbfm_wh3/assets/137820223/7f31ba6d-e9d4-4435-8b80-44255400b7a7)

The mix  of them grants 0 control.

Here are their Nurgle "friends".

Exalted Hero:
![image](https://github.com/chadvandy/cbfm_wh3/assets/137820223/ba126920-7e08-4dc4-9f09-4d3a607d6472)

Plagueridden:
![image](https://github.com/chadvandy/cbfm_wh3/assets/137820223/d6b54ca5-78df-4a48-be53-656cac99d204)

**Comment by 7h3bub1** [comment]
@floskan Yup, I can make a save file if it's needed.
The issue can be seen from the start of Khorne campaign, it takes two turns to see it gor Nurgle.
It isn't obvious, but when both of the heroes are in an region, it gives x+(-x) control.

**Comment by Harmandodelavega** [comment]
Fixed an issue where Chaos Heroes weren’t increasing control in regions owned by them.
4-1 probably fixed
