### ISSUE TITLE
Henri not affected by Bretonnian tech "Temple Tithes"

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1173]
dlc07_brt_paladins set missing henri

**Comment by floskan** [comment]
Is that the wardsave?

**Comment by floskan** [comment]
> dlc07_brt_paladins set missing henri

Just curious for future bugs with missing heroes/lords, do i add all variants to these kinds of sets or just the base unit record?

**Comment by Drazhir2** [comment]
Unit Record in **unit_set_to_unit_junctions** takes a **main_units** key so you just need all variations from that table (to catch all mount options for the character)

**Comment by floskan** [comment]
> Unit Record in **unit_set_to_unit_junctions** takes a **main_units** key so you just need all variations from that table (to catch all mount options for the character)

Alright, thanks. I got it right then
