### ISSUE TITLE
Tunelling not excluded for Empire forts

### ISSUE THREAD

**Issue by TrubbleMods** [chadvandy/cbfm_wh3#118]
The only regions included in the excluded campaign group are the Ulthuan regions.

There is a need to add empire fortress and cathay gates to the exclude group. (The cathay gates are added to the excluded campaign group on the chaos campaign map as they should be.)

**Comment by mfvreeland** [comment]
@TrubbleMods 
Are these exclude groups defined in a table? Do you know where?

**Comment by mfvreeland** [comment]
CA seems to have fixed this for the Great Bastion in 2.3, but no word on empire forts. Needs testing.
