### ISSUE TITLE
Haunted Forest missing Exotic Animals icon

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1182]
#432
![20230627235913_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/2083ef0a-4a09-4328-8d85-9c84a8a70a18)

**Comment by AmazingTriangularHairMan** [comment]
It should also be a ten-slot settlement like other magical forests.

**Comment by Harmandodelavega** [comment]
merged #432
