### ISSUE TITLE
Reductions to sea lane travel time don't apply to River Ruin canal and incident doesn't work

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1185]
"missing_effect"

travel_time_mod "missing_effect" wh3_dlc23_teleportation_node_template_chaos_dwarf_canal

or something like that

**Comment by mfvreeland** [comment]
The notification part was apparently fixed by CA in 4.1:

"Fixed the “Journey Complete” event not appearing when a character travelled via the Uzkulak Canal Sea Lane in Immortal Empires."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
