### ISSUE TITLE
Beastmen Herdstone effect bundles not being removed right

### ISSUE THREAD

**Issue by frolof1** [chadvandy/cbfm_wh3#1188]
**Describe the bug**
Beastmen herdstones apply effect bundles, such as a plague or siege debuffs to blood ground regions adjacent to a herdstone. 

**Expected behavior**
The behaviour of the bug seems to be that the herdstone effect bundles are not being removed. The only "way" to remove the bug is to kill the factions entirely via console commands. Only when razed entirely does it seem to get rid of it. But it's not always the case.

**To Reproduce**
I have been attempting to reproduce, with little success. Seems to be something intricate with how beastmen factions can return, perhaps?

**Screenshots**
https://imgur.com/a/PW9c00j
![20230701153952_1](https://github.com/chadvandy/cbfm_wh3/assets/57967968/2155fd91-682b-43ff-8eaf-a0e9ef350284)
![20230701153951_1](https://github.com/chadvandy/cbfm_wh3/assets/57967968/b632b6cf-7da4-47e1-a225-d2681140030e)

These are one set of screenshots. Almost all regions in the badlands suffer from beastmen effect bundles that either debuff them or apply chaos attrition.

**Saves**
Sadly I use mods that would break the game for you if you tried the save.

**Additional context**
What is important is that I use mods. Which might break the legitimacy of the issue.
But I have seen this problem before too.

**Comment by Harmandodelavega** [comment]
#1003
