### ISSUE TITLE
Mannfred's quest battle vs. greenskin shamans does not work properly

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1189]
https://github.com/chadvandy/cbfm_wh3/issues/715
You're prompted to kill or rout the shamans but doing so does not actually advance the counter, and killing/routing all 4 does not rout greenskins armies (which I seem to remember happening in game 2 with Thorgrim's equivalent quest battle). You have to defeat the enemy the old-fashioned way.

![20230701160851_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/df029896-7941-4f97-aab1-ad22fd79afac)
![20230701161222_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/191ab2b3-4875-4081-b85e-3892c76a58f9)

**Comment by Harmandodelavega** [comment]
merged https://github.com/chadvandy/cbfm_wh3/issues/715
