### ISSUE TITLE
[Meta]AI Settra has two Khepra Guard RoRs at once #207

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1190]
#207
![20230701183148_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/4ea0b25c-ba75-4839-8933-a91f22f71f7d)
![20230701183150_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/863fcc53-0c91-4d02-8675-47c2b82d83cb)

I think something is wrong with RoR limitations, I saw Khemri immediately re-recruit the spearmen RoR after it got wiped out the previous turn.

**Comment by Y-311** [comment]
You can recruit up to 3 of this unit.

**Comment by Harmandodelavega** [comment]
Are you using CBF?

**Comment by allenhu0912** [comment]
Community Bug Fix Mod 3-Batch 4 is currently active in my mod list. Don't have any other mods that look like they touch RoRs/Tomb Kings/whatever.

**Comment by floskan** [comment]
Was sure we fixed that but maybe not

**Comment by Harmandodelavega** [comment]
I checked the sets and they're definitely correct

**Comment by allenhu0912** [comment]
It's my screenshot. I have the mod enabled and I don't remember ever turning it off. There's the slim possibility that Steam did something funny while the internet was acting up and possibly cause the mod to not be enabled, but otherwise CBFM should have been enabled at the start of the campaign and while I took the screenshot.

**Comment by Harmandodelavega** [comment]
If I understood correctly your internet was acting up, gonna assume it was that and not some freak circumstance
