### ISSUE TITLE
Malagor beast-paths stance (mby few others) movement buff not working the turn it's entered

### ISSUE THREAD

**Issue by VidarSarnesjo** [chadvandy/cbfm_wh3#1192]
Switching to the stance at the beginning of the turn will not grant the extra 50% movement range. If you remain in the stance the turn after the movement range is applied correctly.

1. Play as Malagor
2. Switch to beast-paths stance (check movement points not increasing)
3. Move somewhere
4. End turn
5. See buff applied at the beginning of next turn (check movement points compared to previous turn)

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/26004021/7860bf06-a837-4bfd-bc69-29d9a53d6638)
![image](https://github.com/chadvandy/cbfm_wh3/assets/26004021/d4bc5fd1-4c31-4201-8f28-21ec815fca30)
![image](https://github.com/chadvandy/cbfm_wh3/assets/26004021/4d6fdcd3-9073-426b-b4bd-b131a96513a0)

Edit:
wh_main_effect_force_all_campaign_movement_range for: wh2_dlc17_bundle_stance_army_tunnelling_horde_beastmen_unique_malagor wh2_main_bundle_stance_army_astromancy wh2_twa03_bundle_stance_army_raiding_def_rakarth wh_main_bundle_stance_army_raiding_def may not be working/working the turn it's activated (use forced march/other stance effect)

**Comment by floskan** [comment]
Would start_turn_initiated fix this?

**Comment by Harmandodelavega** [comment]
> Would start_turn_initiated fix this?

mby, or you could just zero it out and use the usual stance effect and see if it works
