### ISSUE TITLE
Embedded vampire buffs from Isabella does not apply to Vlad von Carstein

### ISSUE THREAD

**Issue by VidarSarnesjo** [chadvandy/cbfm_wh3#1195]
**Describe the bug**
Isabella's faction as well as her trait applies buffs to embedded vampire heroes. These buffs do not apply to Vlad

**Expected behavior**
The buffs should apply to Vlad as well.

**To Reproduce**
1. Play as Isabella
2. Embed Vlad von Carstein
3. Check Vlad's stats before and after

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/26004021/7a5f25f4-12d1-4647-8ec3-3f1ab373fbdc)
![image](https://github.com/chadvandy/cbfm_wh3/assets/26004021/e0b415cc-e195-460b-a19d-dd59e1430c40)

**Comment by allenhu0912** [comment]
Vlad isn't a vampire hero. Just like Kroq-gar isn't a Saurus Oldblood lord.

**Comment by VidarSarnesjo** [comment]
> Vlad isn't a vampire hero. Just like Kroq-gar isn't a Saurus Oldblood lord.

Why would he not count as one? Looks like an oversight to me.

**Comment by Harmandodelavega** [comment]
behind the scenes stuff

**Comment by AmazingTriangularHairMan** [comment]
I would consider both this and Kroq-Gar's faction effect an oversight. Vlad is a vampire, he is a hero. He is a vampire hero and should therefore benefit from the stat increase Isabella's faction gets. Kroq-Gar should also benefit from his faction effects.
On top of that, Isabella and Vlad as heroes miss unique skills like Diviner or Loremaster of Vampires that they usually have as lords, unless this has been integrated into this mod already. I've been using a standalone mod for this for the longest time.

**Comment by Harmandodelavega** [comment]
Just report bugs or submit fixes
