### ISSUE TITLE
Lord of the minor faction Pallid Nurslings : Methanion the Mephitic isn't immortal

### ISSUE THREAD

**Issue by RandomHumanBret** [chadvandy/cbfm_wh3#1199]
#788
Once he have been killed he doesn't come back, i assume he isn't immortal !
I figured it during a randomized starting position mod where after someone beated him a new lord appeared in the diplomatic screen and i never saw this faction using ever again the great unclean one Methanion.

**Comment by Harmandodelavega** [comment]
merged with #788
