### ISSUE TITLE
Blessed Horned Ones no primal instincts, Blessed Stego no missile resist

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#120]
CA changed a lot of LM units in the IE update, mostly by giving them Primal Instincts.
However some Blessed units (and possibly some RoR) seem to have been forgotten and are missing Primal Instincts, leading to these special units being notably worse than regular variants due to how powerful the new Primal Instincts buff is.

![image](https://user-images.githubusercontent.com/55892027/188315573-c05941ea-c022-4fcf-b2d8-cfd2668ff02e.png)

**Comment by SpookyFen** [comment]
Reminds me that Feral Cold Ones still don't count as "cold one units" for the purposes of LM red tree skills etc.

**Comment by Harmandodelavega** [comment]
removed the stego text since we got a duplicate

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Blessed Horned Ones now have Primal Instincts as intended."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
