### ISSUE TITLE
Mutant follower drops on battle loss instead of win

### ISSUE THREAD

**Issue by VoidPeer** [chadvandy/cbfm_wh3#1203]
is there any way to fix a follower that spawn for 3 faction?
according to this website https://twwhub.dev/culture/wh_dlc08_nor_norsca/followers there is a follower Mutant that have Enemy leadership: -4 (local region) Won a battle (6%)
but the only way to get is Lose battle with 6% but the info on web and in game say Win battle 6%
https://i.ibb.co/QHxG1d9/mutant.jpg
How do i know is on Lose battle? u may ask well i test it and i farm the followers in WH2 and WH3. the way i do it is leave small settlement surround by 4-10 lords and every 2nd turn play manual battle and retreat(lose battle) with every singe lord.
is there a way to change that to Win 6% just like the game have and web?
and 3 faction that can spawn that are Norsca, Beastman and Warriors of Chaos.
btw this mod is a must have for my games. if this mod is outdated i dont even play the game. TY!! for all the work the team put on it!

**Comment by Drazhir2** [comment]
Confirmed, there is a **not** keyword in there
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d1330e8c-8359-4c9d-886a-688c0b162989)

I can't see a way to make an elegant fix for that one, it would require overwriting the whole vanilla followers script.

**Comment by Harmandodelavega** [comment]
Followers script bugs are starting to pile up, might be worth it

**Comment by Drazhir2** [comment]
actually no, we don't need to overwrite the full script to fix a few of these, load_followers is called pre_first_tick so we can just remove the broken ones and add the fixed ones at first_tick to correct them (see text file)
[zzz_cbfm_followers_mutant.txt](https://github.com/chadvandy/cbfm_wh3/files/12001554/zzz_cbfm_followers_mutant.txt)

**Comment by Drazhir2** [comment]
I will rewrite the previous script so we can have a unique followers fix script that's easily extendable for the future.

**Comment by mfvreeland** [comment]
This issue is still in 4.1.

**Comment by Harmandodelavega** [comment]
@mfvreeland they changed the loc to say it drops on loss
