### ISSUE TITLE
Grom's starting province has shrunk

### ISSUE THREAD

**Issue by AmazingTriangularHairMan** [chadvandy/cbfm_wh3#1204]
**Describe the bug**
As the title suggests, Grom's Mortal Empires / Immortal Empires starting settlement Massif Orcal in Bretonnia has been shrunk down from a ten-slot to an eight-slot settlement during the transition from the second to the third game.

**Expected behavior**
I believe this to be an oversight much like Sartosa, Gaean Vale and the still missing Elven Colonies and would like this issue to be rectified. It's the sole reason I have yet to play a Grom campaign in the third game.

**To Reproduce**
I will save you the trouble of having to reproduce this issue and will point to the screenshots submitted below instead.

**Screenshots**
See screenshots submitted.

**Saves**
Not applicable.

**Additional context**
I have been informed by an unrelated modder that this appears to be a start position issue. I know next to nothing about modding and so have nothing to add in this regard, but apparently it is a difficult thing to fix for anyone that isn't CA. Perhaps there is something that you good people can do to fix this.
On an vaguely note: If anyone would be willing to teach me in modding beyond telling me to go to Tha Modding Den, it would be my honour to contribute to making the last game in the trilogy the best and most bug-free it can be.

Thank you for your time.

![20230707045306_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/f5b1296f-9fca-4128-8117-b5817e0674b4)
![20230707044252_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/b3e44b0b-4033-4716-8e4a-29313ce22c8d)

**Comment by Harmandodelavega** [comment]
@AmazingTriangularHairMan Step 1 download RPFM https://github.com/Frodo45127/rpfm/releases/tag/v4.0.22
This wiki should help you also https://tw-modding.com/wiki/Main_Page
forget about using github for now, if you manage you can drop packs in the discord
ask here or in the modding den on discord if you need help

**Comment by Harmandodelavega** [comment]
merging with #998
