### ISSUE TITLE
Post battle screen animation bugged

### ISSUE THREAD

**Issue by xXAlduin99** [chadvandy/cbfm_wh3#1205]
**Describe the bug**
The level up, loot and item-animation in the post battle screen in the middle of the screen in campaign is bugged for the western part the empire. As Karl Franz, Festus and Balthasar Gelt you don't get the animation. It just gets skipped.

**Expected behavior**
The animation in the post battle screen is correctly played.

**To Reproduce**
1. Play as Festus, Karl Franz or Balthasar Gelt
2. Attack the starting enemy army
3. Auto resolve
4. Wait in the post battle screen, after the result no more animation are played

**Comment by Harmandodelavega** [comment]
#871
