### ISSUE TITLE
Lord and Hero Corruption traits can only be curred in untained prov, even if your fc speads its own corruption 

### ISSUE THREAD

**Issue by DrenderD** [chadvandy/cbfm_wh3#121]
So basically there are 6 traits in the game for corruption: Vampiric, Chaos Undivided, and the four subtypes of Chaos.

You gain these traits by being in a region with more than 8 corruption of a given type.

Chaos undivided cannot get any of the chaos corruption traits. However, monogod factions can get corruption traits from the other monogods. So for example Khorne can get "Corrupted by Nurgle".

However, there is an oversight/bug in the script which handles removing these traits. The script looks like this if you're curious:

if chaos >= 8 then
	Give_Trait(character, "wh2_main_trait_corrupted_chaos");
elseif vampiric >= 8 then
	Give_Trait(character, "wh2_main_trait_corrupted_vampire");
elseif khorne >= 8 then
	Give_Trait(character, "wh3_main_trait_corrupted_khorne");
elseif nurgle >= 8 then
	Give_Trait(character, "wh3_main_trait_corrupted_nurgle");
elseif slaanesh >= 8 then
	Give_Trait(character, "wh3_main_trait_corrupted_slaanesh");
elseif tzeentch >= 8 then
	Give_Trait(character, "wh3_main_trait_corrupted_tzeentch");
elseif chaos < 3 and vampiric < 3 and skaven < 3 and khorne < 3 and nurgle < 3 and slaanesh < 3 and tzeentch < 3 then
	if character:trait_points("wh2_main_trait_corrupted_chaos") > 0 or character:trait_points("wh2_main_trait_corrupted_vampire") > 0 or character:trait_points("wh3_main_trait_corrupted_khorne") > 0 or character:trait_points("wh3_main_trait_corrupted_nurgle") > 0 or character:trait_points("wh3_main_trait_corrupted_slaanesh") > 0 or character:trait_points("wh3_main_trait_corrupted_tzeentch") > 0 then
		Give_Trait(character, "wh2_main_trait_non_corrupted");
	end
end

It works like this: if you are in a region with no corruption at all, you have a chance of getting the "non-corrupted" anti-trait. This removes the corruption traits and their penalties.

But that's exactly it: you need a region with no corruption at all. It doesn't matter who you are, the region has to be completely untainted.

So in order to cure yourself, you have to go find a completely untainted region on the map and sit there, hopefully with the AI having enough anti-corruption buildings and heroes to prevent you from adding any of your own corruption (I hope you didn't take the blue line skills for adding corruption). If you are sitting in a region of your own corruption type, you will never have the corruption of other gods removed. You need a completely uncorrupted region.

And yes if vampires and skaven were playable it would screw them over too. It will also cause you to have difficulty removing the vampire corruption trait if you get it on any chaos character.

**Comment by Harmandodelavega** [comment]
"And yes if vampires and skaven were playable it would screw them over too. It will also cause you to have difficulty removing the vampire corruption trait if you get it on any chaos character."

looks like a necro, think it was fixed before even IE released
