### ISSUE TITLE
Completing Imrik's quest to confederate Caledor doesn't give you the option to confederate when completing it

### ISSUE THREAD

**Issue by Denarius40** [chadvandy/cbfm_wh3#122]
Playing as Imrik if you complete the quest by occupying, sacking or razing 6 different settlements the event window that let's you choose the different options to confederate Caledor doesn't pop up.  I verified that Caledor was still alive when I completed the quest.

There are unverified claims that the event window does pop up correctly if you don't do any diplomacy before completing the quest. I'll try to verify that asap.

**Comment by Cataph** [comment]
check if this is among the Imrik fixes in 2.1

**Comment by Denarius40** [comment]
It isn't in the patch notes. Though I did start a new campaign and could confederate whether I used diplomacy or not.

**Comment by Harmandodelavega** [comment]
fixed by 2.2 pretty sure
