### ISSUE TITLE
Chorfs immediately re-hire Soul of Damnation and Ice-Forged Legion hellcannon RoRs the turn after I destroy them

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1222]
#1082
Killed them while defending during the enemy turn, they are back again next turn in a different army.

**Comment by mfvreeland** [comment]
When you destroyed these RoRs, were they from the same faction that re-built them on the next turn, or was it a different faction?

**Comment by allenhu0912** [comment]
Same faction (Astragoth's)

**Comment by Harmandodelavega** [comment]
merged with https://github.com/chadvandy/cbfm_wh3/issues/1082
