### ISSUE TITLE
Mark of Khorne increases Armor but does not say so

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1223]
In all cases where an unmarked unit is compared to its Khorne marked equivalent, the Khorne marked one has higher armor, ranged between 10 (for units with high armor) and 20 (for units with low armor). However, the tooltip for the Mark of Khorne does not mention this.

**Comment by Drazhir2** [comment]
it's not an effect, it's baked into the units stats which makes it tricky to display like you want
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/19689995-90e6-41b2-8821-a1fa52b1ea6b)

**Comment by Autumnchain** [comment]
I know that it's not an effect, none of the Marks are. The description when one mouse overs the Mark of Khorne attribute on the unit card simply does not mention that Khornate marked units will have more armor than unmarked or differently marked units of the same tier and weaponry.

**Comment by Drazhir2** [comment]
My bad, here's the fix:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/7d307fdf-66d6-4dc6-9aa0-03271f9ad3f9)

[zzz_cbfm_mark_kho_armour.patch](https://github.com/chadvandy/cbfm_wh3/files/12059142/zzz_cbfm_mark_kho_armour.patch)

**Comment by floskan** [comment]
Removed from main
