### ISSUE TITLE
Ostermark cannot recruit Huntsman Generals

### ISSUE THREAD

**Issue by twohands95** [chadvandy/cbfm_wh3#1226]
**Describe the bug**
Wolfram Hertwig of Ostermark cannot recruit Huntsman Generals at all. The AI cannot do it and you as the player cannot do it using Mixu's Unlocker. Every other Elector Count is able to recruit them.

**Expected behavior**
To be able to recruit Huntsman Generals for the AI or the player using an unlocker.

**To Reproduce**
1. Play as Wolfram Hertwig with an unlocker.
2. Try to recruit a new general.
3. Observe missing tab for Huntsman Generals.
4. Or observe the AI never recruiting them.

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/139687720/4f892894-f9f7-4d7c-9f79-de4b9a92d85e)

**Additional context**
I talked to Mixu, and he confirmed that it was a vanilla bug.

**Comment by Drazhir2** [comment]
Here is the fix (rename to .pack)
[zzz_cbfm_ostermark_huntsmarshal.patch](https://github.com/chadvandy/cbfm_wh3/files/12064418/zzz_cbfm_ostermark_huntsmarshal.patch)

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/605205b8-408f-4145-bab6-805ec069ca1e)

**Comment by Drazhir2** [comment]
Fixed in 4.1.0

**Comment by floskan** [comment]
Removed from main
