### ISSUE TITLE
ksl_streltsi.variantmeshdefinition is missing a weapon variant (Marthenil)

### ISSUE THREAD

**Issue by Marthenil** [chadvandy/cbfm_wh3#123]
Slot name: "weapon_1" should include "ksl_streltsi_rifle_2h_01.wsmodel"

**Comment by Harmandodelavega** [comment]
@Marthenil I think I found the line, should I just change the 2 to a 1?

	<SLOT name="weapon_1" attach_point="be_prop_0" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_props/ksl_streltsi_rifle_2h_02.wsmodel" >
			<META_DATA>audio_melee_weapon_type:axe</META_DATA></VARIANT_MESH>


<VARIANT_MESH>
	<SLOT name="body" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_body_01.wsmodel" >
			<META_DATA>audio_entity_type:wh3_ksl_human_male</META_DATA>			<META_DATA>audio_armour_type:leather</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_body_02.wsmodel" >
			<META_DATA>audio_entity_type:wh3_ksl_human_male</META_DATA>			<META_DATA>audio_armour_type:leather</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_body_03.wsmodel" >
			<META_DATA>audio_entity_type:wh3_ksl_human_male</META_DATA>			<META_DATA>audio_armour_type:leather</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="head" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_head_01.wsmodel" />
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_head_02.wsmodel" />
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_head_03.wsmodel" />
	</SLOT>
	<SLOT name="weapon_1" attach_point="be_prop_0" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_props/ksl_streltsi_rifle_2h_02.wsmodel" >
			<META_DATA>audio_melee_weapon_type:axe</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="weapon_2" attach_point="be_prop_1" />
	<SLOT name="shield" attach_point="be_prop_2" />
	<SLOT name="weapon_3" attach_point="be_prop_3" />
	<SLOT name="weapon_4" attach_point="be_prop_4" />
	<SLOT name="weapon_5" attach_point="be_prop_5" />
	<SLOT name="stump_neck" attach_point="spine_2" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_neck_hu1c.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_neck_hu1c_1.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_right_arm" attach_point="clav_right" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_right_arm_hu1c.rigid_model_v2" >
			<META_DATA>equipment</META_DATA>			<META_DATA>is_stump</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_left_arm" attach_point="clav_left" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_left_arm_hu1c.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_waist" attach_point="root" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_waist_hu1c.rigid_model_v2" >
			<META_DATA>equipment</META_DATA>			<META_DATA>is_stump</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_severed_head" attach_point="neck_0" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_head_hu1c_1.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_head_hu1c.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
	</SLOT>
</VARIANT_MESH>

**Comment by Marthenil** [comment]
An entry needs to be added to the weapon slot so that rifle_01 gets assigned randomly. 
Full file with fix:

```
<VARIANT_MESH>
	<SLOT name="body" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_body_01.wsmodel" >
			<META_DATA>audio_entity_type:wh3_ksl_human_male</META_DATA>			<META_DATA>audio_armour_type:leather</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_body_02.wsmodel" >
			<META_DATA>audio_entity_type:wh3_ksl_human_male</META_DATA>			<META_DATA>audio_armour_type:leather</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_body_03.wsmodel" >
			<META_DATA>audio_entity_type:wh3_ksl_human_male</META_DATA>			<META_DATA>audio_armour_type:leather</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="head" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_head_01.wsmodel" />
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_head_02.wsmodel" />
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_streltsi/ksl_streltsi_head_03.wsmodel" />
	</SLOT>
	<SLOT name="weapon_1" attach_point="be_prop_0" >
        <VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_props/ksl_streltsi_rifle_2h_01.wsmodel" >
			<META_DATA>audio_melee_weapon_type:axe</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/ksl/ksl_props/ksl_streltsi_rifle_2h_02.wsmodel" >
			<META_DATA>audio_melee_weapon_type:axe</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="weapon_2" attach_point="be_prop_1" />
	<SLOT name="shield" attach_point="be_prop_2" />
	<SLOT name="weapon_3" attach_point="be_prop_3" />
	<SLOT name="weapon_4" attach_point="be_prop_4" />
	<SLOT name="weapon_5" attach_point="be_prop_5" />
	<SLOT name="stump_neck" attach_point="spine_2" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_neck_hu1c.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_neck_hu1c_1.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_right_arm" attach_point="clav_right" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_right_arm_hu1c.rigid_model_v2" >
			<META_DATA>equipment</META_DATA>			<META_DATA>is_stump</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_left_arm" attach_point="clav_left" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_left_arm_hu1c.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_waist" attach_point="root" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_waist_hu1c.rigid_model_v2" >
			<META_DATA>equipment</META_DATA>			<META_DATA>is_stump</META_DATA></VARIANT_MESH>
	</SLOT>
	<SLOT name="stump_severed_head" attach_point="neck_0" >
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_head_hu1c_1.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
		<VARIANT_MESH model="VariantMeshes/wh_variantmodels/hu1c/dlc02_blood_pack/dlc02_stump_head_hu1c.rigid_model_v2" >
			<META_DATA>is_stump</META_DATA>			<META_DATA>equipment</META_DATA></VARIANT_MESH>
	</SLOT>
</VARIANT_MESH>

```

**Comment by Harmandodelavega** [comment]
Fixed by CA, thanks Marthenil
