### ISSUE TITLE
Queen Bess/others missing from unit preview

### ISSUE THREAD

**Issue by Torgan82** [chadvandy/cbfm_wh3#1233]
Also feral bears missing from Drycha and Beast lore Treemen skills apparently
![20230718194235_1](https://github.com/chadvandy/cbfm_wh3/assets/139915142/3649989d-23ef-4712-882b-b3f0b308f8fb)
![20230718194308_1](https://github.com/chadvandy/cbfm_wh3/assets/139915142/73bc4e48-5dfc-4c1f-af37-8f55d2440cae)

**Comment by floskan** [comment]
All of this works except rank 7 skills which we fixed @Harmandodelavega

**Comment by Harmandodelavega** [comment]
so it's just the unit preview?

**Comment by floskan** [comment]
> so it's just the unit preview?

Yeah some units, mostly ror, doesn't get previews
