### ISSUE TITLE
Ariel's Chosen + melee attack in forest battles trait doesn't work

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1234]
Not too sure what counts as a forest battle, but even while defending my forest settlements my army doesn't seem to get +8 melee attack.

**Comment by floskan** [comment]
I can't see why it wouldn't work looking at the tables

**Comment by Bogdanov89** [comment]
Could it be that you have to be sitting among literal trees on a manual-battle-map , and the tooltip is wrong/outdated?

Or perhaps the map itself has to have some kind of a "forest" tag, and CA forgot to put it on some of the maps?

**Comment by allenhu0912** [comment]
![20230719140616_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/2e3f4f72-f296-4ad4-95e7-84f660e5a7cf)
Get attacked over the end turn in a forest settlement-> 55 attack on my last waystalker here
![20230719140952_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/3ff01a62-3257-456e-a514-9147aca24fa0)
After the battle, still 55 attack
![20230719141000_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/fd6b61bd-5d23-459f-9674-0893b1f67177)
Other hero in the same stack has Ariel's Chosen

**Comment by Harmandodelavega** [comment]
Did you check in battle?

**Comment by allenhu0912** [comment]
Went back to the savefile to check. Still 55 melee attack
![20230720084456_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/03960405-70a8-47d5-8e87-6b15b81c718f)

**Comment by Harmandodelavega** [comment]
https://discord.com/channels/373745291289034763/581350140942483456/1131656816967831663
