### ISSUE TITLE
Khorne DW Marauders and Chariots affected by two vet Khorne skills 

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1235]
Bloodthirster skill tree has the following oddities:

- Marauders of Khorne dual weapons benefit from skills Khorne's Chosen (infantry) and Overwhelming Stampede (cavalry & dogs/bats ??!)
- Chariots of Khorne benefit from both Forged in Blood (contains all the war machines & chariots) and Overwhelming Stampede

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/40d6b0b4-95c0-4fb6-a716-348034b082b1)

![](https://cdn.discordapp.com/attachments/581350140942483456/1131229201517789347/slika.png)

**Comment by Bogdanov89** [comment]
Yes the "Community Bug Fix Mod - 3-Batch 5" is enabled in my WH3 mod manager v1.37.4

**Comment by Harmandodelavega** [comment]
little correction inbound

**Comment by chadvandy** [comment]
5.1: "Fixed an issue where Marauders of Khorne (Dual Axes) were being affected by the Overwhelming Stampede skill"
"Fixed an issue with Chaos Chariots of Khorne incorrectly receiving buffs from the Overwhelming Stampede Skill"
