### ISSUE TITLE
Settlement defense post-battle options same as settlement attack

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1238]
After settlement defense
![20230720101303_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/4daba837-cc2d-4320-9b66-4dd86acaddf6)
After standard battle
![20230720102534_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/2972d1c3-6dff-4752-b6ca-611496780338)

**Comment by Harmandodelavega** [comment]
https://discord.com/channels/373745291289034763/581350140942483456/1131659349945761983
