### ISSUE TITLE
Wood Elves can equip Young Stag follower on heroes despite having no effect whatsoever

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1239]
Provides +3 leadership to Lord's army, has no effect when equipped by heroes

**Comment by Harmandodelavega** [comment]
This kind of stuff will likely never get fixed for balance reasons https://trello.com/c/V1LGM2N2/592-followers-not-working-for-heroes-lords check comments

**Comment by allenhu0912** [comment]
Technically not a bugfix, but would it be possible to just not allow heroes to equip it? I agree that it would obviously be broken to make it actually work on heroes.

**Comment by Harmandodelavega** [comment]
If you don't allow heroes to equip it, it also won't drop on them.
It also might just not be possible

**Comment by Bogdanov89** [comment]
Yea something like "works only when equipped on a lord" being added as a text to these problematic items description would be phenomenal.

**Comment by mfvreeland** [comment]
@Harmandodelavega When #1537 closes, should this close also? Or does this issue encompass different followers/scopes?

**Comment by Harmandodelavega** [comment]
@mfvreeland it's more than that

**Comment by floskan** [comment]
I will make new issues for all scope issues i find and do something about, so it's easier to remove whatever CA fixes
