### ISSUE TITLE
movement orders for flying units crashes the game

### ISSUE THREAD

**Issue by RowdyDwarf** [chadvandy/cbfm_wh3#126]
Sometimes giving movement orders to flying units crashes the game.
It doesn't happen immediately during a battle, but most of the time I cannot finish a battle because of this.

I started a thread because of this over at the total war forums with all the relevant files attached:
https://forums.totalwar.com/discussion/308180/sky-junks-or-flying-units-cause-the-game-to-freeze-and-crash

This issue is detrimental to pretty much every faction in the game. It really sucks the joy out of the game, yet I'm sceptical if CA will ever get around fixing this, because it appears to be a rare issue. Might even be on my end, though I never had such a problem in WH2.

Build is v2.0.0 15717.2658933, no mods.

**Comment by Cataph** [comment]
so is this specific to the sky junk in certain maps?

asking to understand but it sounds like a non-fixable for us

**Comment by RowdyDwarf** [comment]
No, it happens with the sky-junk, the balloon, furies, the demon prince, longma riders, bloodthirster and flamer chariot of tzeentch. But I suspect it may happen with any flying unit.

I haven't noticed anything regarding specific maps. It happened on maps of the chaos realms, Cathay and in the Empire regions.

**Comment by Harmandodelavega** [comment]
Apparently was a hardware issue, the guy updated his forum thread
