### ISSUE TITLE
Be'lakor's Tzeentch manifestation doesn't get cooldown reduction from tech if Tzeentch is 'ascendant'

### ISSUE THREAD

**Issue by Scrapulous** [chadvandy/cbfm_wh3#1268]
merging in #762
Warriors of Chaos get a rite-style mechanic called Unholy Manifestations. Be'lakor gets one from each chaos god; the Tzeentch manifestation is called "The Curser's Boon." It has a 15 turn cooldown. Be'lakor can research a tech called Boon Maker; one of the effects of this tech is to reduce the cooldown on that manifestation by 5 turns. So far, so good.

Meanwhile, the Warriors of Chaos also have a seasonal kind of mechanic similar to the Beastmen moon thing (I think? I don't beast much). Every ten turns or so a different chaos god becomes 'ascendant,' and when that's the case, all Unholy Manifestations associated with that god become 'more powerful'. I think the way it works is that the game just replaces the basic ones with new ones that look identical and have the same text.

So when Tzeentch is ascendant, the cooldown reduction from that Boon Maker tech does not work, I think because it's a different manifestation just with identical look and feel and CA just didn't realize that they'd need to make the tech's cooldown reduction apply to both.

Good stuff, right?

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed Belakor’s upgraded Unholy Manifestations not having their cooldowns reduced by his unique technologies."

**Comment by Harmandodelavega** [comment]
merging in https://github.com/chadvandy/cbfm_wh3/issues/762
