### ISSUE TITLE
Harald Hammerstorm can fail to spawn after completing his quest as non CoC WoC

### ISSUE THREAD

**Issue by pigwithsnoot** [chadvandy/cbfm_wh3#1274]
mod edit: #1217 mby related

When playing as Be'lakor (Shadow Legion) you can fail to spawn Harald Hammerstorm after completing his quest to kill 3000 guys.

This seems to be a vanilla bug as after it happened to me I searched and found this:

https://forums.totalwar.com/discussion/332717/harald-hammerstorm-not-appearing-bug

**Comment by mfvreeland** [comment]
Does it fail only sometimes or always? It will probably be much easier to fix if it's always.

**Comment by Drazhir2** [comment]
I just tested the Harald rush at turn 4:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/7d96e1f8-f17b-4c3a-abcc-f48631af8908)

Then I tested the long way running a UniqueAgentSpawned listener to see if he spawned for the AI (turn 25), he didn't and spawned properly upon quest completion a few turns later:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/49e92524-90cc-4f39-afb5-eea872179580)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/1edd81be-d130-42ba-9ef7-74881166cf95)

From my testing it looks fine, now if there's a weird trigger to it I have no idea.

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed an issue where Harald Hammerstorm would not spawn when completing his quest as non-Champions of Chaos factions."

**Comment by Harmandodelavega** [comment]
presumed fixed
