### ISSUE TITLE
Zhao Ming's Dragon aerial attacks are using Yuan Bo's attacks

### ISSUE THREAD

**Issue by aimop95** [chadvandy/cbfm_wh3#1277]
**Describe the bug**
When Zhao Ming transforms into a dragon and attacks an aerial unit, the visuals for his attacks are using Yuan Bo's Dragons attacks (Jade fire breath and visual instead of Zhao's orange blade attacks and breath). The sound of Zhao's blades are still there but the visuals are not.

**Expected behavior**
Zhao Ming's dragon aerial attacks should use his unique visuals, not Yuan Bo's.

**To Reproduce**
1. Play as Zhao Ming
2. Transform into a dragon
3. Attack an enemy aerial unit
4. Zhao's breath attacks become jade green and use jade visual effects that are the same as Yuan Bo's, instead of Zhao's unique orange floating blade attack

**Screenshots**
If applicable, add screenshots to help explain your problem. The more in-game text we can see to reference the details in question, the better.

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**

**Comment by Reznovi4** [comment]
![20230909190133_1](https://github.com/chadvandy/cbfm_wh3/assets/144545703/4aa6c349-c8a3-45c1-9b99-5fa963c6f775)
![20230909190134_1](https://github.com/chadvandy/cbfm_wh3/assets/144545703/b4914cae-83d2-4216-b87d-a97531d0173e)

**Comment by Drazhir2** [comment]
Iron dragon uses the Jade dragon meta for FLY_ATTACK_2
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/97bd2626-facc-4e10-bb17-d1047f8e2eb7)

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed an issue causing Zhao Ming to display Yuan Bo’s dragon effects in flying combat animations."
