### ISSUE TITLE
The Changeling and Yuan Bo skill nodes overwritten

### ISSUE THREAD

**Issue by CathayZhao** [chadvandy/cbfm_wh3#1280]
Yuan Bo, Changeling, and Kairos have a unique skill that was overridden by another skill due to skill node location overlapping.
![1](https://github.com/chadvandy/cbfm_wh3/assets/75666345/dbb3b4b4-6e80-439e-b651-b0dd5fe91717)

In my opinion, this is a bug since CA can delete unused skills like top_bar_1 for Yuan Bo, but It is still not clear if this is a bug or if CA decided to not use them.

This small mod I made should fix it, and feel free to use it:
https://steamcommunity.com/sharedfiles/filedetails/?id=3030768780&tscn=1693898026

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1: 

"Fixed the following skills not appearing in game due to overlapping coordinates on the skill node set.
“Lord of Wei Jin” for Yuan Bo
“Iridescent Scrivener” for Kairos Fateweaver
“Master Schemer” for The Changeling"

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
