### ISSUE TITLE
Lord Magistrate can give tacticians stand your ground ability to the whole army

### ISSUE THREAD

**Issue by CathayZhao** [chadvandy/cbfm_wh3#1281]
Lord Magistrate's wh3_dlc24_skill_all_lord_improved_hold_the_line skill's effect scope is general_to_force_own instead of character_to_character_own, so all units in the army will get the tacticians stand your ground ability in campaign.

![2](https://github.com/chadvandy/cbfm_wh3/assets/75666345/9243bd47-e785-4581-97f9-a4c062635703)

**Comment by mfvreeland** [comment]
sick

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"The Grand Magistrate’s Tactician’s Stand Your Ground skill no longer applies to all units in his army. Just himself, the selfish git."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
