### ISSUE TITLE
Malagor has wrong starting spells since update 4.0

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1283]
**Describe the bug**
Malagor in 4.0 starts with generic Lore of Wild great bray shaman starting spells (bray scream & devolve) instead of Flock of Doom and Enfeebling Foe.
Unknown what happens when Malagor gets all of his usual spells unlocked via skill tree, due to the space limit in the "spell sphere" UI.

**Expected behavior**
Malagor the Crowfather should have the Flock of Doom and Enfeebling Foe starting spells.

**To Reproduce**
1. Play as Malagor, check out his starting spells

**Screenshots**
![malagor bug](https://github.com/chadvandy/cbfm_wh3/assets/55892027/07f38c56-38d4-4176-91f0-153196fbd979)

**Additional context**
![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/c112a055-1c63-4a35-9ac0-8ede7ed03997)

https://www.reddit.com/r/totalwar/comments/168k8c2/ca_broke_malagors_starting_spells_lmao/

**Comment by mfvreeland** [comment]
Hotfixed by CA
