### ISSUE TITLE
Broken 3D Portholes for Marauder Horsemasters and Javelinmen

### ISSUE THREAD

**Issue by Totalkeks** [chadvandy/cbfm_wh3#1285]
Since update 4.0 3D Portholes for all Marauder Horsemasters and Javelinmen no longer works, only horse is visible, but not rider.

**Expected behavior**
In every battle porthole is not correctly displayed, riders missing.

**To Reproduce**
Start any battle with Marauder Javelinmen or Horsemasters - WoC or Norsca

**Comment by Drazhir2** [comment]
I have no clue how to fix this but I can confirm:
![marauders_porthole](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b1f762d8-f082-477c-8cea-4d3be5973181)

**Comment by mfvreeland** [comment]
Can this be fixed?

**Comment by Harmandodelavega** [comment]
apparently fixed in 4.1

**Comment by Drazhir2** [comment]
confirmed fixed in 4.1
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/939f0cb5-a174-4a21-a284-1c79e6abb29f)
