### ISSUE TITLE
Aekold Hellbrass does not spawn with his items when playing as not Tzeentch faction

### ISSUE THREAD

**Issue by Beardmath** [chadvandy/cbfm_wh3#1289]
**Describe the bug**
The Windblade and Breath of Life do not spawn when unlocking Aekold Hellbrass as non Tzeentch faction.

**Expected behavior**
When the player unlocks Aekold Hellbrass as any faction that can, The Windblade and Breath of Life should also spawn.

**To Reproduce**
1. Play as Warhost of the Apocalypse/ Heralds of the Tempest/The Decadent Host/ Puppets of Misrule/ Shadow Legion/ Legion of Chaos.
2. Unlock Aekold Hellbrass.
3. Choose either option to spawn Aekold Hellbrass.
4. Aekold Hellbrass spawns without The Windblade or Breath of Life.

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/144474803/d5e5a6e8-9123-4eef-8813-44d6b78dfe35)
![image](https://github.com/chadvandy/cbfm_wh3/assets/144474803/64502fba-debe-4c1e-a94a-6a0f7a54a1b9)

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**
I know what the problem is. The faction set for both The Windblade and Breath of Life are anc_set_exclusive_tzeentch. I found this out by using console commands and looking at https://github.com/Shazbot/WH3-Dump/blob/main/db/ancillaries_tables/data__.tsv
I am just an idiot who knows jack and, wants his game to work.

**Comment by Drazhir2** [comment]
Not yet tested but this should fix the issue (rename to .pack)
[zzz_cbfm_aekold_items.patch](https://github.com/chadvandy/cbfm_wh3/files/12562394/zzz_cbfm_aekold_items.patch)

**Comment by Drazhir2** [comment]
tested it with vilitch, works fine:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/08b7fee6-b945-437b-ac00-804ba7004423)
