### ISSUE TITLE
AI units perform significantly worse on charge at higher battle difficulty

### ISSUE THREAD

**Issue by Jman5** [chadvandy/cbfm_wh3#1291]
Increasing the difficulty while keeping the bonuses at zero makes AI units perform worse. Playing on Easy is the only way to even it out.

No idea if this is something you guys can fix, but [here is my bug report from the forum with screenshots and replays.](https://forums.totalwar.com/discussion/335764/ai-units-perform-worse-at-higher-difficulties#latest)

**Comment by mfvreeland** [comment]
This looks like pretty typical RNG variation to me. How many times did you run these tests?

**Comment by Drazhir2** [comment]
I had a quick look out of curiosity testing the 2 extremes (easy vs VH) and there might well be something to it. I noticed the difference is made really early in the fight, like the AI struggles to deal damage on the charge even though you can see the charge animation.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/78b5ade7-25b7-4961-a8be-76b470e3acb3)

I don't think this is something we can fix btw.

**Comment by mfvreeland** [comment]
@Drazhir2 That's great data, thank you. If the difference is consistently being made early in the fight, that may signal an issue with how charge bonus is being figured, although I'm afraid you're probably right that we can't access stuff at this level.

**Comment by mfvreeland** [comment]
More testing (full explanation of tests in video description): https://www.youtube.com/watch?v=l7y7KO8667o

This isn't a simple scaling issue, unfortunately. Charge bonus seems to be essentially fully nullified for the AI above Easy difficulty, even if it should be absurdly high.

**Comment by Harmandodelavega** [comment]
You've probably checked already but maybe kv_rules has something to do with it, search for "charge" or "difficulty"

**Comment by Drazhir2** [comment]
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/651378d8-48f5-4de1-9b4f-c01371574f4b)

**Comment by mfvreeland** [comment]
> You've probably checked already but maybe kv_rules has something to do with it, search for "charge" or "difficulty"

I did check there, yeah. Unfortunately there's nothing I could find with any affect on this; it seems like a code-level problem entirely.

**Comment by mfvreeland** [comment]
Fixed by CA in 4.0.3
