### ISSUE TITLE
Warplock Jezzails and Ratling Guns Not Firing

### ISSUE THREAD

**Issue by OnlyHeskuin** [chadvandy/cbfm_wh3#1299]
**Describe the bug**
Skaven Ratling Guns and Warplock Jezzails unable to fire. Warplock Jezzails simply don't fire and Ratling Guns are stuck in their animation loop where they lower their guns

**Expected behavior**
Ratling guns and warplock jezzails to fire

**To Reproduce**
1. Play as Skaven
2. Start Battle with Warplock Jezzails and Ratling Guns
3. CWait for enemy to get into range
4. Experience crash/bug

**Comment by Drazhir2** [comment]
Give them a good line of sight and they shoot fine:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/0524ad6d-c042-41b4-a500-1f23e2ced6f8)

**Comment by mfvreeland** [comment]
Line of sight issues are definitely a thing in WH3, but they're aren't specific to these weapons, and we can't do anything to fix them. You can get them to fire if you line them up just right.
