### ISSUE TITLE
Tomb Kings unable to build walls in Khatep starting settlement, Books of Nagash icon off-center

### ISSUE THREAD

**Issue by AmazingTriangularHairMan** [chadvandy/cbfm_wh3#1300]
**Describe the bug**
Khatep of Exiles of Nehek can't build walls in his major starting settlement, Clarak Spire.

**Expected behavior**
Was expecting walls, did not get an option for walls. Clearly a bug, as in the next province over I could've built walls in the major settlement there.

**To Reproduce**
1. Play as Khatep
2. Exist
3. Try to build walls in Clarak Spire
4. Get no walls to build in Clarak Spire

**Screenshots**
Here's two screenshots for comparison. One of the starting province with no walls and one of the next province over, where walls are available.
![20230912123551_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/610d7c06-c45b-4989-aa32-ef1f7f378a58)
![20230912123556_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/fd169975-8d3c-46e2-910c-e563da5efecb)

**Additional context**
I was playing Tomb Kings to check for an entirely different bug where followers and ancilliaries were considered enchanted items and ended up finding this. Tomb Kings also have a few other minor bugs since 4.0 that I'm not sure would warrant separate issues to be opened, like the Books of Nagash icon being off-center or Settra's unique Tomb Prince hero's trait being badly formatted.

![20230912133237_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/ad1a6f2b-aa1d-4ec6-823a-b73185edc03c)
![20230912132402_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/d7951938-6270-48cb-84c7-e13443b70358)

Thank you for your time.

**Comment by mfvreeland** [comment]
The icon part of this wasn't entirely fixed, as the issue can still manifest after a battle or at turn start. I will add to this script to fix it fully at some point.

**Comment by mfvreeland** [comment]
Clarak Spire part of this possibly fixed in 4.1:

"Fixed an issue where defence/garrison buildings could not be built in the Clarak Spire settlement."

**Comment by mfvreeland** [comment]
Confirmed both parts of this are fixed in 4.1.
