### ISSUE TITLE
Tomb Kings unable to build Scorpion Nest in minor settlements

### ISSUE THREAD

**Issue by AmazingTriangularHairMan** [chadvandy/cbfm_wh3#1301]
**Describe the bug**
When playing Tomb Kings, you can't construct the Scorpion Nest in minor settlements. In the second game, it was a tier 4 building but was changed to tier 3 in the third game. Despite this, it is unavailable to construct in minor settlements while Ushabti - which were also lowered a tier - are. I believe this to either be a bug or yet another oversight on CA's part. The tooltip for the building also does not denote that it is unavailable in minor settlements or anything like some other buildings do, it's just not offered.

**Expected behavior**
Expected Tomb Scorpions in minor settlements, cannot get building for Tomb Scorpions in minor settlements.

**To Reproduce**
1. Play as any Tomb Kings faction.
2. Obtain minor settlement.
3. Check for Scorpion Nest building in Advanced Military section.
4. Only get Ushabti offered.

**Screenshots**
Here's screenshots from two different campaigns. For comparison: First one's from a Settra campaign where you can see the building available in a major settlement and the other from a Khatep campaign where it is unavailable in minor settlements as previously stated. I went and checked if this was the case for all four Tomb Kings factions and wouldn't you know it? So it was.

![20230912134113_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/54dc80aa-c5c4-4b45-aaad-5b9c7f6792dc)
![20230912121315_1](https://github.com/chadvandy/cbfm_wh3/assets/138838480/ddbe15b9-e868-4dcf-a947-a9d702631a96)

Thank you for your time.

**Comment by mfvreeland** [comment]
This can be changed via db tables, and your logic seems sound, but it's also possible that this is intended behavior.

**Comment by Bogdanov89** [comment]
Just to add a recent CA reply on this topic:

![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/0ba6cf30-641c-4d16-9df7-c29e2827ba1d)

**Comment by AmazingTriangularHairMan** [comment]
...But then the building's tooltip is wrong

**Comment by AmazingTriangularHairMan** [comment]
Sorry, didn't mean to press that. What I meant to say is that the tooltip posted is wrong. The tooltip there on CA's end doesn't hold up when the building can now be constructed at tier 3. I agree with the comment about there being an excessive amounts of Tomb Scorpions available otherwise. My screenshots were taken without any mods, just the base game.

Admittedly, I'm surprised that CA bothered to respond at all.

**Comment by Grimmys** [comment]
I just started a Tomb Kings campaign today, and this one surprised me.

I don't recall having ever seen before a situation where a (advance) military building of level 3 or less can't be build in minor settlements...
It's true that the change would be quite big, but I think it would be more consistent.

After all, we can already "spam" Ushabti this way, so what's the difference with Scorpions?

**Comment by Harmandodelavega** [comment]
I think there's a few, definitely ones with more levels, but anyways it's too big a change

**Comment by mfvreeland** [comment]
I think CA pretty much confirmed that the way it is right now is intentional.
