### ISSUE TITLE
Wargor replenish troops skill broken

### ISSUE THREAD

**Issue by simos90** [chadvandy/cbfm_wh3#1304]

**Comment by Bogdanov89** [comment]
I recently played a Malagor campaign and was also a bit confused by the hero Wargor army replenishment bonus effect.
In some situations my army seemed to replenish rather fast and in other cases it was much slower.

I am not sure does it require a specific kind of territory (own/allied) to work which is kinda tough for Beastmen, or is it perhaps somehow affected by the Full Moon event bonuses (those happen every ~7 turns for all Beastmen and one of them affects replenishment).

**Comment by simos90** [comment]
> I recently played a Malagor campaign and was also a bit confused by the hero Wargor army replenishment bonus effect. In some situations my army seemed to replenish rather fast and in other cases it was much slower.
> 
> I am not sure does it require a specific kind of territory (own/allied) to work which is kinda tough for Beastmen, or is it perhaps somehow affected by the Full Moon event bonuses (those happen every ~7 turns for all Beastmen and one of them affects replenishment).

it makes no difference either way. if you remove the wargor hero from your army and check how many troops are being replenished without it and then add the hero back to the army the replenishment does not improve. no matter where you are it simply does not work.

**Comment by Harmandodelavega** [comment]
probaly fixed by CA
