### ISSUE TITLE
Incarnate Elemental of Beasts missing from all Beastmen lord skills.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1305]
**Describe the bug**
Beastmen got 2 new units in the SoC dlc - the Tzaangors and the Incarnate Elemental of Beasts.
Tzaangors is properly present in multiple Beastmen lord skills but the Incarnate is completely missing.
Noticed on Morghur the Shadowgave but likely affects all Beastmen lords.

**Expected behavior**
Incarnate Elemental of Beasts (like any recruitable unit) should be affected by at least 2 of the Lord "red line" skills.
My guess is "Freakish Mutations" and "Bestial Butchers".

**To Reproduce**
1. Play as Beastmen with SoC DLC and take a look at the Lord red line skills - the Incarnate is missing.

**Additional info**
Incarnate is present in two Beastmen technologies/research, so its likely CA just forgot to add Incarnate to the beastmen lord skills.

**Comment by Drazhir2** [comment]
known issue: https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/202-known-issue-beastmen-lords-can-t-buff-the-incarnate-elemental-of-beasts-with-their-redline-skills

I agree freakish mutations/bestial butchers is where they should go.

Here is the fix (rename to .pack) couldn't test it properly as I don't own SoC but it's simple enough:
[zzz_cbfm_incarnate_bst_skills.patch](https://github.com/chadvandy/cbfm_wh3/files/13196817/zzz_cbfm_incarnate_bst_skills.patch)

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Added the Incarnate Elemental of Beasts to the Beastmen redline skills 'Bestial Butchers' and 'Freakish Mutations.'"
