### ISSUE TITLE
Magic Wards of Climate Change commandment missing in certain provinces

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1311]
Chimera Plateau and "many others" apparently

adding some screenshots from a previous issue for orientation
![264990682-643dfd89-759c-49d3-a76a-86d604f612ff](https://github.com/chadvandy/cbfm_wh3/assets/66144788/03d4b0f7-bc92-4907-ab8a-21fa6cbbf3dd)
![265300663-60a8fc69-33b5-461e-9df1-9893645fb441](https://github.com/chadvandy/cbfm_wh3/assets/66144788/bd9bf387-53ce-4e34-a02f-b20443171201)

**Comment by Drazhir2** [comment]
are there still some missing? I haven't checked the DB but this "should" be fixed in hotfix 403
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/126db178-acf4-4be6-8885-d023d63b106e)

**Comment by Drazhir2** [comment]
yep I crosschecked with a list of province/region/climates I have in my random stuff and can confirm they added all the ones that were missing:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/85b35465-d886-4e0e-944d-04cdb235bb53)
