### ISSUE TITLE
cathay - building decreasing cost effect doesn't works

### ISSUE THREAD

**Issue by valexis2** [chadvandy/cbfm_wh3#1312]
conscription camps effect that decrease recruitment cost for peasants doesn't works

the first level 1 conscription camps yin should decrease recruitement cost of peasants by 40% in the province, it doesn't work
First time i play cathay, found less than 6 turns after i began the miao ying campaign

it's french but i think you can understand with the pictures
https://www.noelshack.com/2023-38-3-1695169587-20230920-002105.jpg
https://www.noelshack.com/2023-38-3-1695169596-20230920-002118.jpg

**Comment by Drazhir2** [comment]
the effect applies to the local region, not the entire province, looks fine to me:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/2ae312c4-fc53-405b-b8f5-1f8d81ba7984)
