### ISSUE TITLE
Celestial Dragon Guard Plumes Change Color when viewed up close

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1314]
https://steamcommunity.com/sharedfiles/filedetails/?id=3039465239
Fixed by this mod.

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed the colour-changing plumes of the Cathay Celestial Guards."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
