### ISSUE TITLE
Mounted Azhag missing Skullmuncha variant and second weapon

### ISSUE THREAD

**Issue by Shigendo** [chadvandy/cbfm_wh3#1318]
**Describe the bug**
When Azhag is mounted on Skullmuncha, Skullmuncha no longer uses the unique armored variant and uses a generic wyvern variant, also his left hand weapon goes missing.

**Expected behavior**
Skullmuncha should have its unique texture and Azhag should be holding his other weapon while mounted.

**To Reproduce**
Put Azhag on Skullmuncha.

**Screenshots**
What mounted Azhag currently looks like:
![image](https://github.com/chadvandy/cbfm_wh3/assets/95164437/bcfc013a-4e1d-4460-812a-d2054df408b4)

How he appears in WH1 and WH2:
![image](https://github.com/chadvandy/cbfm_wh3/assets/95164437/68d7e189-9eac-49d2-8f6f-112bed29e013)

**Comment by mfvreeland** [comment]
If anyone still has WH2 installed, we could probably pull the variant from there.

**Comment by Drazhir2** [comment]
It's more than a VMD, it's an entirely separate model with its saddle which hasn't been ported over to WH3
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/21d8b479-27a4-4372-9362-a8e9faed2ee9)

If you need the files hit me up on discord.

**Comment by Drazhir2** [comment]
https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/1468-bug-azhag-the-slaughterer-does-not-have-his-unique-skullmuncha-mount

I love the "it is not something we can currently fix as the files no longer exist." like they don't have source control or the warhammer 2 files. But if CA doesn't want to port that model over we are for sure not doing it either.

**Comment by Drazhir2** [comment]
Fixed by Dead Baron https://steamcommunity.com/sharedfiles/filedetails/?id=3143700150
