### ISSUE TITLE
Wrong enslave campaign group member for the Norsca one

### ISSUE THREAD

**Issue by RhoxGSAINT** [chadvandy/cbfm_wh3#1319]
**Describe the bug**
Campaign group member wh_captive_option_enslave_chaos_wh_main_sc_nor_norsca is wrong and has ACTOR instead of ORIGINATOR. Thus, any culture facing Norsca gets to enslave the enemy

**Expected behavior**
Norsca should get the enslave option not the enemy of the Norsca

**To Reproduce**
1. Play as Empire or Dwarf
2. Fight as Norsca and see that you have access to the enslave captive option
3. Start as Norsca
4. Fight non-Norsca culture and you won't have access to the enslave captive option

**Screenshots**
https://discord.com/channels/373745291289034763/581350140942483456/1156014817522487307

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1

**Comment by mfvreeland** [comment]
Looking at what they've done in the DB in 4.1, they've removed enslave options for Norsca/Chaos completely unless they're fighting each other. This puts them in line with other WH1 races, but it's different from Rhox's fix. CA's prerogative, I suppose. Fixed either way.
