### ISSUE TITLE
Drycha Glamoured Expendable listed as negative

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#132]
Since IE launched Drycha faction has the following issues:
- all her elf units receive Glamoured attribute that is supposed to make them Expendable (per faction description) but the Expendable effect is missing.
- her city garrisons became regular WE garrisons instead of Drychas usual themed malevolent tree stuff.

![image](https://user-images.githubusercontent.com/55892027/188363870-00782bbb-e6bb-4a5f-9743-f4a9fd53927c.png)

**Comment by Cataph** [comment]
garrison should be fixed in 2.1

**Comment by mfvreeland** [comment]
Does anyone still have WHII installed? I'd be curious if the expendable part of Glamoured ever worked. I do still have WHII Assembly Kit installed, but looking through there I see no indication that it should work. An effect exists to make all Wood Elf units expendable, but nothing activates it.

I did find a way to add the expendable attribute with Glamoured, but the trouble is that I know of no way to remove it later once Drycha gets her upgraded version of Glamoured.

**Comment by Harmandodelavega** [comment]
> Does anyone still have WHII installed? I'd be curious if the expendable part of Glamoured ever worked. I do still have WHII Assembly Kit installed, but looking through there I see no indication that it should work. An effect exists to make all Wood Elf units expendable, but nothing activates it.
> 
> I did find a way to add the expendable attribute with Glamoured, but the trouble is that I know of no way to remove it later once Drycha gets her upgraded version of Glamoured.

I do what tables do you need

**Comment by mfvreeland** [comment]
> > Does anyone still have WHII installed? I'd be curious if the expendable part of Glamoured ever worked. I do still have WHII Assembly Kit installed, but looking through there I see no indication that it should work. An effect exists to make all Wood Elf units expendable, but nothing activates it.
> > I did find a way to add the expendable attribute with Glamoured, but the trouble is that I know of no way to remove it later once Drycha gets her upgraded version of Glamoured.
> 
> I do what tables do you need, or just msg me I'll do a search for you

I have the tables from Assembly Kit. I'm just curious if you start a WH2 campaign with Drycha, do elf units start as expendable? My suspicion is that they don't.

**Comment by Bogdanov89** [comment]
This is how it looks like on the campaign map:
![image](https://user-images.githubusercontent.com/55892027/192122086-9d55bd64-d08e-4e5b-a06f-9f079d41b198.png)

And this is how it looks like in the manual battle:
![image](https://user-images.githubusercontent.com/55892027/192122104-5f260ea3-fb55-47b8-a976-c227f6a645a6.png)

And this is a screenshot of a Malevolent Dryad after two Wood Elf units were lost in battle (no leadership penalty for dead/routed allies cause they likely have a working Expendable attribute):
![image](https://user-images.githubusercontent.com/55892027/192122149-38f7b8a0-91e7-4555-8099-e2b7a6745ee2.png)

**Comment by mfvreeland** [comment]
> In TWW2 this is how it looks like on the campaign map: ![image](https://user-images.githubusercontent.com/55892027/192122086-9d55bd64-d08e-4e5b-a06f-9f079d41b198.png)
> 
> And this is how it looks like in the manual battle in TWW2: ![image](https://user-images.githubusercontent.com/55892027/192122104-5f260ea3-fb55-47b8-a976-c227f6a645a6.png)
> 
> And this is a screenshot of a TWW2 Malevolent Dryad after two Wood Elf units were lost in battle (no leadership penalty for dead/routed allies cause they likely have a working Expendable attribute): ![image](https://user-images.githubusercontent.com/55892027/192122149-38f7b8a0-91e7-4555-8099-e2b7a6745ee2.png)

Interesting. Honestly, I'm not sure how this is happening based on what  I can see in WH2 Assembly Kit. This may be too annoying to find out, but if Drycha gets her skill that upgrades Glamoured, does that remove expendable? If it doesn't, we can fix this in WH3 easily. If it does, it's iffy. There doesn't seem to be a way that I can see to remove an attribute once it's been added.

**Comment by Bogdanov89** [comment]
Here is a big picture composed of 3 screenshots for Insidious Glamour from TWW 2.
To summarize both the basic Glamour and the upgraded Insidious Glamour work fully & normally, including the Expendable passive.

![insidious glamour](https://user-images.githubusercontent.com/55892027/192920933-a540347a-b6a3-456f-b433-f264a09e5eab.jpg)

**Comment by mfvreeland** [comment]
@Bogdanov89 Thanks for getting those details. I was under the impression that Insidious Glamour removed Expendable, but so long as it doesn't, this should be easy to fix.

**Comment by mfvreeland** [comment]
PR is up. If you want to try the fix early, @Bogdanov89, feel free (.pack attached here)

[drycha_test.zip](https://github.com/chadvandy/cbfm_wh3/files/9670579/drycha_test.zip)

**Comment by Bogdanov89** [comment]
Thanks!
It works properly as far as i can tell.
