### ISSUE TITLE
Greater daemons summoned by greater gate abilities don't have bound spells

### ISSUE THREAD

**Issue by Shanghai-Patriarch** [chadvandy/cbfm_wh3#1321]
Greater daemons were granted bound spells, which is updated a long time ago.
When I play as Slaanesh, I found that the Keeper of Secret summoned by cultist hero still remains in the old version that use wind of magic to cast normal spells.
I haven't checked other daemon factions and I'm not sure whether this should be considered as a bug.
Maybe the technologies that gives greater daemons more bound spells can't work for summoned units, but at least they may at least have the initial bound spells.

**Comment by mfvreeland** [comment]
Maybe fixed for Tzeentch in 4.1 at least? Needs testing:

"Fixed summoned Greater Daemon units having regular spells instead of bound spells."
