### ISSUE TITLE
Slaanesh "Everlasting Gifts" research causing issues in mid-late game

### ISSUE THREAD

**Issue by Coolisron** [chadvandy/cbfm_wh3#1324]
When playing as Slaanesh and researching the "Everlasting Gifts" technology it changes devotee gain from "gifts of Slaanesh" from 5 per turn to 25 per turn. 

Early game this causes no discernable issues but when researched in the mid-late game it completely breaks the "gifts of Slaanesh" mechanic. The break is when all effects of the "gifts of Slaanesh" stop appearing and cease to have any impact on the game. 

I can't tell if this is the result of quintupling the amount of devotees gained or something else.

**Comment by Coolisron** [comment]
I have no idea but I can start a new campaign and test it sometime today or tomorrow.

**Comment by Coolisron** [comment]
I did some testing and the Everlasting Gifts research works fine. A random landmark from a different mod interfered with the "gifts of Slaanesh" mechanic.

This issue can easily be closed and apologies for any wasted time. 

Cheers y'all

**Comment by mfvreeland** [comment]
Thanks for testing thoroughly.
