### ISSUE TITLE
Allied recruitment does not work correctly

### ISSUE THREAD

**Issue by xXAlduin99** [chadvandy/cbfm_wh3#1325]
**Describe the bug**
If you want to recruit allied units from the outposts, the outpost will not have the correct access to the unit roster of the target ally faction. Building Tier 2 and Tier 3 will not change anything, and moving the outpost will also not change the available units. Also, every region seems to have the same available units and not all units that should be available are available.

**Expected behavior**
The allied recruitment should give access to all the units in the province, and if you have a Tier 2 or Tier 3 outpost it should give access to the global roster.

**To Reproduce**
1. Play as any faction
2. Ally with a faction and build a outpost, in the mid or lategame
3. Look at the allied recruitment
4. Try to move the outpost to other regions
5. Build Tier 2 and Tier 3 of the outpost

**Comment by mfvreeland** [comment]
I've noticed this as well, although I think the problem may be with what is displayed rather than what is really available. I've found that I can recruit more than what it said I could recruit when building an outpost. This seems like a new bug, as I don't remember it occurring prior to 4.0.

**Comment by xXAlduin99** [comment]
> I've noticed this as well, although I think the problem may be with what is displayed rather than what is really available. I've found that I can recruit more than what it said I could recruit when building an outpost. This seems like a new bug, as I don't remember it occurring prior to 4.0.

So there are 3 things I found out while playing regarding this.
1. The displayed units are wrong, so yes, you are right, the display is bugged
2. The local allied rucruitment works fine, without issues except the display bug
3. However, the global allied recruitment is completely bugged and does not work at all, you get the local allied recruitment always, despite having a Tier 2/3 outpost

I think it is bugged since the allied outpost recruitment fix for Nakai they did with one of the hotfixes.

**Comment by mfvreeland** [comment]
This was fixed a while back, not sure exactly when.
