### ISSUE TITLE
Wounds Passive does not undo when entity healed above 25%

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1326]
Possibly not a bug. This mod https://steamcommunity.com/sharedfiles/filedetails/?id=3047408500 fixes it.

**Comment by Harmandodelavega** [comment]
intended, was a comment in some patch notes when it was introduced

**Comment by Drazhir2** [comment]
From Patch 2.0.0:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/644730ba-c4ac-4c7f-aa5b-a5eddb943cc5)
