### ISSUE TITLE
Shadows of Change Missing Animations

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1331]
https://steamcommunity.com/sharedfiles/filedetails/?id=3054537925

Shadow of Change left some animations unused. This mod fixes the bugs.

**Comment by mfvreeland** [comment]
See also #1277

**Comment by mfvreeland** [comment]
This fix removed at the request of the mod author, who explained that there are some balance implications to Crowmen and Vortex Beast fixes. The fix for the Iron Dragon, which I independently created before this mod (#1277), will remain.
