### ISSUE TITLE
Tomb King's second dynasty lord Rakhash has wrong trait in tech tree

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1339]
The tech tree says he gives +5% income local province

On the character screen it says this is factionwide. It seems that this is the correct bonus from what I can tell on the campaign map.

**Comment by Drazhir2** [comment]
Looking around looks like the 5% factionwide is indeed the correct one. Here's the fix for the tech tree:
[zzz_cbfm_rakhash.patch](https://github.com/chadvandy/cbfm_wh3/files/13462912/zzz_cbfm_rakhash.patch)
