### ISSUE TITLE
Coatl RoR missing bound spell

### ISSUE THREAD

**Issue by Sp00kyrex** [chadvandy/cbfm_wh3#1340]
**Describe the bug**
The Lizardmen Coatl RoR "Spirit of Tepok" is missing its bound spell "Birona's Timewarp".

**Expected behavior**
The RoR should display both spells Earth Blood and Birona's Timewarp on the unit card. Only Earth Blood is displayed and accessible in-battle.

**To Reproduce**
1. Play as any Lizardmen faction.
2. Unlock and Recruit the Spirit of Tepok RoR.
3. Attack any enemy.
4. While in battle only the bound Earth Blood spell is available.

**Additional context**
I've created a minor DB modification that I think resolves this issue by disabling the "requires_effect_enabling" tickbox in the "unit_abilities_tables" DB.

[zzz_cbfm_coatl_ror_bironas_timewarp.patch](https://github.com/chadvandy/cbfm_wh3/files/13402728/zzz_cbfm_coatl_ror_bironas_timewarp.patch)

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

Fixed the Spirit of Tepok (Coatl) Regiment of Renown unit not having the bound Birona’s Timewarp spell in campaign.
