### ISSUE TITLE
Akshina Ambushers Knock Back Multiple Enemies

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1344]
Documented in the following video (https://www.youtube.com/watch?v=USVyyIASIS8).

**Comment by mfvreeland** [comment]
Splash attacks perhaps?

**Comment by mfvreeland** [comment]
Yeah, it's splash attacks. Probably should be removed, but we can't say for certain this is a bug without CA confirmation.
