### ISSUE TITLE
game crashes when trying to recruit a lord or hero

### ISSUE THREAD

**Issue by adaaaa44** [chadvandy/cbfm_wh3#135]
everytime i try to recruit lord or hero, game just crashes. 0 mods active

**Comment by Cataph** [comment]
dude.

**Comment by chadvandy** [comment]
@adaaaa44 Go to your AppData/Roaming/The Creative Assembly/Warhammer3/ folder, and delete all contents in the saved_characters folder. It's a bug caused by having a modded character saved and then removing that mod. Not something we can fix.
