### ISSUE TITLE
Griffon Riders become Giant while Griffons become Tiny

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1351]
Exactly what the title says. This https://steamcommunity.com/sharedfiles/filedetails/?id=3091106810 mod has fixed the issue.

**Comment by mfvreeland** [comment]
The riders are definitely oversized, but I'm not sure the Griffon models themselves are wrong.

**Comment by mfvreeland** [comment]
This was fixed.
