### ISSUE TITLE
Vassal stays afk and doesn't exist in the diplomacy tab.

### ISSUE THREAD

**Issue by Kaelbar** [chadvandy/cbfm_wh3#136]
Playing as Valkia, second campaign it happens, both time the vassal's faction was destroyed before i took the dark fortress. What happens is that the only option i have to occupy is "occupy and vassalize" which give me the city and raise a new army of the vassal next to the said city. Problem is, the faction doesn't exist in diplomacy, doesn't move, doesn't get attacked. They still exist in war coordination tho, even if they don't move. I've yet to test if by getting attacked next to it they would participate in the battle and if they do, if it's possible to kill them again and "re-raise" them from the dead by giving them another city. I'll update after testing.

Edit : can't say for the first occurrence but the second time said faction had been confederated by wintertooth.
Edit 2 : second campaign second bugged vassal now, i can now say for sure that it happens when the faction was destroyed before the dark fortress is taken since i never got the issue with any faction that was still existing. Can't find anything about them in my event feed so can't say if they were confederated or just destroyed.

**Comment by chadvandy** [comment]
known, can't fix. #2
