### ISSUE TITLE
Miscast Chance Reduction double-dip with CBFM

### ISSUE THREAD

**Issue by otwk** [chadvandy/cbfm_wh3#1370]
It seems that CBFM still has a fix for the Miscast base Chance reduction effect active, despite CA secretely fixing this in Patch 4.0 (or 4.0.X) for most cases (excluding e.g. https://github.com/chadvandy/cbfm_wh3/issues/1369).

I'm playing as the Barrow Legion, with no global Miscast Reduction or anything of the sort, and all my Necromancers only have 5% Miscast Chance, purely from Earthing and three points in the respective spells. This should be 20% (and it is 20% when I turn off CBFM); it seems CBFM causes one of the effects to apply twice.

I'm assuming removal of db/effect_bonus_value_unit_ability_junctions_tables/zzz_cbfm_miscast_reduction_fix would fix this issue.

**Comment by Harmandodelavega** [comment]
The UI tells you how much miscast reduction you have?
Anyways thanks, I wasn't sure they fixed it but thought leaving it in wouldn't do anything

**Comment by Harmandodelavega** [comment]
got it
