### ISSUE TITLE
Kislev/ZharrNaggrund/Weijin/Hexoatl Herdstone bonuses broken effects

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1371]
The three Special Beastmen Herdstones added in Patch 4.1 have broken unique effects. All of them grant bonus recruit rank to Bray-Shamans up until rank 5, when they start granting the effect they were presumably supposed to grant (reduced WoM cost when casting spells for Kislev, Missile Strength bonus for Zharr-Nagrund and increased speed for Wei-Jin). Presumably, what they were supposed to do was grant the specified bonuses in increments of 2% per level. In addition, the replaced effect for Morrsleib's Eclipse (Hexoatl) has broken values as it goes 3 -> 5 -> 3 -> 4 -> 5 when presumably, it should be increasing in increments of 1 at a time.

**Comment by Drazhir2** [comment]
Hexaotl inconsistency:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/f44e58ae-05f8-4c59-9b1f-f0d7183b7078)

That one looks like a botched copy/paste/modify job:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/637676f0-ba0c-4dae-9271-3358769e011c)

**Comment by Autumnchain** [comment]
Another issue with the new Herdstones. They have 1 more building slot than normal, also due to carelessly copy-pasting the Altdorf Herdstone.

**Comment by mfvreeland** [comment]
Maybe fixed in 4.1.3: "Fixed outstanding issues with the three new unique Beastmen herdstone buildings. They will now provide the correct unique effect at all 5 levels and provide the correct number of building slots."

**Comment by Drazhir2** [comment]
effects are fixed:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/ea2658cd-9e6a-4fb7-94e9-8ee14dc4582e)
