### ISSUE TITLE
Skaven Warlock Engineers can establish undercities without a cooldown. 

### ISSUE THREAD

**Issue by ValkenOfAskir** [chadvandy/cbfm_wh3#138]
Back in TW:WH 2, Warlock Engineers had a 10 turn cooldown between establishing undercities and the price for undercities increased per undercity.
For reference https://totalwarwarhammer.fandom.com/wiki/Under-City.

Now in TW:WH 3 the Warlock Engineers can just run from city to city and establish an undercity per turn, without the price increasing. 
The price does seem to change by some kind of source, however it is not permanently increasing per established undercity.

**Comment by ValkenOfAskir** [comment]
Note that I have not tested if two seperate Engineers can establish an undercity on the same turn.

**Comment by chadvandy** [comment]
removed
