### ISSUE TITLE
Chorf trait "Cannonry Experience" range doesn't work

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#1396]
Scope is wrong on range

This part down here is moot since convoys can't get other arty

wh_main_effect_force_stat_ammunition_artillery
wh_main_effect_force_stat_range_artillery

link to sets that use arty class but other than hellcannon chorf arty has chariot class

Use wh3_dlc23_chd_category_warmachines_2 from floskan's fix [zzz_cbfm_convoy_trait_fix.tsv](https://github.com/floskan/cbfm_wh3/commit/e73f1546bb319379c0a788cdef7ac373e6af0a9a#diff-83a3b545e63fcabf21a35c1297bdf8988a8edf37057f0546ee5c3642356beab0)

![image](https://github.com/chadvandy/cbfm_wh3/assets/66144788/1068745b-052a-4937-a1ae-66e2372d6d08)

**Comment by Drazhir2** [comment]
https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/1874-known-chaos-dwarf-convoy-lord-trait-cannonry-experience-bugged?page=1#post-16050
