### ISSUE TITLE
Enemy AI armies across the campaign map are deploying vertically on the battlefield instead of horizontally.

### ISSUE THREAD

**Issue by MechyFoxVT** [chadvandy/cbfm_wh3#1397]
Mod edit: 4.1.4
" Fixed a bug with defensive formation in deployment that was introduced with Hotfix 4.1.0. The bug caused the AI to misalign the army when the deployment zones were not lined up North to South. "

**Describe the bug**
In certain sections of the campaign map, including the Chaos Wastes, various regions of the Empire, Norsca, and some regions of the World's Edge Mountains, enemy armies deploy vertically, leaving vast swaths of their forces defenseless against cavalry and bunches up their units.

**Expected behavior**
These armies should be deploying horizontally like a normal human being.

**To Reproduce**
1. Play any update 4.1 or later.
2. Start a Boris Ursus campaign and manually fight the first battle.
3. The enemy army will be vertically placed. 
4. There are various regions of the map where this occurs, and we're not sure how many maps this bug affects exactly. If somebody can find a way to fix Boris' first battle I have no qualms with figuring out how to set up land battles in as many regions of the map as I can and testing them.

**Additional context**
A large portion of the bug is on the CA forums, yet CA has failed to fix this issue in almost a month and three hotfixes. Wanted to see if a fix could be modded out since it looks like it's not gonna be fixed until CA comes back from the holidays at the very least.

https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/1381-known-bug-ai-armies-setting-up-vertically-moving-army-vertically-instead-of-horizontally?page=1#post-17150

**Comment by CapitaineYolo** [comment]
I can confirm this, have had this happen too in my latest empire campaign fighting festus in hochland

**Comment by mfvreeland** [comment]
I have seen this as well and can confirm the bug, although I am not sure exactly what causes it. I am fairly certain that it isn't something we can fix, unfortunately, as it's a battle AI thing.

**Comment by Drazhir2** [comment]
Looks like CA found the cause https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/1381-known-bug-ai-armies-setting-up-vertically-moving-army-vertically-instead-of-horizontally?page=2#post-21619 so hopefully a fix is coming soon™

It's indeed not something modders can fix.

**Comment by Grimmys** [comment]
Could we put "cant-be-fix" label on this one?
