### ISSUE TITLE
Summoners of rage not benefitting from generic warrior of chaos rank 7+ skill line "Freakish Mutations"

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#14]
![20220826013439_1](https://user-images.githubusercontent.com/34427023/186997214-e427a9b5-de4c-42e3-b582-ccbbbd333796.jpg)
![20220826013445_1](https://user-images.githubusercontent.com/34427023/186997221-c6855e84-8142-498d-9542-3b0351ecd86f.jpg)

No leadership or wardsave buffs visible

**Comment by chadvandy** [comment]
fix by Cataph
zzz_cbfm_chaos_veterans

**Comment by Harmandodelavega** [comment]
Everything but Skullcrushers fixed, deleting the rest
