### ISSUE TITLE
Chaos Chariots, Marauder Horsemen, and Chosen of Tzeentch missing from Tzeentch red skills

### ISSUE THREAD

**Issue by jcm2762** [chadvandy/cbfm_wh3#141]
Hello,

Kairos, the Heralds of Tzeentch, and Exalted Lords of Change (I assume they share same tree - not confirmed) all are missing red line buffs for the Chosen of Tzeentch in their skill trees.  Chaos Warriors and Chosen could receive a barrier buff similar to that of the marauders at the "Accursed Horrors" skill, and Chosen could also receive armour, leadership, and missile resistance at rank 7 or above from the "Armour of Delirium" skill. 

I do have the Champions of Chaos DLC installed. 

Thank you for the incredible volunteer work you and your volunteer team are doing! 
Please email me at jcm2762@gmail.com if you would like further information about this. 

![Kairos Missing Chosen Skills_2](https://user-images.githubusercontent.com/112905003/188511190-e9678bb8-e975-4dc0-8970-0f520917cd15.png)
![Kairos Missing Chosen Skills_1](https://user-images.githubusercontent.com/112905003/188511191-9435579b-2e3d-4267-9b6a-2b6e18fa0332.png)

**Comment by mfvreeland** [comment]
These seem like eminently reasonable suggestions to me, but as this involves a small design choice, I think this is unfortunately a wait-for-CA item.

**Comment by Harmandodelavega** [comment]
His mortal/DaeP lord does get this though, feels bad for Tzeenchers

**Comment by Harmandodelavega** [comment]
would love to fix this but alas

**Comment by mfvreeland** [comment]
This issue has received renewed interest in light of Version 3.0 being released. Chat on Discord suggests consensus on adding Chosen somewhere in the redline. After further consideration, I am inclined to go with the initial suggestions here if everyone agrees with that.
