### ISSUE TITLE
Unbreakable flying units prevent battle from ending

### ISSUE THREAD

**Issue by tomas352000** [chadvandy/cbfm_wh3#1415]
**Describe the bug**
In this case i experienced this when fighting thorek ironbrow with an unbreakable gyrocopter unit, wiping out his army lead to the gyrocopters simply hovering over my army forever refusing to attack, forcing me to retreat and lose the battle that i rightfully should have won

**Expected behavior**
I expect them to engage in melee or retreat from the battlefield to prevent the soft-lock

**To Reproduce**
Play as any faction (in my case lizardmen) and attack a dwarf army that added an unbreakable rune to one of their gyrocopters (Altho this can probably happen with other flying units too)

**Comment by mfvreeland** [comment]
I thought if there were only flying units left, they were forced to land. This has always been my experience. Are you sure there were no other units hiding elsewhere?

**Comment by tomas352000** [comment]
thats not how it works - it applies a leadership penalty to flying units that simply encourages it to attack eventually routs them, however, the same thing cannot happen to an unbreakable unit - leading to a soft lock

**Comment by mfvreeland** [comment]
Ah OK; that makes sense. There is probably a way to fix this using some battle scripting to turn off the unbreakable attribute if only flying units or left, but it will require some investigation. Do you have a save from right before a battle where this can happen, by chance? It would make testing it much easier.

**Comment by Drazhir2** [comment]
I have a more elegant solution to fix Thorek. Seeing as it only comes from the Rune of Stoicism, I propose this fix:

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/68d5cab5-bf2d-4fb7-9ae3-43190e4ad516)

[zzz_rune_of_stoicism_flyers.patch](https://github.com/chadvandy/cbfm_wh3/files/14413422/zzz_rune_of_stoicism_flyers.patch) (rename to .pack)

And we can re-evaluate later if more unbreakable flyers pop-up.

**Comment by mfvreeland** [comment]
Excellent solution @Drazhir2

**Comment by allenhu0912** [comment]
There are other ways to easily get unbreakable flying units. One of the Chorf lords has a flying mount and also has a perk in his skill tree that grants Unbreakable. Bretonnian Lords can get Unbreakable through the Legend trait. Of course anyone can become Unbreakable by defeating Gotrek. Usually the AI will just land and attempt to melee if their last unbreakable flying unit runs out of ammo though, so perhaps only the dwarf flyers need fixing.

**Comment by Drazhir2** [comment]
I would rather put in the easy Thorek fix for now, instead of spending time on a script that will have to be run during each and every battle and see if any more flying unbreakable soft locks get reported.
