### ISSUE TITLE
Exalted hero of Tzeentch can't attack aerial units when mounted on disc

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1419]
https://www.reddit.com/r/totalwar/comments/1axhxk9/the_exalted_hero_of_tzeentch_is_bugged_he_doesnt/

**Comment by mfvreeland** [comment]
I looked into this one a bit today. Mr. ThreeHead can attack ground targets while mounted on the disc, but he seems to have no attack animations for aerial attacks, so he's helpless in an air engagement. Hopefully the animations exist and just weren't hooked up correctly.

**Comment by mfvreeland** [comment]
The animations exist; they were just never assigned to flying attacks. I am tying this fix into the other Tzeentch disc issue in 4.2 (#1422) since we were already modifying this anim set. Tested in custom battle: Mr. ThreeHead can attack in the air now.
