### ISSUE TITLE
New tzeentch units have no disc vfx

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1422]
https://www.reddit.com/r/totalwar/comments/1axbsxu/new_tzeentch_units_lack_particle_efffects_for/

**Comment by floskan** [comment]
I might've been too hasty in removing this: https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/3713-vfx-issues-with-flamers-and-similar-units-in-patch-4-2-1?page=1

Would it look better with your fix @mfvreeland  ?

**Comment by mfvreeland** [comment]
Nah, they added the same stuff I had added; that part works. There may be additional visual bugs, but it's not related to the persistent disc effects.
