### ISSUE TITLE
Charge Audio Missing for Male Cathay Units

### ISSUE THREAD

**Issue by HeuristicVigil** [chadvandy/cbfm_wh3#143]
Editor's edit: in audio_group_sound_assignments_tables
replace this
wh3_cth_human_male	charge		wh3_grp_vocalisation_cathay_male_collision
with this
wh3_cth_human_male	charge		wh3_grp_vocalisation_cathay_male_charge

 If you go to "db/audio_group_sound_assignments_tables", then examine all of the "wh3_cth_human_male" group sounds you will notice that the situation "charge" has the "wh3_grp_vocalisation_cathay_male_collision" incorrectly or deliberately linked. This is a duplication of the same key in the situation "collision". The entity type "wh3_cth_human_female" has the correct group sound "wh3_grp_vocalisation_cathay_female_charge" linked.

This results in an entirely female audio being played for mixed units charging, and silence for all-male units.

**Comment by HeuristicVigil** [comment]
I have a fix in a packfile, but no idea how pull requests work or how to upload here.

**Comment by floskan** [comment]
Can't you drag the pack into a comment? Otherwise you can drop in in the modding den discord!

**Comment by mfvreeland** [comment]
@HeuristicVigil 
If you have a fix in any format, let us know. We can implement it so you don't have to mess with pull requests and all that jazz.

**Comment by Harmandodelavega** [comment]
I remember looking at it and it was pretty easy, sorry but as of know I got a big backlog so I may not prioritize it

**Comment by HeuristicVigil** [comment]
> @mfvreeland 
> If you have a fix in any format, let us know. We can implement it so you don't have to mess with pull requests and all that jazz.

I have a file ready to go. What would be the best way to get it to you?

**Comment by Harmandodelavega** [comment]
@HeuristicVigil deleted a few superfluous lines
