### ISSUE TITLE
Saytang didn't spawn after quest completion

### ISSUE THREAD

**Issue by SeiphSeiph** [chadvandy/cbfm_wh3#1441]
Hello,

First time I'm submitting a bug so sorry if I miss some things 

**Describe the bug**
Playing as Yuan Bo on IE, I finished the two quests to spawn Saytang (1500 kills then get the 6 units) and 20 turns after there is still no Saytang

**Expected behavior**
Gundam should have spawn after the second quest

**To Reproduce**
Steps to reproduce the behavior: I'm not sure how easily it is to reproduce, I saw on Steam discussions / Reddit TotalWar / Official forums that I'm not the only one, some ppl did reload their save few turns before and it worked it seems, but I'm playing on legendary so this is not possible, I will start a new campaign tonight with Yuan Bo to try it again, on very hard.

**Screenshots**
I can add screenshots of the quests completed if needed

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**
I use around 10 mods for UI and graphics

**Comment by Drazhir2** [comment]
Saytang shows up fine in pure vanilla:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/f32b8554-3339-413d-b976-8856f7f56fb7)
