### ISSUE TITLE
Norsca Technologies have Missing Effects

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1445]
New technologies were added to Norsca but this included some oversights:
- Marauders of the West does not give a bonus to sacking Wood Elf settlements.
- A Land Beyond the Mountains does not give a bonus to sacking Chaos Dwarf and Ogre settlements.

**Comment by Drazhir2** [comment]
Here's the fix:
[zzz_cbfm_norsca_tech.patch](https://github.com/chadvandy/cbfm_wh3/files/14455307/zzz_cbfm_norsca_tech.patch)

**Comment by mfvreeland** [comment]
Fix merged to main
