### ISSUE TITLE
Bretonnian lords have mixed up portraits

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1448]
![Skärmbild 2024-03-03 211343](https://github.com/chadvandy/cbfm_wh3/assets/34427023/352abc69-b0d9-4b06-a897-bf8a452b4654)

**Comment by floskan** [comment]
Would this be as simple as just swapping around stuff in portrait_settings until it's right?

**Comment by Drazhir2** [comment]
good luck finding all the variants when there's only 2 different versions:

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/671cb3b2-8959-4fb4-947b-2ddd366d5f66)

unfortunately WH3-Dump doesn't keep history of the ui images so no idea when these were changed.

**Comment by Drazhir2** [comment]
the weird thing is they're all properly named in the bins so someone jumbled the images around?
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b0e4d8fa-ec79-474d-8185-28cd708af5ce)

either re-order the images themselves or play with the bin to link the correct lord to the correct images.

**Comment by Drazhir2** [comment]
To help with the re-ordering here is 1 through 4 in order:

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/deb2820a-c3d8-437a-9c21-0b8a5abb00b0)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/aa1449af-3d11-4f8b-b37c-1adb6005bd2c)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/f01f0b17-5f31-499f-a953-d2950a21193a)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/10d5c554-b9bb-4746-bd5b-14a8a3e4a081)

**Comment by Drazhir2** [comment]
To help with the reordering here is 1 through 4 in order:

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/6fa2f682-f24e-413e-8b6f-f6f138058fc9)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d1775882-4b9e-4b53-bb0a-31b40cf9494c)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d1ccf141-c268-43ab-857e-3a6397bebf78)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/8911c4fc-1761-448e-9d65-36bbddf972b8)

**Comment by floskan** [comment]
Thanks, i'll try to get to this later this week

**Comment by floskan** [comment]
I fixed the variants in the unit card and porthole, but variant 2 in the details screen has both the crest from variant 2 and 3 on top of the helmet. I'm a beginner with using asset editor and can't figure out why it looks like that in game

**Comment by mfvreeland** [comment]
4.2.2: "Fixed an issue with Bretonnia Lords where their unit cards did not match their 3D model"

**Comment by Drazhir2** [comment]
they re-ordered the pictures, they also fixed the double helmets in the VMDs which isn't mentioned in the patch notes
