### ISSUE TITLE
Unknown Bretonnian or Norscan AI faction has never ending turn (Coop IE)

### ISSUE THREAD

**Issue by Arbiter8822** [chadvandy/cbfm_wh3#145]
My buddy and I are playing Empire and Kislev and we are at turn 143, we cannot get past the turn as faction 50(unknown faction either Bretonnian or Norscan) has a turn that doesn't end.

**Comment by Harmandodelavega** [comment]
modded? what mods?

**Comment by Harmandodelavega** [comment]
https://w3.reddit.com/r/totalwar/comments/xnvjs3/rip_my_turn_170_chaos_coop_campaign_this_faction/

**Comment by Harmandodelavega** [comment]
end turn crash has been fixed in 2.2
