### ISSUE TITLE
Chaos Dwarf tech "Weapons of War" missing rank 7 bonus

### ISSUE THREAD

**Issue by Inquisitor-no-5** [chadvandy/cbfm_wh3#1450]
Describe the bug:
"Weapons of War" tech (top right in Military tree) is missing the effect of granting rank 7+ units the "Infernal Engineer" passive ability.

Expected behavior:
The tech granting the "Infernal Engineer" passive ability.

To Reproduce:
1. Play as any Chaos Dwarf
2. Open tech panel
3. Check "Weapons of War" tooltip
4. See that granting "Infernal Engineer" to rank 7+ units is mission from the tooltip

Additional context:
Possibly only a tooltip error, haven't researched the tech in my current game.

**Comment by floskan** [comment]
Seems to be completely removed
