### ISSUE TITLE
Cathay legendary lords loses certain abilities in dragon form

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1456]
Such as deadly onslaught, the red line aoe buffs

**Comment by floskan** [comment]
I'm like 95% sure I had access to it in a Zhao ming campaign I played a while back.. the dragon siblings lost their (specific) spells while in dragon form several times as well.. hard to tell how it's supposed to be though

**Comment by mfvreeland** [comment]
![2024-03-06 17_25_41-Total War_ WARHAMMER 3](https://github.com/chadvandy/cbfm_wh3/assets/112144702/1b4bdfc7-58de-4473-b11c-becd99255c77)
![2024-03-06 17_24_52-Total War_ WARHAMMER 3](https://github.com/chadvandy/cbfm_wh3/assets/112144702/28a11042-9a1b-403a-b54d-7bc0f7b03cf8)

Looks like it's intended.

**Comment by floskan** [comment]
Great that it's clarified at least. I just need to check if the spells available to them in dragon form actually is though
