### ISSUE TITLE
Chaos Sorcerer Lord of Tzeentch (Metal) doesn't have access to the Chaos Warshrine in campaign

### ISSUE THREAD

**Issue by ScavengerSaens** [chadvandy/cbfm_wh3#1457]
Chaos Sorcerer Lords are supposed to get access to their warshrine mounts at rank 14, but Tzeentch (Metal)'s is missing. It doesn't appear in event message, the character loadout drop-down, or their skill page. The hero version and other Sorcerer Lords are unaffected.

**Comment by mfvreeland** [comment]
Confirmed fixed.
