### ISSUE TITLE
Manticores benefitting from wrong 7+ red line

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#146]
Not sure this qualifies as a bug but manticores is under freakish mutations (monsters and war beasts) and not under speed & malice (cavalry and flying units) daemonic fliers is under speed and malice. I don't really know how to move units between buffs without them catching both

**Comment by Bogdanov89** [comment]
Lore-wise Manticores belong under something called "freakish mutations" so perhaps it was intended since they are more of a flying brute and less of a graceful fragile cavalry?
I really do not know how to tell what CA intended here.

**Comment by Harmandodelavega** [comment]
Technically they are both a war beast and a flying unit so we'll just close this one

**Comment by Harmandodelavega** [comment]
ok, maybe it's a bug

**Comment by mfvreeland** [comment]
No consensus on whether or not this should be fixed.
