### ISSUE TITLE
Skaven plagues not applying after agent action.

### ISSUE THREAD

**Issue by jtslugmaster08** [chadvandy/cbfm_wh3#147]
Reproduction steps. 
1. Unlock rite to spawn a plague agent.
2. Use agent on any enemy city.
3. Confirmation of plague success will appear however there is no indication of a plague being spread nor is the plague affect applied either.

Additional notes. I tested on Clan pestilence, but I did hear from others in the steam comment section that it was for other skaven factions as well.

**Comment by mfvreeland** [comment]
I don't think this is fixable via mod. The bonus value that triggers the code to start a plague does not seem to work at all unless there is a Nurgle plague type assigned, and there seems to be no way outside of code to assign a Nurgle plague type (not that this would really fix the issue, either, since Skaven plagues should not be Nurgle plagues).

**Comment by TheTiberon** [comment]
Not sure if this helps but the Clan Pestilens unique undercity building (Grand Plague Cauldron) correctly applies and spreads a skaven plague to the immediate and surrounding regions and armies. 

![20220921132933_1](https://user-images.githubusercontent.com/114020131/191572245-83b6c701-b9fb-4251-ad0e-ab83c7b48b43.jpg)
![20220921132958_1](https://user-images.githubusercontent.com/114020131/191572249-fe5801c0-b0e3-4285-b570-73e76c11a304.jpg)
![20220921133007_1](https://user-images.githubusercontent.com/114020131/191572252-e38e23d0-cb83-4378-bc31-c87f651d880b.jpg)
![20220921133453_1](https://user-images.githubusercontent.com/114020131/191572751-2af405e8-f273-4b4f-80d6-a0dd0164f0f2.jpg)

**Comment by mfvreeland** [comment]
@TheTiberon That's very interesting. I'll dig into this again and see what I can find...

**Comment by chadvandy** [comment]
the building uses a script to apply the plague. It looks like the `infect_with_plague` action outcome exclusively works with Nurgle plagues at the moment. A fix could be using a script to listen for this through a https://chadvandy.github.io/tw_modding_resources/WH3/scripting_doc.html#CharacterGarrisonTargetAction event

**Comment by chadvandy** [comment]
removed
