### ISSUE TITLE
BOON OF CHAOS 'ARCANE EXEMPLAR' DOES NOT UNLOCK FOR CHAOS LORD/EXALTED HERO OF TZEENTCH

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1473]
https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/3882-boon-of-chaos-arcane-exemplar-does-not-unlock-for-chaos-lord-exalted-hero-of-tzeentch?page=1

**Comment by floskan** [comment]
@mfvreeland Is this something that can be integrated somehow into the boon fix you currently have out?

**Comment by mfvreeland** [comment]
Yes, I will take a look.
