### ISSUE TITLE
Cockatrice and Manticore in monstrous rank 7 red line instead of flying

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1494]
#146

**Comment by floskan** [comment]
Ok i saw this being a discussion earlier. I'll make a pack for this and then you guys decide if manticores and cockatrice should be moved to flying or not

**Comment by Harmandodelavega** [comment]
Didn't the manticore have the same problem? It should be wherever it is. Anyways it's technically monstrous so I wouldn't sweat it
