### ISSUE TITLE
Beasts of nurgle not affected by "Savage bloodlust" red line buffs

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#15]
![20220827201233_1](https://user-images.githubusercontent.com/34427023/187043050-8b195b68-babb-471a-9434-41a4997d24f2.jpg)

No charge bonus or armor

**Comment by chadvandy** [comment]
seems like they should be in unit set `chs_daemon_monsters_beasts`?

**Comment by Cataph** [comment]
yeah they are still in suspiciously few sets, still a bug in 2.1
