### ISSUE TITLE
Celestial general on Longma don't cause fear 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1503]
https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/3915-we-re-almost-there?page=1

**Comment by floskan** [comment]
Did CA stop having unit changes in their patch notes? Feels like I've missed more of these since I only found this looking at the diff

**Comment by mfvreeland** [comment]
Good catch! CA forgets to mention things like this often, unfortunately.
