### ISSUE TITLE
Hide in forest inconsistencies

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1504]
https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/3927-hide-in-forest-inconsistencies?page=1

Malagor the Dark Omen has hide in forest (he shouldn't have it since he is a flying unit)

Several monstrous infantry units do not have hide in forest, despite being supposed to:

    Minotaurs of Khorne (both variants)
    K'daai Fireborn

Several chariot units do not have hide in forest, despite being supposed to:

    Light & Heavy War Sleds
    Exalted Seeker Chariot
    Herald of Slaanesh (both chariot mounts)
    Alluress (both chariot mounts)
    Gorebeast Chariots of Khorne
    Blood Shrine of Khorne
    Herald of Khorne (Blood Throne mount)
    Bloodreaper (Blood Throne mount)
    Settra (Chariot of the Gods)
    Black Coach

**Comment by Harmandodelavega** [comment]
I'm not so sold on these big single entity chariots and warmachines having hide but whatever

**Comment by floskan** [comment]
The majority of added units are heroes and lords on chariots and the respective unit they use as mount already have hide in forest
