### ISSUE TITLE
Hag witch projectile bugs

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1505]
https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/3926-hag-witch-projectile-bugs?page=1#post-40320

**Comment by mfvreeland** [comment]
Has anyone attempted to simply change the trajectory type in the DB to see if that fixes it?

**Comment by floskan** [comment]
I asked that in the forum thread as well, but I can try it out
