### ISSUE TITLE
MyMod->Import not working

### ISSUE THREAD

**Issue by DontCallMeDari** [chadvandy/cbfm_wh3#151]
I'm trying to apply some bug fixes per the readMe.  I have it cloned on my computer but when I go to MyMod -> Import, nothing happens.  

It's my first time using gitHub so I might have done something wrong there.
The path for the repository is "C:\Users\[I'm not posting my real name]\Documents\Mod Backups\MyMod\zzz_community_bugfix_mod" and if I look in the "cbfm_wh3" subfolder I do see the folders for the mod.

My MyMod folder path is "C:/Users/[I'm not posting my real name]/Documents/Mod Backups/MyMod" if that matters.

**Comment by DontCallMeDari** [comment]
Just to clarify, clicking import does make RPFM recognize that I have changes to the pack file, but the file is empty, no tables or scripts.

**Comment by DontCallMeDari** [comment]
So I got it to import the pack by changing the location of the git pull, but now it's not properly reading the files, all the tables in db are not being read and I can't add to them.

**Comment by Harmandodelavega** [comment]
The issues is not the place for it but while we're at it I'll say I had similar problems

**Comment by Harmandodelavega** [comment]
better ask in the modding discord
