### ISSUE TITLE
No ally recruitment except Dreadspears from Lokhir despite higher tier military buildings (Co-op)

### ISSUE THREAD

**Issue by Velykos** [chadvandy/cbfm_wh3#154]
Not sure if anyone has had an issue with DEs as a whole, whether it's just Lokhir, or whether there's some CA oversight somewhere

But I was completely unable to recruit from my player ally, no matter what military buildings they bought. Just dreadspears.

**Comment by Harmandodelavega** [comment]
You were Lokhir?

**Comment by Velykos** [comment]
No I was Vilitch
My partner was Lokhir
