### ISSUE TITLE
Burning Chariot of Tzeentch not included in missile damage buffs from "Many-Coloured Fires"

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1541]
![Skärmbild 2024-04-11 140302](https://github.com/chadvandy/cbfm_wh3/assets/34427023/6f40fd33-9530-4ab1-ae22-d28f52960415)

Should def get the buffs as well. Can't check DB's now if they actually get them though

Looks like another copy paste job for another one of Daniels effects

**Comment by floskan** [comment]
Confirmed by CA to be a bug

**Comment by mfvreeland** [comment]
5.0.3: "Where an effect applied only to Flamers and Exalted Flamers of Tzeentch (and sometimes Changebringers), it now always applies to Changebringers and Burning Chariots of Tzeentch as well"

**Comment by Drazhir2** [comment]
looks fixed, they swapped to another unit_set
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/6895b5f8-c1ec-48a6-b21c-bfd0847d9ead)
