### ISSUE TITLE
Waaagh doesn't get upgraded to Big Waaagh when Waaagh gets called

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1548]
Applies to generic and LL Waaaghs
![Skärmbild 2024-04-13 153931](https://github.com/chadvandy/cbfm_wh3/assets/34427023/7b96e741-5188-422e-90de-bef0021de3fb)
![Skärmbild 2024-04-13 160922](https://github.com/chadvandy/cbfm_wh3/assets/34427023/bf566e74-02ee-44de-b2d3-0e42602b1726)

**Comment by floskan** [comment]
Works for the player 
![Skärmbild 2024-04-13 163548](https://github.com/chadvandy/cbfm_wh3/assets/34427023/e4ce8e1c-f097-412d-8d70-f1896132a9ce)

![Skärmbild 2024-04-13 163541](https://github.com/chadvandy/cbfm_wh3/assets/34427023/3391295e-2031-4b97-85f8-25f7b4d7edb0)

**Comment by Harmandodelavega** [comment]
some wh2 bugs which might have not been fixed
https://github.com/chadvandy/cbfm_wh3/issues/709
https://github.com/chadvandy/cbfm_wh3/issues/710

**Comment by mfvreeland** [comment]
Reposting from Discord:
I had chance to dive a little deeper into the campaign waaagh script, and while I don't really understand their thinking behind it, it seems pretty clear that CA definitely intended for the upgraded waaagh abilities to only go to the player(s). There are numerous explicit checks for whether or not the faction in question is human-controlled made before every instance that updates these abilities. It was undoubtedly designed this way on purpose, which makes its status as a bug questionable (unlike the AI not using the basic abilities in battle, which I think absolutely is a bug).

I still think it could be changed so the AI gets the upgraded abilities, but I'm iffy about adding this to CBFM now.

**Comment by floskan** [comment]
I'm fine with whatever! What we have with the fix is still miles better then nothing

**Comment by Harmandodelavega** [comment]
Did the AI get it in WH2? I think that would settle it

**Comment by floskan** [comment]
Seems like the ai starts with higher base reputation after finishing their waaagh then the player does

**Comment by mfvreeland** [comment]
The AI also semi-randomly gets reputation boosts. Basically, their design is totally different, presumably because CA didn't think the AI could normally perform well enough to get Waaaghs. It's a system that could probably use retuning, but I worry that messing with it gets into the realm of balancing more than bug fixing.

**Comment by mfvreeland** [comment]
FYI, this does not appear to have been changed in 5.0 (script still explicitly limits Big Waaaagh abilities to human players). I am still chalking this up to CA design, however mysterious.
