### ISSUE TITLE
Virulent contagion upgraded doesn't spread beyond the first target

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1554]

**Comment by floskan** [comment]
Confirmed bug, this is probably scripted because i can't find the upgraded ability in the db

**Comment by Drazhir2** [comment]
not scripted, there are 2 different spread settings
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/a77c5928-7fe0-4687-a23d-f363adeea248)

but both regular and upgraded use the same
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/055612c3-3cae-4e88-86c5-a7ae5ebaf91d)

maybe have a go at assigning the upgraded spread to the upgraded ability phase.

**Comment by floskan** [comment]
> not scripted, there are 2 different spread settings ![image](https://private-user-images.githubusercontent.com/135981276/323153220-a77c5928-7fe0-4687-a23d-f363adeea248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTkyMzEsIm5iZiI6MTcxMzM1ODkzMSwicGF0aCI6Ii8xMzU5ODEyNzYvMzIzMTUzMjIwLWE3N2M1OTI4LTdmZTAtNDY4Ny1hMjNkLWYzNjNhZGVlYTI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMzAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQ1Njg3ZDI2NGQ2YTM5MzE3NTliMDk2NTMwMjc0YTM0MDlkM2Q4YTZlYzQzMWZlNmMyYTgyZDJhMmEzOGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wRZIdKXV4IBpRiy3pgvHYPkMAuKK-dApCEP5xaO4Ky0)
> 
> but both regular and upgraded use the same ![image](https://private-user-images.githubusercontent.com/135981276/323153407-055612c3-3cae-4e88-86c5-a7ae5ebaf91d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTkyMzEsIm5iZiI6MTcxMzM1ODkzMSwicGF0aCI6Ii8xMzU5ODEyNzYvMzIzMTUzNDA3LTA1NTYxMmMzLTNjYWUtNGU4OC04NmM1LWE3YWU1ZWJhZjkxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMzAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODlkNDNlMmFiZTE2MDYwMDJjOTY4MjQyNmMxNTUyYzQ0MDc4NDQ4NDRlNTUzMzNkNjc5MmYyNDdkMTQwYWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JY9XxD7Vu5ddv1lGuzZXRK8j4aXHiSvNZw3MRTqg0ko)
> 
> probably need to assign the upgraded spread to the upgraded ability phase. Certainly worth a try.

Yep it wasn't more to it then that, thanks

**Comment by floskan** [comment]
<img width="601" height="74" alt="Image" src="https://github.com/user-attachments/assets/84daed73-c808-46d4-9753-bb2852f8503e" />
