### ISSUE TITLE
Oglok the 'Orrible has different lord traits in tech tree vs actual lord (tech tree is wrong)

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1555]
![20240414111902_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/23ca668b-5b2e-4359-9be5-fa5a976326eb)
![20240414112110_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/9caf0140-a81c-4675-abdf-b64634c435e4)

**Comment by mfvreeland** [comment]
5.0.3: "Fixed the tooltip in the Greenskin technology tree for Oglok the 'Orrible's trait displaying the wrong effects"
