### ISSUE TITLE
Aspiring Champions ror not benefitting from ritual staff

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#156]
halberd ror also needs MD and expert charge defence

**Comment by floskan** [comment]
Can't make adding wh3_dlc20_chs_inf_aspiring_champions_mtze_ror to wh3_dlc20_chs_spear_halberd_units_rank_1 to 9 work

**Comment by floskan** [comment]
https://forums.totalwar.com/discussion/319451/the-tech-that-buffs-halberd-units-for-vilitch-doesnt-affect-the-aspiring-champions-ror

**Comment by Harmandodelavega** [comment]
they added a non ror rank 1 set
