### ISSUE TITLE
Daemon slayer yellow skill line costs 3 per skill instead of the regular 2 per skill for lords

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1573]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/569-deamon-slayer-lord-yellow-line-skills-are-3-2-pt-cost-instead-of-2-1-pt?page=1

**Comment by Drazhir2** [comment]
missing wh3_dlc25_skill_node_dwf_daemon_slayer_self_04 from the fix

**Comment by floskan** [comment]
Yes, theres no lord variant available

**Comment by mfvreeland** [comment]
5.0.4: "Fixed an issue where some generic combat skills in the Daemon Slayer's skill tree used the hero variants (three levels instead of two that lords usually require)"

**Comment by Drazhir2** [comment]
fixed except 11 where we put colossal_strike instead

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d0f2eba9-2079-45d7-987f-7e634aa6e903)

**Comment by floskan** [comment]
Do we agree that they should have colossal strike?

**Comment by mfvreeland** [comment]
> Do we agree that they should have colossal strike?

I would say yes. CA explicitly stated on Discord at some point (IIRC) that their intent was to replace Deadly Onslaught with Colossal Strike for all anti-large heroes.

**Comment by floskan** [comment]
Might be fixed by 5.1.0

**Comment by mfvreeland** [comment]
Not fixed in 5.1.
