### ISSUE TITLE
New dlc characters mounts can be stolen

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1577]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/587-elspeth-mount-can-be-stolen-if-losing-a-battle?page=1

**Comment by Drazhir2** [comment]
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/63e77df8-9bc4-44de-ad5b-81f0a8c8828f)

**Comment by mfvreeland** [comment]
5.0.3: "Fixed an issue where some mounts could be stolen post-battle, sorry Bubebolos."

**Comment by Drazhir2** [comment]
Fixed in 5.0.3
