### ISSUE TITLE
The Runesmith's New Learned Intuition Skill has the Wrong Scope for one or more Effects

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1578]
The Ambush Defence Chance has a scope of "Lord's Army" which is useless for a hero.

**Comment by mfvreeland** [comment]
5.0.3: "Fixed the Runesmith skill "Learned Intuition" having a lord's army scope instead of a hero's army scope."

**Comment by mfvreeland** [comment]
Scope for `wh_main_effect_force_army_campaign_ambush_defence_success_chance` was fixed, scope for `wh_main_effect_general_mod_tunnel_interception_chance` was not, scope for `wh_main_effect_character_mod_ancillary_drop	1` we actually never needed to change.

**Comment by floskan** [comment]
Wasn't ancillary drop set to character to character own?

**Comment by mfvreeland** [comment]
Yes, but that's typical. Heroes can get ancillaries, too.

**Comment by floskan** [comment]
Hm, are you sure it works when it's in an army? I've seen plenty of threads on reddit and the forums where people complain about it doing nothing..

**Comment by mfvreeland** [comment]
I'm fairly certain. The scope for `wh_main_effect_character_mod_ancillary_drop` is almost always `character_to_character_own`. If that doesn't work here, then it doesn't work in 1,000 other places.

**Comment by floskan** [comment]
Yeah that's what I'm worried about

**Comment by mfvreeland** [comment]
I think it _should_ work, since characters get ancillaries, not armies/forces. If it doesn't work for heroes when they're embedded -- but it does when they're acting as agents -- then really we would need to add a new separate effect for each instance; replacing the scope would just invert the problem so that it _only_ works when heroes are embedded.

**Comment by Drazhir2** [comment]
heroes on the campaign map don't drop ancillaries, it's done post battle, the **wh_main_effect_character_mod_ancillary_drop** effect explicitly applies to the **post_battle_ancillary_drop_chance_mod** bonus value.

It should be fairly easy to test, you can dump **character_interface:post_battle_ancillary_chance()** of the lord before and after getting the skill with the hero.

**Comment by mfvreeland** [comment]
> It should be fairly easy to test, you can dump **character_interface:post_battle_ancillary_chance()** of the lord before and after getting the skill with the hero.

Well shoot, if the only test that matters is testing the *lord* post-battle, then no testing is required: @floskan was absolutely right and this problem exists in many places. Do heroes have their own ancillary drop chance that's calculated post-battle? That's the only way these skills would be doing anything.

**Comment by mfvreeland** [comment]
> so any hero skill (assuming the lord ones work correctly) in this list doesn't work? (not even thinking about ancils yet)

Evidently, yup. That's a lot of broken stuff.

**Comment by Drazhir2** [comment]
I'm afraid I have slightly bad news but it looks like agent_to_parent_army_general_own doesn't work either, same steps as before:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/7b20a8fe-fbbb-4dbe-ac6f-e624d84f3e18)

**Comment by mfvreeland** [comment]
That's... odd. `agent_to_parent_army_general_own` is the scope that the basic scouting option uses, and I thought that one worked?

**Comment by Drazhir2** [comment]
Yep agent action scouting works, that's the 25% difference you see, no trace of the extra 15% though.

**Comment by mfvreeland** [comment]
Do we know for sure that embedded heroes can't get post-battle ancillaries themselves? This process all appears to happen in code, so I guess we can't know, but will `hero_character:post_battle_ancillary_chance()` return a value? Maybe it is used.

**Comment by Drazhir2** [comment]
I am very sure heroes don't drop ancils from battle. That being said did I bork my second test? I just ran it with full character logging out of curiosity and it's working with agent_to_parent_army_general_own

```
[out] <75.0s>    DRZ[1] wh2_dlc17_dwf_thorek -25		first tick
[out] <75.0s>    DRZ[1] wh_main_dwf_runesmith -25
[out] <75.0s>    DRZ[1] wh_main_dwf_lord 0
[out] <133.7s>   DRZ[1] wh2_dlc17_dwf_thorek -25	runesmith fully skilled
[out] <133.7s>   DRZ[1] wh_main_dwf_runesmith -25
[out] <133.7s>   DRZ[1] wh_main_dwf_lord 0
[out] <164.7s>   DRZ[1] wh2_dlc17_dwf_thorek 15		runesmith embedded
[out] <164.7s>   DRZ[1] wh_main_dwf_runesmith -25
[out] <164.7s>   DRZ[1] wh_main_dwf_lord 0
```

**Comment by floskan** [comment]
So.. the scope is actually working? The one i used I mean

**Comment by mfvreeland** [comment]
Yep!
