### ISSUE TITLE
Non-overcasted Final Transmutation has gotten a 75% damage decrease (Typo)?

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1579]
Looks like they missed adding a 1 when changing the tables

**Comment by mfvreeland** [comment]
5.0.3: "Reverted oversight causing final transmutation to deal about a quarter the intended damage when not overcast"

**Comment by Drazhir2** [comment]
back to 133 dmg in 5.0.3
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/3cbbd3a0-877f-4062-8e77-d7ec37106612)
