### ISSUE TITLE
Karl franz innate skill boosting elector count state troops is missing ap damage

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1582]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/623-karl-franz-innate-skill-doesn-t-affect-melee-ap-damage?page=1

**Comment by floskan** [comment]
Here's another one, i'm getting worried we have some random fix that doubles the effects of buffs or something similar..

**Comment by mfvreeland** [comment]
Good catch. All we can do is keep an eye out for others.
