### ISSUE TITLE
Doomfire Warlocks/Waywatchers weapon animation bugs

### ISSUE THREAD

**Issue by AncestorGod** [chadvandy/cbfm_wh3#159]
Hi I would like to report some of animations bugs Ive seen so far

- Doomfire Warlocks are just missing their swords( regular unit and RoR variant).
- Waywatchers are using high elf bows when shooting( when they stand idle they use their proper waywatcher one).

**Comment by Harmandodelavega** [comment]
mby relevant

https://trello.com/c/uR8cAoUL/395-ellyrian-reaver-archers-glade-riders-glade-lord-on-horse-lean-to-the-left-when-they-gallop

https://trello.com/c/kKIjjfLB/394-waywatchers-swords-pop-up-from-their-waist-and-stick-to-their-hands-when-they-fire-left-right-or-backwards

**Comment by mfvreeland** [comment]
Is this bug still present?

**Comment by Harmandodelavega** [comment]
swords apparently fixed the other I'm gonna merge with another issue
