### ISSUE TITLE
Missing bonus recruitement for Karl Franz 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1591]
Since last patch (5.0) Karl's skill "Best of the empire" doesn't apply the +2 bonus to units lvl during recruitement.

The bonus is well mentionned in the campain effects of the caracter, but has no real effect. 

EDIT: The effect only applies to elector count units. Should we change the locs or somehow make him give two chevrons to all units recruited normally as well?

**Comment by floskan** [comment]
It uses wh3_dlc20_effect_increased_rank_woc_recruitment_panel

**Comment by mfvreeland** [comment]
It looks like CA fixed this by changing the effect to apply to all_units, which should work. Assumed fix in 5.1.
