### ISSUE TITLE
Chaos Lord of Nurgle can't be ascended when it reaches rank 15 (Nurgle factions) or get their ascended trait

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1595]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/666-chaos-lord-of-nurgle?page=1

**Comment by mfvreeland** [comment]
5.0.3: "Fixed an issue where Chaos Lords of Nurgle would not ascend to Daemon Princes when playing as Nurgle factions"

**Comment by mfvreeland** [comment]
Confirmed fixed in script.
