### ISSUE TITLE
Texture bugs

### ISSUE THREAD

**Issue by AncestorGod** [chadvandy/cbfm_wh3#160]
Hi I noticed couple of texture bugs:
- Arcane Phoenixes uses their RoR texture
- Cold One Dread Knights mounts are using Malus Spite textures
- Repanse mount, Suleman, is using generic bretonnian barded horse texture

**Comment by mfvreeland** [comment]
I can confirm the Rapanse mount issue. It's not just a texture bug, though: Rapanse is really just using a Grail Guardian mount variant. This was easy to fix in the DB for my Balanced Cavalry Speeds mod, though. I'll port that fix here and take a look at the other two.

**Comment by mfvreeland** [comment]
Can't confirm the Arcane Phoenix or Cold One Dread Knights are bugs. Everything appears correct in the DB for them. I will add the fix for Suleman.
