### ISSUE TITLE
Tamurkhan not having regular (non-chieftain) toad dragons buffed by his innate and other chieftain unit set issues

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1601]
Will add chieftain variants of nurgle units where missing

**Comment by floskan** [comment]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1211-tamurkhan-does-not-buff-all-non-demonic-units?page=1 Missing more units + dogs

**Comment by chadvandy** [comment]
5.1: "Effects that apply to Nurgle units should now also apply to Tamurkhan's Chieftain's units"

**Comment by mfvreeland** [comment]
Confirmed fixed by CA in 5.1
