### ISSUE TITLE
Miao Ying's item set costs upkeep

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1613]
![屏幕截图_231_](https://github.com/chadvandy/cbfm_wh3/assets/34427023/fd2b25a6-dfd8-4c8e-afca-756d82283950)

**Comment by mfvreeland** [comment]
5.0.3: "Fixed the effects provided by Miao Ying's quest item set"

**Comment by mfvreeland** [comment]
This was actually supposed to provide allegiance points, evidently. CA converted the upkeep cost into an allegiance point bonus.
