### ISSUE TITLE
The shockwave radius of dwf_scannon_ball_grapeshot should be changed from 3 to 0.3 ( Like empire cannons)

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1618]

**Comment by mfvreeland** [comment]
5.0.3: "Adjusted Dwarf grape shot to be in line with the imperial grape shot. Curtailing excessive shockwave radius around each projectile."

**Comment by Drazhir2** [comment]
Fixed in 5.0.3:
- shockwave radius is now 0.3 
- they also changed marksmanship bonus, projectile mass and few other bits.
