### ISSUE TITLE
WoC portraits in the lord recruiment/replacement panels look wonky

### ISSUE THREAD

**Issue by sm0kin** [chadvandy/cbfm_wh3#162]
![woc_wonky](https://user-images.githubusercontent.com/42816583/188858843-8b536b5a-e76f-4a1c-9753-619fe2290c98.png)

Looks like something is wrong with the portraits.

**Comment by chadvandy** [comment]
it's... beautiful

**Comment by mfvreeland** [comment]
Did they fix this in 2.2?

**Comment by mfvreeland** [comment]
Pretty sure this was fixed, and if it wasn't, well it's beautiful anyway.
