### ISSUE TITLE
No Nurgle Authority Skill for Chaos Sorcerer of Nurgle 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1626]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/807-no-nurgle-authority-skill-for-chaos-sorcerer-of-nurgle?page=1

**Comment by mfvreeland** [comment]
5.0.4: "Fixed an issue where Chaos Lords of Nurgle and Chaos Sorcerer of Nurgle variants were missing their Nurgle Authority skills"

**Comment by floskan** [comment]
And 5.1.0 might have fixed Seal of sickness being missing from Chaos lords of Nurgle

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1
