### ISSUE TITLE
Balthazar Gelt/Elspeth doesn't get mastery of elemental winds from Temple of elemental winds

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1631]
"The new landmark that gelt gets in Cathay that gives all battle wizards mastery of elemental winds doesn't give him the ability. I would assume this is a bug/oversight since it makes wizard squad idea not as fun due to gelt being weaker than all his wizards."

Opinions on this?

I feel they should have it, no real harm in Gelt being on par with wizard heroes

**Comment by allenhu0912** [comment]
This doesn't seem to work for Gelt with Steam Workshop version of CBFM, even though he has Mastery of Elemental Winds his spell intensity is still 100%

![20240526101829_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/74a8dc58-e9ea-4e47-9b3c-a148c6addcb1)
![20240526101835_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/2556d1d2-8af7-45bb-ae25-51954a6b6246)

**Comment by allenhu0912** [comment]
Never mind, the actual spell does show spell intensity when I prepare to cast, just that this tooltip in particular seems to be bugged.
