### ISSUE TITLE
malakai beer taps tier 4  don't provide liquid fortification to the army they are in.

### ISSUE THREAD

**Issue by Chrismmar** [chadvandy/cbfm_wh3#1642]
**Describe the bug**
for some reason, when you upgrade the beer taps from teir 2 to teir 4. they forgot to keep the buff onto the army its embedded into.

**Expected behavior**
it should buff both the army its in, and any army in its circle of influence.

**To Reproduce**
1. Play as Malakai.
2. upgrade beer tap from tier 2 to tier 4
3. shoot yourself in the foot
4. Profit?
I tested it multiple times in different saves and it always happens.
**Screenshots**
Before I upgrade
https://cdn.discordapp.com/attachments/883074111763529798/1235720833398214767/image.png?ex=66356635&is=663414b5&hm=9068c955658d9a5e63ce6bd2939565a5d0092f67c0e26a11a5c78d301cef3400&

after I upgrade
https://cdn.discordapp.com/attachments/883074111763529798/1235720890105462814/image.png?ex=66356642&is=663414c2&hm=594bceec052b1c230fdceb5e9fa033fed71f504d9aa799896bcfbeec4e5800c4&

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**

**Comment by Chrismmar** [comment]
it is from the beer taps building, the second level of it says it gives liquid fortification.

**Comment by Drazhir2** [comment]
Yeah no.

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/bc165757-3c2b-451d-82fb-875490f11d20)

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/0cc44ed3-d793-4036-883f-00e5ea6715b4)

Liquid Fortification is only found on the tankard ancillary, bugman's rangers and a copy from eltharion's dungeon mechanic.
