### ISSUE TITLE
Bankruptcy attrition issues

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1649]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/890-double-upkeep?page=1

**Comment by chadvandy** [comment]
5.1: "Fixed issue where bankruptcy attrition was being applied a turn early"

**Comment by AphyriaCelosia** [comment]
![image](https://github.com/chadvandy/cbfm_wh3/assets/173944160/0c27be0e-279f-462f-8be2-5518eac67f04)

No early attrition near as I can tell (following the steps from the thread), should have already taken casualties if the bug was applying.

**Comment by mfvreeland** [comment]
Fixed by CA
