### ISSUE TITLE
Daemon Prince of Nurgle gets no ascension trait

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1651]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/855-daemon-prince-of-nurgle?page=1

**Comment by floskan** [comment]
Needs similar fix to #1425 , also #1595 probably needs a scripted fix

**Comment by mfvreeland** [comment]
CA fixed the first part of this in 5.0.3, but they did not account for transitioning directly to a Nurgle Daemon Prince from a Chaos Lord. If this is still possible for Festus, we should probably leave our fix in.
