### ISSUE TITLE
The Hammer of Smednir not awarded for capturing Karak Dum 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1661]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1019-the-hammer-of-smednir?page=1

**Comment by Drazhir2** [comment]
Locked behind chorf DLC
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/4ec273b3-a6de-4ec0-999a-a0bdc88c178a)
