### ISSUE TITLE
VCoast Legendary Admirals missing lore information on tech tree

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#167]
Two issues so far with VCoast legendary admirals tech descriptions:
- the one required tech is listed twice
- all the legendary admiral lords are missing the description what Lore of magic they use (descriptions worked normally at tww2 VCoast release)

![vcoast](https://user-images.githubusercontent.com/55892027/188883490-dd562f79-fae6-4907-abbc-6c74c53284c5.jpg)

**Comment by chadvandy** [comment]
seems to be caused by doubling up of `technology_node_links` and `technology_required_technologies`

**Comment by Harmandodelavega** [comment]
https://trello.com/c/j0Klywg0/215-cst-admiral-tech-is-missing-lores-of-magic-information

probably relevant
