### ISSUE TITLE
Dwarf technology Iron Readiness redundant for Irondrakes

### ISSUE THREAD

**Issue by atthias** [chadvandy/cbfm_wh3#168]
so I found a bug but one that cannot be really fixed without making a design decision 

thanks to the mod creator for spotting it https://steamcommunity.com/sharedfiles/filedetails/?id=2856256955&searchtext=ironbreakers

in the Main_units  table irondrakes(both variants) have been set to have 1 turn of recruitment time 

however in technology effects junction tables the tech Iron readinesss (wh_main_tech_dwf_mil_6_0) still gives one turn in recruimtent duration which is useless as we speak 

so what do we do?

**Comment by mfvreeland** [comment]
Irondrakes are recruited in one turn now? Are we sure _that's_ not the bug? Seems pretty wild.

**Comment by atthias** [comment]
> Irondrakes are recruited in one turn now? Are we sure _that's_ not the bug? Seems pretty wild.

I do not know I am only passing on what I see

**Comment by Harmandodelavega** [comment]
Useful in red territory lol

We can't give it a random buff unfortunately so nothing to do about it

**Comment by mfvreeland** [comment]
Yeah, this is one of those situations where we can't do anything without making a design decision. Therefore, we do nothing.
