### ISSUE TITLE
Festus loses access to plagues

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1681]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/895-festus-plagues-bug

**Comment by floskan** [comment]
@mfvreeland This one has info from Rhox in the forum link on what should be changed

**Comment by Drazhir2** [comment]
Here's the fix, rename to lua and drop in script/campaign/mod
[zzz_cbfm_festus_plagues.lua.txt](https://github.com/chadvandy/cbfm_wh3/files/15239699/zzz_cbfm_festus_plagues.lua.txt)

**Comment by mfvreeland** [comment]
5.0.3: "Fixed an issue where certain plague symptoms could disappear/become unavailable when playing as Festus the Leechlord"

**Comment by Drazhir2** [comment]
fixed
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/7f853d0b-b7ba-4326-b160-6def656f22c1)
