### ISSUE TITLE
Beastlord's Presence (Rakarth skill) bugs

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1682]
"Beastlord's Presence, in Rakarth's red line Steel Wheel, doesn't add +10% Damage Resistance, because of the change of Beastlord's Gaze, which adds +10% Damage Resistance compared with WH2.

And, Beastlord's Presence can't affect Master with Cold One Chariot and Death Hag with Cauldron of Blood, and maybe more."

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1070-beastlord-s-presence?page=1

**Comment by mfvreeland** [comment]
This sounds like a design change, not a bug, unless I'm missing something.

**Comment by AlarielleRadiant** [comment]
I don't think so, cuz Beastlord's Presence will replace Beastlord's Gaze, and "+10% Damage Resistance" disappear.
And, Cold One Chariot and Cauldron of Blood are large units, but Beastlord's Presence can't affect them.

**Comment by allenhu0912** [comment]
IMO, would be best if you could have both abilities, rather than one replacing the other as an upgrade.

**Comment by floskan** [comment]
From 6.2:
"Added a Resistance effect to ‘Beastlord's Presence’ to mirror ‘Beastlord's Gaze’; Rakarth's later ability is now a true upgrade! "
