### ISSUE TITLE
Wolf of the wastes skill missing forsaken ror + loc mentions flat charge when it's % charge

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1688]
Also noticed someone mentionen Move bite having the wrong loc but couldnt find it

**Comment by floskan** [comment]
Might be fixed in 5.2: "Fixed the Mournhowls' 'Wolf of the Wastes' skill not applying to the Daemonspew (Forsaken) RoR unit."

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.2.
