### ISSUE TITLE
Malakai shooting is bugged and his second and third shots miss constantly 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1697]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1087-malakai-shooting-is-bugged-and-his-second-and-third-shots-miss-constantly?page=1

**Comment by mfvreeland** [comment]
They changed his ranged weapon completely in 5.0.3, so maybe it's fixed?

**Comment by Drazhir2** [comment]
Fixed in 5.0.4, short boy shoots 3 times now.
