### ISSUE TITLE
Skull of Katam don't boost spells to listed Spell Mastery 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1698]
"Skull of katan is listed to boost spell mastery to 220%, but ingame it's only 200%"

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1078-skull-of-katam-don-t-boost-spells-to-listed-spell-mastery?page=1

**Comment by mfvreeland** [comment]
By design, spell mastery is capped at 200% no matter how many boosts it gets, so this isn't really a bug. It is odd that an item exists that would go over that threshold right away, but perhaps it's meant to counter any debuffs that would negatively affect spell mastery (up to 20%).
