### ISSUE TITLE
Gelt's skill "Will of the Patriarch" does not increase Wizard recruit rank for normal recruitment 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1709]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1153-gelt-s-skill-will-of-the-patriarch-does-not-increase-wizard-recruit-rank-for-normal-recruitment?page=1

**Comment by floskan** [comment]
Could change scope to character_to_province_own_factionwide instead of character_to_faction but then he'll lose recruit ranks from his mechanic instead

**Comment by mfvreeland** [comment]
5.0.3: "Balthasar Gelt's unique skill "Will of the Patriarch" now correctly increases Battle Wizard recruit rank"

**Comment by mfvreeland** [comment]
CA changed the scope to `faction_to_province_own_factionwide`. I guess that covers all bases.
