### ISSUE TITLE
Gunnery units not generating schematics

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1716]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1168-schematics-issue?page=1

**Comment by Drazhir2** [comment]
found this list, but something tells me these files should not be in the final release of the game, I wonder if we can change them, otherwise it's a fix for CA:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/28c41622-2eb7-4e12-aa02-0bc761606180)

**Comment by Drazhir2** [comment]
Here is the list to be added to the json:

```
"wh3_dlc25_emp_cha_engineer",
"wh3_dlc25_emp_cha_engineer_mechanical_steed",
"wh3_dlc25_emp_cha_engineer_warhorse",
"wh3_dlc25_emp_cha_master_engineer",
"wh3_dlc25_emp_cha_master_engineer_mechanical_steed",
"wh3_dlc25_emp_cha_master_engineer_warhorse",
"wh3_dlc25_emp_cha_master_engineer_steam_tank",
"wh2_dlc13_emp_cav_pistoliers_ror_0",
"wh2_dlc13_emp_inf_handgunners_ror_0",
"wh2_dlc13_emp_art_mortar_ror_0",
"wh2_dlc13_emp_cav_outriders_ror_0",
"wh2_dlc13_emp_veh_steam_tank_ror_0",
"wh3_dlc25_emp_veh_steam_tank_volley_gun",
```

Hopefully I didn't miss any. The one issue from that bug report we can't solve is the reinforcing army not generating schematics.

**Comment by mfvreeland** [comment]
To check tomorrow: "Fixed an issue where multiple unit types in Elspeth’s roster wouldn’t receive Schematics from damage dealt in battle"
