### ISSUE TITLE
Clarified that Malagor the Dark Omen's "Crowfather" skill gives +20% Missile Strength to the Lord's Army

### ISSUE THREAD

**Issue by Layotees** [chadvandy/cbfm_wh3#172]
per Reddit thread: https://www.reddit.com/r/totalwarhammer/comments/wzvamh/loving_the_new_crowfather_skill_of_malagor/

user RawXenon posts:
"I just looked into this skill, turns out it applies to all units in his army, not just himself. But for some reason, they put the scope as "character_to_force_own_unseen", which unlike "character_to_force_own" hides the part of the description that says "for all units".

So his skill buffs all missiles in his army, they just used the wrong scope so it isn't visible in the description, making it look like it buffs only himself."

**Comment by floskan** [comment]
Don't know if this was intended since Khazrak gives a similar buff but only at 15%. It used to be 20% missile resist if i remembered correctly

**Comment by Harmandodelavega** [comment]
I checked Warhammer 2 files and the hidden effect for the whole army is still there it's just for missile resist though
