### ISSUE TITLE
Tomb king lords lost their shields in campaign and battle

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1722]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1056-tomb-king-s-lord-losing-shield?page=1

**Comment by Drazhir2** [comment]
mmmmh not resolved apparently, giving them shields back made them loose their heads :(

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/bf5883de-ca5c-426b-b8ad-54b8915b778d)

**Comment by Drazhir2** [comment]
I'm just really bad at this xD didn't close xml tags.

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/ae819097-08aa-45f5-a837-397b8f373b44)

**Comment by Drazhir2** [comment]
Wrong fix, the head slot is closed too early (not xml compliant), what needs to be done is close the shield slot properly (by adding a </SLOT> before weapon_3)

**Comment by mfvreeland** [comment]
6.3 notes: "Two Tomb King leader variants were not holding their weapons. This has been resolved."
