### ISSUE TITLE
Morghur apparenty missing attrition immunity from non-Athel Loren forests

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1727]
"ay 7, 2024, 4:03:39 AM
In Warhammer 2 Moghur the Shadowgave's has attrition Immunity to both Athel Loren and Awakened Forest. In Warhammer 3 the latter half of the bonus is missing. That means unlike in 2 (and as would be appropriate for his lore) he's taking a full 6% attrition when fighting in one of the two main Wood Elf regions.

I'm assuming this is an oversight and something missed during the move to 3, because I don't understand why Moghur of all LLs would get nerfed like this."

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1207-moghur-s-attrition-immunity-to-awakened-forest-from-wh2-is-missing?page=1

**Comment by mfvreeland** [comment]
Only the effect text was changed. The effect applies to both:
![image](https://github.com/chadvandy/cbfm_wh3/assets/112144702/ee7c2c60-9ee7-4117-a545-071a02b7d2e6)
