### ISSUE TITLE
Kislev gets penalty for suitable climate in Norsca

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1729]
"Playing as Kostaltyn I own several of the old Wintertooth / World Walkers provinces, and I seem to get the unpleasant/uninhabitable penalties for both Mountain and Frozen, even though the icon is green for them (as it should be)"

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1188-kislev-climate-penalty-for-suitable-climate?page=1

**Comment by mfvreeland** [comment]
I wonder if this is Kislev-specific or if the climate wasn't fully changed in Norsca.

**Comment by floskan** [comment]
Looks more like an old save or something, works fine for me
