### ISSUE TITLE
Reload time reduced by rank but not shown

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1735]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1215-reload-time-reduced-by-rank-but-not-showed-anywhere?page=1

**Comment by mfvreeland** [comment]
Hasn't this always been the case? Either way, doesn't seem like a bug.

**Comment by floskan** [comment]
Yeah my bad, i was just adding everything i saw at this point over at the forums
