### ISSUE TITLE
RoR forsaken of nurgle missing from unit sets (Nurglish factions)

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1737]

**Comment by Harmandodelavega** [comment]
https://github.com/Harmandodelavega/cbfm_wh3/commit/0cda01de3a1376339cb9ddc7d4c9e31e2f010ffb @floskan duplicate
https://github.com/chadvandy/cbfm_wh3/pull/1608

**Comment by floskan** [comment]
Yes my bad
