### ISSUE TITLE
Skaven corruption states that it reduces all other types of corruption in the province UI, but it actually does not

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1746]

**Comment by allenhu0912** [comment]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/3519-skaven-corruption-tooltip-states-that-it-reduces-other-corruption-it-does-not?page=1

**Comment by mfvreeland** [comment]
It seems set up correctly in the DB and in script. If I get to a point where I can test this directly, I'll come back to it, but for now I don't see why it wouldn't work.

**Comment by allenhu0912** [comment]
It actually does work, it's just that it's counted as "buildings" rather than "other corruption" in the corruption change breakdown, which is misleading.

**Comment by mfvreeland** [comment]
Ah, that makes sense since the building value is what is ultimately adjusted by the effect bundle, but I agree that makes it confusing in the UI.
