### ISSUE TITLE
Various graphical issues (celestial dragon guard, war drum, demigryph knights, doom-seekers, tomb king lords)

### ISSUE THREAD

**Issue by Drazhir2** [chadvandy/cbfm_wh3#1754]
Fixes for the following:
- celestial dragon guard ror/war drum ror heads missing #1606 
- celestial dragon guard ror crossbows missing #1606
- demigryph knights missing some shields
- tomb king lords shields missing #1722
- dragon slayer hero uses doomseeker bodies instead of their unique ones

[zzz_cbfm_graphics_fixes.patch](https://github.com/chadvandy/cbfm_wh3/files/15263540/zzz_cbfm_graphics_fixes.patch) (rename to .pack)

**Comment by mfvreeland** [comment]
Thank you for consolidating these.

**Comment by mfvreeland** [comment]
Just for clarification: Most of this wasn't patched. It's just the Dragon Slayer stuff that may have been.

**Comment by Drazhir2** [comment]
Do we trust CA that the dwarf stuff is fixed? Or do I boot up the game? :)

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/0aa908d1-f76f-4ff0-a90f-e36336cc3378)

**Comment by Drazhir2** [comment]
Dwarf stuff can be removed from CBFM
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/7d4717f1-0465-4375-8cbb-3ea7516ecbe6)

**Comment by mfvreeland** [comment]
It seems like CA fixed everything in 5.1 except the missing crossbows for the Dragon Guard RoR

**Comment by mfvreeland** [comment]
6.3 notes: "Two Tomb King leader variants were not holding their weapons. This has been resolved."
