### ISSUE TITLE
Jorek Grimm doesn't have Restock despite having his skill tree converted to a standard dwarf Engineer's, Break Open the Casks does nothing

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1759]

**Comment by mfvreeland** [comment]
Screenshots? Why would the skill not work if it's no different than a usual engineer?

**Comment by allenhu0912** [comment]
Standard Dwarf Engineers have Restock! innately. Break Open the Casks! reduces cooldown and gives an extra use, but does nothing because Jorek does not have Restock! to begin with, just like how Skink Oracles did not have Cold-Blooded and the perk that reduced its cooldown did nothing.

**Comment by mfvreeland** [comment]
Ahhh, ok. That makes sense. Thank you for clarifying.

Fix should be to provide Jorek with Restock! innately, I suppose.  Should be fairly simple.
