### ISSUE TITLE
Belegar's "Greatest of Grudges" severity 5 times lower than Warhammer 2

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#176]
![image](https://user-images.githubusercontent.com/39225561/188973424-b64d64ce-439a-4d66-adcd-b8b885579f08.png)

**Comment by Emberrays** [comment]
Fix is incorrect, reward is bugged. see fix from WH2. https://github.com/chadvandy/community_bugfix_mod/commit/02c9cd262b0b253b05a963fe86ecc337fc52c1db

**Comment by mfvreeland** [comment]
I updated the fix for this to include FlyingFox's fix for the reward, which was previously broken (and previously fixed by CBFM) in WH2.

**Comment by Harmandodelavega** [comment]
Maybe I don't follow but this seems quite arbitrary.
One reason for it being lower severity is probably because it will last longer than anything else, and thus will gain 1 or more age modifiers

**Comment by mfvreeland** [comment]
> Maybe I don't follow but this seems quite arbitrary. One reason for it being lower severity is probably because it will last longer than anything else, and thus will gain 1 or more age modifiers

Maybe, but it feels really odd to have the grudge that is the driving motivator behind Belegar's very existence ever rated as lower in severity than anything else. Besides that, it was always 10 in WH2.

**Comment by mfvreeland** [comment]
With the release of 2.2, CA has normalized most starting grudges to rate at 5 severity, but the Karak Eight Peaks grudge has remained at 2. The question now is should this mod be updated to change in to 5, or should we assume that CA, having just examined all of these grudge numbers, really does want this one to start at 2 now? 

Although I made the original fix to set this back to 10, I am inclined to think now that CA intended the reduction, probably for the reasons @Harmandodelavega mentioned previously. Thoughts?

**Comment by mfvreeland** [comment]
Also worth noting that the reward part of this issue is still borked in 2.2, so that fix should remain in CBFM regardless.

**Comment by Harmandodelavega** [comment]
My opinion stays the same, and yeah they "might" have double checked the grudge severity

**Comment by Harmandodelavega** [comment]
readding the labels just as a reminder that it's still in the build

**Comment by Harmandodelavega** [comment]
deleted severity, not sure where the "reward" fix is

**Comment by Harmandodelavega** [comment]
just for reference #254

**Comment by mfvreeland** [comment]
@Harmandodelavega The reward fix was from Flying Fox, so I think it will have "ff" in there somewhere. Should be left in.

**Comment by mfvreeland** [comment]
Fixed by CA 13 months later
