### ISSUE TITLE
Missing muzzle/smoke effect on landship crew and hochland (and lots of others) 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1765]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1364-missing-muzzle-smoke-effect-on-landship-crew-and-hochland-and-lots-of-others?page=1

**Comment by mfvreeland** [comment]
This is causing incompatibility with the latest version because CA updated this table in 5.2.5. I am reverting this for now but re-opening the issue in case it becomes a problem again.
