### ISSUE TITLE
Soul quench has a faulty range indicator (wrong target intercept value) 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1767]
"Soul quench has a projectile range of 300m, which is correctly stated in the stat card

However the target intercept value is set to 250m, which results in the spell range indicator (the blue circle) being shorter than the actual usable range"

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1322-soul-quench-has-a-faulty-range-indicator-wrong-target-intercept-value?page=1

**Comment by mfvreeland** [comment]
CatholicAlcoholic put up a fix on Discord: https://discord.com/channels/373745291289034763/581350140942483456/1238866258523455598
