### ISSUE TITLE
Dwarf redline skill bug - Honoured By Grimnir 

### ISSUE THREAD

**Issue by KrumTy** [chadvandy/cbfm_wh3#1779]
**Describe the bug**
Honoured By Grimnir doesn't provide 12% weapon strength for Slayers rank 7+

**Expected behavior**
It should provide both AP and Base damage but it currently only boosts Base damage

**To Reproduce**
1. Play as Dwarves 
2. Rank up the skill

**Screenshots**

Low rank Doomseekers:
![20240510220520_1](https://github.com/chadvandy/cbfm_wh3/assets/6672056/ba15c751-feff-482a-8b8c-e0fac3715bf6)
High rank Doomseekers (same ap damage):
![20240510220526_1](https://github.com/chadvandy/cbfm_wh3/assets/6672056/72b3eed7-31a9-42c3-81e0-b468aed87f35)
Skill:
![20240510220305_1](https://github.com/chadvandy/cbfm_wh3/assets/6672056/34cdb950-297b-405c-b19e-51c946941512)

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1
