### ISSUE TITLE
Confusing tooltip regarding hero recruit rank for Star Chambers

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1784]
![20240511014648_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/d9b84c81-c792-484c-bacf-837c88b2b1e9)

**Comment by mfvreeland** [comment]
It's all part of the great plan, you see. You just need to determine it.

**Comment by allenhu0912** [comment]
Seems like all of the factionwide hero recruit rank bonuses are broken in a similar way.

**Comment by allenhu0912** [comment]
I don't see this bug anymore for my recent campaigns
