### ISSUE TITLE
Ghoritch doesn't spawn if quest battle fought manually

### ISSUE THREAD

**Issue by DBKotor** [chadvandy/cbfm_wh3#1789]
**Describe the bug**
Ghoritch doesn't spawn after his quest battle

**Expected behavior**
After you get the Whip quest as Throt, you should get Goritch upon completion

**To Reproduce**
1. Play as Thrott
2. Get quest for the whip
3. Do quest for the whip, fighting the battle manually
4. Ghoritch doesn't spawn

**Additional context**
Vanilla, IE, WH3.

Tried reloading the battle, restarting campaign, doing it with teleport or walking up to quest battle. Ghoritch always survived the battle but never spawned.

**Comment by Drazhir2** [comment]
Hello DBK, would it be possible to get a savegame where the issue is present? As you'll see here https://github.com/chadvandy/cbfm_wh3/issues/726#issuecomment-2105736506 I could not replicate that issue.

**Comment by mfvreeland** [comment]
Could be tied specifically to fighting the battle manually.

**Comment by Drazhir2** [comment]
After running the LH script with some logging, the mission listener is properly created but it seems the MissionSucceeded event does not fire after the manually fought quest battle (you can see it firing turn 1 when I kill the first enemy) even though the mission success pop-up shows up and you get the magic item.

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/4f500f6d-0d43-491c-9a60-59eed9989343)

It's a weird one but I don't think the LH script itself is the cause. I will run a test with Coeddil which is the other LH that unlocks on quest battle.

**Comment by mfvreeland** [comment]
"(you can see it firing turn 1 when I kill the first enemy)"

What does turn 1 mean in this context?

I am inclined to agree with you now that the script isn't the issue. It seems more fundamental, like a potential edge case problem with listeners themselves maybe.

**Comment by Drazhir2** [comment]
scratch everything I said, I am stupid, the script log ofc switches when you fight the battle so I was looking at the wrong log

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d7edd14f-b150-4a43-8ba4-346c36550277)

Ghoritch does spawn but... watch out Elspeth! don't turn around xD

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/7d122438-786d-4ff4-911b-02f61beb94fc)

**Comment by mfvreeland** [comment]
Good catch! Now I am curious how this was working with autoresolve...

**Comment by Drazhir2** [comment]
Well it's pretty random, the script was using a global faction variable which explains the various spawn locations reported (empire, lustria, cathay...) depending on the state of that variable.

I hunted them down and it's CA defining that global faction in various bits, so one more fix to remove every global faction variable (the vanilla ghoritch spawn would be a script break now). Might need some more thorough testing (just normal gameplay with the fix and debug enabled) but looks good.

Here is the second fix: [zzz_cbfm_global_faction_var.lua.txt](https://github.com/chadvandy/cbfm_wh3/files/15321094/zzz_cbfm_global_faction_var.lua.txt) (rename to lua and drop in script/campaign/mod)

**Comment by Drazhir2** [comment]
big oopsie on that one :(

get_factions_bonus_value and get_highest_ranked_general_for_faction should be removed from the fix

**Comment by mfvreeland** [comment]
No worries, already done and tested.

**Comment by mfvreeland** [comment]
5.0.4: "Fixed an issue where several different Legendary Heroes (I've got my eye on you, Ghoritch!) could spawn at a random character that did not belong to the player"

@Drazhir2 Will need to see if they fixed the global faction var issue generally or if this is a more focused fix that ignores that elephant

**Comment by Drazhir2** [comment]
script/campaign/wh3_main_legendary_characters.lua - Fixed (both functions used by Ghoritch and Ariel)
script/campaign/wh3_campaign_ai.lua - Fixed
script/_lib/lib_campaign_manager.lua - Fixed
script/campaign/wh3_campaign_nurgle_plagues.lua - Fixed

I believe that covers all cases we found
