### ISSUE TITLE
Sacrifice to Mathlann spawns two blarks

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1799]

**Comment by mfvreeland** [comment]
Consistently?

**Comment by floskan** [comment]
I just copied the title from a bug report, there was zero explanation behind it iirc

**Comment by Drazhir2** [comment]
can confirm, easily reproduced by giving you a bunch of def_slaves then insta building/perform ritual:

before:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/216e548c-9a98-48c3-a276-0259fff180af)

after:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/8619aca6-8136-4f63-9c6d-384cae0191a6)

it looks properly setup in the db:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/f7ca70e1-2857-4e25-ab68-4ea77cfd6731)

**Comment by mfvreeland** [comment]
So it's spawning one on the campaign map and then also adding one to the pool. Neat. IIRC, the latter is the correct effect.

**Comment by Drazhir2** [comment]
Yes the second effect is the correct one, I can't see any db issue.

Might be worth it to test the Tehenhauin ritual that's setup the same to see if the underlying gamecode has been broken.

**Comment by mfvreeland** [comment]
Rituals are scripted I believe. I'll see if I can track this down today.

**Comment by Drazhir2** [comment]
Only the unlocking part of it is scripted (wh2_campaign_rites.lua), not the performing part

**Comment by Drazhir2** [comment]
I had a go with Tehenhauin and there's definitely something wonky with the gamecode behind that new column.

Before:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/2af07989-6f4b-4b4f-aa65-d18dc2c14753)

After there is no map spawn but it added 2 to the pool, one with reduced cost like a returning lord (I suppose that's the one we should get from the ritual) and one with regular recruit cost. They are both wh2_dlc12_lzd_red_crested_skink_chief_legendary with stronger traits:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/122f03ac-cbc8-4400-90af-95cab96bdb6d)

Listeners only triggered once like the blark:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b590f54e-e87c-48e6-bfdd-42c8a180ca02)

**Comment by Drazhir2** [comment]
Reported to CA https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1711

**Comment by mfvreeland** [comment]
God damn it.

**Comment by floskan** [comment]
Doesn't look like the hotfix did anything regarding this

**Comment by mfvreeland** [comment]
Maybe fixed in 5.0.5, need to check Tehenhauin

**Comment by Drazhir2** [comment]
Tested Skink Chiefs and they are fine now in 5.0.5. Didn't test blarks but I suppose they're fixed too.

**Comment by mfvreeland** [comment]
Fixed in 5.0.5

**Comment by floskan** [comment]
Was this truly fixed? seeing some people talking about this not being fixed on the forums

**Comment by mfvreeland** [comment]
Just tested it; it seems to work fine.
