### ISSUE TITLE
Jade Wizard loses Mastery of Elemental Winds trait when mounted on Imperial Pegasus 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1800]
"​Jade Wizard loses Mastery of Elemental Winds trait when mounted on Imperial Pegasus, but regains it when dismounted or mounted on Barded Warhorse. "

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1565-jade-wizard-loses-mastery-of-elemental-winds-trait-when-mounted-on-imperial-pegasus?page=1

**Comment by chadvandy** [comment]
5.1: "Fixed an issue where Jade Wizards on Pegasus were not gaining the Elemental Winds skill once the Temple of the Elemental Winds was constructed"

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1
