### ISSUE TITLE
 Orc boar chariots are not effected by any technology 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1801]
"Orc boar chariots for the green skins are not effected by any technologies, specifically technology that effects orcs and boars, whereas goblin wolf chariots are effected by technology that effects goblins and wolves.

They are also not effected by Azhags unique skill line that effects orc infantry and cavalry, but that may be an oversight instead of a bug."

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1549-orc-boar-chariots-are-not-effected-by-any-technology?page=1

**Comment by floskan** [comment]
Do we add the chariots anywhere?

**Comment by floskan** [comment]
Yeah after looking through the tech tree it seems fair that they get some kind of buff

**Comment by floskan** [comment]
@mfvreeland Thoughts on letting Azhag buff chariots in his unique skill line? I was planning to add the boars to "Boar Paintin'" and "Boar Ridin'" where the regular orc boyz and biguns get buffs

**Comment by mfvreeland** [comment]
@floskan Seems reasonable to me. We've made similar additions in the past. Go for it.

**Comment by mfvreeland** [comment]
@floskan What makes you think this was maybe patched?

**Comment by floskan** [comment]
> @floskan What makes you think this was maybe patched?
Because there were some minor changes to the tech tree, i think chariots have their own nodes now. Azhag's skills are pretty much the same though.

**Comment by mfvreeland** [comment]
Got it. Well, the tech tree side has definitely been addressed, and it does look like they added new RoRs to Azhag's unique line, so they reviewed these and decided not to add chariots here. Removing for now.
