### ISSUE TITLE
Goblin Hewer lost their model

### ISSUE THREAD

**Issue by KrumTy** [chadvandy/cbfm_wh3#1809]
**Describe the bug**
Goblin Hewer lost their artillery model

**Expected behavior**
For them to have a model.

**To Reproduce**
1. Hover over the unit during a battle. When not hovered it's all gray.

**Screenshots**
![20240517213256_1](https://github.com/chadvandy/cbfm_wh3/assets/6672056/22d9fe40-7a07-42d2-bdea-ae2e2fa225e5)

**Comment by mfvreeland** [comment]
Is this still a bug? I don't seem to have this problem in my game in 5.0.5.

**Comment by chadvandy** [comment]
5.1: "Fixed an issue causing the Goblin Hewer to distort or appear invisible."

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1
