### ISSUE TITLE
Slave pens not reducing the slave diktats cost.

### ISSUE THREAD

**Issue by Thedefense** [chadvandy/cbfm_wh3#1810]
**Describe the bug**
Slave pens not reducing the slave diktats cost.

**Expected behavior**
​I've build a slave pen and according to the tooltip, it should reduce the slave diktats cost by 5% in that province.

**To Reproduce**
Play as any Dark Elf faction, get enough slaves for a diktat and build a slave pen in a province, after the building is complete activate a diktat which should be a bit cheaper to active there but its not and costs the same with or with out the building.

**Comment by Drazhir2** [comment]
already fixed in CBFM https://github.com/chadvandy/cbfm_wh3/issues/1365

**Comment by Thedefense** [comment]
I just tested this on a save with and with out the community bug fix mod, both cases the diktat cost didn´t change if i had the building or not.

**Comment by Drazhir2** [comment]
I had a go on a fresh save and you're right, it doesn't work, I'm reopening the original issue, leave this one closed.
