### ISSUE TITLE
ALT+Right Click Issue

### ISSUE THREAD

**Issue by June-2k** [chadvandy/cbfm_wh3#1811]
**Describe the bug**
Moving 2 or more units with ALT+Right Click lowers unit formation width by 1 every time the order is issued.

**Expected behavior**
ALT+Right Click should not be modifying unit width in any way whatsoever.

**To Reproduce**
1. Select 2 or more units
2. Use ALT+Right Click to move units

**Screenshots**
https://www.youtube.com/watch?v=zI_NVpPQYTE visual demonstration.

**Additional context**
Bug has been in the game since WH3 launch, not present in previous titles. Tested this on vanilla game with validated files, bug is visible in YouTube videos from other players.

**Comment by Drazhir2** [comment]
Handled by the game code, not something we can fix.
