### ISSUE TITLE
Beastmen and Cult of Pleasure Armies do not fall under the Category of Corruption Inducing Armies

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1816]
Mother Ostankya has a faction effect that says it grants her forces a Melee Attack bonus against armies that spread corruption. However, for the purposes of the game engine, the Beastmen as well as the Cult of Pleasure are not included under this category.

**Comment by Drazhir2** [comment]
Currently applying to these cultures, any others missing?

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/e9d7af95-c413-4e6c-9de7-29c2aef8e927)

**Comment by Autumnchain** [comment]
It looks like Norsca is missing from this as well.

**Comment by floskan** [comment]
Can we even add sub cultures to this?
