### ISSUE TITLE
stahlberg's letter (sylvania elector item) gives xp vs bretonnia instead of undead

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#182]
could do with a hidden scope, if anyone knows how feel free to add

**Comment by Harmandodelavega** [comment]
look for Sylvania talisman or something like that in the table

**Comment by Drazhir2** [comment]
Fixed in 4.1.0
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/100b45a2-1e9a-4204-9541-247532a4cddf)
