### ISSUE TITLE
Markus Wulfhart Imperial supply units don't benefit from the empire tech tree.

### ISSUE THREAD

**Issue by jp28dew** [chadvandy/cbfm_wh3#1827]
So far, I found that huntsmen and wagons don't get buffs from the "missiles" tech tree.

**Comment by jp28dew** [comment]
![Screenshot 2024-05-27 000657](https://github.com/chadvandy/cbfm_wh3/assets/41582956/46ad9e6e-59f2-4da4-976a-0df830625d88)
![Screenshot 2024-05-27 000719](https://github.com/chadvandy/cbfm_wh3/assets/41582956/694e807b-97e0-41dd-8192-c333f5f3ae67)
![Screenshot 2024-05-27 000736](https://github.com/chadvandy/cbfm_wh3/assets/41582956/0bf9e25f-326d-4fd0-aa95-0f266f176799)

Supply Huntsmen units don't have range upgrades, missile resistance, or ammunition buffs, while non-supply units get all these buffs.

**Comment by mfvreeland** [comment]
To check tomorrow: "Fixed an issue where Markus's lords red skill line didn't affect Huntsmen recruited from Imperial Supplies"
