### ISSUE TITLE
Dwarf engineer missing from some tiers of workshop building garrison

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1831]

**Comment by Drazhir2** [comment]
details? screenshots? looks fine to me, they're on the 3 tiers of malakai workshop and 4 tiers of regular settlement buildings

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/e0dbc6d8-8f63-49bb-a94e-e6389c9dbec3)

**Comment by floskan** [comment]
Sorry, I forgot to add this way back. I have a screenshot somewhere I will add

**Comment by Drazhir2** [comment]
ah yes indeed, with proper info I can confirm it's missing from 4

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/a3e3692d-93f6-4f08-8a63-27dafb7e7952)

**Comment by floskan** [comment]
My bad! Haven't had much time to focus on Warhammer right now, but I'm getting there👌

**Comment by chadvandy** [comment]
5.1: "Fixed the Guild Masters' Council building missing the Master Engineer garrison"

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1
