### ISSUE TITLE
bug for sisters of twilight，wood elf

### ISSUE THREAD

**Issue by nightspirit01033** [chadvandy/cbfm_wh3#1835]
when i submit and only use this mod and play as sisters of twilight，i can't assign my ancient treeman lord to the office of “Treesinger of Isha”.Please fix this bug！！！

**Comment by Bogdanov89** [comment]
This has been talked about before, Treesingers are exclusively Elves - not treeman.

**Comment by nightspirit01033** [comment]
Elven Lords don't have the Treeman Lords' skill bonus to Treeman troops,this dissonance between skills bonus and office bonus is uncomfortable，but i see it......Do other races have changes like this for background reasons rather than bugs?

**Comment by Bogdanov89** [comment]
> Elven Lords don't have the Treeman Lords' skill bonus to Treeman troops,this dissonance between skills bonus and office bonus is uncomfortable，but i see it......Do other races have changes like this for background reasons rather than bugs?

Treesingers are elven mages, as in elf only.
It is a bug that you can assign a treeman to a position that is exclusively meant for an Elf mage.
Furthermore Isha is an elven goddess, so a treeman does not care about such a deity nor does it serve such a god.

There is no "background reason", this is a standard bug/oversight just like any other.
If CA wanted Treeman to be in that office spot they should/would have named it anything other than "elven mage of elven god".

**Comment by nightspirit01033** [comment]
...u are definitely right，i just cant part with the fact that  the regeneration，skin of wood  and the skewering branch cant work on treekin units meanwhile...anyway，thanks
