### ISSUE TITLE
Grudge Rakers and Malakai's Triple Rifle have Issues

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1836]
>https://steamcommunity.com/sharedfiles/filedetails/?id=3254968951
>https://steamcommunity.com/sharedfiles/filedetails/?id=3255191320
Both Malakai and Grudgerakers have issues with their weapons. They are supposed to fire their 3 and 2 shots (repectively) in succession and then reload. Instead, they fire all of their shots at once and then reload. These two mods fix the issues.

**Comment by mfvreeland** [comment]
5.0.4: "Made Malakai's gun a tiny bit less eager - it now fires its bullets in sequence instead of firing every bullet immediately on the first shot"

Needs confirmation on Grudge Rakers

**Comment by Drazhir2** [comment]
Grudgerakers are still broken, 6 projectiles then 0 instead of 3 then 3.

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/9a8e1389-d54b-476e-a4cc-27e8c4801ced)

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1, including the high/low firing animations that I wasn't able to fix.
