### ISSUE TITLE
Ward save for Battle Wizards from Protection of the Patriarch tech not applied to garrisoned wizards from wizard building

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1844]
![20240603223843_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/f3b359af-990f-4e46-9355-a0dbad629e5a)

**Comment by mfvreeland** [comment]
5.1.1 notes: "The Empire technology "Protection of the Patriarch" now also applies the ward save bonus to Battle Wizards that are part of garrisons."

**Comment by mfvreeland** [comment]
Fixed by CA
