### ISSUE TITLE
Marks' Fix

### ISSUE THREAD

**Issue by AlarielleRadiant** [chadvandy/cbfm_wh3#1845]
Fix lots of marked units and lords.

Khorne
The Bloodbrute Behemoth (Ghorgon)
Melee Attack: 71→74
Melee Defence: 43→38
Spell Resistance: 0%→15%
Brutes of the Hound (Marauder Berserkers)
Melee Attack: 50→55
Melee Defence: 31→26

Slaanesh
Azazel
Physical Resistance: 20%→25%
Prince Sigvald the Magnificent
Physical Resistance: 10%→5%
Hellstriders of Slaanesh
Physical Resistance: 10%→5%
Hellstriders of Slaanesh (Hellscourges)
Physical Resistance: 10%→5%
Mirror Guard (Chaos Warriors)
Physical Resistance: 10%→5%
Chaos Chariots of Slaanesh
Physical Resistance: 10%→5%
Daemon Prince of Slaanesh
Speed (flying): 80→85
Speed (ground): 65→70

[zzz_cvfm_marks_fix.zip](https://github.com/user-attachments/files/15546546/zzz_cvfm_marks_fix.zip)
- Warden of Hope

**Comment by floskan** [comment]
We need to update these to match the marauder ror buffs
