### ISSUE TITLE
Oxyotl Campaign Map Stutter

### ISSUE THREAD

**Issue by HalberdOctopus** [chadvandy/cbfm_wh3#1846]
When playing a campaign as Oxyotl's faction, Ghosts of Pahuax, panning the camera around on the campaign map is very stuttery.

Disabling 3D UI elements (by holding spacebar and opening the menu arrow on the right side of the screen) seems to stop the stutter, but that also hides the names of settlements and armies, so that isn't a good long-term solution.

To reproduce:
1. Start an Oxyotl campaign
2. Try to move the camera around on the campaign map

**Comment by HalberdOctopus** [comment]
That's a shame, thank you for responding

**Comment by HalberdOctopus** [comment]
Thank you for your response, is it okay for me to close the thread as "not
planned" or is that a breach of etiquette?

**Comment by mfvreeland** [comment]
Yes that's fine, no worries!
