### ISSUE TITLE
The Father of Blades and Necrotic Phylactery ancillaries are unfusable. Both can be obtained by all faction (should be Nurgle exclusive that added in the lastest DLC)

### ISSUE THREAD

**Issue by Frankkkkkkke** [chadvandy/cbfm_wh3#1850]
![屏幕截图(428)](https://github.com/chadvandy/cbfm_wh3/assets/140299241/9d672899-71e4-427d-accd-6f46154dc472)

**Comment by Drazhir2** [comment]
Looks like they don't drop randomly but come from fusing green items:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/c4a8683d-75a5-4f79-a9f3-d60687a5500d)

For the random drop they're properly setup in the db with the correct faction set:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/457c0366-7c36-4b0c-a4da-cbf4741d8292)

Unfortunately the Item Fusing code cannot be changed by modders, that one is on CA to fix.
