### ISSUE TITLE
Engineers Don't Have Scout Ruins

### ISSUE THREAD

**Issue by Bladderfishy** [chadvandy/cbfm_wh3#1851]
**Describe the bug**

Fairly simple. Engineers for Empire seem to be missing the "Scout Ruins" ability.

**Expected behavior**

As above.

**To Reproduce**

Scout a ruins with an engineer

**Screenshots**

![image](https://github.com/chadvandy/cbfm_wh3/assets/172141289/18aaf753-e195-4fca-a749-e205c8365bdd)

**Saves**

**Additional context**

**Comment by Drazhir2** [comment]
missing from engineers indeed:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/e95bfc99-1cdd-4e31-8464-fd003859582c)

**Comment by chadvandy** [comment]
5.1: "Fixed a number of Heroes missing the Scout Ruins action"

**Comment by AphyriaCelosia** [comment]
![image](https://github.com/chadvandy/cbfm_wh3/assets/173944160/ff982704-2af2-4e71-8791-2185c1a956e0)

Tested via Wissenland & Nuln (starts with engineer) and panning to Mordheim. Appears to be working now.

**Comment by mfvreeland** [comment]
Fixed by CA
