### ISSUE TITLE
Game crash when activating Dwarf Shieldwall ability for a unit that is in a docked status

### ISSUE THREAD

**Issue by SubRyan** [chadvandy/cbfm_wh3#1855]
**Describe the bug**
Game crash when activating Dwarf Shieldwall ability for a unit that is in a docked status

**Expected behavior**
Shieldwall should be disabled for units in a docked status

**To Reproduce**
1. Play as a Dwarf faction with Shieldwall tech unlocked
2. In a settlement battle, dock an appropriate unit that has the Shieldwall ability onto a wall or defensive monument
3. Active Shieldwall
4. Experience crash/bug

**Screenshots**

**Saves**

**Additional context**
tba

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1
