### ISSUE TITLE
Tempest has a shorter duration when overcast

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1866]
![20240615174344_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/71aff87b-2e17-43e4-9011-e868a852c741)
![20240615174350_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/3f35bea6-c23b-46f2-a032-862497798db1)

I feel this is a bug as the cost-effectiveness of the spell actually goes down when overcast. Usually they're the same (e.g. double winds but double damage), and no other spell I remember reduces duration when overcast.

**Comment by mfvreeland** [comment]
Possibly fixed in 5.1.2: "Tempest from the Lore of High Magic now matches its visual duration at 17 seconds for both regular and overcast."
