### ISSUE TITLE
Gotrek and Felix lack Mentor skill

### ISSUE THREAD

**Issue by SubRyan** [chadvandy/cbfm_wh3#1869]
**Describe the bug**
Felix lacks Mentor skill since the release of the new skill tree

**Expected behavior**
Felix should have the Mentor skill like the other LH 

**To Reproduce**
1. Play as Dwarfs or Empire
2. Recruit Gotrek or Felix
3. Notice lack of Mentor skill

**Screenshots**

![image](https://github.com/chadvandy/cbfm_wh3/assets/13555076/856c78d9-52fc-4e58-a189-9413917bfbbd)

![image](https://github.com/chadvandy/cbfm_wh3/assets/112144702/f561b19c-d8a6-4c45-bec7-81ee7c89096d)

**Saves**

**Additional context**
I believe this to be an oversight as other Legendary Heroes have had the Mentor skill added to them.

**Comment by mfvreeland** [comment]
From 5.1.1 notes: 
"Removed the Mentor skill from the Legendary Heroes that had it. (This was misleading in most cases where other Heroes gained experienced (e.g. Saytang the Watcher would give experience to Gate Master Heroes) and in some cases, there would be no characters to give experience to. This now makes it consistent across all Legendary Heroes, as some did not have this skill.)"
