### ISSUE TITLE
Waywatchers are missing their weapons + alpha missing on the RoR

### ISSUE THREAD

**Issue by Drazhir2** [chadvandy/cbfm_wh3#1878]
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/c045f990-0713-4826-af05-83b5b62621a0)

**Comment by Drazhir2** [comment]
classic patch 5.0.0 change, referencing non-existing wsmodels
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/12f33b76-b570-4b4f-bf50-94f3f2fd03c1)

**Comment by mfvreeland** [comment]
Can this be fixed by simply pointing the variant mesh definition to the rigid models?

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/666

**Comment by mfvreeland** [comment]
The wsmodels were evidently added in 5.1. This may also be the case for previous visual fixes in this PR: https://github.com/chadvandy/cbfm_wh3/pull/1758
