### ISSUE TITLE
Chaos Marks Fix After 5.1

### ISSUE THREAD

**Issue by AlarielleRadiant** [chadvandy/cbfm_wh3#1879]
The Bloodbrute Behemoth (Ghorgon)
Armour:50 (Ghorgon)→60

Brutes of the Hound (Marauder Berserkers)
Armour:15 (Marauder Berserkers)→35
_It refers to Marauders (15) and Marauders of Khorne (35)_

Note:
I should change their armour, not melee attack.

Gorbeast Chariots of Khorne
Armour:130 (Gorbeast Chariots)→140
Melee Attack:35→30 (Gorbeast Chariots)
Melee Defence:25→27 (Gorbeast Chariots 32)

[zzz_cbfm_marks_fix.zip](https://github.com/user-attachments/files/15981653/zzz_cbfm_marks_fix.zip)
by Warden of Hope

**Comment by mfvreeland** [comment]
Is this meant to be a complete replacement of #1845?

**Comment by AlarielleRadiant** [comment]
Sure.

**Comment by mfvreeland** [comment]
Old fixes removed, new fixes added directly to main
