### ISSUE TITLE
Chaos Sorcerer Lord (Death) gets Allure of Slaanesh innate instead of Chaos Sorcerer (Death)

### ISSUE THREAD

**Issue by dragonkip04** [chadvandy/cbfm_wh3#1881]
**Describe the bug**
When playing as The Ecstatic Legions, the Chaos Sorcerer **Lord** (Death) gets the Allure of Slaanesh background skill instead of Chaos Sorcerer (Death) hero. This should be in line with how the Chaos Sorcerer (Shadow), (Fire) and (Metal) heroes get that background skill when playing as The Ecstatic Legions. It looks like it was mapped to the Chaos Sorcerer **Lord** instead.

**Expected behavior**
Map the Allure of Slaanesh background skill back to the Chaos Sorcerer (Death).

**To Reproduce**
1. Play as The Ecstatic Legions
2. Recruit the Chaos Sorcerer (Death) hero
3. See that the Chaos Sorcerer (Death) hero never get the Allure of Slaanesh background skill

**Screenshots**
**Chaos Sorcerer (Death)** in database
![image](https://github.com/chadvandy/cbfm_wh3/assets/173291507/c3d68f55-cfac-4a2b-97d1-2adc0cf05335)

**Chaos Sorcerer (Shadow)** in database
![image](https://github.com/chadvandy/cbfm_wh3/assets/173291507/c08e17e8-3c20-4fc4-b9cb-82ef74c7ec16)

**Chaos Sorcerer (Fire)** in database
![image](https://github.com/chadvandy/cbfm_wh3/assets/173291507/92ba8426-bdf2-4444-9c81-7ba0eb06bf97)

**Chaos Sorcerer (Metal)** in database
![image](https://github.com/chadvandy/cbfm_wh3/assets/173291507/c0ffffd2-19d4-416f-b214-1de133337b2c)

**Chaos Sorcerer Lord (Death)** in database
![image](https://github.com/chadvandy/cbfm_wh3/assets/173291507/a2ff1e99-fc93-447f-9773-52041b17c78e)

**Additional context**
I made a simple mod to fix this. Maybe you can include it in your future update.
[chs_sorc_death.zip](https://github.com/user-attachments/files/15993472/chs_sorc_death.zip)

**Comment by mfvreeland** [comment]
I am confused by this. It seems like you're fixing it for Azazel's Chaos Sorcerer (Death) but breaking it for Azazel's Chaos Sorcerer *Lord* (Death). There needs to be an item for the Lord version as well; you're removing what was there and not replacing it with anything.

**Comment by dragonkip04** [comment]
From looking at the background skills of Chaos Sorcerer ***Lord*** (Shadow)/(Fire)/(Metal), they aren't supposed to get Allure of Slaanesh. Only the heroes are supposed to.

![image](https://github.com/chadvandy/cbfm_wh3/assets/173291507/355beed4-fb3e-452f-bae7-63e8903a72c2)

**Comment by mfvreeland** [comment]
Ah, I see. That's quite strange that Vilitch and Festus get this but Azazel doesn't, but it does seem consistent across the other lores.
