### ISSUE TITLE
Dwarf aura runes applying at battle start and not changing

### ISSUE THREAD

**Issue by AphyriaCelosia** [chadvandy/cbfm_wh3#1882]
**Describe the bug**
When using dwarven unit runes that give an aura to the unit, the aura seems to be applied at the start of battle to units in the radius, but then the affected units aren't updated afterwards - units that move away from the aura giver retain the benefit, and ones moving into range do not receive the buff.

**Expected behavior**
The auras should update live, such that units lose or gain the buff as they move out or into range of the aura-giver.

**To Reproduce**
1. Play as dwarves.
2. Forge aura-giving banner runes (Rune of Courage, Rune of Stoicism etc.)
3. Equip to units and fight manual battle.
4. Put some units in range of aura-bearer at start of battle, then move them away and see if they retain aura.
5. Move other units who weren't in range at battle start into range, and see if they gain the aura benefits.

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/173944160/c28b434c-6e1c-4114-a1ce-c3b84b339a63)

**Comment by mfvreeland** [comment]
Maybe fixed in 5.1.2:
Fixed the following abilities not affecting units that were not nearby when the battle began:
- Rune of Stoicism
- Ancestor Rune
- Rune of Courage
- Spirit Conduit (Hierotitan)
