### ISSUE TITLE
Chaos Lord of Nurgle broken leg texture

### ISSUE THREAD

**Issue by mfvreeland** [chadvandy/cbfm_wh3#1888]
![image](https://github.com/chadvandy/cbfm_wh3/assets/112144702/079c42ba-2c77-4b33-a24c-96f361d1604f)

Fix submitted by Dead Baron

**Comment by Virall88** [comment]
looks like CA corrected it

**Comment by mfvreeland** [comment]
> Looks like CA corrected it, give it a look please

You are correct. We're removing this fix.
