### ISSUE TITLE
Game Crashes when opening

### ISSUE THREAD

**Issue by i-van-drago** [chadvandy/cbfm_wh3#1894]
**Describe the bug**
everytime i open the game, it crashes before it gets to the main screen. I get a pop up that says error with
zzz_community_bugfix_mod.pak

then some more detail in the error saying 
wh3_dlc23_skill_innate_chd_hero_daemonsmith_sorcer_hashut_3_fanatical

No other mods in place

**Expected behavior**
Should load to main screen

**To Reproduce**
1. Apply mod
2. Launch WH3

**Screenshots**
[If applicable, add screenshots to help explain your problem. The more in-game text we can see to reference the details in question, the better.]
(https://imgur.com/a/qP2z4li)

**Saves**
NA
**Additional context**
NA

**Comment by Drazhir2** [comment]
CBFM has not been updated yet for the latest patch, you can find a beta pack on the Da Modding Den discord in the community_bugfix channel or wait for the update.
