### ISSUE TITLE
Incorrect culture's currency icon appearing for unit upkeep

### ISSUE THREAD

**Issue by spartanvi** [chadvandy/cbfm_wh3#190]
**Describe the bug**
When viewing a unit's upkeep, the game loads whatever currency "icon_income.png" is currently cached, even if it's for the wrong culture. Ex: the chaos favor currency icon can appear for Dwarf Ironbreakers in a Dwarf campaign. 

**Expected behavior**
The game should always load the correct culture's currency icon.

**To Reproduce**
1. Start a campaign with any Legendary Lord who's faction has a culturally unique currency (e.g.  Archaon The Everchosen).
2. Load a campaign save of another faction (e.g. Thorgrim Grudgebearer).
3. Click the Hammerers and view the statistics panel. 
4. Observe the wrong currency icon in the unit's upkeep.

**Screenshots**
![image](https://user-images.githubusercontent.com/112998185/189017348-fb39c7c6-bffd-462d-b407-b1a0fd2149c9.png)

**Additional context**
The issue occurs because the game is looking for the icon_income.png in the specific culture's ui/skin/ folder instead of using the icon from ui/skin/default/. A bandaid fix can be achieved adding the appropriate icon_income.png to each culture's subfolder.

**Comment by Harmandodelavega** [comment]
should have been fixed by 2.2
