### ISSUE TITLE
Vassal income resetting after loading a save

### ISSUE THREAD

**Issue by PussWonker26** [chadvandy/cbfm_wh3#1900]
If you save and load the game while having a vassal you no longer receive the vassal tribute you should up until that turn.

Whenever you vassalize someone, you receive a certain amount of income based on their economy. But as of the latest patch, resetting your game through a save and load, including just quitting the game, seems to reset the vassal income, only getting whatever they will start making after that save/load turn.

1. Play as Archaon (or any WoC/Slaanesh)
2. Vassalize any faction
3. Enjoy vassal tribute
4. Save/Load
5. Now you no longer have the vassal income you would get up until that point in the campaign

![image](https://github.com/chadvandy/cbfm_wh3/assets/174572562/e72ace82-6aa0-449a-9ca6-d7d0a515710b)
![image](https://github.com/chadvandy/cbfm_wh3/assets/174572562/364f8308-329c-4795-9c83-47eae3b92c4e)
![image](https://github.com/chadvandy/cbfm_wh3/assets/174572562/c52a73f4-5bb7-4187-812e-506d56b47f6e)
![image](https://github.com/chadvandy/cbfm_wh3/assets/174572562/a0a782ff-db78-4c36-89e5-dab0e5dae418)

**Comment by mfvreeland** [comment]
Mostly fixed in 5.1.1, fully fixed in 5.1.2.
