### ISSUE TITLE
Several CoC units for Khorne factions don't have increased recruitment cost like other units

### ISSUE THREAD

**Issue by AlarielleRadiant** [chadvandy/cbfm_wh3#1905]
​Old units still cost nearly 8 times upkeep ,but new units in Champions of Chaos, DLC, only cost nearly 4 times upkeep.
So what will happen? Chosen of Khorne is cheaper than Chaos Warriors of Khorne.
They think it's by design, but it's definitely not. 

Dux edit:
It's not all CoC units, but it's many of them that don't have a higher cost; some other CoC units do. Khorne is meant to have higher base recruitment costs like Nurgle as a matter of faction balance, so none of these units should be exempt.

**Comment by TWSSYesterday** [comment]
I think this is by design as it's this cost due to an override table...

**Comment by mfvreeland** [comment]
Where are you seeing this? I see Chaos Warriors of Khorne and Chosen of Khorne both costing 4x upkeep.

![image](https://github.com/user-attachments/assets/b1a91707-94a5-4a5f-9ace-1c93ec06791a)

**Comment by AlarielleRadiant** [comment]
![20240716131602_1](https://github.com/user-attachments/assets/bcae6839-f21f-4e90-af18-4b98993e0bfc)
![20240716131605_1](https://github.com/user-attachments/assets/6c232d88-365a-4e46-85c6-b0d3876564fa)

**Comment by mfvreeland** [comment]
What is causing that? It's not the recruitment value in the DB. There must be an effect somewhere, modded or otherwise.

**Comment by mfvreeland** [comment]
It's not strictly an old unit/new unit thing, because Khorne Marauders were new in Champions of Chaos, yet they seem to suffer from the same problem. I tried looking at it a bit, but I can't figure out what's going on. These values simply aren't matching the DB, but they aren't even consistently higher. Very strange.

**Comment by mfvreeland** [comment]
Cataph has the answer:

![image](https://github.com/user-attachments/assets/c4bba580-98e2-438b-af85-a21379ea2fd5)

The higher costs are intended, but Chosen were forgotten. The fix will be to add them to this table.
