### ISSUE TITLE
Beastlord's Presence, Not Simply to Add +10% Damage Resistnace

### ISSUE THREAD

**Issue by AlarielleRadiant** [chadvandy/cbfm_wh3#1906]
Beastlord’s Presence can’t affect Cold One Chariots (and as a mount), Scourgerunner Chariots (and as a mount) and Cauldron of Blood, and maybe more.
![20240703214232_1](https://github.com/chadvandy/cbfm_wh3/assets/169959655/a1388d58-d583-4b9f-aad0-d221f0c2652e)
![20240703214240_1](https://github.com/chadvandy/cbfm_wh3/assets/169959655/8ed72447-d149-47ac-98b1-4b7d2eae60d3)
![20240703214242_1](https://github.com/chadvandy/cbfm_wh3/assets/169959655/faf0f12a-bdc3-4653-9e8d-537e6e54a7df)
![20240703214245_1](https://github.com/chadvandy/cbfm_wh3/assets/169959655/1949460f-9967-45c3-94aa-45819c08f334)
![20240703214248_1](https://github.com/chadvandy/cbfm_wh3/assets/169959655/9e26831f-e56e-4950-8200-4e44a5e704cd)

**Comment by mfvreeland** [comment]
The lack of damage resistance mod was fixed already (#1682). As for the ability not targeting mounts, this is a consequence of the invalid usage flag `unit_is_not_large`, which evidently only includes large units, not large mounts. We can't do anything about this, as invalid usage flags are all defined in game code; we cannot modify them or add new ones.
