### ISSUE TITLE
Oxyotl's army abilities from Silent Sanctums don't work properly for adjacent regions

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1910]
I don't think they work at all in adjacent regions, what seems to be happening instead is that they are applying to regions in adjacent provinces instead, but I'm not completely sure.

**Comment by mfvreeland** [comment]
They seemed to work for me the last time I played an Oxyotl campaign, although that was several versions ago. Screenshots or a save may be useful here.

**Comment by allenhu0912** [comment]
I remember them working in past campaigns too but not in my current one. For example, I built two Silent Sanctums in Tehenhauin's starting province The Night Forest Road (two region province, both regions immediately adjacent to each other), each providing a different army ability. If I take a fight in that province, I only get the army ability from the current region and not the other region despite obviously being in a region adjacent from it.

I can provide more screenshots later if needed but here's the link to my bug report on CA's forum:
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/2800-issues-with-adjacent-regions-effects?page=1

Notice how Oxyotl cannot get both army abilities (one from Konquata and one from Citadel of Lead), despite Konquata and Citadel of Lead being obviously adjacent to one another. Also note how the Slann is getting the army ability from Fateweaver's Crevasse which is several regions away but is in an adjacent _province_.

**Comment by mfvreeland** [comment]
OK, that clears it up. It's strange how they did it, but basically the ability is activated in two scopes, one for the local region and one for adjacent provinces. This means that adjacent _regions_ in the same province don't count, which is obviously wrong. It should be fixable with scope changes in the DB.
