### ISSUE TITLE
Vampire Coast secondary lords can not Raise Dead while on the Sea regions.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#1914]
**Describe the bug**
As Vampire Coast (Noctilus) i can not use Raise Dead on my secondary generic lords while on the Sea regions/provinces.
For secondary generic lords the Raise Dead button is greyed out & states "no units currently available to raise"
But lord Noctilus is at the same location and can Raise Dead normally.
I have all mods disabled for this test, and the issue can be seen from turn 1 onwards in any sea region/province. 

**Expected behavior**
Raise Dead always worked on any Sea region/province for every lord of the Vampire Coast, be they Legendary Lords or generic/secondary.

**To Reproduce**
1. Play as Count Noctilus
2. Recruit generic lord from Noctilus (horde panel) on turn 1
3. Try to use Raise Dead from either lord in any Sea region/province
4. Noctilus can always Raise Dead but the Secondary generic Lord can never Raise Dead while on the sea

**Screenshots**
![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/3dbbf17c-444f-4c1f-90bb-e4afff0ad180)

**Comment by mfvreeland** [comment]
I took a look at this one, but I can't tell what the difference is. Can other horde captains raise dead at sea by chance?

**Comment by Bogdanov89** [comment]
> I took a look at this one, but I can't tell what the difference is. Can other horde captains raise dead at sea by chance?

Unfortunately i do not have the save game anymore but from what i recall Noctilus and the four tech-tree "legendary" admirals (burke, macdonald, montfort & adley) can use Raise Dead on both Sea and Land.

It is just the generic lords (vampire fleet admiral polearm/pistol) that are unable to use Raise Dead on the Sea but are able to on Land.

**Comment by Bogdanov89** [comment]
> That tracks, then. For whatever reason, only horde captains with access to shipbuilding (the legendary ones from the tech tree plus LLs) can raise dead at sea. Has it always been this way in WH3, or is this a new development? If this changed during WH3's lifetime, there's a chance we could figure it out looking through the diffs, but I suspect this might be a code issue, in which case we won't be able to fix it.

In a Tww3 youtube video (dated Oct 26, 2022) a generic vampire coast lord is still unable to use Raise Dead at Sea - its icon is greyed out, though the video creator does not mouse-over it to display the explanation tooltip of the greyed icon.

Its possible CA has unintentionally damaged this mechanic during the transition between Tww 2 and Tww 3.
Personally i can not fathom a legitimate reason why would CA intentionally deny Raise Dead at Sea to Vampire Coast generic lords.

Thanks for looking into this and i truly hope a fix is possible.

**Comment by Bogdanov89** [comment]
CA_Liam#6659 replied to this bug report on the CA forums with the following:
"Hey there! Thanks for posting. This is the intended design :) Please do post feedback on the forums as we do monitor it"

I am guessing this github issue can be closed now, if that is the protocol.
Thanks for looking into it.
