### ISSUE TITLE
Trappings of Blood set Bug

### ISSUE THREAD

**Issue by Aetius452** [chadvandy/cbfm_wh3#1916]
I think the armour of Khorne for the warriors of chaos factions might be bugged since I never seem to get it unlike its paired Item, the axe of khorne. This keeps players from getting the set´s bonus.

**Comment by Aetius452** [comment]
![20240709162230_1](https://github.com/chadvandy/cbfm_wh3/assets/175161225/8f68b488-7f34-438c-b320-da52eac35931)

**Comment by Drazhir2** [comment]
Duplicate of #1917
