### ISSUE TITLE
Trappings of blood set bug

### ISSUE THREAD

**Issue by Aetius452** [chadvandy/cbfm_wh3#1917]
I think the armour of Khorne for the warriors of chaos factions might be bugged since I never seem to get it unlike its paired Item, the axe of khorne. This keeps players from getting the set´s bonus.
![20240709162230_1](https://github.com/chadvandy/cbfm_wh3/assets/175161225/c938a51c-5ac4-43fc-a52a-682a85d24021)

**Comment by mfvreeland** [comment]
Confirmed in the DB: `wh3_main_anc_weapon_axe_of_khorne` is provided to the `anc_set_exclusive_chaos` faction set, but `wh3_main_anc_armour_armour_of_khorne` is only given to `anc_set_multi_khorne_daemons`. Should be a simple fix.

**Comment by Aetius452** [comment]
Thanks for fixing the bug.
________________________________
De: Dux ***@***.***>
Enviado: martes, 16 de julio de 2024 8:55 a. m.
Para: chadvandy/cbfm_wh3 ***@***.***>
Cc: Aetius452 ***@***.***>; Author ***@***.***>
Asunto: Re: [chadvandy/cbfm_wh3] Trappings of blood set bug (Issue #1917)


Confirmed in the DB: wh3_main_anc_weapon_axe_of_khorne is provided to the anc_set_exclusive_chaos faction set, but wh3_main_anc_armour_armour_of_khorne is only given to anc_set_multi_khorne_daemons. Should be a simple fix.
