### ISSUE TITLE
Throt has access to the generic Hell Pit landmark instead of his special one

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#192]

**Comment by floskan** [comment]
I looked up the buildings from wh2, and it looks like this for Clan moulder: http://honga.net/totalwar/warhammer2/building.php?l=en&v=warhammer2&f=wh2_main_skv_clan_moulder&b=wh2_main_special_hellpit_pits_moulder_1

While in wh3 the building is just gone and replaced with the generic skaven version of hellpits landmark

**Comment by floskan** [comment]
Also, certain resource buildings that gave growth juice doesn't anymore
