### ISSUE TITLE
Oxyotl's Silent Sanctum ability Sotek's Sanctum deals insane damage

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1923]
I'm not sure how or why it happens, but it will often delete entire infantry units almost instantly (<5 seconds) which is way more damage than what the tooltip suggests (75-150 to 25+ entity units). A post on the CA bug report forum blames this on the contact effect continuously refreshing and immediately applying the first tick of damage when a unit stands on top of the poison. From my personal observation the damage seems to be normal when the enemy unit walks out of the poison, but if they still have living entities standing inside they take insane damage, the more entities the greater the damage.

**Comment by mfvreeland** [comment]
Can you link to the bug report on the forum?

**Comment by allenhu0912** [comment]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/3058-poison-of-sotek-damage-bug?page=1

**Comment by mfvreeland** [comment]
Are you using a unit scale lower than ultra? According to CA_Liam on that report, improper damage scaling with unit size may be the crux of the issue, in which case we will need to wait for CA to fix this.

**Comment by allenhu0912** [comment]
No I'm playing at ultra. I suspect that there might be some sort of confusion in that post, since there are multiple similar abilities. Tehenhauin's faction can get a similar army ability (I haven't tried it out yet in WH3), Ark of Sotek Bastiladons get a weaker version of the ability (did not seem buggy when I tried it in my campaign), and Oxyotl can get an army ability with his Silent Sanctums (instantly annihilates anything that stays standing within the poison, normal damage if they walk out of it). All of them are called something similar to "Sotek's poison" and the bug report on CA's forum is pretty ambiguous about which one they're referring to. I can make a few screenshots if it's not clear.

There have been other bug reports about damaging effects not working under ultra (e.g. Treeman mortis engine effect from wood elf tech tree doing no damage) on their forums so I guess CA might have just jumped to an assumption.

**Comment by mfvreeland** [comment]
Looking through the DB, I can't tell why this ability would be acting the way it's being described. It sets up an immobile vortex that does no direct damage at all but instead applies a contact effect to any unit in the vortex. This contact effect should apply 8 damage to up to 25 entities (per unit) every two seconds. The Jungle Swarm ability, which IIRC is common to all Lizardmen after using a certain rite, is set up almost exactly the same, except that the damage profile for its contact effect is only 5 damage to up to 15 entities every two seconds. Is it possible that Oxyotl's version is just overtuned?

It may be worth checking the unit card for any unit that is currently being affected by this contact effect. My only thought would be that maybe it keeps getting reapplied, so it stacks multiple versions of the same contact effect, but I don't know of any other contact effect that works this way.

**Comment by allenhu0912** [comment]
Jungle Swarm is the ability Tehenhauin can buy with sacrifices IIRC. I'm not sure about Jungle Swarm but I don't think Oxyotl's ability is numerically overtuned since it should have similar damage output to Flock of Doom, but it's incredibly obvious that it deals way more damage. I have been looking at the unit card, basically if there are living entities standing in the poison the contact effect gets refreshed constantly (visually, it looks like the duration is stuck at 11 seconds remaining). My best guess is that somehow the damage effect deals one tick of damage immediately upon applying the contact effect, and since the contact effect is continuously and rapidly reapplied if there's living entities standing in the poison, they get annihilated instantly. I can't think of any way to prove or disprove this guess though.

**Comment by mfvreeland** [comment]
If you have the ability to test this easily, can you try with the below .pack active? Just move to data folder and change the extension from .patch to .pack. This is just a hunch, but it may be what's causing this to trip out while jungle swarm works ok.

[sotek_test.patch](https://github.com/user-attachments/files/16419248/sotek_test.patch)

**Comment by allenhu0912** [comment]
Screenshots before and after installing the pack file

Before:
Start of cast
![20240729175218_1](https://github.com/user-attachments/assets/cc4c1b4a-f18b-4b48-9b00-252d1106e99b)
2 seconds later
![20240729175228_1](https://github.com/user-attachments/assets/38a08bf3-d5f8-4f69-9b8d-18cd9df8d829)
4 seconds later
![20240729175400_1](https://github.com/user-attachments/assets/dc77206a-83b7-4fe3-ae6e-b4757c48e1d2)


After:
Start of cast
![20240729182041_1](https://github.com/user-attachments/assets/acf64ff9-c5b2-4079-8fff-15028f53a7d9)
2 seconds later
![20240729182049_1](https://github.com/user-attachments/assets/f46775d9-fa9f-4009-afc7-fa2221003f0c)
6 seconds later
![20240729182105_1](https://github.com/user-attachments/assets/9fea566f-c101-4e25-aaec-617c36c8780a)
12 seconds later
![20240729182113_1](https://github.com/user-attachments/assets/a193d29d-6a80-4790-9e1d-b574d4d772d3)

I don't think the pack file made a difference. In both cases I used the feral cold ones summon to keep the chaos knights in place but this far exceeds what damage they could possibly do. The damage the knights take are a bit different but this is mostly due to different number of entities caught in the poison AoE. In either case you can see that even with AI trying to run out of the AoE the knights are taking ridiculous damage.

**Comment by mfvreeland** [comment]
So much for my hunch. I see what you mean -- it definitely looks bugged -- but honestly I have no idea why. I don't see how this could be bugged by the regular "jungle swarm" ability is not, as they both work in exactly the same way, just with slightly different numbers. I am at a loss.

**Comment by allenhu0912** [comment]
During the buggy portion the HP drops extremely fast (i.e. much faster than once per second), the non-buggy portion at the end is one second per tick as expected.

**Comment by allenhu0912** [comment]
Likely no longer relevant as the ability was reworked
