### ISSUE TITLE
Ghosts of Pahuax doesn't get +ammo post battle option vs chorfs

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1925]
For the vast majority of effects Chorfs are considered chaos-aligned similar to Norsca. However Oxyotl's faction only gets the standard ransom post battle option vs Chorfs instead of the +ammo option (available for daemon factions, WoC, Norsca and Skaven).

![20240727235103_1](https://github.com/user-attachments/assets/ed8e4da3-a8eb-464a-b5dc-1b1178bed5d2)

**Comment by mfvreeland** [comment]
What is that +ammo option called?

**Comment by allenhu0912** [comment]
![20240729180547_1](https://github.com/user-attachments/assets/187265f1-36cf-467d-b2b5-2d6bc1168f32)
