### ISSUE TITLE
Von Carstein bloodline lords get Fleet-Footed instead of Blade Shield in combat line

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1926]
It seems that the tweak/nerf to Vlad's combat line was accidentally applied to the Von Carstein bloodline lords as well. I think it's unintentional as it wasn't listed in the changelogs, and CA has already had issues with goofing up vampire skill trees before (namely, Vlad and Isabella getting bloodline lord spells instead of pure lore of vampires).

![20240730191332_1](https://github.com/user-attachments/assets/26828547-8332-40b1-94a9-bd2153b9e4d4)

**Comment by floskan** [comment]
After seeing the node names i'm inclined to believe this wasn't on purpose
