### ISSUE TITLE
Stance Teleport in Tzeentch

### ISSUE THREAD

**Issue by AlarielleRadiant** [chadvandy/cbfm_wh3#1934]
Stance Teleport will turn to Stance None at the end of the turn immediately. Therefore, armies will suffer losses, which is not consistent of "immune to most attrition".
Step 1
Play as Karios, the Changeling, Deamon Prince or Vilitch.
Step 2
Stay at such place like high Vampiric Corruption.
Step 3
Keep Stance Teleport.
Step 4
End turn.
Step 5
Stance Teleport will turn to Stance None at the end of the turn immediately.
Step 6
The army suffers losses.
![image](https://github.com/user-attachments/assets/0fe11d71-1193-40f6-b290-b5872e9ca763)
![image](https://github.com/user-attachments/assets/fb8c37b3-f0ae-46c4-ae0f-4d2ec75817e3)

**Comment by Harmandodelavega** [comment]
#1169
