### ISSUE TITLE
CBFM causes the Red Duke to lose The Ordo Draconis

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1945]
with CBFM:
![20240822181053_1](https://github.com/user-attachments/assets/71859e24-5053-4e39-bd15-89ad98b0790a)
without CBFM:
![20240822181357_1](https://github.com/user-attachments/assets/3bc466f7-cec0-4884-b0d8-76a4915074dd)

**Comment by mfvreeland** [comment]
#296
