### ISSUE TITLE
Enemy Ogre camps boost recruitment rank for the player

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1948]
Deleted the ogre camp with console commands, lost 2 recruit rank.
![20240825214529_1](https://github.com/user-attachments/assets/df695652-0a1c-4bef-8cf8-4992ba6aff36)
![20240825214339_1](https://github.com/user-attachments/assets/8ec6ab80-f9d9-4876-abc5-fa11a9043f93)

Deleting the ogre camp to the north (you can just see that it's at the province's edge) further reduces recruit rank by 3.

**Comment by floskan** [comment]
force_to_force_own_provincewide is the scope used, could something else work better here @mfvreeland

**Comment by mfvreeland** [comment]
@floskan Where is the effect that does this?

**Comment by floskan** [comment]
@mfvreeland Circle around the camp sounds pretty on brand for camps, i don't know if there's a better scope for it that we could make?

**Comment by mfvreeland** [comment]
@floskan We could create a force_to_force_own_provincewide_own_faction (or something like) custom scope that is basically a copy of the existing force_to_force_own_provincewide scope but limited to to own faction. I am honestly kind of surprised this doesn't exist already -- it seems like this *should* be the default behavior of the existing scope -- but it would be easy to create. 

But I agree with you that the circle seems more intuitive for a camp bonus, anyway, so I think I'll do that.
