### ISSUE TITLE
Grom the Paunch's defeat trait does not give your units fear vs greenskins, only terror

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1949]
![20240901221046_1](https://github.com/user-attachments/assets/deecef89-18bd-43e2-888f-a0dff77dac29)

Frightened by enemy unit despite having terror

**Comment by mfvreeland** [comment]
Terror is supposed to always include fear. Is this not what it's doing?

**Comment by mfvreeland** [comment]
Ah, I see what you mean. It's probably just missing the attribute, then. We've seen that oversight in other places before.

**Comment by floskan** [comment]
Could just add the fear attribute to groms defeat trait unless i'm missing some issue that would cause
