### ISSUE TITLE
Campaign Reward - Thorek's "Ancestor Rune of Grungni" Army Ability  - Not Functioning as Described

### ISSUE THREAD

**Issue by ValiantSubmitter** [chadvandy/cbfm_wh3#1950]
**Describe the bug**
In the Dwarf campaign of Thorek, one of the final high-end rewards of his Artifact Vault feature doesn't work as described in the tooltip.
The "Ancestor Rune of Grungni" army ability is supposed to do the following for the stationary area of effect of the ability:
-- +24 Melee Attack <-- functioning
-- Unbreakable attribute <-- functioning
-- Unit is invulnerable to damage (does not apply to summoned units) <-- NOT FUNCTIONING

Units in the area of effect are getting the melee attack & unbreakable attribute, but are still taking damage as usual, and dying as normal.

Found a post on reddit describing this issue as recently as one year ago, so it isn't a recent break in effect. 

**Expected behavior**
Units within the army ability's stationary area should be invulnerable to damage (except summoned units)- if they leave this circle, the effect is lost as usual.

**To Reproduce**
1. Play as Dwarfs: Thorek Ironbrow by default
2. Unlock the Ancestor Run of Grungni, and equip to a character to grant the army ability
3. Use the army ability on units taking any amount of damage.
4. Watch units take damage/die.

**Screenshots**
N/A

**Saves**
Easy to reproduce, grant ancillary item via console.

**Additional context**
Thank you!!

**Comment by mfvreeland** [comment]
This was probably an oversight when they made invulnerable an attribute in 5.0. We should be able to fix this.
