### ISSUE TITLE
Renowned and Feared skill for Nurgle Lords doesn't increase unit recruit rank

### ISSUE THREAD

**Issue by goonit89** [chadvandy/cbfm_wh3#1956]
The blue skill line Renowned and Feared skill available for Ku'gath, Epidemius, Heralds of Nurgle and Exalted Great Unclean Ones does not provide an increase to unit recruit rank.

Step 1
Select Renowned and Feared for appropriate lord
Step 2
Recruit a new unit into Lords army
Step 3
New unit does not receive recruit rank bonus

**Comment by Harmandodelavega** [comment]
#365

**Comment by goonit89** [comment]
Appears that issue is related to Tyrion's defeat trait not applying to Nurgle recruitment
