### ISSUE TITLE
Waystalker doesn't Stalk

### ISSUE THREAD

**Issue by sgproductions87** [chadvandy/cbfm_wh3#1958]
**Describe the bug**
Waystalker was 200 metres away from the nearest rat and unit card said Waystalker was stalking but tooltip on hover said he wasn't. Then he got shot by Warp Lightning Cannons and I was a sad panda. He only went back on Stalk when returning to trees and left it if he came out.

**Expected behavior**
Waystalker stalks even when firing (because Snipe).

**To Reproduce**
1. Play as Wood Elves  (Orion probably best to try because he starts with Stalk)
2. Embed Waystalker and attack enemy
3. Run him around 200m+ away. Observe icon above unit card showing Hidden, but hover over him with cursor and tooltip doesn't say Hidden. Hover over units hidden in trees - it says Hidden. So that's how you know something is wrong.

**Screenshots**
![20240910141356_1](https://github.com/user-attachments/assets/80f63c54-9253-4881-813f-39cebe615d79)

**Additional context**
I was playing as Argwylon and running a lot of mods but none had interaction with Stalk or Waystalkers or Wood Elves.

**Comment by mfvreeland** [comment]
Can't repro in vanilla 6.0.2
