### ISSUE TITLE
Win a walled siege in Jungle/Desert region Vow not always working

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#196]
Pledge to Campaign
may not work for walled minor settlements, reinforcing armies, or not at all

**Comment by floskan** [comment]
Can you try to add saves, more info or screenshots of your reports?

**Comment by Harmandodelavega** [comment]
#196

**Comment by floskan** [comment]
Not affecting embedded heroes currently

https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/4095-needs-more-info-pledge-to-campaign-not-triggering-on-jungle-desert-sieges-for-embedded-heroes

**Comment by mfvreeland** [comment]
As discussed on Da Den, I don't see why this should have stopped working. This will require some investigation. A save would be nice.

**Comment by mfvreeland** [comment]
Yeah, this isn't broken (anymore).
