### ISSUE TITLE
Boris and Ostankya don't receive the Banner of the Orthodoxy ancilllary from researching "Orthodoxy Blessed"

### ISSUE THREAD

**Issue by Mandras2** [chadvandy/cbfm_wh3#1968]
### Problem:

Ostankya and Boris (the Kislev factions) have access to the "Orthodoxy Blessed" technology but use separate technology nodes not accounted for in the script that awards ancillaries for researching techs.

**"technology_nodes" table:**
wh3_main_tech_ksl_4_14  <----------(default node used by Katarin/Kostaltyn)
wh3_main_tech_ksl_4_14_boris
wh3_dlc24_ostankya_tech_ksl_4_14_ostankya

**"technology_nodes_to_ancillaries_junctions_tables" has the banner linked to all three nodes:**
wh3_main_anc_magic_standard_banner_of_the_orthodoxy	wh3_dlc24_ostankya_tech_ksl_4_14_ostankya
wh3_main_anc_magic_standard_banner_of_the_orthodoxy	wh3_main_tech_ksl_4_14_boris
wh3_main_anc_magic_standard_banner_of_the_orthodoxy	wh3_main_tech_ksl_4_14

**the script "wh3_campaign_tech_tree" only has this line under ancillary_mapping:**
wh3_main_tech_ksl_4_14 = "wh3_main_anc_magic_standard_banner_of_the_orthodoxy"

### FIX:

**add two lines to "wh3_campaign_tech_tree" at the end of ancillary_mapping ={ }:**
wh3_dlc24_ostankya_tech_ksl_4_14_ostankya = "wh3_main_anc_magic_standard_banner_of_the_orthodoxy"
wh3_main_tech_ksl_4_14_boris = "wh3_main_anc_magic_standard_banner_of_the_orthodoxy"

**Comment by floskan** [comment]
Might be fixed since the tech tree has changed

**Comment by mfvreeland** [comment]
Yeah, these unique Boris/Mother O techs are gone.
