### ISSUE TITLE
The Reliquary Overload Ability is in the Files but not Actually Given to Mortis Engines

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1973]
Exactly what the description says. The following mod fixes it:
>https://steamcommunity.com/sharedfiles/filedetails/?id=3354227608

**Comment by Autumnchain** [comment]
I wonder what the reason for removing the explosion was. The explosion, as it existed in the files, is an ok consolation prize for losing an expensive unit but it's not very powerful. It's 48 damage (50% AP) and a 15m range. An explode on death ability would have to be far more powerful for it to affect game balance and considering the Mortis Engine's main ability is to kill enemies with proximity, it would be preferable to have a 1HP Mortis Engine than charging it into a enemy unit to blow up on them.

**Comment by allenhu0912** [comment]
Mortis Engines are primarily used by being embedded within your own infantry blobs. Making the Mortis Engine explode upon death really just serves as insult on top of injury should the VC player get it killed.
