### ISSUE TITLE
Researching certain Tomb Kings tech while under 100 research points stops the research from finishing

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1996]
Seems to apply to techs that have specific costs beyond research rate

Fix suggested by Shin 
https://discord.com/channels/373745291289034763/581350140942483456/1311310114057355316

**Comment by floskan** [comment]
Not all 1 turn tech is added to the fix now, need to add some stuff. Looked at gameplay from game 2, all tech associated with a cost only took 1 turn to research

**Comment by mfvreeland** [comment]
As far as I know, all tech that costs resources other than research points is supposed to only take one turn by design, and that has always been the case with every race that has techs like this. The extra resource cost being subtracted more than once also sounds like an obvious bug. Will this also fix that?

To do this fix right, we should really include all techs with a resource cost from all races (assuming they are broken too).

**Comment by floskan** [comment]
It would "fix it" with the side effect of being granted extra overflow for having the tech cost so low

**Comment by mfvreeland** [comment]
Maybe we could compromise and make the value something like 25. You'd still get overflow, but not quite as much. The current system will give you extra overflow whenever your research rate is over 100%, anyway. CA would need to fix this properly, but in the meantime I think this band-aid is sensible.

**Comment by floskan** [comment]
Yeah, I agree. I'll look if there's more tech to be added to this

**Comment by floskan** [comment]
I think adding other races tech to this fix isn't necessary considering how rare it is to ever be under 100 research rate. Many races often go over 100 and some does that really early on in the campaign.

**Comment by allenhu0912** [comment]
Maybe you can go under 100 with High Elves if you hire a Luddite lord.

**Comment by floskan** [comment]
I've added all tech that costs money or urns. If someone notices something similar happens to other factions, we'll make that into a separate fix

**Comment by kasperchaz585** [comment]
> Seems to apply to techs that have specific costs beyond research rate
> 
> Fix suggested by Shin https://discord.com/channels/373745291289034763/581350140942483456/1311310114057355316

Hey when I click on this link it takes me to discord but shows me nothing. I am new to using github.

**Comment by mfvreeland** [comment]
From 6.3 notes: "Fixed an issue where some technologies, such as Dynasties would get stuck on 1 turn before completion and charge it’s cost again when it got reset"

**Comment by mfvreeland** [comment]
Looks like it was fixed in the post-beta changes.

**Comment by mfvreeland** [comment]
https://www.reddit.com/r/totalwar/comments/1n6kyl1/new_tomb_king_technology_bug/
