### ISSUE TITLE
Chaos vassals have passive / maybe rebel AI

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#2]
https://www.reddit.com/r/totalwar/comments/wxf6v7/chaos_warrior_vassals_are_just_standing_around_i/?utm_medium=android_app&utm_source=share

**Comment by chadvandy** [comment]
zzz_cfm_braindead_norsca_vassals - NEEDS TESTING!

**Comment by chadvandy** [comment]
fix doesn't work - there's not much that can be done about this. It's caused by confederation-related code that we can't really affect at all. Flagging for CA.

**Comment by chadvandy** [comment]
closing because we can't do much here

**Comment by sm0kin** [comment]
With patch 2.2.0 CA changed some of the occupation options, e.g. reinstating elector count faction (prolly also revived norscan vassals), to no longer work for already confederated faction by ui-locking (greying out) the related occupation button.
