### ISSUE TITLE
Miao Ying "Evasion" skill requires 5 points in the previous nodes, compared to the 4 that is standard

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2002]

**Comment by allenhu0912** [comment]
Same thing for Zhao Ming so possibly intended

**Comment by floskan** [comment]
Maybe. Yuan Bo has 4 points required with the same amount of spells in the previous category

**Comment by mfvreeland** [comment]
I'm gonna say this is a bug/oversight.
