### ISSUE TITLE
Eight Peaks dilemma will soft lock game when dorf faction is AI not player

### ISSUE THREAD

**Issue by LordOmlette** [chadvandy/cbfm_wh3#2005]
**Describe the bug**
In wh3_campaign_underdeep.lua => UnderdeepForeignSlotBuildingCompleteEvent, the code checks to see if the undercity just built was "wh3_main_underdeep_dwf_main_karak_eight_peaks_3".  If it is, then it launches the dilemma "wh3_main_dwf_move_capital_eight_peaks".  The problem is that this cannot possibly succeed since the AI can't respond to a dilemma.

**Expected behavior**
If you're not the faction owning Eight Peaks, your campaign should not stop forever just because the AI got a dilemma.

**To Reproduce**
1. Mind your own business.
2. Let some Dwarf faction capture Eight Peaks.
3. Wait for them to finish the final undercity.
4. Your campaign is over, you cannot proceed.

**Additional context**
script\campaign\wh3_campaign_underdeep.lua line 175

**Comment by mfvreeland** [comment]
Good find. I'll make sure this gets into our first batch post-patch if CA hasn't fixed it on their end in 6.0.

**Comment by mfvreeland** [comment]
Doesn't look like this script was touched in 6.0 or any of the hotfixes thus far.
