### ISSUE TITLE
Unyielding Assult does not work 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2010]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5269-unyielding-assult-does-not-work?page=1

**Comment by mfvreeland** [comment]
I don't think Unyielding Assault is meant to apply to vigor effects, which are fundamental to all units. It's meant to make it so melee attack debuffs (like those from hex spells) don't affect him, and that works fine. Gonna say not a bug.
