### ISSUE TITLE
Multiple main settlement chains for Skarsnik and Wurrzag

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#202]
can be fixed in slot template permitted building chains, building set to building junctions or maybe building culture variants too I think

Karaz a Karak/Black Crag/8Peaks as Skarsnik (probably all Grns)

**Comment by Harmandodelavega** [comment]
no biggie

**Comment by mfvreeland** [comment]
This can become a more significant problem, at least when playing as Lizardmen, if Itza gets destroyed by another race. Reclaiming it will then default to the regular (non-Itza) primary chain, which locks out Itza's unique characteristics (including lowering the max number of building slots).

I have a fix for Itza at least. I will have to investigate K8P to see if a similar issue can arise there.

**Comment by Harmandodelavega** [comment]
CA says Itza is fixed

**Comment by mfvreeland** [comment]
Indeed, Itza is fixed. I'm not sure about the current status of the others.

**Comment by mfvreeland** [comment]
The special settlements are still busted for Skarsnik and Wurrzag in 4.2 because they use unique main settlement chains that weren't accounted for with the special settlements like Karaz-a-Karak or Black Crag. The fix is pretty simple, will add a PR for it soon.

**Comment by floskan** [comment]
> The special settlements are still busted for Skarsnik and Wurrzag in 4.2 because they use unique main settlement chains that weren't accounted for with the special settlements like Karaz-a-Karak or Black Crag. The fix is pretty simple, will add a PR for it soon.

Can you ping me when you put up a PR for this? Was looking to try a Wurrzag campaign!
