### ISSUE TITLE
Skarsnik gets a buggy version of the orc recruitment building after capturing K8P

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#2035]
![20241214101016_1](https://github.com/user-attachments/assets/49b3464b-ac9e-4042-9943-b3b155cd3ba6)

I believe it's bugged as it doesn't even have a name like other buildings do. I suspect they forgot something when reworking Skarsnik's faction. The correct building chain is on its right.

**Comment by floskan** [comment]
> ![20241214101016_1](https://private-user-images.githubusercontent.com/54481962/395795790-49b3464b-ac9e-4042-9943-b3b155cd3ba6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzcxOTYsIm5iZiI6MTczNDI3Njg5NiwicGF0aCI6Ii81NDQ4MTk2Mi8zOTU3OTU3OTAtNDliMzQ2NGItYWM5ZS00MDQyLTk5NDMtYjNiMTU1Y2QzYmE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE1MzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YTQ2ZmYzNDI5OWMyNDM5YTkwNjY3NTQ3NTY3ZTkxZDQxNTE3NmY0ZGEyMzgxZTM4ZjIyYjI0Zjg2ZGYxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SwZOF3yUT4jrIAtJEjgeCcSeObKSBWOGBFEJTJ26GpU)
> 
> I believe it's bugged as it doesn't even have a name like other buildings do. I suspect they forgot something when reworking Skarsnik's faction. The correct building chain is on its right.

Do you have a save @allenhu0912

**Comment by allenhu0912** [comment]
I used the console command mod to force confederate K8P on turn 1. This wasn't an actual campaign, and it might be fine if you acquire K8P normally, or without mods.

**Comment by floskan** [comment]
> I used the console command mod to force confederate K8P on turn 1. This wasn't an actual campaign, and it might be fine if you acquire K8P normally, or without mods.

Yeah this works fine
