### ISSUE TITLE
Redundant skill for Butchers and Slaughtermasters 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2039]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5510-redundant-skill-for-butchers-and-slaughtermasters?page=1

**Comment by mfvreeland** [comment]
Skill still has other useful effects, but yeah part of it is redundant

**Comment by mfvreeland** [comment]
Fixed in 6.0.3.
