### ISSUE TITLE
Gorbad Ironclaw "Regimental" Big plan not working

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2040]
"The Big plan regimental doesn't increase campaign movement speed. The upkeep reduction looks like  its working.  I cant tell if the vigor reduction is working."

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5486-gorbad-ironclaw-big-plans-dont-work?page=1

**Comment by mfvreeland** [comment]
According to CA_Liam, the effect works but it only applies next turn (true for many things) and cannot apply during a Waaagh, which hard caps army movement speed to 100. CA may adjust some of this in the future, but I don't think we should touch it.
