### ISSUE TITLE
New Tech "Avalanch Smash" is downgrade for Rock Lobber RoR 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2053]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5539-new-tech-avalanch-smash-is-downgrade-for-rock-lobber-ror?page=1

**Comment by floskan** [comment]
Also maneater tech for eshin maneater, loses weeping blades

**Comment by mfvreeland** [comment]
It would be cool if they allowed multiple contact effects...

**Comment by mfvreeland** [comment]
Fixed in 6.0.3
