### ISSUE TITLE
CHAOS LORD OR EXALTED HERO WITH CHAOS CHARIOT OR GORBEAST CHARIOT 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2065]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5556-chaos-lord-or-exalted-hero-with-chaos-chariot-or-gorbeast-chariot?page=1

**Comment by mfvreeland** [comment]
Duplicate of #1883
