### ISSUE TITLE
Thorgrim Grudgebearer loses 1 High King's Decree on ending turn 1 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2073]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5597-thorgrim-grudgebearer-loses-1-high-king-s-decree-on-ending-turn-1#post-5605

**Comment by floskan** [comment]
Might this be something going wrong in the script @mfvreeland

**Comment by mfvreeland** [comment]
Turned out to be a db problem after all... the bonus value for the effect was unhooked in 6.0 for some reason.
