### ISSUE TITLE
Skullcloak effects triggers when any army wins a battle, not just skulltaker

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2077]
https://www.reddit.com/r/totalwar/comments/1hdu7cm/skulltaker_isnt_a_bloodletter_hes_a_freaking/

Sounds way to overtuned and probably not intended

**Comment by mfvreeland** [comment]
Is this one particular ability? Maybe we can just change a scope to reign it in.

**Comment by floskan** [comment]
I haven't played skulltaker myself but as i understand it all effects that can trigger on the skullcloak tab triggers no matter what army does it. Blood hosts can spawn more blood hosts etc

**Comment by mfvreeland** [comment]
Fixed in 6.0.3
