### ISSUE TITLE
Chosen and Chaos Warriors of Khorne units have no visual flame effect on their weapons 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2092]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5674-update-6-0-0-chosen-and-chaos-warriors-of-khorne-units-have-no-visual-flame-effect-on-their-weapons?page=1

**Comment by mfvreeland** [comment]
Duplicate of #2091
