### ISSUE TITLE
Beastmen don't get a Bray Shaman in their Garrison when building Herdstone Enhancements 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2097]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5806-beastmen-don-t-get-a-bray-shaman-in-their-garrison-when-building-herdstone-enhancements?page=1

**Comment by mfvreeland** [comment]
The garrison is just maxed out, and the game decided to cut the hero
