### ISSUE TITLE
Violent hunger gift of chaos not working for skullcrushers

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#21]
https://forums.totalwar.com/discussion/319822/violent-hunger-gift-of-chaos-doesnt-apply-bloodgreed-to-skullcrushers#latest

**Comment by chadvandy** [comment]
this one is strange - there's no "mkho" variant of Skullcrushers, so I don't see an immediate way to assure the ability only applies to marked Skullcrushers instead of all Skullcrushers. @Cataph any insight?

**Comment by mfvreeland** [comment]
I am 99% certain that Warhammer lore dictates there can be no such thing as an unmarked Skullcrusher.

**Comment by Cataph** [comment]
Yeah they should definitely get it, Skullcrushers are by default marked by Khorne just like Hellstriders are Slaaneshi by default. They even explicitly have the faux-attribute Mark of Khorne.

**Comment by chadvandy** [comment]
Ah gotcha, I was looking for a unit ability for the mark not an attribute. I'll toss in the fix when I get home

**Comment by chadvandy** [comment]
fixed by #39

**Comment by floskan** [comment]
Doesn't actually give them bloodgreed, 
[Legion of the Gorequeen skull.1142578000978.zip](https://github.com/chadvandy/cbfm_wh3/files/9482373/Legion.of.the.Gorequeen.skull.1142578000978.zip)
