### ISSUE TITLE
Naval march stance doesn't affect vigor

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#210]
in eff bundle to eff jun change the scope of:
 wh_main_bundle_stance_navy_double_time     wh_main_effect_force_campaign_stance_begin_fatigued_4_tired
to "force_to_force_own"

https://steamcommunity.com/app/1142710/discussions/1/3546050190336960435/

**Comment by mfvreeland** [comment]
Is it supposed to? I thought only land march stance affected vigor by design, but I could be wrong.

**Comment by Harmandodelavega** [comment]
Only high elves get normal vigour when marching on sea
