### ISSUE TITLE
Skrag's World-Swallower and Prophet of the Great Maw intensity do not stack 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2109]
"Both work in isolation once the battle starts, the problem is as they are the same ability phase they can't stack. You will have 110% intensity rather than 120%."
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5825-skrag-s-world-swallower-and-prophet-of-the-great-maw-intensity-do-not-stack?page=1

**Comment by floskan** [comment]
Would making a new ability with the same effect work for this?

**Comment by mfvreeland** [comment]
@floskan Have you tested this? It seems like a clever solution that should work, but I wanna make sure.

**Comment by mfvreeland** [comment]
Fixed/changed by CA in 6.3, no longer applicable.
