### ISSUE TITLE
Lava Arachnarok Spider Stats

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#2112]
Before 6.0, the Lava Arachanrok was a very high cost unit and its Leadership, Melee Attack and Melee Defence stats were on the level of rank 9 regular Arachnarok spiders. However, their cost has been reduced by a lot but their stats weren't lowered to go with it. It's questionable if it's a bug but it seems like their Leadership, Melee Attack and Melee Defence should be on the level of regular Arachnarok's.

**Comment by floskan** [comment]
It's still a rare unit that you might get 2-3 of in a normal campaign, not sure this qualifies as a bug

**Comment by mfvreeland** [comment]
Definitely too debatable to qualify as a bug.
