### ISSUE TITLE
Khorne corruption gives the stated melee attack twice

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2122]
![Screenshot_2024-12-23-10-46-39-35_a5f05134355d0c28d0e7113add1d3465](https://github.com/user-attachments/assets/a3bce78c-0fd0-45e8-862b-79bd12fad8d7)

**Comment by allenhu0912** [comment]
I've had similar issues with the physical resistance from low levels of Nurgle corruption.

**Comment by floskan** [comment]
> I've had similar issues with the physical resistance from low levels of Nurgle corruption.

Does this mean physical resistance loss is doubled?

**Comment by allenhu0912** [comment]
No, you get very small amounts of phys res if you're not playing as Nurgle, but there are low levels of Nurgle corruption. But what you actually get is double the value the tooltip tells you.

https://github.com/chadvandy/cbfm_wh3/issues/1829

**Comment by floskan** [comment]
![image](https://github.com/user-attachments/assets/e2f7b6ba-2400-473a-9a02-0d2298ee1fca)

**Comment by floskan** [comment]
@mfvreeland Can you tell why this is doubling? The effects never seem to be tied to the same corruption bundles but it still doubles

**Comment by floskan** [comment]
![image](https://github.com/user-attachments/assets/d46c6420-3a19-4ad7-81af-60649a349b09)

Testing a pack with all hidden MA effects set to 0 fixes it when playing as Kho at least, not sure if this affects AI khorne factions or something.

**Comment by floskan** [comment]
Seems to be fixed. If there's a need to revisit this for other monogods corruption i'll grab an older pack and keep working on this
