### ISSUE TITLE
Azhag not giving army immune to psychology 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2123]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5971-azhag-s-army-missing-immune-to-psychology?page=1

**Comment by mfvreeland** [comment]
The scope limits the ability to neutral territory (neither friendly nor enemy) for some reason. This really limits the usefulness of the ability and seems like an oversight. I'd say it's a bug.

**Comment by floskan** [comment]
From 6.2:
"Azhag the Slaughterer’s trait, Slaughterer, now correctly grants Immunity to Psychology to his army. "
