### ISSUE TITLE
Louen Leoncoeur heal is one use and automatically goes off at the beginning of the battle

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2124]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5946-louen-leoncoeur-heal-is-one-use-and-automatically-goes-off-at-the-beginning-of-the-battle?page=1

**Comment by mfvreeland** [comment]
It's passive with unlimited duration. Not a bug.
