### ISSUE TITLE
Tomb king lords cost money to replace

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#213]
maybe only if they're killed in battle and your army retreats

**Comment by Bogdanov89** [comment]
this is the same bug from TWW2 that CA fixed at some later point, but i guess its back because TWW3 is some old version of TWW2.
![image](https://user-images.githubusercontent.com/55892027/189141765-220b66d6-44b2-4842-a29a-29633775503d.png)
