### ISSUE TITLE
Azhag - missing death magic, overlapping vampiric immunity 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2131]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5984-azhag-useless-bonuses-missing-death-magic?page=1

**Comment by mfvreeland** [comment]
The leftover Vampiric Immunity for quest items and landmarks is redundant, but it doesn't cause any problems. This is not really a bug. CA is almost certainly going to rework Azhag a little for 6.1 also.

**Comment by mfvreeland** [comment]
Looks like you were right about the missing magic! CA fixed in 6.0.5.
