### ISSUE TITLE
Overlapping Character Skills 6.x

### ISSUE THREAD

**Issue by dragonkip04** [chadvandy/cbfm_wh3#2156]
**Describe the bug**
Various characters have overlapping skills causing one skill to disappear. This is due to these skills being assigned to the same skill node. The ones I have found are as follows:
**Grimgor's** Immortulz Armour causes Hatred to disappear
The **Goblin Big Boss'** Ambusher causes Nasty Skulker to disappear
The **Prologue Cultist of Khorne's** Gate of Khorne causes Hates Slaanesh to disappear

**Expected behavior**
Move one of the overlapping skills to uncover the other. Usually one node to the right.

**To Reproduce**

1. Recruit any of these characters
2. Open their skills panel
3. See that the skills are missing

**Additional context**
I made a simple mod to fix these. Maybe you can include it in your future update.
[overlapping_skills_6.x.zip](https://github.com/user-attachments/files/18266714/overlapping_skills_6.x.zip)

**Comment by floskan** [comment]
Thank you, we'll make use of your fix minus the fix for Grimgor since we already have that in CBFM.
