### ISSUE TITLE
Skullcrushers doesn't benefit from WoC red line 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#22]
https://steamcommunity.com/sharedfiles/filedetails/?id=2853823444&searchtext=Skullcrusher

https://www.reddit.com/r/totalwar/comments/wwfe7w/_/

The first part of Redline buffs work fine, they just aren't assigned to a rank 7+ skill

**Comment by Harmandodelavega** [comment]
wh3_dlc20_kho_cav_skullcrushers_mkho_ror	kho_cavalry_chariots removed
