### ISSUE TITLE
Bray Shaman missing missile res skill (overwritten node) 

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#221]
name: shadow_hide
you will probably have to move immortality as well

**Comment by Harmandodelavega** [comment]
@mfvreeland  where do you see it fixed

**Comment by Harmandodelavega** [comment]
still overwritten my many_limbed_friend

**Comment by mfvreeland** [comment]
I just tested it in vanilla and saw the skill: 
![image](https://github.com/chadvandy/cbfm_wh3/assets/112144702/756b6f25-e4d1-4265-a09e-b9e94ba47ffd)

**Comment by Harmandodelavega** [comment]
ok, just in case, this isn’t from great bray shaman right?

**Comment by mfvreeland** [comment]
This is from the regular (hero) bray shaman. I was totally focused on the missile resist skill, though, and didn't check the underlying issue. There's still two skills with the same node, so I'll revert the removal of this in the PR (and update for 4.0 table format), which I think should fix it either way.
