### ISSUE TITLE
Dwarfs are able to equip only 1 unique banner rune per lord

### ISSUE THREAD

**Issue by VidarSarnesjo** [chadvandy/cbfm_wh3#242]
**Describe the bug**
The Dwarfs can't utilise more than 1 unique banner rune per army. In the second game they could equip as many as they deemed fit and they had available. 

**Expected behavior**
You should be able to equip as many runes as you like and have available in each army.

**To Reproduce**
1. Play as any dwarf
2. Craft a set of 3 runes
3. Try to equip them all in a single army

**Comment by Bogdanov89** [comment]
This is part of CAs global change to not allow identical ancillaries to be stacked on a single lord/hero.
Whether its intended to affect dwarf runes or not is impossible to tell at this point, unless CA directly clarifies.

**Comment by Harmandodelavega** [comment]
Yeah, might be intended
