### ISSUE TITLE
Thorgrim starting Master Engineer hero "Tom Philipson" missing unique trait, item, and unlocked skills from Warhammer II

### ISSUE THREAD

**Issue by VidarSarnesjo** [chadvandy/cbfm_wh3#243]
**Describe the bug**
The master engineer starting hero for Thorgrim used to have a unique trait, an item, as well as some skills unlocked at game start in Warhammer II.

**Expected behavior**
A unique trait "Engineer's Cipher" and the item "double barrel" should be provided at game start. The skills "Grudge-Raker" and "Immortality" also used to be unlocked.

1. Play as Karaz-a-Karak
2. Check the starting hero

**Screenshots**
Warhammer III state: (https://i.imgur.com/acqEYyv.png) (https://i.imgur.com/4eGtQwV.png)

**Comment by Harmandodelavega** [comment]
Double barrel is faction locked to vampire coast now

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2
