### ISSUE TITLE
Snotling Pump Wagons are not affected by the skill "Sneaky Stabberz" at rank 7+ redline

### ISSUE THREAD

**Issue by VidarSarnesjo** [chadvandy/cbfm_wh3#244]
**Describe the bug**
Sneaky Stabberz generic redline skill does not apply bonuses to the Pump Wagons after rank 7.

**Expected behavior**
Since the skill states that Pump Wagons are affected by the skill, they should have the bonuses.

**To Reproduce**
1. Play as any greenskin
2. Recruit Pump Wagons
3. Level the skill "Sneaky Stabberz"
4. Get a Pump Wagon regiment to rank 7

**Screenshots**
(https://i.imgur.com/qRO0ZeS.png)
(https://i.imgur.com/lb71Nop.png)
(https://i.imgur.com/Noug9E7.png)
(https://i.imgur.com/aqhwh1W.png)

**Saves**
(Btw, savegames can't be uploaded to Git)
(https://i.imgur.com/y8CnG9c.png)

**Comment by floskan** [comment]
Saves can be uploaded if you make a zipfile with the save in it
