### ISSUE TITLE
Skaven Slingers use the wh_main_weapon_trail_rifle as weapon trail

### ISSUE THREAD

**Issue by voszo** [chadvandy/cbfm_wh3#246]
**Describe the bug**
Not sure if this is intended but Skaven slinger use the rifle trail as weapon trail. What i think looks a bit silly.

**Expected behavior**
They should be using the weapon trail "wh_main_weapon_trail_arrow_small"

**To Reproduce**
1. Check table db/projectile_display_tables/data__
2. Check for key "wh2_main_skv_sling_bullet"
3. The column "Trail Fx" is set to "wh_main_weapon_trail_rifle"

**Comment by Harmandodelavega** [comment]
@voszo are you sure this is a bug? they call the projectile in the files "sling_bullet" and it's been like this since WH2, if you got a screenshot and it's ridiculous I'll change it
