### ISSUE TITLE
No dismemberment for TK/Vcounts

### ISSUE THREAD

**Issue by sirmicou** [chadvandy/cbfm_wh3#247]
Hello !

I have to report you a bug/missing feature, which concerns Tomb Kings and Vampire Coast : there is no dismemberment for units from those factions (even with the Blood DLC), while it works on the Vampire Counts skeletons and zombies units (and even on units from all other factions)...

It would also be nice to see, like the Vampire Counts units, skeletons and zombies still fighting with missing head or members.

Can you fix this please ?

Thank you !

**Comment by Harmandodelavega** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2853265255

not sure it's a bug, closing for now
