### ISSUE TITLE
All non-artillery war machines (e.g. steam tank)missing firing sound

### ISSUE THREAD

**Issue by sirmicou** [chadvandy/cbfm_wh3#248]
https://github.com/Shazbot/WH3-Dump/commit/e7942f19e2b1a392b503f000a7a72a958ed6c373#diff-d5f6ef2732b2560913d9612cd11ed81567d8c3c9137323ced9ad73249b95922a  mby fixed

When Empire steam tanks are firing, there is no sound (I mean the main cannon, because the turret's sound works well).

ChaosRobie:
I can elaborate on "Steam tank missing firing sound from main cannon"
(https://trello.com/c/OQU2Kn80))](https://trello.com/c/Y9YUbBTL/693-steam-tank-missing-firing-sound-from-main-cannon)
It's actually all non-artillery war machines, their projectile firing sound simply doesn't play. It's not related to animation.
To check, I switched the great cannon to behave like a war machine, and it's firing sound disappears. Also when I change the steam tank to behave like regular artillery, it's firing sound reappears.

Update:
found out why none of your tanks have firing sound, your entire "missile weapon" column in battle_engines_tables is blank, you gotta add keys from missile_weapons_tables into it,also

https://github.com/Shazbot/WH3-Dump/commit/e7942f19e2b1a392b503f000a7a72a958ed6c373#diff-d5f6ef2732b2560913d9612cd11ed81567d8c3c9137323ced9ad73249b95922a

**Comment by Bogdanov89** [comment]
This is a really old bug, i think CBFM did include a fix for it in TWW2 but perhaps was removed if CA got around to fixing it towards the end of TWW2.
Unfortunately many such bugs are back in TWW3.

**Comment by mfvreeland** [comment]
If there is an old fix to this, does anyone have it?

**Comment by Harmandodelavega** [comment]
It's still an open issue infortunately

**Comment by Harmandodelavega** [comment]
https://github.com/Shazbot/WH3-Dump/commit/e7942f19e2b1a392b503f000a7a72a958ed6c373#diff-d5f6ef2732b2560913d9612cd11ed81567d8c3c9137323ced9ad73249b95922a mby fixed

**Comment by sirmicou** [comment]
It seems 3.1 fixed that...
