### ISSUE TITLE
Awful "Pixelated" Corruption Frontiers

### ISSUE THREAD

**Issue by sirmicou** [chadvandy/cbfm_wh3#249]
Hello,

Just a picture to report what ugly effect happens on the campaign map with corruption at frontiers between provinces :

[img]https://us.v-cdn.net/5022456/uploads/editor/2i/ab7mgvjjy43r.png[/img]

Is it possible to make this softer and less squared or geometric ?

Thank you !

**Comment by Harmandodelavega** [comment]
No caps lock

**Comment by mfvreeland** [comment]
CA is working on this apparently, but we can't fix it.
