### ISSUE TITLE
Dwarf ancestor spirits (Thanes) haven't been updated for ethereal changes

### ISSUE THREAD

**Issue by kurtbaird** [chadvandy/cbfm_wh3#252]
**Describe the bug**
When CA updated ethereal units as part of 2.0, they didn't fully apply the changes to the Thane Dwarf Ancestor Spirts (the two that start with Belegar, the one with Thorek and and the one summoned through Horn of Ancestors).

Their physical resistance is still 75%, their HP isn't buffed (although only units who have had physical resistance had a health buff) and the weapon damage hasn't been updated properly

More info can be seen in the patch notes for 2.0 to see how the changes were applied correctly to the Runesmith and Master Engineer heroes. 

**Expected behavior**
To bring them in line with other ethereal units, that should have 55% physical resistance and have their HP buffed. 

AP weapon damage should be buffed be consistent with the weapon damage changes to the other Ancestors. 

**To Reproduce**
1. Load up a Belegar campaign
2. Inspect unit stats

OR

1. Look at units in quick battle

**Comment by Harmandodelavega** [comment]
UNITS
ANCESTOR SPIRIT

Armour-Piercing Damage: 125 → 250
Removed the 250 Base Weapon Damage
DRAMAR HAMMERFIST

Hit Points: 2532 → 3292
Physical Resistance: 75% → 55%
Armour-Piercing Damage: 220 → 280
Removed the 60 Base Weapon Damage
Added Contact Effect: Frostbite
HALKENHAF STONEBEARD

Armour-Piercing Damage: 125 → 250
Removed the 250 Base Weapon Damage
Added Contact Effect: Frostbite
HANS VALHIRSSON

Armour-Piercing Damage: 125 → 375
Removed the 125 Base Weapon Damage
Added Contact Effect: Frostbite
KING LUNN IRONHAMMER

Armour-Piercing Damage: 125 → 250
Removed the 250 Base Weapon Damage
Added Contact Effect: Frostbite
THRONI IRONBROW

Hit Points: 2532 → 3292
Physical Resistance: 75% → 55%
Armour-Piercing Damage: 90 → 320
Removed the 230 Base Weapon Damage
Added Contact Effect: Frostbite

**Comment by Harmandodelavega** [comment]
Per the patch notes it's probably not a bug but an oversight, gonna close
