### ISSUE TITLE
Immortality battle effects weird behavior

### ISSUE THREAD

**Issue by Diesel215** [chadvandy/cbfm_wh3#253]
**Describe the bug**
Da Immortulz Banner is not stopping models within the attached unit from dying before leadership drops below half. These deaths occur more often when hit by large amounts of damage at a time, such as siege towers, artillery, or cavalry charges.

**Expected behavior**
A unit with Da Immortulz Banner should be unable to lose any models within the unit until leadership drops below half of the base amount

**To Reproduce**
To easily reproduce the issue:
1. Enter the first battle of Grimgor Immortal Empires campaign
2. Shoot at unit of black orcs (with Da Immortulz banner equipped) with your doomdiver catapult

**Comment by grubby997** [comment]
they dont actually die, they stand up after being knocked down and then end up being disconnected from their unit which ends up meaning that the black orc will just stand in the spot that they got knocked into and only attacking if a enemy unit is in range

**Comment by ArmourYoshi** [comment]
This also happens with Ungrim's "Journey's End" effect and existed in the final few patches of WH2. They also get these units back at the end of the battle so no replenishment required. WH2 screenshots but this doesn't seem to be different in WH3.
![20210415233846_1](https://user-images.githubusercontent.com/113547884/192165788-822433ab-9bd6-42f6-9ce1-63892f691808.jpg)
![20210415233849_1](https://user-images.githubusercontent.com/113547884/192165789-03b06224-afd2-4f06-a97b-db0e568449a4.jpg)
![20210415234458_1](https://user-images.githubusercontent.com/113547884/192165791-3e6b4212-b78c-48f4-9717-282d8f98c367.jpg)

**Comment by Harmandodelavega** [comment]
https://forums.totalwar.com/discussion/294831/da-immortulz-banner-bugged-does-not-prevent-artillery-and-maybe-ranged-deaths#latest

**Comment by mfvreeland** [comment]
Unsure if this is fixable, as the proper flag is enabled in the DB. I believe this will require a code fix on CA's part.

**Comment by Harmandodelavega** [comment]
#901 adding this for reference
