### ISSUE TITLE
Shield Block tooltip shows wrong stats and has iffy persistence

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#255]
**Describe the bug**
Shield block tooltip (on hovering shield icon next to armour on shielded units) shows a fixed amount of 35 and 55 respectively instead of the actual block chance. For example, Malekith shows 55% instead of the 60 he has. Localized text looks ok.
It also has very brief persistence in battle and quickly reverts to the armour tooltip.

**Expected behavior**
Should show adaptive block chance and consistently persist on hover.

**To Reproduce**
Hover on any shielded unit's block chance.

**Comment by Harmandodelavega** [comment]
should be fixed in 3.0
