### ISSUE TITLE
Wood Elf gryphon wood and haunted forest unique buildings both give vampiric attrition immunity 

### ISSUE THREAD

**Issue by atthias** [chadvandy/cbfm_wh3#260]
**Describe the bug**
both gryphon wood as well as the haunted forest unique buildings do give immunity to vampire attrition   
**Expected behavior**
one of them should have a different effect

**To Reproduce**
1. Play as sisters of twillight as I did (not sure if this applies to other WE)
2. own the regions mentioned above 
3. look at the building browser and hover over the unique building with you mouse
4. see that both buildigns offer the same effect for vampiric corruption 

**Screenshots**
[https://steamcommunity.com/sharedfiles/filedetails/?id=2861139694](url)
[https://steamcommunity.com/sharedfiles/filedetails/?id=2861140269](url)

**Comment by Harmandodelavega** [comment]
Can't do much about it
