### ISSUE TITLE
Daemon Prince's Nurgle's Gifts VIII lord recruit rank bonus not working unless replacing

### ISSUE THREAD

**Issue by AManInBlack** [chadvandy/cbfm_wh3#262]
At the top of the "Daniel" Daemons of Chaos campaign's devotion tree, one of the major boosts for Nurgle is currently bugged.

The bonus "Lord recruit rank: +20 for Heralds of Nurgle (all armies)" does not seem to be working.

![20220910084836_1](https://user-images.githubusercontent.com/9606491/189488674-44606215-95c2-463a-ac0e-3aa09fca665e.jpg)
Here, you can see I've activated the bonus, maxing out the devotion tree.

![20220910085000_1](https://user-images.githubusercontent.com/9606491/189488886-5d069330-9883-49a5-a7c9-437ccc97c743.jpg)
Here, you can see that the bonus isn't working. The expected behavior would be that new Heralds of Nurgle would be recruited at rank 22, not 2. (I have another +1 from a miscellaneous unique building. This bug was present before I built that building however.)

I'm given to understand, [based on a bug post in the official CA forums](https://forums.totalwar.com/discussion/321972/demon-princes-nurgles-gifts-viii-lord-recruit-rank-not-working-erroneously-set-as-army-bonus), that this issue is limited to Nurgle only. I haven't tested the other gods myself, however.

**Comment by AManInBlack** [comment]
I've attached the savefile, in case that is helpful.

[Legion of Chaos_Quick Save.953195233448.save.zip](https://github.com/chadvandy/cbfm_wh3/files/9540672/Legion.of.Chaos_Quick.Save.953195233448.save.zip)

**Comment by AManInBlack** [comment]
Oddly, it does function when replacing a lord in an existing army. (This also serves as a workaround until the bug is fixed.)

![20220910115942_1](https://user-images.githubusercontent.com/9606491/189496010-3e2a7756-5435-43b7-b39f-3744409c5b51.jpg)
![20220910120407_1](https://user-images.githubusercontent.com/9606491/189496099-6bf5cf83-a2f6-4784-88a3-88a922bcfd12.jpg)

**Comment by floskan** [comment]
There's also https://steamcommunity.com/sharedfiles/filedetails/?id=2855389124

**Comment by Mandras2** [comment]
The current fix "zzz_cbfm_lord_recruit_rank" is granting +20 recruit rank to any lords (its using the wrong scope: faction to province vs faction to force when it was originally meant to fix replacement lord recruit rank which seems to be fixed by CA). Also Nurgle's Gift VIII recruit rank is no longer +20, its +10.

The end result is you can recruit all non-Nurgle Herald lords out of provinces at level +20 and all Nurgle Heralds at +30.
