### ISSUE TITLE
Sorcerer's devotion to Slaanesh mechanic broken.

### ISSUE THREAD

**Issue by Ru5tyShackleford** [chadvandy/cbfm_wh3#264]
**Describe the bug**
With the correct character level and amount of soul currency, choosing to devote a character (in my case, Sigvald's starting Shadows Sorcerer) to Slaanesh(Shadows) removes souls, but doesn't affect the character at all. All devotion options remain in the menu.

This is only an issue with the Community Patch enabled. I disabled it mid-campaign, devoted again, and it worked as intended.

**Expected behavior**
Devoting to Slaanesh changing the hero to it's Slaanesh Sorcerer variant.

**To Reproduce**
1. Play as Chaos Warriors
2. Level a sorcerer to required level and collect the required amount of souls
3. Choose to devote character to Slaanesh
4. Souls are removed, nothing happens.

**Additional context**
I do not know if this affects other heroes, lords, or devotion options.

**Comment by mfvreeland** [comment]
I could not reproduce this bug, with or without CBFM loaded. Do you have a save by chance?

**Comment by Ru5tyShackleford** [comment]
Okay, weird. Now that I had the time, I did an uninstall and reinstall of the framework, tested it twice, and now it seems to be working! I hate the Steam Workshop sometimes. Sorry!
