### ISSUE TITLE
Be'lakor not using the WoC blue skill line

### ISSUE THREAD

**Issue by sumsarz** [chadvandy/cbfm_wh3#267]
**Describe the bug**
Be'lakor has the generic blue skill line that features Draftmaster and the capstone which also gives +1 rank to recruitment, which does nothing for warband recruiting.

**Expected behavior**
Be'lakor should have the same blue skill line as Archaon, which feature skills that actually makes sense for WoC factions.

**Additional info**
The blue line doesn't match up for IE, but it's "correct" within the context of RoC. I deem IE considerations to trump RoC considerations.

**Comment by Harmandodelavega** [comment]
Might be a problem with the Realm of Chaos campaign, since he's availalble to other factions there

**Comment by sumsarz** [comment]
That's probably why. From my perspective it's more important he's got proper skills for IE than RoC (in which he seems hard to unlock in any case, and most won't play with anyway.)

**Comment by Bogdanov89** [comment]
Yea be'lakor is pretty much an IE only lord so he should be made to work for IE.
Getting him in ROC campaign is a gimmick.

**Comment by Harmandodelavega** [comment]
Mixu:
"there are faction/subculture and whatever else checks in skill node tables that would easily prevent weird behaviour"
