### ISSUE TITLE
Grimgor can put Da Immortalz Banner on himself (AI only)

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#269]
**Describe the bug**
`wh_main_banner_magic_standard_da_immortulz `Immortalz banner makes git immune to death if above half morale.
Grimgor can get unbreakable.
Problem.

**Expected behavior**
Banner should not be equippable on Grimgor, only black orc units. Grimgor is not in the permitted unit set. Player can't do it. **AI bug only?**

https://www.reddit.com/r/totalwar/comments/xbn4lh/grimgor_unbreakable_immortalz_banner_invincible/

![image](https://user-images.githubusercontent.com/54819130/189540921-e8ef05db-bb32-4be4-9f23-fa3d2203a408.png)

**Comment by mfvreeland** [comment]
I guess we don't have to worry about #253 at least

**Comment by Harmandodelavega** [comment]
https://forums.totalwar.com/discussion/294831/da-immortulz-banner-bugged-does-not-prevent-artillery-and-maybe-ranged-deaths#latest

**Comment by mfvreeland** [comment]
Is this still an issue in 2.2?

**Comment by Harmandodelavega** [comment]
Yeah nah can't figure this one out
