### ISSUE TITLE
Thorek Runecrafting discount still 50% despite patch notes

### ISSUE THREAD

**Issue by voszo** [chadvandy/cbfm_wh3#270]
Mod Edit: Turns out they forgot to reduce it to 25% AND his legendary item set bonus gives him another 25% discount

1. Patchnotes 2.1.0 said the Runecrafting cost is reduced to 25% but it is still 50%
2. After some time in the game the costs are also bugged further, it even gets to 75% and maybe further down (maybe on confederation?). I think the scope in the "effect_bundles_to_effects_junctions_tables" is wrong. Setting the effect key "wh2_dlc17_pooled_resource_oathgold_runecrafting_mod" to the scope "faction_to_faction_leader_unseen" instead of "faction_to_faction_own_unseen" fixed the problem for me

**Additional context**
See patchnotes section Dwarfs: https://www.totalwar.com/blog/tww3-update-210/

**Comment by mfvreeland** [comment]
Confirmed still a bug in 2.2?

**Comment by Harmandodelavega** [comment]
@mfvreeland If you see me messing around with a card post 18 october I checked it and it should have at least an unvalidated tag
