### ISSUE TITLE
Warden and the Paunch High Elf units not in the tech tree

### ISSUE THREAD

**Issue by Notians** [chadvandy/cbfm_wh3#271]
**Bug**
Rangers, Silverin Guard, Lions, and Lion Chariots from the warden and the paunch DLC do not appear in the high elf tech tree nor do they receive any tech tree buffs

**Expected Result**
These units should be appearing in the tech tree and receiving their respective tech bonuses

**To Reproduce**
1. Play as High Elves
2. Look at tech tree and check bonuses. See that said units do not appear

**To check if it may just be a visual oversight**
3. choose applicable tech, (ie. speed bonus from tier 1 on the tech tree should apply to rangers)
4. See that once completed, the tech does not benefit rangers or other units from the same dlc

**Screenshots**
Completed Tech(should be applying to rangers)
![image](https://user-images.githubusercontent.com/113328583/189580654-8a3f0145-0f8a-4f7a-ae84-2d56d312f1f5.png)

Unreceived Bonus
![image](https://user-images.githubusercontent.com/113328583/189580694-14fddded-7e49-43b8-88c1-dd968c9a0875.png)

**Extra**
Someone already made CA aware
https://forums.totalwar.com/discussion/322211/ie-high-elf-tech-tree-is-missing-units-from-warden-and-the-paunch-dlc

**Comment by Bogdanov89** [comment]
For easier viewing:

![image](https://user-images.githubusercontent.com/55892027/189635650-a7c6c990-a819-47fe-b037-dd994d09d6fe.png)

**Comment by mfvreeland** [comment]
The HE tech tree currently ported over to WH3 is hardly the only thing based on a version before Warden and the Paunch, sadly. There are many bugs like this. Every report helps!

**Comment by floskan** [comment]
I'm on this one

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2
