### ISSUE TITLE
'Oath-Brothers of Tor' don't have 'By our Blood'

### ISSUE THREAD

**Issue by valky666** [chadvandy/cbfm_wh3#272]
I am puzzled, why the RoR-unit doesn't have the usual last-stand ability, like any other Kislevite unit. (but their 2 monsters)
Thy should have it as well.

**Comment by mfvreeland** [comment]
It's because Tretch Craventail stole it from them.

JK (sorta). It looks they just forgot to add a value to a table. I'll add this to my last batch of fixes.

**Comment by valky666** [comment]
> It's because Tretch Craventail stole it from them.

Now that would explain a lot :Þ
Have a good one - nice to see that mod up and running again!

**Comment by mfvreeland** [comment]
Evidently fixed in 3.0.
