### ISSUE TITLE
Pigbarter can only build minor-defenses

### ISSUE THREAD

**Issue by valky666** [chadvandy/cbfm_wh3#273]
When playing as Ghorst, I noticed in Pigbarter I can only set-up the basic chain for defense, which is usually for minor settlements.
Settlement is basic like any other non-special, so it doesn't provide a better garrison by its provincal capital chain.

![image](https://steamuserimages-a.akamaihd.net/ugc/1781758824909951752/0133334D5AEDC826BFB45CE582AEBC62E7313A03/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

**Comment by pigwithsnoot** [comment]
I believe this may have been fixed by CA as of patch 2.2. 

CAMPAIGN
The Pigbarter settlement chain is now appropriately that of a major settlement.

**Comment by Harmandodelavega** [comment]
Gonna assume it was fixed in 2.2
