### ISSUE TITLE
AI will still try to retreat when ambushed if in force march/already lost a battle

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#275]
**Describe the bug**
If you ambush an army in force march (or otherwise unable to retreat), you can just sit in a corner and wait for enemies to peacefully walk off the map (escape zone). 
They will all die because they "lost" a battle while unable to retreat, despite no actual fighting occurring.
**This even allows very weak armies to kill powerful armies (that cant retreat) by simply hiding far away and waiting until the enemy walks off the edge of the map (escape zone).**
https://www.reddit.com/r/totalwar/comments/xbzo2d/psa_if_you_manage_to_ambush_an_army_in_force/

**Expected behavior**
Ambushed armies that can not retreat should not be heading for the "escape zone" because that will be certain death for their entire army.
If possible AI should be made to seek out the player and fight until the ambush battle is won or lost... or at least not go for the guaranteed death "escape zone".

**To Reproduce**
1. Play as any faction with ambush stance (both basic and attack-move skaven/beastmen ambush stance should work)
2. Ambush an army that can not retreat (due to force march stance or already having retreated once)
3. Simply hide in any corners, anywhere far that will not alert the AI army (they continue their peaceful walk to "escape zone")
4. Entire AI army dies because they "lost" a battle from which they could not retreat by peacefully walking to the "escape zone".

**Screenshots**
Thread with more info https://www.reddit.com/r/totalwar/comments/xbzo2d/psa_if_you_manage_to_ambush_an_army_in_force/

**Additional context**
If an ideal bug fix via mods is not possible then just making the AI ignore escape zones (especially when unable to retreat) would be good enough until CA fixes this... or disabling the peaceful walk AI does when its ambushed, if no other solution exists.

**Comment by mfvreeland** [comment]
I don't think battle AI is moddable, so unfortuantely, this probably isn't fixable.

**Comment by mfvreeland** [comment]
Fixed in 5.3
