### ISSUE TITLE
Beastmen Lord skills don't buff Manticore

### ISSUE THREAD

**Issue by Rastafarian-Targaryen** [chadvandy/cbfm_wh3#277]
None of the red line skills of all Beastmen lords I checked buff Manticores. An old oversight from what I understand. 

I'd imagine they would be grouped together with the Chaos Spawns and single entities, but it's also plausible that they'd be grouped with harpies and other beasts. I screenshotted both groups.

![manticore](https://user-images.githubusercontent.com/113367585/189688851-ce5300a1-e0c7-498a-8fef-bfe509816774.png)

**Comment by Bogdanov89** [comment]
this could be because its all from an old version of TWW2 before BM got manticores as regular recruitable units.
they were summon-only for a long time for beastmen so nothing buffed them, but thats ancient tww2 history.

**Comment by Rastafarian-Targaryen** [comment]
I remember poking around and seeing people asking for it to be added to their roster proper lol, that would be a reasonable backstory for this issue. Not sure if fixing an oversight like this is perfectly within the mod's scope, but figured I'd post

**Comment by Harmandodelavega** [comment]
Fix originally by Sm0kin
