### ISSUE TITLE
Copher Port gets covered by another landmark port for Kairos and Skarbrand

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#279]
**Describe the bug**
Copher landmark is in place for Kairos and Skarbrand, maybe others, but another port is also overlapping, respectively Lothern and Erengrad.
Copher port for them has borked localization and cannot be upgraded.

**Screenshots**
![20220912200555_1](https://user-images.githubusercontent.com/54819130/189725092-1ae973eb-6d14-4c68-a583-3b7a0aca4f01.jpg)
![20220912200538_1](https://user-images.githubusercontent.com/54819130/189725105-c606ab6f-6054-4cbd-b725-71a70106cbfe.jpg)
![20220912200124_1](https://user-images.githubusercontent.com/54819130/189725573-43b55381-706c-4f0a-bd14-80ff012ffcd1.jpg)
![l7xdx2nq9fn91](https://user-images.githubusercontent.com/54819130/189725589-19c9cfef-f618-4674-95ed-c8204f5cfa4b.jpg)

**Comment by Harmandodelavega** [comment]
They fixed it for all except the daemon prince, I haven't played him much is he supposed to have special ports or something?

**Comment by Harmandodelavega** [comment]
In the 2.2 patch notes, it explicitly states he should have basic ports in special locations, removing
