### ISSUE TITLE
Blessed Stegadon lacks missile resist

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#283]
normal stego has it 

fixed by Harmando

**Comment by mfvreeland** [comment]
Fixed in #254, addressing #120

**Comment by Harmandodelavega** [comment]
> Fixed in #254, addressing #120

just for the record, this is a wh2 bug

**Comment by mfvreeland** [comment]
Ah ok. Yeah, I never knew about that one before. In that case, #120 is essentially just blessed horned ones not getting primal instincts (which used to be a good thing) after primal instincts was buffed.

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

Blessed Stegadon receive their missing 15% missile resistance.

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
