### ISSUE TITLE
Disabled campaign movement trait spawn (Strategist/Tzeentch equivalent) on heroes since they don't work and can't be fixed

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#289]
Strategist
Tzeentch has an equivalent trait too

disable it?

**Comment by mfvreeland** [comment]
I agree with disabling it. Anyone not agree?

**Comment by Harmandodelavega** [comment]
they added fatigue reduction to the tzeentch one so we should remove it

**Comment by floskan** [comment]
Hag witches also has strategist now

**Comment by Harmandodelavega** [comment]
Yeah but it works for heroes now, doesn't show on the movement bar though
