### ISSUE TITLE
Tzar Guard with 2handed swords not holding their swords properly

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#304]
pack here https://trello.com/c/JJIaKuOB/560-tzar-guard-with-2handed-swords-not-holding-their-swords-properly 

may have been fixed in the new patch don't really know

by Mixu

**Comment by Layotees** [comment]
![image](https://user-images.githubusercontent.com/113050609/194608624-3c7f141d-66d3-4552-8115-2fa8a728fc4c.png)
Looks fixed to me.
