### ISSUE TITLE
Pink horrors also affected by melee infantry bonuses/Couple units incorrectly affected by Beastmen anti-order effects

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#31]
HV edit: didn't include blue horrors considering they're hybrids, even though it's probably still a bug

4.2 fucked wh3_main_tze_inf_pink_horrors_0	too, need to exclude them also from "chs_daemon_infantry_rank7"
"chs_daemon_infantry"

**Comment by mfvreeland** [comment]
This file is causing a crash in 5.1.3. I am removing for now; we can re-add a modified version later if this bug still exists.
