### ISSUE TITLE
Characters on eagles/possibly other mounts can get stuck while casting missile spells/abilities

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#314]
ChaosRobie fix

""projectile spells will often cast (no animation) and instantly refund all cooldown/WoM to the user anyways. So far as I can tell there is no way around this, "

- a SOLUTION was provided to me on the modding den by Chaos Robbie, try setting up: db/land_units_to_battle_personalities_junctions_tables and db/battle_personalities_tables

Under land_units~, your created unit/character key goes in LAND UNIT column. IN battle_personalities table, your units key goes in the KEY column, That works if you're copying your animations from a vanilla entry that can cast projectiles!"

https://steamcommunity.com/sharedfiles/filedetails/?id=2914235097

[Bound_fireball_mount_fix.patch](https://github.com/chadvandy/cbfm_wh3/files/11777646/Bound_fireball_mount_fix.patch) rename to pack

https://discord.com/channels/373745291289034763/581350140942483456/1069404669123764344

https://github.com/chadvandy/cbfm_wh3/commit/5f32295d085841ace9c13c4aecb43b3eafc5f6a7 (old fix)

**Comment by Harmandodelavega** [comment]
I don't think this fix works, saw another character on an eagle getting locked up, went and checked and he had autonomous rider ticked

**Comment by Littlebob86** [comment]
Hey! So this is my fix. It's not about getting stuck. I think it's a Los issue. Have a look at the way the rider is facing when the eagle is idle. He's facing the sky.

So ticking the fireball casts from mount fixes the issue

**Comment by Harmandodelavega** [comment]
just remove it until we can test a proper fix, 99% sure it doesn't work

**Comment by Harmandodelavega** [comment]
old filename was alarielle something something

**Comment by Littlebob86** [comment]
Hey! 

I think this was fixed in this thread. Supposedly it's an animation issue. Again, I did a dirty fix by ticking can fire from mount under the projectile

https://discord.com/channels/373745291289034763/1123321068661256293

**Comment by Harmandodelavega** [comment]
probably fixed by ca
