### ISSUE TITLE
Skaven techs added in Moulder DLC missing, also Mutant Rat Ogre missing from a few buffs

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#315]
tech_skv_4_5
tech_skv_4_6

not present in tech nodes and tech nodes links

**Comment by floskan** [comment]
Here's the missing tech + mutant rat ogre buffs on monstrous abominations

![20220926182753_1](https://user-images.githubusercontent.com/34427023/192341829-0596efc9-6c9f-4168-b1db-dfc2f99e543f.jpg)
![20220926182755_1](https://user-images.githubusercontent.com/34427023/192341836-6cb9c50c-6a22-4db4-b332-888499e726aa.jpg)
![20220926182757_1](https://user-images.githubusercontent.com/34427023/192341845-d56465d4-fe64-4356-b098-d22903c2381d.jpg)
