### ISSUE TITLE
Missing dlc units from Clan Eshin Moulder contract rewards (recruit cost)

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#317]

**Comment by Sanatyr** [comment]
"cbf_missing_rat_ogres_mutant"

there is a unit set with rat ogre mutant/ lab version "wh2_dlc16_skv_rat_ogres_mutant_rat_ogres"

**Comment by floskan** [comment]
Seems this would just cause a crash
