### ISSUE TITLE
Knights of Immolation are not available for DAE(mons of Chaos) in Custom battles 

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#32]
wh3_twa07_tze_cav_doom_knights_ror_0

**Comment by chadvandy** [comment]
full removal isn't possible without some pain - so it's just added to Daniel for now

**Comment by Harmandodelavega** [comment]
Knights of Immolation are available for WoC when they should be DAE in Custom battles

this was the original title, changed it so when people look at resolved fixes they just see what was changed

**Comment by chadvandy** [comment]
@Cataph this isn't a bug?

**Comment by Harmandodelavega** [comment]
There doesn't seem to be much consistency in what the Daemon Prince gets or not, but if anything it seems like he doesn't get mortals, so I would remove this
