### ISSUE TITLE
Orion is penalized for standing in shallow water as if he is a small unit

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#324]

**Comment by Harmandodelavega** [comment]
never tested

**Comment by floskan** [comment]
Orion has slightly more health as of current patch

**Comment by mfvreeland** [comment]
> Orion has slightly more health as of current patch
Are you sure? It doesn't seem like the HP value has changed.

**Comment by mfvreeland** [comment]
Fixed by CA God knows how long ago
