### ISSUE TITLE
Nakai secondary lord building Sentinel Hall lists bonuses twice.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#327]
**Describe the bug**
Nakai secondary lords building Sentinel Hall lists bonuses twice.
I was unable to determine does it actually give bonuses twice - or merely lists them.

**Expected behavior**
Text in building description to not be duplicated.

**To Reproduce**
1. Play as Nakai
2. Recruit secondary lord (slaan life mage in my case)
3. Look at Advanced Military recruitment building Sentinel Hall (blue color)
4. Notice that Unit Experience gain per turn bonus +50 is written twice (unknown does it actually award bonus exp twice).

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/190571002-bfec5583-a843-4c9f-9140-3ab92f51df9a.png)

**Additional context**
Its the same building that has a bugged population surplus cost (costs nothing instead of 3 pop) so it seems to be some issues with it.

**Comment by Harmandodelavega** [comment]
deleted
