### ISSUE TITLE
Nakai technology Sequence of Traversal seems to do nothing.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#328]
**Describe the bug**
Nakai tech Sequence of Traversal supposed to give 15% campaign move range and 15% campaign line of sight.
However upon research my armies do not seem to have gained any additional campaign movement range.
Before tech research was done my lords had 130 movement range, and next turn after the research they still had 130 movement range.
As far as i was able to tell the movement range circle on the map did not change after research was done.

**Expected behavior**
Tech giving proper 15% bonus movement range on campaign for all armies and heroes.

**To Reproduce**
1. Play as Nakai
2. Research Sequence of Traversal
3. Notice it does not seem to affect the movement range of lords and heroes

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/190571749-a6747d15-d247-4efd-8b30-bb417da34891.png)

![image](https://user-images.githubusercontent.com/55892027/190571803-a697a209-722f-4361-bfaa-504b344c4a0c.png)

**Additional context**
Technology description text is rather unclear. Seems to me like it should affect every lord and hero for nakai faction.

**Comment by chadvandy** [comment]
This may be a cap on movement range instead of a malfunctioning effect - it applies for all other armies of the faction fine, but it's easy to get Nakai up to 130/130 and I don't know if you can make it jump any higher.

**Comment by Bogdanov89** [comment]
In my current Nakai campaign for several lords i can see 150/150 for army movement from other various bonuses (not in March stance).
So as far as i can tell the bonuses for the movement properly display up to 150/150 , which i think is the cap (50% extra).

However the Sequence of Traversal did not increase the movement number from the 130/130 in the screenshot for any army/hero.
And from what i could visually tell it also did not increase the circle indicating possible army movement on the campaign map.

**Comment by chadvandy** [comment]
It definitely affected another lord I had on the map when I researched it, but not Nakai, but thanks for the info about the 150s. I'll look into what's going on.

**Comment by Harmandodelavega** [comment]
Probably because the movement buff does not kick in the turn it was researched
