### ISSUE TITLE
Nakai secondary lord building Portal of Tlanxla missing recruit time for some units

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#329]
Ancient Salamander, Ripperdactyl, Horned Ones and Blessed Spear riders should take the same time in local for a normal Lizardmen faction and in global for a secondary Nakai horde army once the relevant unit is mentioned in this building

(Secondary hordes don't have local recruitment and this is the norm for all units in portal effects)

by Jianni and Sm0kin

**Describe the bug**
Nakai secondary lords have buildings that greatly reduce the global recruitment duration for high tier units.
Even units that take a long time to recruit like Feral Carnosaurus, Ancient Stegadon and Feral Troglodon are reduced to 1 turn global recruitment.
However some high tier units and even medium tier units from the Portal of Tlanxla building chain (ancient salamander, cold one spears and horned one cavalry, coatls and ripperdactyls) have an unusually low bonus for its recruitment duration reduction, resulting in their recruitment taking 3 turns even when fully upgraded.
Overall feels unintended that these medium and high tier units take so long to recruit compared to max tier units from other buildings.
Perhaps CA intended that the reduction is at 2 or 3 to keep it in line with other bonuses that the other two buildings have but have overlooked it.

**Expected behavior**
Portal of Tlanxla building chain global recruitment duration changed to a better value to match other building bonuses.

**To Reproduce**
1. Play as Nakai
2. Recruit secondary lord
3. Compare the bonuses that the "basic military recruitment" buildings give

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/190580366-1a0a5d49-279e-42f5-b161-9ef02e881fdb.png)

**Additional context**
Nakai buildings (especially for secondary lords) seem to be something that CA regularly overlooks, both in TWW2 as well as in TWW3.

**Comment by Harmandodelavega** [comment]
https://trello.com/c/yuZIEjYN/313-nakai-portal-buildings-missing-recruit-time

**Comment by Bogdanov89** [comment]
Just to mention that my bug report is about Portal of Tlanxla bonuses being strangely weak compared to other buildings - not about the bonuses missing.
As far as i can tell the bonuses are there and working - they are just extremely weak compared to other similar buildings, so perhaps an oversight.

**Comment by floskan** [comment]
> Just to mention that my bug report is about Portal of Tlanxla bonuses being strangely weak compared to other buildings - not about the bonuses missing (like the changed title suggests). As far as i can tell the bonuses are there and working - they are just extremely weak compared to other similar buildings, so perhaps an oversight.

The Trello link mentions the weak bonuses as well

**Comment by mfvreeland** [comment]
This fix is causing a crash in 5.1.3, and it looks like CA may have fixed it: "Aligned the global recruitment durations for secondary Lords under Nakai (when their buildings are maxed out) with the local recruitment durations for Nakai himself"

I am removing this for now to fix the crash. If a bug still exists, we can apply a different fix later.
