### ISSUE TITLE
'The Bloodbrute Behemoth' (Ghorgon) - missing/wrong stats

### ISSUE THREAD

**Issue by valky666** [chadvandy/cbfm_wh3#331]
Noticed in my BM campaign - he has some weird stats, compared to a regular rank 9 ghorgon.
He is marked as Khorne-unit, but it's missing the reduced defense + spell resistance. Further the MA value is slightly too high.

Behemoth:
MA: 71 -> 69 (similar to a rank 9 unit)
MD: 43 -> 38 (Mark of Khorne)
Spell-resistance: +15% (Mark of *drumroll* Khorne)

**Comment by Harmandodelavega** [comment]
We can't change stats on units unless it's completely unambigous
