### ISSUE TITLE
"unlock_ai_starting_generals" function trying to unlock legendary lords that are already on the map

### ISSUE THREAD

**Issue by sm0kin** [chadvandy/cbfm_wh3#338]
**Describe the bug**
wh_legendary_lords.lua is a remnant from wh2 times, when legendary lords like Grombrindal, Ghorst, etc didn't have their own faction and had to be unlocked to be recruitable. Due to these lords existing at campaign start now the script throws errors when trying to unlock them. E.g.:

Here the script tried to unlock Karl Franz when I played a Reikland campaign.

********************
SCRIPT ERROR, timestamp <345.1s>
Tried to unlock legendary lord with forename [names_name_2147343849], but that legendary lord already has a military force (i.e. is on the map) - how can this happen?

stack traceback:
	[string "script\campaign\main_warhammer\wh_first_turn.lua"]:3105: in function 'char_with_forename_has_no_military_force'
	[string "script\campaign\main_warhammer\wh_first_turn.lua"]:3057: in function 'unlock'
	[string "script\campaign\main_warhammer\wh_first_turn.lua"]:3046: in function 'callback'
	[string "script\_lib\lib_core.lua"]:1930: in function <[string "script\_lib\lib_core.lua"]:1930>
	[C]: in function 'xpcall'
	[string "script\_lib\lib_core.lua"]:1930: in function 'event_protected_callback'
	[string "script\_lib\lib_core.lua"]:1991: in function 'event_callback'
	[string "script\_lib\lib_core.lua"]:2051: in function <[string "script\_lib\lib_core.lua"]:2051>
********************

**Expected behavior**
I don't think the script needs to exist in the current iteration of the IE campaign.

**To Reproduce**
1. Play as the empire
2. force_confederate any empire faction
3. script error

**Additional context**
Might be connected to this issue:
https://github.com/chadvandy/cbfm_wh3/issues/25

**Comment by chadvandy** [comment]
good catch. Looks like it may be related to #25 because it does reference the proper Isabell startpos ID, I'll test it
