### ISSUE TITLE
Clan moulder missing unique exotic animals and furs building

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#344]
Clan moulder has unique buildings that weren't properly added to the tables similarly to issue #192, will submit a pr that will add them back. Example pic here:
![20220918190940_1](https://user-images.githubusercontent.com/34427023/190919804-7cf89b03-65f3-4df7-8f95-c5f95cb895ac.jpg)

It has the additional effect of giving growth juice per turn

**Comment by Harmandodelavega** [comment]
easier way to do this, just add a context expression requirement IsFactionClanMoulder for growth juice on the normal building in effect junction

**Comment by Harmandodelavega** [comment]
This is fine, but it's better for people who enable this mid way and some descriptions are placeholder on the Moulder one I think
