### ISSUE TITLE
Heartrender & the Darksword should spread Slaanesh instead of Undivided Corruption

### ISSUE THREAD

**Issue by Gingerglaahk** [chadvandy/cbfm_wh3#346]
It doesn't make sense for Morathi's weapon to spread undivided corruption now that she spreads Slaanesh corruption

![image](https://user-images.githubusercontent.com/29358271/190926947-04b2c7c6-82b5-4bcd-b81a-aad6568fcb33.png)

**Comment by chadvandy** [comment]
removed
