### ISSUE TITLE
Many Skaven minor factions could never recruit Eshin sorcerers

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#353]
wh2_dlc12_skv_clan_fester
wh2_dlc12_skv_clan_mange
wh2_dlc15_skv_clan_ferrik
wh2_dlc15_skv_clan_kreepus
wh2_dlc15_skv_clan_volkn
wh2_dlc16_skv_clan_gritus
wh3_main_skv_clan_carrion
wh3_main_skv_clan_skrat
wh3_main_skv_clan_verms

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed a number of Skaven factions being unable to recruit Eshin Sorcerer Heroes."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
