### ISSUE TITLE
Unique Thorek follower "Kraggi" cannot be re-equipped

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#354]
https://trello.com/c/yn4xOoJI/314-kraggi-assistant-at-the-forge-unique-thorek-ancillary-cannot-be-reequipped-once-it-is-unequipped

missing entry in ancillaries_included_agent_subtypes_tables
In the WH2 fix Sm0kin also unchecked unique to faction/can be destroyed, but I'm not sure if it matters

**Comment by mfvreeland** [comment]
Fixed by CA, removed.
