### ISSUE TITLE
Fortress of Dawn have a Chaos settlement skin instead of High Elven One

### ISSUE THREAD

**Issue by kraker001** [chadvandy/cbfm_wh3#36]

**Comment by chadvandy** [comment]
taken turn 1 - are you using the dynamic settlement skins mod or something?
![image](https://user-images.githubusercontent.com/39225561/187770841-c2be6f93-d618-4425-8afd-ad062c40625f.png)

**Comment by kraker001** [comment]
I saw the bug in reddit looks like op have some mod related problems

**Comment by chadvandy** [comment]
kk thanks!
