### ISSUE TITLE
Add Immortal Empires campaign check to Belakor campaign line fix

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#364]
https://github.com/chadvandy/cbfm_wh3/issues/267 ref

**Comment by mfvreeland** [comment]
Is this still broken?

**Comment by Harmandodelavega** [comment]
Yeah, our fix still overwrites the old campaign line in ROC

**Comment by Harmandodelavega** [comment]
No longer needed, Belakor's got another little problem but not this one
