### ISSUE TITLE
Daemons of Chaos not benefitting from Renowned and Feared Recruit Rank buff on Nurgle Lords & clarification that R&F effect is factionwide for Nurgle factions

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#365]
wh2_main_skill_ll_self_defense_nur only affects merc xp

I hid the new DAE effect and ended up creating a scope (factionwide for Nurgle factions) for the og skill since I didn't wanna give the  DAE one factionwide too and didn't want to confuse people with two different effects

I didn't make a new skill with a faction check in char_skill_nodes since A: I'm not good at it B: it would overwrite the skill for people who ranked it up

**Comment by chadvandy** [comment]
name of skill or screenshot would be helpful so we don't have to load up the game to find context

**Comment by mfvreeland** [comment]
Still bugged in 2.2?

**Comment by mfvreeland** [comment]
Appears fixed in 6.0
