### ISSUE TITLE
Waaagh tech not giving passive gain

### ISSUE THREAD

**Issue by msolefonte** [chadvandy/cbfm_wh3#368]
Greenskins have some techs (first and last) to increase Reputation per turn. These are dummies and do not work because they are not bound to any pooled resource.

**Comment by msolefonte** [comment]
Just created the issue to keep track of the problem. PR already submited: #367

**Comment by mfvreeland** [comment]
As discussed on Discord, only the initial tech isn't working, and it was never supposed to. The tech it's tied to is supposed to be unlocked by default, though, which is what is causing the confusion. We can't fix this without messing with startpos, which ain't worth it, but I'm keeping the issue up for visibility.
