### ISSUE TITLE
Rigid Models don't get blood on them

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#370]
Parts that use rigid models rather than wsmodels in battle don't take blood. As in, they can't get bloodied, like Sigvald who has a specific setting in his wsmodel to not get dirty. This is part 1 of the issue and we can't fix it.

Part 2 being that there are whole units that only use rigid models, like Free Company Militias, so they can be pretty noticeable in battle as the only clean guys in a ketchupped army. _This_ part we _could_ fix by generating wsmodels for all of them, but it's just too much stuff. Just reporting this further for visibility.

Repro:
Just send free company (NOT the sartosan kind) in melee and notice how they don't get ketchup on them.

**Comment by mfvreeland** [comment]
Several things now ketchup-eligible according to 4.1 notes, not sure if relevant to this specific issue or not:

"- Blood will now appear on Kroxigor weapons for regular, ancient and blessed variants.
- Blessed Carnosaurs will now get splattered with blood.
- Skink blowpipes and club weapons will also get splattered with blood. 
- Black Guards of Naggarond, you guessed it, will now be splattered with blood."

**Comment by Harmandodelavega** [comment]
@Cataph

**Comment by Cataph** [comment]
quick glance they didn't fix the rigid issue but just swapped those units and items to wsmodel
until you actually verify a unit with a rigidmodel getting blooded, this is still a nonfix.
