### ISSUE TITLE
Can not use Cold-Blooded on Rampaging units via unit bar.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#375]
**Describe the bug**
*EDIT* also happens with other LM faction, not specific to Nakai faction.
Nakai has ability Primal Roar (starts with it) that can cause friendly units nearby to go Rampage once they are damaged.
This Rampage can not be removed by the Cold-Blooded ability that every LMen lord and hero have.
When i attempt to cast Cold-Blooded on a unit Rampaging from Nakai's Primal Roar it will fail to cast and deselect the lord/hero (does not waste cooldown).
Not sure does this issue exists with the regular Rampage that some LM units still have.

**Expected behavior**
Able to cast Cold Blooded on Rampage-ing units that was caused by Nakai Primal Roar

**To Reproduce**
1. Play as Nakai
2. During battle use Primal Roar and wait till one of your units gets damaged to Rampage!
3. Try to use Cold-Blooded (from a lord or hero, i tried from skink caster hero and skink chieftain hero).
4. See that your current selection gets deselected and the Cold Blooded ability is not cast at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/191607315-077ecb5e-5aa7-4cf2-9ad7-010eb8bedf9d.png)

**Additional context**
I do not know does Cold Blooded also fail to cast on units affected by normal Rampage (not the Primal Roar version).

**Comment by Bogdanov89** [comment]
Actually i am encountering this issue also when playing Mazdamundi faction.
With Slann (Life) lord i could not cast Cold-Blooded on a Rampaging Feral Carnosaur through the unit bar located at the bottom-center of player screen during manual battles.
However when i tried casting it on the actual model of the Feral Carnosaur it seems to have worked.
**So the issue seems related to being unable to cast Cold Blooded via the unit bar located at the bottom-center of player screen during manual battles.**

**Comment by mfvreeland** [comment]
To clarify, the bug here only has to do with selecting the unit on which to cast via the unit bar rather than the model on the field. Is that correct? That's quite an odd one, if so.

**Comment by Bogdanov89** [comment]
Yes that is the summary, i would click on Cold Blooded ability and mouse over a rampaging unit in the bottom-center unit bar and when i try to click the Ability would simply not cast and my selection (lord/hero with Cold Blooded) would get deselected.

**Comment by mfvreeland** [comment]
Doesn't seem fixable, fairly easy to work around.
