### ISSUE TITLE
Ghoritch has missile damage only for self in his unique skill tree

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#377]
![20220921233122_1](https://user-images.githubusercontent.com/34427023/191615157-659f02cc-746f-4ded-b218-0d26589f67a0.jpg)

This was 10% health in warhammer 2(wh_main_effect_character_stat_mod_unit_health) , should probaby be that here too.

**Comment by mfvreeland** [comment]
Fixed by CA, removed.
