### ISSUE TITLE
Nakai Old Ones' Favour counter not working in Temples panel.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#378]
**Describe the bug**
Nakai faction gathers Old Ones' Favour from vassal cities and battles.
Its shown properly on the counter in the top middle of the screen.
However there is also a counter in the Temples of the Old Ones' panel (button in top middle of the screen) that is always showing 0.
Usually panels like that have a counter that shows you how much of a currency you have so you can decide how to spend it.
ATM the Favour amount is not at all visible (anywhere on the screen) when you open the Temples panel due to this bug.

**Expected behavior**
Counter for Favour working in Temples panel (top left corner).

**To Reproduce**
1. Play as Nakai
2. Get any amount of Favour
3. Open panel for Temples of the Old Ones
4. Notice the counter in the top left of the panel always shows 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/191616997-f78cd461-8a1b-4123-942a-ecd793986ae7.png)

**Comment by Harmandodelavega** [comment]
Spelling

**Comment by chadvandy** [comment]
The dy_prestige component uses "SlavesAmount", for some odd reason, instead of `PooledResourceContext(&quot;lzd_old_ones_favour&quot;).Total`

![image](https://user-images.githubusercontent.com/39225561/191636362-308dc1d8-93fc-48c0-9d53-33b6ec3f00e9.png)

**Comment by Harmandodelavega** [comment]
fixed in 2.2 (saw it on a stream)

**Comment by Harmandodelavega** [comment]
Deleting
