### ISSUE TITLE
Tz'arkan, Bohemond of the Flame, Cavill should be unique names?

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#383]
Bohemond is the leader of one of the Bretonnian crusader factions, Cavill is Eltharion's starting hero, a reference to an actor and Tz'arkan is the demon possessing Malus.

They appear on random lords

Relevant tables are names__.loc and names_tables, in names_tables change frequency to 0

Bohemond might be trickier because I think it's the combination of a name and a title

**Comment by mfvreeland** [comment]
Agree

**Comment by chadvandy** [comment]
Tz'arkan is linked to the Tzeentch group, seems intentional as a gag for the demon returning home or something

Bohemond of the Flame is listed in names twice, one is 1 frequency, ironically the one that isn't listed as unique is the one used by the startpos character. Changing that and Cavill
