### ISSUE TITLE
Iridescent Horror (Metal) skill buffs assault units despite having assault unit

### ISSUE THREAD

**Issue by ILiveInATree** [chadvandy/cbfm_wh3#391]
**Describe the bug**
Tzeentch's Iridescent Horror (Metal) Hero has the "Assault Units" skill, instead of "Assault Unit," the agent action they actually have, and thus they cannot increase its level.
**Expected behavior**
Iridescent Horror (Metal) Heros should have the "Assault Unit" in their skill tree, allowing them to increase the power of their "Assault Unit" agent action, much like Iridescent Horror (Tzeentch) does.

**To Reproduce**
1. Playing as a Tzeentch race faction (Oracles of Tzeentch), build a Moment of Potential recruitment building.
2. Recruit an Iridescent Horror (Metal).
3. View the agent actions, and compare them to the skill tree.
4. Cry.

**Screenshots**
![Screenshot from 2022-09-22 22-27-50](https://user-images.githubusercontent.com/114209917/191898617-ea3e7d51-83ef-4cf2-b8e0-18a3fa311004.png)

![Screenshot from 2022-09-22 22-32-56](https://user-images.githubusercontent.com/114209917/191898630-0311cd64-7b16-4101-93d1-b62f459e229b.png)

![Screenshot from 2022-09-22 22-36-57](https://user-images.githubusercontent.com/114209917/191898645-4e0aec4d-9c57-4404-b37b-232b05864ce9.png)

**Comment by AManInBlack** [comment]
This issue was not fixed by CA in 2.2.

**Comment by Harmandodelavega** [comment]
Are you sure this was meant to be in vscode? @floskan

**Comment by floskan** [comment]
No, dunno how that happened
