### ISSUE TITLE
goblin wolf chariot fires 2 arrows per bow

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#40]
2 crewmen means the 2 shots per volley is correct for UI, but x2 projectiles is a mistake and makes for double dps.

notice that the only other chariots who have multiple projectiles are Tiranoc (magic bows) and CO chariots (repeaters), and they have half as many engines.

fix: wolf chariot gobbos fire 1 arrow instead of 2 for each bow

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2, should be removed

**Comment by chadvandy** [comment]
removed
