### ISSUE TITLE
Feral Bastiladon has both Rampage & Primal Instincts

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#403]
**Describe the bug**
Feral Bastiladon is the only LM unit that has both Primal Instincts and Rampage.
It is a tier 2 unit and rather lackluster so it kinda "needs" the new buffed Primal Instincts, but still this looks like an oversight by CA.
The Primal Instincts do not exist on any other "Feral" LM unit.
Update 2.0 patch notes added Primal Instincts to all non-feral Bastiladon units, so its likely that Feral Bastiladon got it by mistake.

**Expected behavior**
Likely that Feral Bastiladons should lose the Primal Instincts since Feral units only have the Rampage.

**To Reproduce**
1. Take a look at LM dinosaurs, Feral Bastiladon is the only Feral to have Primal Instincts.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/192081439-8f87f000-3786-4cab-816d-fbe0846c83ca.png)

**Comment by Harmandodelavega** [comment]
Don't know how to remove abilities
