### ISSUE TITLE
unclear effect scopes (TBD)

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#41]
They fixed a bunch of scopes since last time I checked.
However, one of them remains misleading (local is usually employed to say 'regionwide')

`province_to_character_enemy    \n(local characters)`

It's not a priority right now but if there are more scopes to fix I'll make a pack.

**Comment by chadvandy** [comment]
did a quick pass on them, a few are still unclear in !cbf_campaign_effect_scopes.loc

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/commit/c4d104203f03585269f840559e78861fb05ed5e8#diff-169c6bd4863f7d0572d30c153af51d468dcdd8fe3774e06d1bedcf8263f19fc0
