### ISSUE TITLE
Waaagh!!! and Da Biggest Waaagh!!! don't work at all for 𝘮𝘪𝘯𝘰𝘳 Greenskin factions.

### ISSUE THREAD

**Issue by pigwithsnoot** [chadvandy/cbfm_wh3#415]
The passive Waaagh resource gain technologies Waaagh!!! and Da Biggest Waaagh!!! do not produce their +1 and +5 per turn associated resources correctly on minor Greenskin factions.

Steps to reproduce:
1. Disable all mods except Mixu's Unlocker (required to play as minor factions).
2. Start as any minor Greenskin faction.
3. Spend one turn to research Waaagh!!!, and then end your turn.
4. Note that no matter how many turns go by it displays 0 instead of +1 Waaagh resource.
![waagh](https://user-images.githubusercontent.com/114365748/192176285-6a633e39-5224-4cc5-ac96-540d15eb3cd9.png)
![UFWSg8x](https://user-images.githubusercontent.com/114365748/192176307-8b526183-245b-4f3c-8c6d-29bcf1512a09.png)
![uCbbhBv](https://user-images.githubusercontent.com/114365748/192176546-40021ee0-508a-4f1e-b492-e53176312aa7.jpeg)

**Comment by Harmandodelavega** [comment]
Pretty sure minor factions never called Waaaghs in WH2, and pretty sure it's intended

**Comment by mfvreeland** [comment]
I'm inclined to agree with @Harmandodelavega. I wasn't sure about it when this was initially brought up on Discord, but in retrospect, this is probably intended design. Unless we have an indication from CA to the contrary, I think this should be considered closed. Thanks for the report, though!
