### ISSUE TITLE
"Book of Arkhan" technology buff does not mention grave guard

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#416]
wh2_dlc11_effect_force_stat_leadership_skeletons_zombies
Leadership: %+n for Zombies, Skeleton Warriors and Skeleton Spearmen units

wh2_dlc11_effect_force_stat_vigour_loss_reduction_skeletons_zombies
Vigour loss reduction for Zombies, Skeleton Warriors and Skeleton Spearmen units

are the only  effects linked to wh2_dlc11_vmp_all_skeleton_zombie_melee_infantry set which includes grave guard

the second effect is not used anywhere but still has wrong loc

remove grave guard from set or add in description?

**Comment by floskan** [comment]
I'd say add in description considering how little tech affects grave guard in general compared to skellies

**Comment by Harmandodelavega** [comment]
checked in WH2 the loc said grave guard
