### ISSUE TITLE
Ghorst not immune to Nurgle plague attrition

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#417]
there's two attrition records

nurgle_plague and plague_nurgle, they didn't add the second one

**Comment by Layotees** [comment]
![image](https://user-images.githubusercontent.com/113050609/194604476-c276662a-03bc-4994-9fce-3cf1feb5929c.png)
Tested, works.

**Comment by mfvreeland** [comment]
Fixed in 5.2
