### ISSUE TITLE
Boon of Chaos "Skullcrusher Leader" not working for skullcrushers

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#42]
Haven't got a lord with this effect yet but it only gives vanguard deployment for the hero himself on a juggernaut and not the skullcrushers in the army.

https://forums.totalwar.com/discussion/319835/skullcrusher-leader-boon-of-chaos-not-working-at-least-for-hero#latest

**Comment by chadvandy** [comment]
fixed by #43

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2, should be removed

**Comment by chadvandy** [comment]
removed
