### ISSUE TITLE
Dark Prince's Envoy/Daemon Whisperer (Cult of Pleasure Ancillaries) spread/trigger from chaos undivided corruption

### ISSUE THREAD

**Issue by Gingerglaahk** [chadvandy/cbfm_wh3#421]
Like everything Morathi related, makes sense that this should be Slaanesh corruption and not undivided

![image](https://user-images.githubusercontent.com/29358271/192363628-d42286b4-7e63-4b26-8351-4fcd19e43c47.png)

**Comment by Gingerglaahk** [comment]
Reading the lua (wh3_campaign_followers.lua), not so sure about this being a Morathi exclusive and therefore maybe it doesn't need to be Slaanesh corruption.

If it is - I can fix it, but if it isn't maybe just close this issue.

What do you guys think?

**Comment by Harmandodelavega** [comment]
> After reading the lua (wh3_campaign_followers.lua , put relevant extract at the bottom of this comment), not so sure about this being a Morathi exclusive and therefore maybe it doesn't need to be Slaanesh corruption.
> 
> If it is - I can fix it, but if it isn't maybe just close this issue.
> 
> What do you guys think?
> 
> `return not character:character_type("colonel") and character:faction():has_technology("wh2_main_tech_def_3_3_3") and character:has_region() and cm:get_corruption_value_in_region(character:region(), chaos_corruption_string) > 10 and not character:has_ancillary("wh2_main_anc_follower_def_diplomat_slaanesh");`

(https://cpecific.github.io/twwh2_ancillary/#wh2_main_sc_def_dark_elves)

Study The Chaos Wastes I think is a Morathi exclusive tech, also can you fix the Daemon Whisperer one too? also Morathi exclusive

**Comment by Gingerglaahk** [comment]
Done, opened PR

@Harmandodelavega do you think we need to change the lua as well? The trigger is done by undivided corruption and not Slaanesh corruption, so maybe change it to slaanesh_corruption_string from chaos_corruption_string .

Never edited a lua before, anything to keep an eye out for?

**Comment by Gingerglaahk** [comment]
Added the lua "as is" from rpfm in one commit, and changed corruption from undivided to slaanesh in another commit.

**Comment by Harmandodelavega** [comment]
> Done them both, opened PR
> 
> @Harmandodelavega do you think we need to change the lua as well? The trigger is done by undivided corruption and not Slaanesh corruption, so maybe change it to slaanesh_corruption_string from chaos_corruption_string .
> 
> Never edited a lua before, anything to keep an eye out for?

makes sense on the surface but should be tested, just to be sure

**Comment by Harmandodelavega** [comment]
I just checked and the Dark prince's envoy (wh2_main_anc_follower_def_diplomat_slaanesh) is not Morathi exclusive, so this may not strictly be a bugfix, although not a stretch either

**Comment by mfvreeland** [comment]
This was partially fixed by CA in 3.1; Daemon Whisperer is now properly tied to Slaanesh corruption in vanilla. The other aspects of this fix will remain in CBFM.
