### ISSUE TITLE
Beastmen Final Quest "Fall of Man" Karl Franz does not appear as reinforcements

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#426]

**Comment by Sensang** [comment]
Same for Khazrak the One-Eye, I would assume it is Beastmen in general.
I have fought this battle 3 times without him appearing and then I gave up.

**Comment by Sensang** [comment]
Oh and I can provide my savegame if it helps

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2
