### ISSUE TITLE
Mortahi's faction gets corrupted by slaanesh trait

### ISSUE THREAD

**Issue by Gingerglaahk** [chadvandy/cbfm_wh3#430]
https://github.com/chadvandy/cbfm_wh3/issues/245
I noticed this happens for all of Morathi's faction's lords and heros:
![image](https://user-images.githubusercontent.com/29358271/192457316-18bcccfd-8a6e-4932-afbd-bc8b85e9abdd.png)

So lore-wise it ties in with them all being corrupted and so on, but game-wise I'm not sure if it's right for a faction to be corrupted by the corruption it spreads.

Should I fix this?

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/245
