### ISSUE TITLE
Thorek's Ancestral Rune of Grungni doesn't properly apply invulnerable

### ISSUE THREAD

**Issue by DontCallMeDari** [chadvandy/cbfm_wh3#433]
Thorek's Ancestral Rune of Grungni doesn't apply the "invulnerable" behavior as is listed on the tooltip. 

1. Play as Thorek
2. Unlock the Ancestral Rune of Grungni
3. Equip the rune to Thorek and have a gyrocopter/gyrobomber in his army in addition to some ground troops like ironbreakers.
4. Play a battle, use the rune and drop a bomb onto your buffed troops.  They will take damage but they shouldn't.

**Comment by floskan** [comment]
Looks like this is fixed with 
![Skärmbild 2024-05-05 194234](https://github.com/chadvandy/cbfm_wh3/assets/34427023/0c59e740-9afb-4b32-bbb4-18a7a59384e8)

being added
