### ISSUE TITLE
Blue line Serve or die skill for Delves, Norsca and some monogod lords only affects warband recruitment cost

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#441]
not so sure if my effect is properly hidden

**Comment by Layotees** [comment]
![image](https://user-images.githubusercontent.com/113050609/194605264-60a5b2af-ad26-4ada-813d-ffd0750af7c9.png)
Fix works for dark elves.  No strange effect text anywhere that I can see in the skill tree or elsewhere.

**Comment by Layotees** [comment]
![image](https://user-images.githubusercontent.com/113050609/194605832-b8145d5b-e77e-42da-bf3f-aae05bb6e6d7.png)
Works for Norsca as well.
