### ISSUE TITLE
Pestilence plague settlement buff wrongly applied to armies.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#445]
**Describe the bug**
Pestilence plague settlement buff wrongly applied to armies.

**Expected behavior**
Pestilence plague should give the army buff to their skaven armies.

**To Reproduce**
1. Play as Pestilence
2. Inflict skaven plague (either agent or undercity building)
3. get your pestilence army infected
4. notice they get the settlement buff which is useless for armies

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/193056298-abe8ea08-b588-4a06-a719-6f668f29c2e8.png)

**Comment by orangenord** [comment]
I have this same issue.

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/147

**Comment by mfvreeland** [comment]
Fixed by CA in 2.3, should be removed.
