### ISSUE TITLE
Treeman Lords lack ability description tooltip in recruitment panel

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#446]
**Describe the bug**
Drycha generic tree lords and tree heroes (and likely regular {not Malevolent} WE generic tree lords and tree heroes) have unique abilities that were well described in TWW2 when mouse-overed in the recruitment panel (before hiring them).
However this description is missing in TWW3 and there is no way to read what these abilities do before hiring the malevolent tree lord or malevolent tree hero.
Attached TWW 2 screenshots explain it best.

**Expected behavior**
Description of these unique abilities shown in the recruitment panel, just like it was shown in TWW 2.

**To Reproduce**
1. Play as Drycha (possibly affects other WE factions as well since their tree lords/heroes also have these unique abilities)
2. Try to recruit a tree lord or tree hero and notice they have unique abilities that are not being explained

**Screenshots**
TWW 2 screenshots:
![image](https://user-images.githubusercontent.com/55892027/193067750-918625b2-399c-45dc-aeed-223910b3d359.png)

**Additional context**
I tried toggling the little button next to selected hero description (outside the recruitment panel, in the bottom left corner) which shows either the hero abilities or hero stats/attributes/abilities but it had no effect on whether the abilities will be explained in the recruitment window.

**Comment by mfvreeland** [comment]
Is this fixable? I'm not sure if we can define mouse-over behavior without some rather complicated UI scripting.

**Comment by Harmandodelavega** [comment]
It used to work, maybe I can check out the WH2 files
