### ISSUE TITLE
Rogue Armies reply "Missing String" to declarations of war

### ISSUE THREAD

**Issue by AManInBlack** [chadvandy/cbfm_wh3#447]
When you declare war on a rogue army, they reply "Missing String" in the diplomacy screen.

![20220929105158_1](https://user-images.githubusercontent.com/9606491/193091900-94e4ee36-8b23-47fb-b024-b55b324d7c6d.jpg)

I have had this issue happen previously as well as this time, and I don't believe that it only happens with this particular rogue army. It's possible that it doesn't apply to all of them, however.

**Comment by Harmandodelavega** [comment]
4.0: "Generic voiceover responses should now trigger correctly when declaring war between factions. "
mby fixed
