### ISSUE TITLE
Mortal lord vet skill "speed and malice" missing hellstriders and doom knights

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#457]

**Comment by Harmandodelavega** [comment]
they fixed the skullcrushers

**Comment by mfvreeland** [comment]
According to the latest notes, they fixed Doom Knights in 4.0.4. Maybe they'll get to Hellstriders in 4.0.6.

**Comment by Harmandodelavega** [comment]
@mfvfreeland no

**Comment by mfvreeland** [comment]
Hellstriders still missing in 4.1.
