### ISSUE TITLE
Warshrines not affected by mortal rank 7 skill

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#458]
added them in the loc too. the effect has warhsrine in the name but the loc didn't so it's safe to say they were meant to be there

**Comment by pigwithsnoot** [comment]
I believe this was fixed today by CA in patch 2.2. 

FREAKISH MUTATIONS

Now properly applies its effects to the Chaos Warshrine unit.

**Comment by Harmandodelavega** [comment]
fixed in 2.2 except they added it in freakish mutations instead of speed and malice, the loc is fine, it's just the database where it's confusing, oh well
