### ISSUE TITLE
Balefire Passive Not Functional

### ISSUE THREAD

**Issue by Bastilean** [chadvandy/cbfm_wh3#46]
See title.  Here's the bugfix:
https://steamcommunity.com/sharedfiles/filedetails/?id=2854116997

**Comment by Aexrael** [comment]
Corpse Carts with Balefire have had changed functionality in wh3 compared to wh2, and is now intended to provide imbuement effects for friendly units, but only the phase effect was updated, the rest of the wh_dlc04_unit_passive_balefire ability was left unaltered, meaning it points to affect enemy targets, it's not flagged as wh_type_area_of_augments, it also has incorrect autoresolver usage and targets compared to similar abilities.

special_ability_phases
Phase display empty -> wh_main_generic_buff_attack_passive

special_ability_to_special_ability_phase_junctions
Target enemies -> Target Self and Target Friends

unit_abilities
type wh_type_hex_of_the_winds -> wh_type_area_of_augments, maybe uniqueness needs to change as well from wh_main_anc_group_common to wh_main_anc_group_uncommon

unit_special_abilities

Autoresolver usage default -> buff_unit
Autoresolver target 1 -> 3

**Comment by mfvreeland** [comment]
@Bastilean I assume by posting here you don't mind if your fix is fully incorporated into CBFM?

**Comment by Harmandodelavega** [comment]
#291 https://github.com/chadvandy/cbfm_wh3/pull/291

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2, should be removed

**Comment by chadvandy** [comment]
removed from CBFM
