### ISSUE TITLE
Non-Dwarf factions are getting runes from combat

### ISSUE THREAD

**Issue by Gingerglaahk** [chadvandy/cbfm_wh3#461]
Seen that for both player and AI, for example:

![image](https://user-images.githubusercontent.com/29358271/193447439-ee770039-9ed7-4147-b7a0-3383b766a158.png)

**Comment by Harmandodelavega** [comment]
> Seen that for both player and AI, for example:
> 
> ![image](https://user-images.githubusercontent.com/29358271/193447439-ee770039-9ed7-4147-b7a0-3383b766a158.png)

think it's a mod

**Comment by Gingerglaahk** [comment]
@Harmandodelavega tbh I don't have any mods that do anything with ancillaries or items but I'll double check

**Comment by Gingerglaahk** [comment]
I think it's related to the [Recruit Defeated Legendary Lords](https://steamcommunity.com/sharedfiles/filedetails/?id=2854819509) mod, I'll post on their page and let's see what they say.

**Comment by Harmandodelavega** [comment]
> I think it's related to the [Recruit Defeated Legendary Lords](https://steamcommunity.com/sharedfiles/filedetails/?id=2854819509) mod, I'll post on their page and let's see what they say.

Don't think it's that, there's a popular mod that lets you steal legendary items and everything else, btw I checked in ancillaries tables and it's dwarf sppecified

**Comment by Gingerglaahk** [comment]
> > I think it's related to the [Recruit Defeated Legendary Lords](https://steamcommunity.com/sharedfiles/filedetails/?id=2854819509) mod, I'll post on their page and let's see what they say.
> 
> Don't think it's that, there's a popular mod that lets you steal legendary items and everything else, btw I checked in ancillaries tables and it's dwarf sppecified

I know that mod but aren't using it.

I think it is the mod I said because they are testing a cross-faction refugees system (i.e. empire getting dwarf lords and for that you have to mess around with ancillary availability. And also as a matter of fact when I disabled the mod it stopped happening :)
