### ISSUE TITLE
Medusae and Scourgerunner Chariots missing from Techs/Names of power

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#463]
HV Edit: from steam comment 
"- Dark Elves missing Scourgerunner entry for the Bolt Cartridges, Exotic Beast Hide Armor and Hunt Outlaws techs
- Medusae units missing entry for the Study the Chaos Wastes, Spoils of War and Under the Yoke tech

Mostly applying to medusa units, will look into this

**Comment by floskan** [comment]
Can someone assign me to this? couldn't find out how to do it myself

**Comment by floskan** [comment]
I'm halfway done with this

**Comment by Harmandodelavega** [comment]
loc is !cbfm_def_scourgeandmedusae now
