### ISSUE TITLE
Daemonic Factions can build the Shrine of Khaine

### ISSUE THREAD

**Issue by Gingerglaahk** [chadvandy/cbfm_wh3#465]
Noticed in my Nurgle playthrough that I can build the Shrine of Khaine and get -15 corruption which of course doesn't make sense.
![image](https://user-images.githubusercontent.com/29358271/193512223-9ae93667-a817-4dbd-bcd1-f71c4f20f215.png)

I think there are two solution - either have a "corrupted" Shrine of Khaine for each chaos god, similar to what Vampire Counts have - 
![image](https://user-images.githubusercontent.com/29358271/193513349-e2adb188-b85b-4132-b421-98eb80ac2491.png)

Or just prevent daemonic factions from building it - you can see in building_chain_availability_sets_tables that wh2_main_special_shrine_of_khaine_other is not available for wh_main_bas_chs .

**Comment by Harmandodelavega** [comment]
Not enough info
