### ISSUE TITLE
Crookback Mountain has iron as a resource but no icon in the settlement display (next to climate indicator)

### ISSUE THREAD

**Issue by Mandras2** [chadvandy/cbfm_wh3#467]
Crookback Mountain has the iron resource but no icon in the settlement display (next to climate indicator)

Fix:
"slot_templates_tables"
wh2_dlc14_special_the_wolf_lands_crookback_mountain_secondary	res_rom_iron

**Comment by Harmandodelavega** [comment]
https://trello.com/c/rYP7EamY/681-wrong-strategic-location-iconswip

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2
