### ISSUE TITLE
Only Skarsnik has his special Waagh ability show up correctly in the frontend (when mousing over the faction traits)

### ISSUE THREAD

**Issue by Mandras2** [chadvandy/cbfm_wh3#468]
Only Skarsnik has his special Waagh ability show up correctly in the frontend (when mousing over the faction traits).

Don't know how to fix this, the frontend is handled differently than WH2.

**Comment by grimharrison** [comment]
can confirm this issue exists in base game (see attached images for demonstration). this only an issue when viewing the popup tooltip seen from the lord selection screen. the popup tooltip for lord-specific waaaghs in campaign and battle are correct.
![azhag_waaagh_tooltip](https://user-images.githubusercontent.com/11903864/236098161-000f7d98-9034-4125-98bd-6ef688da6f13.jpg)
![grimgor_waaagh_tooltip](https://user-images.githubusercontent.com/11903864/236098162-9013bca4-2036-46cf-93ed-077970c59bb3.jpg)
![skarsnik_waaagh_tooltip](https://user-images.githubusercontent.com/11903864/236098164-57855833-e2cb-4861-b774-4938bbd8c515.jpg)
