### ISSUE TITLE
Mounted units not affected by healing cap modifiers

### ISSUE THREAD

**Issue by dstroma1** [chadvandy/cbfm_wh3#470]
When playing as any vampire count faction, in the majority of campaign battles all undead cavalry (hexwraith, black knights, blood knights etc) will become unhealable with invocation of nehek. If you cast on one of these units and mouse over their health bar you can see their healing cap shrinking as if they were being healed, but their health does not increase and no entities are resurrected. Happens the majority of campaign vampire count battles. Doesn't seem to happen to any non-cavalry unit.

**Comment by Harmandodelavega** [comment]
Does this happen immediately or mid battle? because if it's mid battle it might have something to do with the broken healing caps not applying to them

**Comment by dstroma1** [comment]
I'll test and get back to you

**Comment by dstroma1** [comment]
Happens mid battle

**Comment by Harmandodelavega** [comment]
fixed and replaced with another bug in 2.2
