### ISSUE TITLE
Dark Prince's envoy (Delf follower) triggers from Undivided rather than Slaanesh corruption

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#478]
#421 #429

[mfvreeland](https://github.com/mfvreeland)

"There is no need to overwrite the whole followers script, and for the sake of future compatibility, I wouldn't recommend it. If it's just the one follower, the default listener that awards it can be removed and replaced by the altered listener in a new script."

wh3_campaign_followers.lua

**Comment by Gingerglaahk** [comment]
Now I know how to edit these type of listeners (just remove one and add a new one) I won't need someone else to finish the job for me in the future 🙈
