### ISSUE TITLE
Skaven Bug

### ISSUE THREAD

**Issue by orangenord** [chadvandy/cbfm_wh3#481]
Clan Pestilence:
- The plague scheme doesn't work as the plague priests 1st city doesn't show the Skaven plague but it will spread correctly to other cities. 
- Under city plague ball works but gives the armies the city stats for the Skaven plague.

Clan Moulder: 
- Deep Freeze doesn't work, heard that many of the lab items are not working.

**To Reproduce**
1. Play as Clan Pestilence and spread the plague to the city. 
2. Play as Clan Pestilence and deploy under city plague ball and get an army to receive the plague. 
3. Play as Clan Moulder and learn deep freeze the mutagen count doesn't go to 200.

**Comment by AManInBlack** [comment]
The plague bug may be related to #147 or #445.

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/451
