### ISSUE TITLE
Plague: Buboes bug

### ISSUE THREAD

**Issue by VinnieYard** [chadvandy/cbfm_wh3#488]
"Attrition: -35% when under siege".
It must be +35%*
![222](https://user-images.githubusercontent.com/115794414/195911864-b6b0bfc5-a34f-4154-a11f-f189a9d7d575.png)
![111](https://user-images.githubusercontent.com/115794414/195911867-08b6c20b-746b-4f07-98a6-454233fc36e2.png)

**Comment by AManInBlack** [comment]
This is fixed for Ku'gath in 2.2. Not sure offhand if it's still (or was ever) present for Festus.
