### ISSUE TITLE
Sword of Khaine gets picked up by AI Heroes, becomes unobtainable

### ISSUE THREAD

**Issue by Sable-Drake** [chadvandy/cbfm_wh3#49]

**Comment by chadvandy** [comment]
need a save where this happens or something

**Comment by chadvandy** [comment]
NOTE: Seems the "sword_of_khaine_BattleCompleted" listener doesn't have *any* check for if a character in a battle that has SoK has lost or won; it only checks if they were in a battle and tries to apply the SoK to the opposite battle side right away. Kinda weird

**Comment by MattinglyBR** [comment]
hello, by defeating the enemy general, the game does not give me the sword. here is a save game

https://drive.google.com/file/d/1AWAWKjLroRraEiur1_0ICpqjShlzaSa0/view?usp=sharing

**Comment by pigwithsnoot** [comment]
This may have been fixed today by CA in patch 2.2.

**Comment by Harmandodelavega** [comment]
> This may have been fixed today by CA in patch 2.2.
