### ISSUE TITLE
Rakarth passive "harpies has no income" don't work

### ISSUE THREAD

**Issue by Glun** [chadvandy/cbfm_wh3#490]
**Describe the bug**
Rakarth ability "Carrion Crows" not removing upkeep from harpies

https://forums.totalwar.com/discussion/322890/rakarth-no-upkeep-harpie-skill-not-working

**Comment by pigwithsnoot** [comment]
It seems this was fixed today by CA in patch 2.2.

**Comment by Glun** [comment]
Fixed by CA
