### ISSUE TITLE
Resurrected cavalry models return with new healing cap and full health.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#491]
**Describe the bug**
Since patch 2.2 cavalry models that get resurrected via Invocation of Nehek, Tomb King mechanic or LM Crystal of Revivification are brought back with full health and a brand new healing cap - essentially making the unit unkillable as long as the resurrecting effect is present.
Best explained in detail on a reddit threat that contains a video: https://www.reddit.com/r/totalwar/comments/y7hsp3/the_infinite_ammo_bug_on_heal_was_fixed_but_a_new/
Video itself https://www.youtube.com/watch?v=PGbMylgkfw4

**Expected behavior**
Cavalry models that get resurrected should NOT return with full health and a brand new healing cap.

**To Reproduce**
1. Play as any faction that has resurrection spells
2. Get a cavalry unit to near death with lots of lost models
3. Cast on them a spell capable of resurrecting models
4. As soon as models start being resurrected the whole unit will rapidly heal to 100% and its heal cap will be reset.

**Screenshots**
Video: https://www.youtube.com/watch?v=PGbMylgkfw4
Reddit https://www.reddit.com/r/totalwar/comments/y7hsp3/the_infinite_ammo_bug_on_heal_was_fixed_but_a_new/

**Additional context**
Perhaps with this bug the lizardmen cavalry can be viable! :)

**Comment by Harmandodelavega** [comment]
fixed in 2.2.1 hotfix
