### ISSUE TITLE
Armour of Ursun Quest does not award armor to Boris Ursus

### ISSUE THREAD

**Issue by FormerDeveloper** [chadvandy/cbfm_wh3#495]
**Describe the bug**
The Armour of Ursun quest line does not award the unique armor to Boris Ursus. Completing the quest shows the quest completion dialog, but the armor is not actually received.

**Expected behavior**
Completing the Armour of Ursun quest (occupy/etc. three settlements) should award the unique armor to Boris Ursus.

**To Reproduce**
1. Play as Boris Ursus
2. Receive the Armour of Ursun quest
3. Occupy/etc. three settlements
4. Verify that the quest is complete
5. Check Boris to see that there's no armor and be sad

**Screenshots**
Here's a screenshot of the armor bug. Quest is complete but no armor. (Please don't judge the state of the campaign, Boris has it rough right now with the more aggressive AI . . . )

**Saves**
I'm sure I could get a save but this is a pretty straightforward bug to reproduce and fix. Let me know if you'd like a save.

**Additional context**
This is a very obvious and easily fixable bug. The incorrect entry is in db/cdir_events_mission_option_junctions_tables (of course it's that table), ID 1108420148, Mission Key wh3_main_ie_qb_ksl_boris_armour_of_ursun, Option Key GEN_CND_AGENT_SUBTYPE. The Value is set to ~~wh3_main_ksl_katarin~~, should be **wh3_main_ksl_boris**.

I'll do a quick mod to verify that this is the problem. It's possible that the bug fix will have to be in place *before* the quest fires; I'm not sure fixing the table entry will fix the problem once the quest has already been set up. As such, I may have to start a new campaign to verify, but I'll try to test out the fix when I get a chance.

Katarin thanks Boris for her new armor. (And how do these bugs slip in like this?! Wasn't it working previously?)

![Boris Armor Bug](https://user-images.githubusercontent.com/112734917/196735956-d39699e6-c54c-4a95-ba2c-b644092d6fec.jpg)

**Comment by FormerDeveloper** [comment]
Update: built a quick mod to test the fix, and I can confirm that making the fix described above under Additional Context will fix the quest. I do think the fix needs to be in place before the quest fires, though.

**Comment by xhsu** [comment]
Could you release this bugfix independently if CBFM has no interest in implementing this fix?
This bug really ruins my Boris run..

**Comment by nytak619** [comment]
fixed in 2.3 which came out today according to blog post

**Comment by Harmandodelavega** [comment]
Pls don't post just to report patch notes, unless you have verified the bug is fixed
