### ISSUE TITLE
Daemon Prince's Nurgle's Gifts VIII lord recruit rank bonus not functioning correctly

### ISSUE THREAD

**Issue by AManInBlack** [chadvandy/cbfm_wh3#499]
#262 is back in 2.2, albeit in a different form. It's now giving +10 recruit rank to all Heralds, regardless of god, when recruiting a new lord at a city. It's working according to the tooltip (+20 to Nurgle, +0 to other gods) when replacing a lord in an existing army.

![20221020135939_1](https://user-images.githubusercontent.com/9606491/197046291-7e97dd67-8c45-46f6-9c17-0d21154aa411.jpg)
The tooltip still says "Lord recruit rank: +20 for Heralds of Nurgle (all armies)".

![20221020140232_1](https://user-images.githubusercontent.com/9606491/197046551-302de62b-c23d-4432-a7d4-f40e366072bd.jpg)
![20221020140128_1](https://user-images.githubusercontent.com/9606491/197046394-f770a087-edb3-49c6-b4a7-de77efe6e665.jpg)
However, it's giving +10 recruit rank, and to to Heralds of all gods, not just Nurgle.

![20221020140307_1](https://user-images.githubusercontent.com/9606491/197046676-0198ec79-421b-4343-9156-51ac08b7d9a9.jpg)
When replacing a lord in an existing army, it's +20 to Nurgle and +0 to other gods.

I noticed this issue (and took these screenshots) under 2.2 with the bugfix mod inactive, on a save originally made under 2.1.

Test save: [Legion of Chaos.1951295005664.save.zip](https://github.com/chadvandy/cbfm_wh3/files/9833583/Legion.of.Chaos.1951295005664.save.zip)

**Comment by AManInBlack** [comment]
Okay. When testing on a fresh save made in 2.2, it's reverted to the behavior of #262. New Nurgle Herald lords leading a new army are level 1, but new Nurgle Herald lords being recruited to replace an existing lord are level 21.

Clean save demonstrating the behavior: [Legion of Chaos.814217848666.save.zip](https://github.com/chadvandy/cbfm_wh3/files/9847390/Legion.of.Chaos.814217848666.save.zip)

**Comment by Harmandodelavega** [comment]
probably long victory was giving you + 10 recruit trank to all ords
