### ISSUE TITLE
can't recruit TK units through outpost (due to missing caps)

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#5]

**Comment by mfvreeland** [comment]
DrunkFlamingo created a fix for this here: https://steamcommunity.com/sharedfiles/filedetails/?id=2854625588

He may generously allow its inclusion here. It's a scripted solution, but I don't think there is a DB-only solution.

**Comment by chadvandy** [comment]
I think I'll leave it as is for now and keep it separate, since DF's fix is quite hefty. Will post a link to it in the description though

**Comment by 13ootyknight** [comment]
found another solution to this on the workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2863826016 

says in the description that it doesn't use scripts

**Comment by mfvreeland** [comment]
@13ootyknight Interesting! This could be a better solution for our purposes. Thank you for sharing.

**Comment by mfvreeland** [comment]
Got permission to adapt the DB-only fix from Steam workshop for CBFM. Will do soon.

**Comment by mfvreeland** [comment]
Fixed in 2.2
