### ISSUE TITLE
Misspelling in the event for discovering an Under-City

### ISSUE THREAD

**Issue by AManInBlack** [chadvandy/cbfm_wh3#500]
Edit: https://trello.com/c/QE79AVIn/777-mere-meer-typo-undercity-detection-string event_feed_strings

It should be a "a mere nuisance."

![20221020222335_1](https://user-images.githubusercontent.com/9606491/197167242-86c183da-8424-4e0b-9895-6335985a6745.jpg)

**Comment by Harmandodelavega** [comment]
https://trello.com/c/QE79AVIn/777-mere-meer-typo-undercity-detection-string
