### ISSUE TITLE
Fixed more effects supposed to target Nurgle RoR/Forsaken of Nurgle and one for Slaanesh RoR in Belakor's Blood & Magic skill

### ISSUE THREAD

**Issue by AManInBlack** [chadvandy/cbfm_wh3#506]
The Rot of Splendor event for Daemons of Chaos says it applies a -25% upkeep cost modifier and -30% recruitment cost modifier for Nurgle units.

![20221023062646_1](https://user-images.githubusercontent.com/9606491/197392022-e934d978-853f-4166-89df-dbd44c19fa0d.jpg)
Neither modifier applies to the Daemonspew, the Forsaken ROR. The modifier does apply correctly to all of the other Nurgle RORs.

Test save: 
[Legion of Chaos.154217848666.save.zip](https://github.com/chadvandy/cbfm_wh3/files/9846572/Legion.of.Chaos.154217848666.save.zip)

I've already recruited the unit in this save, but you can kick it to see that there's no discount on the recruitment.

**Comment by AManInBlack** [comment]
There's a similar DOC event for Tzeentch units, "The Changer's Promise".

Wyrd Spawn do not get the discount from it, while all of the other Tzeentch RORs do.

**Comment by Harmandodelavega** [comment]
new name of file is nurgle_ror and nur_plaguebearers_forsaken_spawn unit was added by CA

**Comment by Harmandodelavega** [comment]
The nurgle forsaken sets are unused but I'm keeping them in anyways
