### ISSUE TITLE
[Meta] Sister's of Twilight Treesinger office no longer allows Ancient Treeman to fill it, even though it applies to them

### ISSUE THREAD

**Issue by mkscho63** [chadvandy/cbfm_wh3#508]
**Describe the bug**
In a previous issue resolved by this mod  https://github.com/chadvandy/cbfm_wh3/issues/339, lord type restrictions were placed on the offices for Sisters of Twilight's Court of the Mage Queen. Most of these were correct however Treesinger of Isha was restricted to only Lore of Life Spellweavers despite also working for Ancient Treemen lords. I believe this was an oversight because the office arguably is more applicable to treemen with it's bonus to other tree units and Ancient Treemen having access to Lore of Life spells by default.

**Expected behavior**
Treesinger of Isha should be restricted to only Ancient Treemen and Lore of Life Spellweavers

**To Reproduce**
1. Play as Sisters of Twilight
2. Recruit Ancient Treeman lord
3. Attempt to put them as Treesinger of Isha in Court of the Mage-Queen
4. It is now blocked

**Screenshots**

![image](https://user-images.githubusercontent.com/9925376/197407526-4cb07ac6-151f-44da-a55b-dea0473a6e8f.png)

**Comment by mkscho63** [comment]
If this change is approved, should just need to remove this line I believe:
![image](https://user-images.githubusercontent.com/9925376/197407883-5deb41da-59cf-44a8-bd82-28ee4645c8b6.png)

**Comment by Bogdanov89** [comment]
I dont think Treeman lords are supposed to be allowed in the Sisters "Court of the Mage-Queen", which is different from the Courts that Durthu and Drycha have access to.
Orions version of the court also does not allow any Treeman to be appointed into offices.
To me it seems Treeman lords should not be allowed to hold any positions in Sisters and Orions courts.

For info the Treesinger of Isha office provides the following bonsues:
![image](https://user-images.githubusercontent.com/55892027/197410433-33af8a44-f816-4671-b640-985bd1dcfa71.png)

**Comment by mkscho63** [comment]
But it also doesn't call out that it isn't allowed. I understand it's up to interpretation a bit but since all these bonuses could apply to both an Ancient Treeman lord and a Lore of Life Spellweaver (since both have Lore of Life and both can have tree units) I would think the preference would be not apply a restriction in the case of this ambiguity. I agree with the other changes that were made in the original issue because it prevents choices that lead to unusable benefits, but this one actually does remove a way to play an army. That's all just my interpretation and opinion though, so I wanted to raise the issue.

**Comment by Harmandodelavega** [comment]
I was almost going to agree with you but I checked around and it seems "Treesingers" in the lore are wood elves, the other problematic thing is beastbinder of Kurnous buffs characters mounted on great stags but spellweavers cannot be on great stags, for the time being we'll leave it like this

**Comment by floskan** [comment]
Treemen used to be able to use that court position fine in game 2, i don't see why they shouldn't now but it's hard to say if it's a bug or intended since they didn't document a ton of small changes like this one

**Comment by Bogdanov89** [comment]
On the following lore webpage this is mentioned:
"Wood Elf mages have an altogether unique relationship with Athel Loren...  This bond allows them to commune with the forest... only the greatest of the Tree-singers can rouse a slumbering Treeman before its time."
& 
"The ability to shape and guide the forest is seen as a useful skill by more than just the Elves. Though the banished fey of Athel Loren's Wildwood have little use for the Asrai, they crave the ability of the Tree-singers and will go to any lengths and make any promises to lure them into their service."
https://warhammerfantasy.fandom.com/wiki/Spellsingers

So as far as lore stuff goes the Treesingers are exclusively WElven/Asrai mages, its even mentioned that the various forest fey (tree creatures) want to hire/charm the Treesinger mages since the forest fey themselves lack this particular magic skill.
Also "Isha" (from Treesinger of Isha) is the ELVEN goddess of life, growth etc... does not make sense to me that an Ancient Treeman would devote himself to an Elven goddess, especially when he possibly is even older than Isha.

**Comment by mkscho63** [comment]
Honestly at this point I'm just in for the lore discussion of Wood Elves haha :D So if we wanna get down and dirty in lore, technically treekin ARE animated trees with the souls of elves in them. I do believe I remember that in the Warhammer Fantasy Roleplaying Game (questionable canon potentially to go to the TTRPG) the Treesinger profession, which is as close as I know to an actual source for what a Treesinger is, is someone responsible for the care of the forests using their magic to encourage the growth of forests. They are considered the "shepherds" of the forest. Given that a treekin has the soul of a wood elf in them, I think it's plausible that they can be Treesingers and being shepherd the forests seems to fit to what the Ancient Treemen do already.

Disclaimer: I'm not just trying to be argumentative here or anything, I'm totally down with whatever people want to do here and don't claim to tell anyone else they are wrong. I just think the discussion is fun heh.

**Comment by Bogdanov89** [comment]
TreeKIN is not the same as a TreeMAN (like Durthu).
TreeMAN are actual tree spirits, usually older than the entire elven race.
TreeKIN are some amalgamation of an elven soul and a tree body, but those do not exist as Lords in TWW2/TWW3 hence can not be placed in an Office.

**Comment by floskan** [comment]
> On the following lore webpage this is mentioned: "Wood Elf mages have an altogether unique relationship with Athel Loren... This bond allows them to commune with the forest... only the greatest of the Tree-singers can rouse a slumbering Treeman before its time." & "The ability to shape and guide the forest is seen as a useful skill by more than just the Elves. Though the banished fey of Athel Loren's Wildwood have little use for the Asrai, they crave the ability of the Tree-singers and will go to any lengths and make any promises to lure them into their service." https://warhammerfantasy.fandom.com/wiki/Spellsingers
> 
> So as far as lore stuff goes the Treesingers are exclusively WElven/Asrai mages, its even mentioned that the various forest fey (tree creatures) want to hire/charm the Treesinger mages since the forest fey themselves lack this particular magic skill. Also "Isha" (from Treesinger of Isha) is the ELVEN goddess of life, growth etc... does not make sense to me that an Ancient Treeman would devote himself to an Elven goddess, especially when he possibly is even older than Isha.

I was never discussing warhammer lore to begin with, just that it was working fine in game 2 and now it doesn't.
They've made plenty of concessions on lore in favor of having better gameplay, changing this for the sake of lore is probably not what happened. But as i said, not very easy to tell if this is a bug or not

**Comment by Harmandodelavega** [comment]
Just to make sure, this issue is linked to #339, so we would be making an exception for just this office, I can see both sides but it just makes sense to lock non elves out
