### ISSUE TITLE
wh3_dlc20_skill_daemon_prince_tzeentch_special_2 skill won't provide the Chaos Sorcerers recruit rank bonus

### ISSUE THREAD

**Issue by CathayZhao** [chadvandy/cbfm_wh3#51]
The effect scope of `wh3_dlc20_skill_daemon_prince_tzeentch_special_2`'s `wh_main_effect_agent_recruitment_xp_wizard_chaos` effect is `character_to_faction_when_on_map_unseen`, so the target is faction and make it useless. I think use the `character_to_region_own_when_on_map` effect scope might fix this bug, or use the `character_to_province_own_factionwide`.

**Comment by Harmandodelavega** [comment]
Think this was meant to be factionwide,second skill for all Daemon Princes follows this trend

**Comment by chadvandy** [comment]
Other specials all have local province or army effects, and any time a +5 recruit rank is used it's targeting the local province

**Comment by Harmandodelavega** [comment]
> Other specials all have local province or army effects, and any time a +5 recruit rank is used it's targeting the local province

You're right, I could've swore the Nurgle one had factionwide replenishment but it's just the Slaanesh one with building income
