### ISSUE TITLE
DOC Herald lords' names are blanked out when promoted to Exalted Greater Daemons

### ISSUE THREAD

**Issue by AManInBlack** [chadvandy/cbfm_wh3#511]
Edit: https://youtu.be/oPi_NCMq9NU?t=9169

When a Daemons of Chaos Herald lord gets promoted to an Exalted Greater Daemon by the dilemma that appears after reaching level 15, their name is blanked out instead of being carried over from their old name (the current behavior for monogod factions) or getting a random name from the name list (the behavior before 2.0.)

To reproduce this, simply promote a Herald lord to an Exalted Greater Daemon. It happens with all four gods' heralds, but only in the Daemons of Chaos faction led by the Daemon Prince.

In this save, simply hit end turn. A Herald of Khorne has an autoresolvable fight that will get him promoted to an Exalted Bloodthirster at the beginning of the turn. [Legion of Chaos_Auto-save.884217848666.save.zip](https://github.com/chadvandy/cbfm_wh3/files/9847624/Legion.of.Chaos_Auto-save.884217848666.save.zip)

**Comment by pigwithsnoot** [comment]
Yeah, I can confirm I also had this happen in an earlier campaign with one of their Slaaneshi lords.
