### ISSUE TITLE
Reinstate / return settlement to elector is greyed out

### ISSUE THREAD

**Issue by GeorgeBates98** [chadvandy/cbfm_wh3#517]
Describe the bug
The option to reinstate electors or return their settlement is greyed out after approximately 20 turns in several campaigns I've tried with no mods. Before whatever is causing this to happen the option is not greyed out and can be used.

To Reproduce
Play approximately 20 turns and see if it can be reproduced.

**Comment by Harmandodelavega** [comment]
> With patch 2.2.0 CA changed some of the occupation options, e.g. reinstating elector count faction (prolly also revived norscan vassals), to no longer work for already confederated faction by ui-locking (greying out) the related occupation button.

think this is it sry
