### ISSUE TITLE
Keeper of Secrets RoR missing passive "Feasting on Fear" in campaign

### ISSUE THREAD

**Issue by AstraEC** [chadvandy/cbfm_wh3#518]
HV edit: wh3_main_lord_passive_feasting_on_fear  in land u to u abilities j only works on lords/needs enabling

The new Slaaneshi greater demon RoR/Keeper of Secrets is supposed to have an additional passive attached to it, Feasting on Fear, which is available to it in multiplayer and stated in the in-game unit directory. When actually recruited during campaign though, the RoR does not have have this passive.

See below pictures.

![image](https://user-images.githubusercontent.com/116610340/197660495-8a219743-7e50-46e0-8619-a025ad3ab007.png)

![image](https://user-images.githubusercontent.com/116610340/197660602-ee04aa02-8b96-48d9-9a62-e3685914a9a5.png)

The other greater demon RoR do not have this discrepancy and all their passives/sidegrades are retained properly when recruited in campaign.

**Comment by Drazhir2** [comment]
Fix by tentigers (rename to .pack)
[zzz_cbfm_keeper_ror_passive.patch](https://github.com/chadvandy/cbfm_wh3/files/12064783/zzz_cbfm_keeper_ror_passive.patch)

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/8e3940b2-b2c3-4208-8c19-39be4003f4b3)

**Comment by Harmandodelavega** [comment]
that fix gives feasting on fear automatically to exalted keeper lords
it's a skill for them
needs a cloned effect without effect enabling @floskan

**Comment by chadvandy** [comment]
5.1: "Fixed an issue where the Marquis of Masochism (Keeper of Secrets RoR) was not correctly receiving the Feasting on Fears ability in campaign and battle"

**Comment by mfvreeland** [comment]
Confirmed fixed in 5.1
