### ISSUE TITLE
Kazador's Trait and Thorgrim's Melee Atk vs Grn and Skv skill don't work properly

### ISSUE THREAD

**Issue by CathayZhao** [chadvandy/cbfm_wh3#52]
Harmando Edit: Update, this skill is obsolete, it now ONLY targets caravans but all that previously had it now use the Ogre, Grn and Skaven one (apart from the 2 ones in the title)

From the description, this effect should only be active when fighting against Greenskins or Skaven, but in `effect_bonus_value_battle_context_junctions_tables` it also includes `fighting_against_caravan`. This line needs to be removed to fix it, but it is not a big deal and requires overite vanilla tables.

**Comment by Harmandodelavega** [comment]
I gave Kazador the same that he had before and added Ogres to Thorgrim since the first half of the ability has them
