### ISSUE TITLE
Cultists on certain mounts/unmounted don't receive the proper buffs

### ISSUE THREAD

**Issue by Gingerglaahk** [chadvandy/cbfm_wh3#526]
Harmando edit: only when mounted on warshrine, "tze_cultist" unit set missing "wh3_dlc20_tze_cha_cultist_mtze_warshrine"

When Kairos is leading an army and has unlocked "Bewitching Potency" skill, Cultists of Tzeentch aren't getting the buff.
However, Iridescent Horrors do, so I think the effect just needs to be applied for Cultists.

![No passive ability](https://user-images.githubusercontent.com/29358271/198618685-b216eb41-cbc9-4443-b961-a5c8b9222557.png)
![Cultist Mastery of Winds](https://user-images.githubusercontent.com/29358271/198618701-149db79c-9dc4-4001-8bb8-97537506ca5b.png)

**Comment by Gingerglaahk** [comment]
Double checked it and if they're not on the Chaos Warshrine mount they get the buff.
I guess it clashes with their Warshrine of Tzeentch effect.
Documenting this anyway because I think it is intentional behaviour and not a bug.

**Comment by Gingerglaahk** [comment]
@Harmandodelavega maybe mark it as "not a bug" for future visibility
Not sure how to do that myself 😓

**Comment by Harmandodelavega** [comment]
cultist on warshrine not getting it is still a bug
