### ISSUE TITLE
Removed obsolete income lost to piracy event/references in Black ark stance tooltip and fixed Black Ark docked stance bonuses + other fake tooltip

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#543]
Needs test just to see if I hid the Piracy effect on the Blark

 

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/198978094-45270b6c-b1a7-4302-a1c8-a8d160d5d927.png)

 

 
 

 

Black Ark dread expansion stance claims it reduces black ark replenishment, but it has never done so. Not even in TWW2.
Black Ark when docked supposedly should reduce the Black ark owners trade income (due to piracy) but its colored green like it is a positive instead of a penalty.

**Expected behavior**
Tooltips updated: Dread expansion stance text should be fixed by removing mention of reducing replenishment of the Ark itself.
Black Ark docked information changed to red color to indicate its a penalty for the owning Ark player, not a positive.

**To Reproduce**
1. Play as Malekith
2a Place Ark in your port city to see the trade income penalty text on the stance button
2b Put ark in Dread expansion stance (anywhere) and notice it does not slow down Ark army replenishment.
*mouse over stances to see text info

**Comment by Harmandodelavega** [comment]
@Bogdanov89 can you check if the +4% replenishment is working?

**Comment by Bogdanov89** [comment]
> @Bogdanov89 can you check if the +4% replenishment is working?

I tried testing this in-game but i was unable to since just entering an owned settlement already boosts replenishment by default.
So i can not tell is the +4% replenishment while docked working since entering a settlement already gives some unknown amount of replenishment boost.

**Comment by Harmandodelavega** [comment]
base replenishment while garrisoned is 12% in fully owned province/ 8% in shared

**Comment by Bogdanov89** [comment]
I tried my best to test this out (no mods enabled) but the results i got are to me not conclusive.
At turn 2 (malus faction) my Black Ark was in a recent taken settlement (just occupied, not looted) had 2 black ark corsair units (province has 3 settlements, 2 of them are hostile to me).
Corsairs have 75 models in a unit (large size in options) and after battle 34 models.
They were replenishing 12 models per turn as the game states.
Some simple math tells me that is about 9% replenishment, which does not seem to fit into any known replenishment numbers.

The ground army (malus himself, lvl1) seems to receive a much larger bonus to replenishment when in a settlement than the black ark (was not in dread expansion stance).
Though how much i can not exactly see since garrisoning the unit would replenish it to full.

**Comment by Harmandodelavega** [comment]
thanks
