### ISSUE TITLE
Malekith AI doesn't get supreme spellshield

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#545]
"in wh_quests.lua', instead of "wh2_main_anc_enchanted_item_supreme_spellshield", devs write "wh2_main_anc_armour_supreme_spellshield"

**Comment by Harmandodelavega** [comment]
@mfvreeland pinging to check if you want to take a look at it

**Comment by mfvreeland** [comment]
We can overwrite this function without overwriting the vanilla script file, although I'm not sure that really matters in this case since this script file is essentially only this one function. @chadvandy, opinion?
