### ISSUE TITLE
Vilitch "Ritual staff" tech affecting Dual Axe Khorne warriors

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#55]
Should apply MD per rank and charge defence on rank 4. Does none of it. 

[reddit link](https://www.reddit.com/r/totalwar/comments/x3tj26/the_extra_mdrank_for_halberd_units_doenst_work/)

**Comment by floskan** [comment]
Can confirm that this does not work at all

**Comment by Velykos** [comment]
Definitely works for Marauders and Chaos Warriors, just not Chosen

**Comment by floskan** [comment]
I noticed wh3_dlc20_chs_inf_chosen_mtze_halberds is missing from wh3_dlc20_chs_spear_halberd_units_rank_1 to 9 which might be why they aren't getting expert charge defense and Melee defence

**Comment by floskan** [comment]
> Works for Marauders and Chaos Warriors, just not Chosen. I BELIEVE. Just played Vilitch and my Chaos Warriors w/ Halberds have massive MD vs SwordNBoard, as well as expert charge defense. Chosen no get tho

Do you have a save that works without mods i can have?

**Comment by Harmandodelavega** [comment]
they removed wh_dlc01_chs_inf_chaos_warriors_2

**Comment by Harmandodelavega** [comment]
just the part where we remove dual axe khorne warriors remains

**Comment by floskan** [comment]
> just the part where we remove dual axe khorne warriors remains

Wouldn't i need to make a new negative effect to remove them? How likely is it that vilitch will recruit dual axe khorne inf?

**Comment by Harmandodelavega** [comment]
@floskan it's already in, just exclude from set
