### ISSUE TITLE
Confederated Norsca factions can not be resurrected/turned into vassals

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#565]
**Describe the bug**
As Be'lakor i was unable to give settlements to two minor vassal factions around Wulfrik the Wanderers spawn location: Naglfarlings and Varg.
These (confederated) factions are missing in the Diplomacy screen and they have no armies nor cities.
The vassal tooltip claims that the factions will be resurrected but i am unable to click on the button (greyed out)

_There was a discussion about this on the CBFM discord and a new github issue was requested (screenshots below).
It was theorized that CA made this (perhaps temporary) change in patch 2.2 to bandaid-fix the ghost faction bug._

**Expected behavior**
WoC able to return any territory to its original owners (and vassalize them), even if that territory originally belongs to a faction that was confederated.

**To Reproduce**
1. Play as WoChaos
2. Wulfrik the Wanderer often swiftly confederates large norska lands around him so go to his territories.
3. Attack a territory that originally belongs to a faction which was confederated (does not show up in diplomacy)
4. Notice the button to return the territory to that faction (and resurrect them if needed) is greyed out.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/200269828-02b3c022-2da9-487c-8d67-30905dac139f.png)

![image](https://user-images.githubusercontent.com/55892027/200270169-28e1e7c5-0211-4225-9e72-3b9cabb75a81.png)

**Additional context**
This particular issue really screws over the WoChaos since they rely on their vassals for income and territory protection, and Norsca tend to confederate wide swaths of territory by defeating faction leaders of other norsca.

**Comment by Cataph** [comment]
liberating confederated vassals caused bad bugs and I could bet this is intentional to avoid them.

**Comment by mfvreeland** [comment]
I am confident enough that Cataph is right about this to consider the issue closed.

**Comment by Bogdanov89** [comment]
I recently made a post on CA forums about this and got a reply:
https://forums.totalwar.com/discussion/328975/confederated-norsca-factions-can-not-be-resurrected-by-wochaos-as-vassals#latest

![image](https://user-images.githubusercontent.com/55892027/223874170-e25ed405-7ff0-4465-9f81-7793b0b7fb27.png)

![image](https://user-images.githubusercontent.com/55892027/223874095-7c0fdb8a-98e1-40e9-a185-6f15428636f9.png)
