### ISSUE TITLE
Winds of Magic/climate issue at Kairos IE starting province/Road to Damnation

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#570]
This also apparently happens in the road to damnation (ROC or IE) and applies cumulative climate penalties

**Describe the bug**
Kairos has Winds of Magic Manipulation mechanic, allowing you to lower winds in one province you own and increase it in another province you own.
But there seems to be an issue with two provinces where Kairos IE starts - The Abyssal Glacier & The Southern Wastes.
Specifically it seems that the new starting city/region (Fateweaver's Crevasse) for Kairos is tied to the wrong province for Winds of Magic.
Fateweaver's Crevasse should be tied to the Abyssal Glacier province, but right now it is tied to the Southern Wastes province.
This causes a few issues:
- The UI shows two dials for manipulating Winds of Magic but they are tied to one another, meaning raising/lowering one affects the other (as if it was just one dial, one province).
- The UI shows the dial for Southern Wastes even when you do not control the Southern Wastes.
- It is impossible to manipulate Winds for the 3 cities that belong to the Abyssal Glacier, because they do not have a province capital as far as Manipulating Winds goes.

This affects Winds of Magic even without Kairos and his Winds Manipulation (Crevasse follows WOM state of Southern Wastes instead of Abyssal Glacier), but its easiest to see it in the Winds Manipulation UI.
You can see in the screenshot that the Abyssal Glacier capital (Crevasse) is not actually a part of the same Wind of Magic rules as the rest of the Abyssal Glacier province (3 minor cities), and you can see the two dials that are linked.

_Also a minor issue but the order of the cities in the UI (province view) and the order of the cities on the campaign map does not match._

**Expected behavior**
Winds of Magic working properly for these two provinces, meaning Crevasse city should be tied to the Abyssal Glacier and not the Southern Wastes.

**To Reproduce**
1. Play as Kairos
2. Conquer at least one more city from the Abyssal Glacier province.
3. Open Winds of Magic manipulation in bottom right corner of UI
4. Notice you have a second dial which should not be there, and notice that increasing WOM on either dial affects the other, and notice that the 3 minor cities of Abyssal Glacier are not affected by either of these dials.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/200649433-308d1905-96a4-4c49-882e-dc19b0a34be5.png)

**Comment by Harmandodelavega** [comment]
#613

**Comment by Harmandodelavega** [comment]
The Road of Damnation one may bugged still but closing for now
