### ISSUE TITLE
Inconsistent skill parent requirements for capstones (Light Archmage and Tzeentch Lord/DaeP)

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#58]
Anomalies in skill nodes for magic trees and how many previous points are required

Archmage, _only light_: requires 2 points for GAConduit instead of 4
Kairos: ditto, but we ignore this due to LL privilege? 
Tzeentch, sorc lord and daemon prince: require 6 points for the middle skill instead of 4 like everybody else

Notice that num parent is usually higher when there are more skills than usual in the previous group (e.g. Wurrzag needs 8 points for his Arcane Conduit because he has all previous skills grouped in a single lot rather than in two), but this is not the case for the mages above.

Possibly more anomalies like those.

**Comment by Cataph** [comment]
Pack on discord https://discord.com/channels/373745291289034763/581350140942483456/1015284005316345907

**Comment by mfvreeland** [comment]
Partially fixed in 4.0 (only for Tzeentch Sorcerer Lords; Light Archmage and Tzeentch Daemon Princes still wonky)
