### ISSUE TITLE
Unholy Lodestone Carts/Mounts have bugged mass.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#588]
battlefield_engines linked to a different battle entity with 100 mass

**Describe the bug**
3 Corpse Cart variants exist: regular, Unholy Lodestone and Balefire.
Regular and Balefire have a mass of 1900.
Unholy Lodestone has a mass of only 300.

**Expected behavior**
All 3 corpse cart variants should have the same mass of 1900.
Does not make sense that adding an Unholy LodeSTONE to a Corpse Cart would make it over 6 times lighter.

**To Reproduce**
1. Check the corpse cart Unholy lodestone mass in the Skirmish vs AI menu, or the twwstats website

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/201467947-fd1d4448-b267-45b9-a914-6bd75662301f.png)

**Comment by Harmandodelavega** [comment]
@Bogdanov89 can I ask you to check mounted Necros and Helman Ghorst mass too?

**Comment by Bogdanov89** [comment]
@Harmandodelavega   
Master Necromancer (lord) and Necromancer (hero) have only 1000 mass on Corpse Cart (Unholy Lodestone), so that will need fixing as well.
If they are mounted on the other variants of Corpse Cart (regular & Balefire) their mass is always 2600 each. 
Ghorst has mass of 2600 on his only mount (unique cart).

**Comment by mfvreeland** [comment]
Good catch. I found the issue, db mistake in the `battlefield_engines` table. Will fix.
