### ISSUE TITLE
Huntsmarshal's Expedition AI does not start with heroes

### ISSUE THREAD

**Issue by Kitpony** [chadvandy/cbfm_wh3#594]
Not so much a bug as a feature that was implemented in a Mortal Empires patch and never carried forward into Immortal Empires.

Specifically --> The Huntsmarshal’s Expedition will now start with Wulfhart’s Hunters when an AI faction
https://www.totalwar.com/blog/total-war-warhammer-ii-the-total-waaagh-update/

The ai never seems to do the quests/recruit the 4 heroes in immortal empires.

**Comment by Harmandodelavega** [comment]
Sorry to bother @Drazhir2 did you check these by chance?

**Comment by Drazhir2** [comment]
just tested it, it works fine, to note they don't start with them but unlock them automatically at:
turn 1 - hertwig
turn 10 - jorek
turn 20 - kalara
turn 30 - rodrik
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/5b4d6189-c0dd-444a-a39e-d9868f9df4c8)
