### ISSUE TITLE
Some agents that should not equip items now do

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#595]
hef_shadow_walker can equip items+... probably ritual like heroes
Mostly a problem for AI which wastes items on it
agent_subtype has a check box for can equip ancillaries, though if it's up to this table pretty much every agent can equip items, which means ritual agents, etc.

**Comment by Mandras2** [comment]
Felix also has mentor skill

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/1903
