### ISSUE TITLE
Slave Pens slaves-per-turn doesn't work for Dark Elves

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#6]

**Comment by chadvandy** [comment]
Fix - zzz_cbfm_def_slaves_effect

**Comment by Dandoz666** [comment]
Just tried it with Morathi still getting no slaves when building slave markets

**Comment by chadvandy** [comment]
def works
![image](https://user-images.githubusercontent.com/39225561/189261763-0a0ad0ac-9b61-41eb-b468-cfc7793ee636.png)
![image](https://user-images.githubusercontent.com/39225561/189261782-74efdf68-6487-47c6-b009-823bd6e46e2f.png)

**Comment by chadvandy** [comment]
-8 from Port building

**Comment by Sensang** [comment]
Yea sorry you have to end turn to see it.. my bad.

**Comment by chadvandy** [comment]
fixed by CA, closing it out
