### ISSUE TITLE
Boon of Chaos "Attuned to Chamon/Uigu/Shyish" does not unlock on heroes

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#602]
does not trigger unless it's a lord

**Comment by mfvreeland** [comment]
Seems they account for embedded heroes since altering the script to account for the new Tzeentch Exalted Hero, but I haven't tested it.

**Comment by mfvreeland** [comment]
Confirmed fixed in my current campaign
