### ISSUE TITLE
Skavenslaves and Clanrats with swords use wrong weapon icon on unit card and Banner Art

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#609]
WH2 fix https://trello.com/c/hGGxUNs8/296-skavenslaves-and-clanrats-use-wrong-icon-and-banner-art 
https://github.com/chadvandy/community_bugfix_mod/commit/f99bed9d5dd400037d385df4e71106fbd8512de0

**Comment by Drazhir2** [comment]
Fixed in 4.2.0
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/78987803-2f80-4944-97f2-c4d2eba36dfb)
