### ISSUE TITLE
Vampire Count select minor factions can't build some high tier buildings

### ISSUE THREAD

**Issue by Aexrael** [chadvandy/cbfm_wh3#61]
factions...
wh2_main_vmp_necrarch_brotherhood
wh2_main_vmp_strygos_empire
wh2_main_vmp_the_silver_host
wh3_main_ie_vmp_sires_of_mourkain

cannot build...
wh2_main_vmp_terrorgheists_1
wh_main_vmp_forest_2
wh_main_vmp_vampires_1
wh_main_vmp_vampires_2

**Comment by Harmandodelavega** [comment]
fixed by this?  #449

**Comment by Harmandodelavega** [comment]
@Aexrael  are you sure it's a bug?
read above comment too pls

**Comment by Harmandodelavega** [comment]
in 4.0 they removed the terrorgheist building from some more minor factions so it's confirmed
