### ISSUE TITLE
Nurgle Ancillaries Comptroller and Preacher of Decay don't work for Legion of Chaos

### ISSUE THREAD

**Issue by TotalWarhead** [chadvandy/cbfm_wh3#610]
They both only apply to Nurgle special recruitment

You can the effects not applying at the 32:05 time mark of the video below:

https://www.youtube.com/watch?v=0bRt2jjMT0I

**Comment by mfvreeland** [comment]
Preacher of Decay apparently fixed, Comptroller not fixed
