### ISSUE TITLE
Vampire Count incident points at incorrect agent_type

### ISSUE THREAD

**Issue by Aexrael** [chadvandy/cbfm_wh3#62]
Incident 25343 wh_main_incident_vmp_summon_the_barrow_lords points at Spy instead of Champion, as this is the wight king incident

**Comment by Harmandodelavega** [comment]
https://trello.com/c/GSSnsH8Z/259-whmainincidentvmpsummonthebarrowlords-is-configured-incorrectly

if anyone wants to grab the pack

Credit to Aexrael

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/commit/a22f9975ba5bb3634eec02c465bb9777313b03bf
