### ISSUE TITLE
In "Lost God" campaign the unit card for Yuri is a goblin, and icon above head is an Ice Witch

### ISSUE THREAD

**Issue by Jdent01** [chadvandy/cbfm_wh3#624]
**Describe the bug**
In "Lost God" campaign the unit card for Yuri is a goblin, and icon above head is an Ice Witch

**Expected behavior**
Yuri should have his custom unit card and the icon above his head should his custom icon or a Boyar icon.

**To Reproduce**
Start a "Lost God" prologue campaign.
![LostGodBug](https://user-images.githubusercontent.com/118621839/202859402-9c3d8636-6fa0-438b-bddb-bd89c11f59a8.jpg)

**Screenshots**
If applicable, add screenshots to help explain your problem. The more in-game text we can see to reference the details in question, the better.

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**

**Comment by Harmandodelavega** [comment]
presumed fixed
