### ISSUE TITLE
Dark Elf AI unable/unwilling to recruit black arks

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#626]
mby fixed in 4.1

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed an issue where AI-controlled Dark Elves weren’t recruiting Black Arks."

**Comment by Drazhir2** [comment]
Fixed
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/128c9263-77d7-4675-b8d7-69cf594c9825)
