### ISSUE TITLE
Red Duke lacks mutually exclusive skill lock

### ISSUE THREAD

**Issue by Aexrael** [chadvandy/cbfm_wh3#63]
Blooddragon lords have mutually exclusive skills wh2_dlc11_skill_vmp_bloodline_blood_dragon_unique_grave_sentinels and wh2_dlc11_skill_vmp_bloodline_blood_dragon_unique_doomrider, but the Red Duke was never configured for this setup and it stands to reason he probably should.

**Comment by mfvreeland** [comment]
Does it stand to reason? Red Duke is a named character, whereas generic Blood Dragon lords are not. Named characters typically get more powerful bonuses than generic characters. You could be right, but I would want to get confirmation from CA on this one.

**Comment by Harmandodelavega** [comment]
pls don't fix this

**Comment by mfvreeland** [comment]
I think we've decided not to fix this.
