### ISSUE TITLE
Invocation of Dazh does not give Boris any supporters (fix in comments)

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#635]
Flying Fox has a fix, although it overwrites the devotion script

pack here: https://discord.com/channels/373745291289034763/581350140942483456/1030789516157517826

**Comment by LordOmlette** [comment]
This has been fixed in 2.4.0.  Instead of checking explicitly for Boris, Tzarina, or Rasputin, the code now looks to see if the culture is Kislev and whether the player is human. This could be a subtle nod to the possibility of more Kislev factions in the future.
