### ISSUE TITLE
Kislev missing 2 Tzar Guard on Bokha Palace garrison (by No.213)(momentarily botched)

### ISSUE THREAD

**Issue by atthias** [chadvandy/cbfm_wh3#64]
so I cannot code but I stumbled across this mod 

problem seems to be that bokha palace is supposed to add tsar great weapon tsar guard besides the sword and shield ones but that does not happen 

the mod author was so kind to include pictures and descriptions in the mod description on steam link below 

https://steamcommunity.com/sharedfiles/filedetails/?id=2818796230

if needed I can ask if you guys can incorporate the work in CBFM

apologies if this is not what you want I cannot code not can I read it but since you prefer to have all issues in one place I will drop them here if I stumble across other bug fix mods

**Comment by mfvreeland** [comment]
![image](https://user-images.githubusercontent.com/112144702/192109999-9e312dbc-39d2-46d8-85aa-611832fc7301.png)

To fix this 4realz, we just need to swap out every "tsar" with "tzar"
