### ISSUE TITLE
Kemmler cannot summon Krell in the Castle Artois battle map.

### ISSUE THREAD

**Issue by WesleyShaver** [chadvandy/cbfm_wh3#653]
Kemmler cannot summon Krell in the Castle Artois battle map.  It always says that it requires a ground area or something like that.

**Comment by Drazhir2** [comment]
This one is fine in vanilla.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/34e96ff0-efcd-4074-95a7-aa71810c77f3)

Summoned Krell:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/c4ac729a-9645-4ebe-837b-0f1e128101fd)

Regular behaviour of spell preview too, for both Krell and Raise Dead:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/59b6b7b5-2062-4cea-9161-36e6239ccde6)
