### ISSUE TITLE
Wood elf landmark threllock in vauls anvil cannot be built

### ISSUE THREAD

**Issue by garland7** [chadvandy/cbfm_wh3#657]
![화면 캡처 2022-12-02 092049](https://user-images.githubusercontent.com/40320450/205186843-33a80266-cfe8-43ed-ba3d-b070cb45d20d.jpg)
![화면 캡처 2022-12-02 092115](https://user-images.githubusercontent.com/40320450/205186853-95f6ae10-94f3-4935-bbb3-857089553631.jpg)
When I play as Argwylon, threllock
 do not appear in the building chain and cannot be built.

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/432
