### ISSUE TITLE
Nakai's Kroxigor and Sacred Kroxigor units use wrong 3D porthole

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#659]
https://trello.com/c/v2tE7dFb/245-nakais-kroxigor-and-sacred-kroxigor-units-use-wrong-3d-porthole

**Comment by Harmandodelavega** [comment]
They touched unit_porthole_camera_settings_tables for sacred kroxigors, it's another table but it might have done something

**Comment by Drazhir2** [comment]
Still broken in 4.1.1, from left to right nakai/regular krox/sacred krox
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/cb4cf4de-b8a4-44a2-9bdf-f21109e5d50f)
