### ISSUE TITLE
Vampire Counts have some missing permissions from units_to_groupings_military_permissions

### ISSUE THREAD

**Issue by Aexrael** [chadvandy/cbfm_wh3#66]
wh_dlc04_vmp_cha_helman_ghorst_0
wh_dlc04_vmp_cha_helman_ghorst_1
wh_dlc04_vmp_cha_master_necromancer_1
wh_dlc04_vmp_cha_master_necromancer_2
wh_dlc04_vmp_cha_master_necromancer_3
wh_dlc04_vmp_cha_necromancer_1
wh_dlc04_vmp_cha_necromancer_2
wh_dlc04_vmp_cha_necromancer_3
wh_dlc04_vmp_cha_strigoi_ghoul_king_0
wh_dlc04_vmp_cha_strigoi_ghoul_king_1
wh_dlc04_vmp_cha_vlad_von_carstein_0
wh_dlc05_vmp_cha_red_duke_0
wh_dlc05_vmp_cha_red_duke_1
wh_dlc05_vmp_cha_red_duke_2
wh_dlc05_vmp_cha_red_duke_3
wh_pro02_vmp_cha_isabella_von_carstein_0
wh_pro02_vmp_cha_isabella_von_carstein_2
wh_pro02_vmp_cha_isabella_von_carstein_4
wh2_dlc11_vmp_cha_bloodline_blood_dragon_lord_0
wh2_dlc11_vmp_cha_bloodline_blood_dragon_lord_1
wh2_dlc11_vmp_cha_bloodline_blood_dragon_lord_2
wh2_dlc11_vmp_cha_bloodline_blood_dragon_lord_3
wh2_dlc11_vmp_cha_bloodline_lahmian_lord_0
wh2_dlc11_vmp_cha_bloodline_lahmian_lord_1
wh2_dlc11_vmp_cha_bloodline_lahmian_lord_2
wh2_dlc11_vmp_cha_bloodline_lahmian_lord_3
wh2_dlc11_vmp_cha_bloodline_necrarch_lord_0
wh2_dlc11_vmp_cha_bloodline_necrarch_lord_1
wh2_dlc11_vmp_cha_bloodline_necrarch_lord_2
wh2_dlc11_vmp_cha_bloodline_necrarch_lord_3
wh2_dlc11_vmp_cha_bloodline_strigoi_lord_0
wh2_dlc11_vmp_cha_bloodline_strigoi_lord_1
wh2_dlc11_vmp_cha_bloodline_von_carstein_lord_0
wh2_dlc11_vmp_cha_bloodline_von_carstein_lord_1
wh2_dlc11_vmp_cha_bloodline_von_carstein_lord_2
wh2_dlc11_vmp_cha_bloodline_von_carstein_lord_3
wh2_dlc11_vmp_inf_crossbowmen
wh2_dlc11_vmp_inf_handgunners

The following have been omitted from the table, while some shouldn't be an issue because recruitment is via a special function, others should likely be there.

**Comment by Cataph** [comment]
Should be noted that that table's use for character is either nihil or unknown or only causes bugs.
The sylvanian levies don't need to be there either since they're added like RoRs.
