### ISSUE TITLE
Skink Oracle has a Priest 3D porthole on campaign map

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#660]
[Skink Oracle has a Priest 3D porthole on campaign map](https://trello.com/c/xfuJKq3D/350-skink-oracle-has-a-priest-3d-porthole-on-campaign-map)

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed the Skink Oracle Hero using the wrong model in the porthole."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1.
