### ISSUE TITLE
Chaos techs based on number of active Chaos Gifts have non-persistent effects

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#67]
https://forums.totalwar.com/discussion/318589/vilitch-tech-temple-of-tzeentch-is-bugged#latest

The phys resist randomly disappears when loading a save and after battles. Don't know if it actually works or if it's visual

**Comment by mfvreeland** [comment]
This is tricky. Everything appears to be correct in the DB, but something must be breaking in battle specifically that prevents the real effect from being applied. I wonder if the other Chaos champion characters have a similar problem with their respective techs like this? They all seem to have one tech that applies an effect to all units based on active Chaos gifts, and all are set up similarly in the DB.

**Comment by ArmourYoshi** [comment]
Can confirm that the other Champions are impacted by this.
https://www.youtube.com/watch?v=ATGrscKsODg

**Comment by mfvreeland** [comment]
@ArmourYoshi Thanks for confirming that. Unfortunately, this does not appear to be a DB issue but rather a problem with the way the game is handling the "additional effect lists" that come from these technologies. This feels similar to the old Ataman problem from earlier in WH3's lifecycle in which the province effects from a Kislev Ataman would work when first unlocked, but then would get reset and would need to be triggered again. 

The correct fix for this will have to come from CA, but in the meantime, it may be possible to script a workaround that would check if these effects should be unlocked every time a battle starts or turn ends and re-apply them as necessary. If I get some time later, I will give this a go.

**Comment by mfvreeland** [comment]
Nothing mentioned in patch notes about this, so I am assuming this fix should stay in CBFM for now.

**Comment by mfvreeland** [comment]
Still not fixed in 3.0, keeping our fix in the mod.

**Comment by mfvreeland** [comment]
Still not fixed in 4.0, keeping our fix in the mod.

**Comment by mfvreeland** [comment]
Not fixed in 4.2

**Comment by mfvreeland** [comment]
FYI, this is still a problem in 5.0.2

**Comment by Drazhir2** [comment]
just dropping this here in case

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/db4ce398-26cb-4887-b854-a301446d260e)

might be a mod conflict but skimming through it looks like line 201 can return no value

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/fdc05e58-abf2-4312-b69e-1b6c9d634e9b)

**Comment by mfvreeland** [comment]
1.  I've never seen such a script break occur in any campaign since that script was released (in 2022), and it runs in every campaign regardless of what faction the player is using.
2. I don't see how that could return no value unless the Gifts of Chaos sets were messed with by another mod. If the number of active initiative is 0, it will return 0, not nil.

**Comment by Drazhir2** [comment]
Exhibit 2 of the same script break, if it's another mod doing it, I'd like to know which one (mayyybe we can fix it) but not possible without comparing mod lists of users having this issue.

![Screenshot_2024-07-09_165433](https://github.com/chadvandy/cbfm_wh3/assets/135981276/4b0406f2-e3c1-408e-8679-b0ac2c649f34)

**Comment by mfvreeland** [comment]
@Drazhir2 I am pretty sure it's this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=3227088267

**Comment by Drazhir2** [comment]
He will be looking into it

![image](https://github.com/user-attachments/assets/0c4a792c-5ffd-4ddf-ba83-4011cc9c686d)

**Comment by mfvreeland** [comment]
Cool. I'm happy to help with it -- it's probably going to be somewhat annoying because our fix essentially replaces the entire system.

**Comment by mfvreeland** [comment]
At long last, this has been fixed in 5.3. The only minor issue remaining is that they left the tooltips for the Slaanesh and Khorne corruption bonuses as +2 per gift, when in reality the bonus for all factions is +1 per gift (Tzeentch and Nurgle show the tooltip correctly). I will leave a small fix for this, but the main script and supporting db entries will be removed.
