### ISSUE TITLE
Undivided Daemon Prince gets Mortal Blow ability twice in unique skills

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#68]
[reddit link](https://www.reddit.com/r/totalwar/comments/x3jh6y/undivided_daemon_prince_lord_in_belakors_faction/)

Skills:
wh3_dlc20_skill_daemon_prince_undivided_special_1
wh3_dlc20_skill_chs_undivided_unique_1

skill node set: wh3_dlc20_skill_node_set_chs_daemon_prince_undivided

Both enable Mortal Blow. The special one also adds aura size. They're not exclusive, so one of the two is a complete waste of points.

Can't fix without taking a design choice in a replacement. Replacement skill will also 99% require a point to be spent in it again.

**Comment by Harmandodelavega** [comment]
fixed in 2.2
