### ISSUE TITLE
More Typos

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#682]
https://trello.com/c/VxOHPEYS/182-rcsc-skill-warriors-crest-apostrophe-typo
https://trello.com/c/Tq3krCqa/168-cobra-mace-of-mazdamundi-quest-description-loc-mistake mazdumandi
https://trello.com/c/t8vkDSVZ/139-def-redline-rank-7-skill-loc-missing-a-comma
https://trello.com/c/4JrAZ22j/22-fiends-of-the-frontier-event-has-typo-would-be-never-be-found-instead-of-would-never-be-found
more in new commit description

**Comment by floskan** [comment]
Removed fixed stuff
