### ISSUE TITLE
Boon of chaos "Slayer of champions" now unlocks with only two characters present

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#69]
This fix is bound up with #44 even if that is fixed, doesn't cause any problems

![20220902153745_1](https://user-images.githubusercontent.com/34427023/188158636-847e848f-1f6b-4e54-ba6c-806510bd8528.jpg)

This is the boon in question, the requirement is to beat an army that has 3 characters in it.

[Shadow Legion_Quick Save.722786269650.zip](https://github.com/chadvandy/cbfm_wh3/files/9478286/Shadow.Legion_Quick.Save.722786269650.zip)

Here's a save of an ambush battle vs a lord + 2 heroes but the battle doesn't give the boon as expected

**Comment by mfvreeland** [comment]
Thanks for providing a save. I believe this is a very similar problem to what we saw with the "Impenetrable" boon, which I was just looking at. I'll work on this.

**Comment by Harmandodelavega** [comment]
Let's not change currently in use labels pls @mfvreeland

**Comment by mfvreeland** [comment]
I just noticed that CA fixed this in 4.1.4 with a new (and undocumented) campaign manager function (`cm:pending_battle_cache_num_attacker_embedded_characters`), but it appears they are testing for two characters being present rather than the three required by the boon description. This should be tested, but it looks like a new (albeit minor) bug.

**Comment by Drazhir2** [comment]
Yeah new bug, they don't follow their own comments:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/3cda9dfe-6612-4bd4-badc-15df316af775)

**Comment by Drazhir2** [comment]
It's fine, read the comment:

-- count the general as one character, so need to have 2 or more embedded characters to pass this test

They're are testing for number of embedded char strictly higher than one.

**Comment by mfvreeland** [comment]
Ok yeah I glossed over the part where the general automatically counts as one, so they only need to find two. It should be fine.
