### ISSUE TITLE
belegar's character trait, to grant vanguard to all armies faction-wide in the underway, doesn't work

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#7]
Fixed by JerreyRough

https://discord.com/channels/373745291289034763/581350140942483456/1012116445750112316

**Comment by chadvandy** [comment]
zzz_cbfm_fix_belegar_underway_trait

**Comment by Cataph** [comment]
as far as I can tell this works fine so IDK

**Comment by chadvandy** [comment]
removed from retail!
