### ISSUE TITLE
Wargrove of Woe (Drycha)'s Unique Tech Does Not Give Physical Resist/does not mention feral bears

### ISSUE THREAD

**Issue by Napstacked** [chadvandy/cbfm_wh3#70]
"Wisdom of the Wildwoods" is a unique technology for Drycha that does not give physical resist to the faction's unique units as it says it does.

![image](https://user-images.githubusercontent.com/112709462/188169572-5a47244a-baa3-46fd-896f-7b7b6d9c2576.png)

(It also doesn't mention or include the new Feral Bears they added in Warhammer 3, which is probably a bug as well, given they're the only one left out.)

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2, should be removed

**Comment by Harmandodelavega** [comment]
Didn't actually fix the localization

**Comment by mfvreeland** [comment]
Needs loc fixed, db changes reverted
