### ISSUE TITLE
Invasion strength of the silent sanctum armies not increasing correctly

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#706]
WH2
>Fixes a bug regarding the strength of the silent sanctum ambushes of oxyotl.

>These are supposed to get slightly stronger every 20 turns. However this fired only if on the 20th, 40th, 60th, .. turn you succesfully ambushed someone. Also it would increase in strength multiple times if you managed to successfully ambush multiple factions in these turns.

>These two things are patched out with the mod. Instead the strength is calculated each time by the number of turns that has passed.

by Photon

https://github.com/chadvandy/community_bugfix_mod/commit/a6c797a9ffba235023a91c82f0c155075cf7caa7

"For what it's worth (and this is probably obvious to people with more experience but I had to learn it the hard way), you can't just take the linked fix file and use it since things in the sanctum script have changed since game 2. Taking just the important part of the code change to get_invasion_power_by_turn() and putting it into the vanilla game 3 sanctum script does appear to work fine from my testing so far. Post turn 40 I've started to see ambushes with feral cold ones, bastilodons, terradon riders, chameleon skinks, etc.

by NRFB

**Comment by mfvreeland** [comment]
I will take a stab at this tomorrow. I would like to do it in a way that doesn't completely overwrite the default script, but it's gonna be slightly annoying with all of the local functions. It should be doable, though.

**Comment by floskan** [comment]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/6118-oxyotl-ambush-current-power-level-not-being-saved?page=1 this is related to this right? Does your fix persist through save load?

**Comment by mfvreeland** [comment]
This fix recalculates the ambush level each time the game is loaded. It's based on the current turn number. So no, strictly speaking it isn't being saved, but it doesn't need to be. This fixes the issue with it not working.

**Comment by mfvreeland** [comment]
CA didn't really fix the core issue here.
