### ISSUE TITLE
First blood voyage before turn 30 gets 18 instead of 19 units and throws a script error

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#707]
WH2 fix by Sm0kin

script is wh2_dlc_hellebron.lua

```
function death_night_setup_army()
	-- First army spawned by Death Night
	random_army_manager:new_force("death_night_army_1");
	
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_main_def_inf_har_ganeth_executioners_0", 2);
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_dlc10_def_inf_sisters_of_slaughter", 2);
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_main_def_cav_cold_one_knights_1", 2);
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_main_def_mon_black_dragon", 1);
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_main_def_mon_war_hydra", 1);
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_main_def_inf_bleakswords_0", 4);
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_main_def_inf_dreadspears_0", 4);
	random_army_manager:add_mandatory_unit("death_night_army_1", "wh2_main_def_inf_witch_elves_0", 2);
 -- more code
end
```

The death_night_army_1 force includes only 18 units, if random_army_manager:generate_force("death_night_army_1 ", 20) is called and a unit_list with 19 units should be returned the script returns a string with 18 units and throws an error.

Solution:
Add one more unit or mandatory_unit to the death_night_army_1 force. E.g. one wh2_main_def_inf_bleakswords_0 (analog to the mp army string).

Ideally the random_army_manager:generate_force should check if the unit_list for a force is empty, e.g.:

```
if #self.force_list[i].units > 0 then
	local unit_index = cm:random_number(#self.force_list[i].units);
	table.insert(force, self.force_list[i].units[unit_index]);
else
    out.design("Random Army Manager: Random Force for army [" .. force_key .. "] can't reach the demanded size [" .. unit_count .. "] because no units_keys where added to the units table.");
end
```

https://github.com/chadvandy/community_bugfix_mod/commit/97951b227334696d2df7cf70bfe0741ff15870f7

**Comment by Harmandodelavega** [comment]
hey @mfvreeland can you take a look at this? 
fec3b94

**Comment by mfvreeland** [comment]
@Harmandodelavega This fix defines a function that is never called, so it wouldn't do anything. That said, it looks like the main Hellebron script has been updated since WH2, and there doesn't appear to be any place where it will attempt to generate `death_night_army_1` with 20 units. It only generates that force with the default number of units, which should spawn the 18 specified without error. I think the bug may be considered fixed by CA unless there is in-game evidence of it still occurring.

**Comment by Harmandodelavega** [comment]
thx
