### ISSUE TITLE
Various healing cap issues

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#72]
https://steamcommunity.com/sharedfiles/filedetails/?id=2855902814

And here's a mod that fixes several of them, for reference

**Comment by bingo12345** [comment]
is this true? it seems quite serious.

**Comment by floskan** [comment]
Yeah it's the same mod with just the metal archmage fix removed.

**Comment by mfvreeland** [comment]
We have permission to incorporate this mod into cbfm from the mod author. I will add tomorrow.

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2. Todo: remove from cbfm

**Comment by chadvandy** [comment]
removed from CBFM!
