### ISSUE TITLE
The AI won't get Ariel if the player starts as Drycha

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#725]
WH2 fix
https://github.com/chadvandy/community_bugfix_mod/commit/697132fa123d10de092fc416cc30cd251425b9d0

**Comment by Drazhir2** [comment]
I fail to see how a **Fix for You can't finish Drycha's quest and obtain Coeddil if you got her via confederation** helps with **The AI won't get Ariel if the player starts as Drycha** looks like 2 entirely different issues.

For the title of this issue, I think it currently works fine, just started a Drycha campaign and the AI listener for the Ariel turn 20 unlock is properly created so there's no reason why the AI wouldn't get her at turn 20.

**Comment by Drazhir2** [comment]
AI getting Ariel while playing as Drycha
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/0d601326-44d3-4225-a873-04d3af564535)
