### ISSUE TITLE
Ulrika, Gorduz, Ghoritch not spawning for AI

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#726]

**Comment by Drazhir2** [comment]
We've seen in #990 that Ariel does in fact spawn for the AI (even when she shouldn't, which we have fix for)

**Comment by Drazhir2** [comment]
So I decided to take a look at all of these little legendary puppies.

The turn based ones spawn for the AI except Gorduz (no idea why yet)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/39729ebb-cb85-4e51-b46d-52c0f59dec09)

There was a typo and a script issue for the rank based ones, I have the fix to make them spawn properly for the AI
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/aea1b145-e5a7-4289-8065-7de18f1ac83f)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/152713c3-2ff9-4f48-a7b6-5dc13f53e59c)

Now there's only little Gorduz left to investigate.

**Comment by Drazhir2** [comment]
For Gorduz I had to rewrite add_building_completed_listeners so it behaves like the others (setup player listeners + return to avoid AI listener and adding spawn_hero_for_ai so it works for the AI):
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b98ea729-e38d-4cb9-aa16-43105e429746)

Now it works for both AI and player.

**Comment by Drazhir2** [comment]
Here are the 2 fixes (rename to .pack)
[zzz_cbfm_legend_ai_rankup.patch](https://github.com/chadvandy/cbfm_wh3/files/12054183/zzz_cbfm_legend_ai_rankup.patch)
[zzz_cbfm_gorduz_ai_spawn.patch](https://github.com/chadvandy/cbfm_wh3/files/12054184/zzz_cbfm_gorduz_ai_spawn.patch)

**Comment by floskan** [comment]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1438-ghoritch-doesn-t-spawn-afther-the-whip-quest?page=1

"Ghoritch just doesn't spawn after his quest battle in IE/WH3. I tried doing it with/without mods, reloading, restarting the campaign and doing it through teleport or manually entering the zone."

**Comment by Drazhir2** [comment]
I saw a similar report about Ghoritch not spawning on reddit a few days ago, worked for me so I don't know if there are more factors at play.

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/e6ef3a7f-5f40-4dd5-8dfb-871688eec486)

**Comment by mfvreeland** [comment]
@Drazhir2 Did you autoresolve that battle? More information from Steam comments: "I have other mods so I don't think I'm a good test case, but I just did the Ghoritch battle as Throt twice. On a manual battle, he never showed up after I won; but after an AUTORESOLVE victory, he appeared.

**Comment by Drazhir2** [comment]
I did AR the battle for my first test.

Playing it manually does indeed cause the issue, and even weirder after the battle I could see for a few seconds the campaign model of the WoC army I just fought in the qb then it disappeared, completed the quest and didn't spawn Ghoritch.

Somehow I doubt this is due to the legendary character script itself, first time I see that weird behaviour with a qb that briefly spawns the lord campaign model after battle.

Coeddil is the other LH that spawns after a qb, might be worth it to try that one to compare.

**Comment by mfvreeland** [comment]
> Playing it manually does indeed cause the issue, and even weirder after the battle I could see for a few seconds the campaign model of the WoC army I just fought in the qb then it disappeared, completed the quest and didn't spawn Ghoritch.
> 
> Somehow I doubt this is due to the legendary character script itself, first time I see that weird behaviour with a qb that briefly spawns the lord campaign model after battle.

I've seen that before in other quest battles or encounters at sea. The script is the only thing that spawns Ghoritch AFAIK, so I imagine it must be failing somehow. That it's only a manual battle triggering it is interesting, though.

**Comment by mfvreeland** [comment]
One thing to note is that CA apparently removed Coeddil spawning from this script. The mission it refers to no longer exists; the function that actually spawns Coeddil after completing the quest is in the World Roots script. I can't tell why the Legendary Heroes script would fail here. My only wild guess is that it's somehow not putting the listener up again soon enough following the conclusion of the QB, but idk why that would be.

**Comment by Drazhir2** [comment]
Copying what I posted in the other issue:

After running the LH script with some logging, the mission listener is properly created but it seems the MissionSucceeded event does not fire after the manually fought quest battle (you can see it firing turn 1 when I kill the first enemy) even though the mission success pop-up shows up and you get the magic item.

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/862c5132-e17b-405d-adbd-5a24bfecaf34)

It's a weird one but I don't think the LH script itself is the cause.

**Comment by Drazhir2** [comment]
Time to start playing with listeners and qb missions, something doesn't smell right
