### ISSUE TITLE
Brt vow bug at high chivalry

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#739]
https://trello.com/c/I8nG0p3j/57-brt-pledge-bug-at-high-chivalry#

sm0kin [Feb 12, 2020 at 7:28 PM](https://trello.com/c/I8nG0p3j/57-brt-pledge-bug-at-high-chivalry#comment-5e4443c424f7c88e410342f3)
Same problem as this:
[Brt vow/troth bug](https://trello.com/c/b90ESJXA/469-brt-vow-troth-bug)
The script doesn't check if a lord already has a pledge (knights/questing/grail).

E.g. you recruit a lord at level 1, finish the pledge to order(knights) and the pledge to campaign(questing). Then once you reach >800(only knights vow) or >1600 chivalry (knights and questing vow) you disband the lord and wait for him to return. Then he'll also have the pledge to knowledge(knight) and the pledge to protect(questing) trait from the global chivalry bonus.
-> all knights and questing vow unit are upkeep free

https://github.com/chadvandy/community_bugfix_mod/blob/master/script/campaign/mod/fix_multiple_vows.lua

**Comment by mfvreeland** [comment]
Wasn't this fixed in 2.3? I haven't encountered yet in my ongoing Bretonnia campaign, but I will keep an eye out for it.

**Comment by Harmandodelavega** [comment]
never heard this reported since wh3
