### ISSUE TITLE
Necrotect unique skill doesn't increase tomb scorpion capacity 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#75]
https://www.reddit.com/r/totalwar/comments/x46gyi/_/

Editor's Note: character_to_faction_unseen scope may be the issue, for this and other skills

**Comment by Harmandodelavega** [comment]
actually a joke I think

**Comment by floskan** [comment]
No, look at the Second screenshot

**Comment by floskan** [comment]
It was a pun, sure, but necrotects doesn't actually increase tomb scorp capacity

**Comment by Harmandodelavega** [comment]
I was watching a Legend stream and the innate trait for Tomb Scorpion was definitely working, the only thing different between those two skills is the scope, in which case all character_to_faction_unseen scopes for characters should be bugged

**Comment by Harmandodelavega** [comment]
Also I'm pretty sure Settra's unit cap skill works and has that scope so I'm at a loss

**Comment by mfvreeland** [comment]
Stumped.
