### ISSUE TITLE
Added missing garrisons (basic) to forts/gates/bastions for Ogres and Welves

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#754]

**Comment by Harmandodelavega** [comment]
They fixed just Ogres

**Comment by Drazhir2** [comment]
they fixed both:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b37e034a-37fe-4d07-b60e-53aafbe88dee)

**Comment by Harmandodelavega** [comment]
Yeah figured it out later
