### ISSUE TITLE
Unrecruited Lords with Loyalty when confederated always have 0 loyalty

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#761]
4.0 edit; Fixed issues with character loyalty when getting reassigned to a faction, closing until we get new reports

https://youtu.be/5fDT3IEGBJk?t=8348

https://forums.totalwar.com/discussion/321019/dark-elf-confederation-loyalty-bug
https://forums.totalwar.com/discussion/322066/morathi-gets-zero-loyalty-lords-when-confederating

**Comment by allenhu0912** [comment]
This still seems to be an issue even though the changelog says it was fixed. Just confederated Karond Kar:

![20230528115246_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/0c202c55-67eb-4991-87cc-52fd46669c0f)

**Comment by allenhu0912** [comment]
This seems to still be an issue with lords that are wounded or otherwise not recruited when you confederate a faction, but I'm not completely sure.

**Comment by mfvreeland** [comment]
Still an issue?

**Comment by allenhu0912** [comment]
Not a thing anymore I think, it was fixed some time ago and it has worked correctly in my DE campaigns.

**Comment by mfvreeland** [comment]
Fixed at some point
