### ISSUE TITLE
Empire politics fixes

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#77]
- unlocal the table
- add stuff for Gelt's faction
- provinces are missing

**Comment by gmoulin** [comment]
I would add the following:
- recreating a dead imperial count faction by liberating a region does not add the faction to the diplomacy screen list. The faction does not get a leader and does not recruit an army
- the fealty increase change per turn and count is 5% per tooltip when the imperial authority is positive (>0). In a 50+ turn campaign, it never triggered once. Something seems really bugged.

**Comment by chadvandy** [comment]
First isn't fixable, I'll track the latter.

**Comment by Harmandodelavega** [comment]
https://trello.com/c/6UgcSaKK/237-missing-demand-return-dilemmas-for-pfeildorf-and-steingart
https://trello.com/c/q9c8prs0/227-no-fealty-bonus-for-returning-reinstating-pfeildorf-steingart
https://trello.com/c/ZPuKwoKX/119-missing-option-to-resurrect-golden-order-when-capturing-pfeildorf

**Comment by sm0kin** [comment]
Seems like the "wh2_dlc13_emp_elector_prestige_endgame_1" dilemma is also missing in wh3.

**Comment by mfvreeland** [comment]
Was this fixed in 2.2? Can this be removed?

**Comment by Harmandodelavega** [comment]
we're kind of using it as a catch all for all empire script bugs by now I think

> https://trello.com/c/6UgcSaKK/237-missing-demand-return-dilemmas-for-pfeildorf-and-steingart https://trello.com/c/q9c8prs0/227-no-fealty-bonus-for-returning-reinstating-pfeildorf-steingart https://trello.com/c/ZPuKwoKX/119-missing-option-to-resurrect-golden-order-when-capturing-pfeildorf https://trello.com/c/w7LLdxh2/140-empire-spy-guild-region-visibility-not-working-at- https://trello.com/c/IO2EBGVL/124-empire-interventions-take-an-already-recruited-lord-at-random-from-your-pool-and-kill-it-after-the-battle-is-done https://trello.com/c/OqBlEkbK/591-imperial-intervention-battle-targets-invalid-generals https://trello.com/c/Wd0CmYge/583-for-imperial-intervention-battle-the-ancillary-event-message-should-be-hidden https://trello.com/c/Xn4nV9xN/587-regions-in-the-bloodgrounds-can-be-returned-to-a-elector-count https://trello.com/c/SxrRwxWQ/355-empire-invasion-trespassing-bug https://trello.com/c/3meS7fEm/336-attacked-recently-returned-region-not-working-as-intended https://trello.com/c/EiMbh0YH/152-trespassing-penalty-after-returning-a-settlement-to-an-elector
> 
> old WH2 fixes

**Comment by Harmandodelavega** [comment]
Gonna close it and make a new issue
