### ISSUE TITLE
Cadai tech isn't providing the +1 forest health to all magical forests.

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#783]
Something around here prolly (worldroots_health_per_turn_all_regions)

-- High-level function for updating pooled resources
function Worldroots:update_worldroots_health()
	out("updating worldroots_health")
	local forests_list = self.forests
	local rites_completed = 0
	
	for forest_ref, forest in pairs(forests_list) do
		local glade_region_interface = cm:get_region(forest.glade_region_key)
		local primary_building_level = glade_region_interface:settlement():primary_slot():building():building_level()
		
		-- only go further if a player owns the glade
		if self:human_wood_elf_controls_glade(forest) and not forest.rite_completed and not forest.rite_active and not cm:is_new_game() then
			-- n.b. all negative factors need to go first otherwise you can be prevented from maxing out the bar!
			
			-- corruption
			if cm:get_total_corruption_value_in_region(glade_region_interface) >= self.corruption_threshold then
				Worldroots:add_pooled_resource_to_all_wood_elves(forest, "wh2_dlc16_resource_factor_corruption", self.corruption_penalty)
			end
			
			-- pacification
			local pacification_count, hostile_count = self:check_pacification(forest)
			
			Worldroots:add_pooled_resource_to_all_wood_elves(forest, "wh2_dlc16_resource_factor_hostile_regions", hostile_count)
			Worldroots:add_pooled_resource_to_all_wood_elves(forest, "wh2_dlc16_resource_factor_pacified_regions", pacification_count)
			
			-- technology
			local human_factions = cm:get_human_factions()
			
			for i = 1, #human_factions do
				local current_human_faction = cm:get_faction(human_factions[i])
				
				if current_human_faction:culture() == "wh_dlc05_wef_wood_elves" then
					local bv = cm:get_factions_bonus_value(current_human_faction, "worldroots_health_per_turn_all_regions")
					
					if bv > 0 then
						Worldroots:add_pooled_resource_to_all_wood_elves(forest, "technology", bv)
					end
				end
			end

**Comment by floskan** [comment]
Looks like this might have a scripted fix now?

**Comment by mfvreeland** [comment]
Looks like it. Fixed in 5.0.
