### ISSUE TITLE
Heals that resurrect used on full health units replenish ammo 

### ISSUE THREAD

**Issue by FormerDeveloper** [chadvandy/cbfm_wh3#79]
This issue was first identified in early access. The Liche Priest of Nehekhara's passive (The Restless Dead), which is supposed to restore health, will also add ammunition to single entity units - specifically the Casket of Souls (including Khatep's mount), the Screaming Skull Catapult, the Bone Giant, and the Warsphynx. Other ranged units do not appear to be affected. 

I suspect the issue is that the ability is supposed to restore figures at max health, but is instead adding ammunition if it's a single entity and there's no figures to restore. After some testing, it appears that it does not trigger additional ammunition if the unit is already damaged - only if the unit is at full health.

I did some looking around in the pack files and didn't see anything right off that looked wrong to me, but I'm admittedly not very familiar with how the unit abilities work. This may actually require a code fix from CA, but I'm putting here in case it's something that can be fixed in a mod.

**Comment by gmoulin** [comment]
It's not just single entity unit, but any undamaged unit. So skeleton archers, catapults, ...

**Comment by FormerDeveloper** [comment]
You're right, it also triggers for the catapults, which are multiple entities. For whatever reason I haven't seen it on any of the archers, though.

**Comment by Harmandodelavega** [comment]
Pretty sure it works for any resurrect effect, and only if the unit is full health

**Comment by FormerDeveloper** [comment]
Update: this appears to be fixed as of patch 2.2.0.
