### ISSUE TITLE
Hero movement on the campaign map is fixed at 100

### ISSUE THREAD

**Issue by FormerDeveloper** [chadvandy/cbfm_wh3#80]
Heroes on the campaign map have a movement range that's fixed at 100. It isn't changed by traits (like Strategist), followers, or anything else that I can tell.

I suspect that this is a code-level issue that may have to be fixed by CA; if so, feel free to close out this issue. For what it's worth, hero movement on the campaign map has been buggy in various ways since WH2.

**Comment by Harmandodelavega** [comment]
#119
