### ISSUE TITLE
Bretonnia AI lords skip vows when gaining multiple levels in one turn

### ISSUE THREAD

**Issue by mfvreeland** [chadvandy/cbfm_wh3#801]
When AI is controlling a Bretonnian faction, vows are granted automatically at XP levels. If the AI skips a level where this is supposed to occur, the vow never gets provided. The problem is straightforward in the vow script and can be fixed fairly easily.

**Comment by Harmandodelavega** [comment]
#716

**Comment by bingo12345** [comment]
is this fix affects heroes too? bretonnia heroes can have same bugs.(unchecked)

**Comment by mfvreeland** [comment]
@bingo12345 
Based on what I am seeing in the script, it doesn't appear that AI Paladins get vows at all. This is corroborated by #738 

I would say this is a separate bug, though.

**Comment by Harmandodelavega** [comment]
@mfvreeland this fixed too?

**Comment by mfvreeland** [comment]
@Harmandodelavega Looks like it should be, yeah. They basically took our fix and added it to the vanilla script.
