### ISSUE TITLE
Oxyotl is allowed to teleport an unlimited number of times per turn

### ISSUE THREAD

**Issue by trgeiger** [chadvandy/cbfm_wh3#81]
In WH2 Oxyotl could only use his teleportation mechanic once per turn. There seems to be no such limit in WH3. The other limitations seem to apply, such as not being able to teleport in hostile territory, although I haven't verified everything.

This allows him to complete all of his Old Ones missions in one turn which isn't ideal, and it's hard to remember if you already teleported in a turn if you're trying to keep track and not abuse the bug.

**Comment by chadvandy** [comment]
are any of the following conditions applied whatsoever? I don't see where they're hooked up if at all

![image](https://user-images.githubusercontent.com/39225561/191631854-2d594315-83f7-4787-8e27-731280878676.png)

**Comment by floskan** [comment]
> are any of the following conditions applied whatsoever? I don't see where they're hooked up if at all
> 
> ![image](https://user-images.githubusercontent.com/39225561/191631854-2d594315-83f7-4787-8e27-731280878676.png)

I doubt it, haven't tried the water one though

**Comment by trgeiger** [comment]
From playing, I know the latter 2 are enforced. You cannot teleport when in hostile territory or when at sea. You are allowed to teleport multiple times a turn, though.

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2
