### ISSUE TITLE
Issue with liberated/confederated factions that revive. Can't initiate diplomacy with them.

### ISSUE THREAD

**Issue by Test-Ing1234** [chadvandy/cbfm_wh3#82]
Like the title says, liberated factions, or confederated factions that respawn as rebels or get liberated cannot be double clicked on to engage in diplomacy with. Cannot find them as factions in diplomacy screen either. So for example, as The Empire, confederate Middenland, Middenland rebels spawn, you can't open diplomacy with them. Or, liberate them from ruins, cannot open diplomacy with them. Same thing if you go with the revive elector count option. https://forums.totalwar.com/discussion/319221/liberate-confederated-faction-bug <---Hopefully what Fifty Tifty says here will help with you guys being able to fix this bug

**Comment by chadvandy** [comment]
known, #2 can't fix
