### ISSUE TITLE
AI Greenskins do not use Waagh ability in battle

### ISSUE THREAD

**Issue by TotalWarhead** [chadvandy/cbfm_wh3#824]
I have not seen skarsnik faction nor 2 generic Greenskins faction pop their Waaghs in battle.

To confirm the AI got to 100% Waagh bar, I restarted a Thorgrim campaign and used the additional stats in FFA and domination mod, which shows Waagh percentage, and it reaches 100% yet the AI never used it in battle.

**Comment by Harmandodelavega** [comment]
#393
