### ISSUE TITLE
Monstrous Strength red line skill not working as it should

### ISSUE THREAD

**Issue by Torhelion** [chadvandy/cbfm_wh3#829]
While playing as Exiles of Khorne, the Chaos lord of Khorne's red line skill ''Monstrous Strength'' (+Weapon strength, +Melee attack for all non-daemonic war beasts, monstrous and monster units) does not apply its bonuses to Minotaurs of Khorne, even though Minotaurs of Khorne are monstrous units, not daemonic (if they were daemonic units, they would have the ''Daemonic'' icon at the bottom of their unit card like all other daemonic units).

Does the game for some reason classify Minotaurs as daemonic units? If they are not classified as daemonic units, then the ''Monstrous Strength'' red line skill should apply its bonuses to both anti-infantry and anti-large variants of Minotaurs of Khorne.

**Comment by floskan** [comment]
They are part of the daemonic red line buffs.

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/issues/459
