### ISSUE TITLE
Wurrzag's Colossal Warpaint skill that adds a physical resist buff applies twice to rogue idols

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#830]
Wurzag skill "wh2_dlc15_skill_unique_grn_wurrzag_colossal_warpaint" applies the effect "wh2_dlc15_effect_skill_physical_resistance_grn_trolls_giants_arachnorok_idol".
Set targets for the effect is "wh2_dlc11_grn_trolls_giant_arachnarok" and "wh2_dlc15_grn_mon_rogue_idol".
Rouge Idols (both base and ROR) are members of both groups; effect is applied twice.

**Comment by bingo12345** [comment]
https://youtu.be/1lGChvTT_6o?t=239

this is true.

**Comment by mfvreeland** [comment]
Notes list this as fixed in 3.0. Needs to be verified.

**Comment by mfvreeland** [comment]
Verified fixed, removing from CBFM.
