### ISSUE TITLE
Red skill "Savage Bloodlust" not affecting any units (Tzeentch lords)

### ISSUE THREAD

**Issue by Bebelmondo** [chadvandy/cbfm_wh3#84]
The second skill in the red line named "Savage Bloodlust" is supposed to give armour and charge bonus to demonic melee units (non flying only). The regular lords of Tzeentch have access to this (like chaos sorcerers), not LL Kairos.
Looking in the database with RPFM it seems not a single unit is linked to this skill when you play as Tzeentch faction.
If you play as another chaos god you have one or two units linked to this skill (at least in the database).

The skill "savage bloodlust" is called : 
**wh2_dlc11_skill_chs_army_buff_savage_bloodlust**

it's linked to those two bonus (charge and armour) : 
**wh3_dlc20_effect_force_stat_armour_chs_melee_daemons**
**wh3_dlc20_effect_force_stat_charge_bonus_chs_melee_daemons**

Those two bonus are linked to the unit sets: 
**chs_daemon_cavalry
chs_daemon_chariots
chs_daemon_infantry
chs_daemon_monster_beasts**

Then nothing, at least for Tzeentch. Not a single unit is linked to those unit sets.
It may be as simple as removing this savage bloodlust skill (for the tzeentch lords) because each Tzeentch units seem to be affected by the other red skills.

**Comment by Cataph** [comment]
should be ok at a glance now in 2.1
