### ISSUE TITLE
Treacherous trait for tomb kings heroes is back to not working

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#840]
wh2_dlc09_skill_innate_tmb_treacherous	wh2_dlc09_effect_force_stat_melee_attack_scorpions	1	character_to_force_own	5.0000
wh2_dlc09_skill_innate_tmb_treacherous	wh2_dlc09_effect_force_stat_melee_defence_tmb_scorpions	1	character_to_force_own	5.0000

Needs to be added into character_skill_level_to_effects_junctions_tables

**Comment by Harmandodelavega** [comment]
@floskan you mean our fix doesn't work? https://github.com/chadvandy/cbfm_wh3/issues/290

**Comment by floskan** [comment]
> @floskan you mean our fix doesn't work? #290

Sorry, didn't look closely enough before submitting
