### ISSUE TITLE
Extended tooltips are not showing

### ISSUE THREAD

**Issue by thephluxer** [chadvandy/cbfm_wh3#844]
**Describe the bug**
Some of the extended tooltips that should show up to kind of explain the contents of the main tooltip are not showing up.

For example the tooltip for On-Board Waste Compactor in the Skaven Forbidden Workshop just shows the tooltip for the On-Board Waste Compactor itself without explaining what the Endless Drum ability actually does.

**Expected behavior**
If a tooltip contains the name of an ability or other things that have tooltips on their own it should also show those tooltips as an extension.

For example the tooltip for On-Board Waste Compactor in the Skaven Forbidden Workshop should also show the tooltip of Endless Drum because the ability gets mentioned in it and has it's own tooltip that can also be shown to further explain things.

**To Reproduce**
1. Play as Ikit Claw
2. Open the Forbidden Workshop
3. Look at the tooltip for On-Board Waste Compactor in the Weapons Teams tree

**Screenshots**
Current:
![image_2023-01-31_01-09-14](https://user-images.githubusercontent.com/8382485/215625227-625f988e-0213-474d-8eaf-c8c2a504c650.png)

Expectation:
![image_2023-01-31_01-09-25](https://user-images.githubusercontent.com/8382485/215625296-0e154a3c-dc45-4ffe-ba55-c9af4ae94967.png)

Mod Edit: Bogdanov screenshots

TWW 2 screenshots:
![193067750-918625b2-399c-45dc-aeed-223910b3d359](https://user-images.githubusercontent.com/66144788/216441428-d8e587c9-ddae-4b4e-95e2-4e20564f31fd.png)

**Additional context**
The screenshots are no mockups but there was actually a version of TWW3 around at some point that didn't have this issue.
The source of the expected screenshot was a preview video of TWW3 i found on Youtube.
I also created a reddit thread about this issue some time ago: [https://www.reddit.com/r/totalwar/comments/yiqf4g/how_do_i_get_extended_tooltips/](url)

**Comment by Bogdanov89** [comment]
Based on the report this seems to be a similar (or identical) issue as the https://github.com/chadvandy/cbfm_wh3/issues/446
Just in this case its Skaven tooltips and in the issue 446 its the Wood Elf tooltips.

**Comment by thephluxer** [comment]
Yes seems to be the same bug. I just can confirm that it is indeed a bug and not just a change in TWW3 because both of my screenshots are from TWW3.
Here the source of the screenshot with extended tooltips: [https://www.youtube.com/watch?v=YVQMVDfnrGc&t=651s](url)
