### ISSUE TITLE
When beastmen herdstones are destroyed you get an extra herdstone shard

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#846]

**Comment by ILiveInATree** [comment]
I don't think this is a bug; it seems like the intended functionality. When a herdstone is destroyed or abandoned before completing the ritual, you get a herdstone shard back so you can't just run out. When you complete a ritual you gain a herdstone shard and keep the herdstone, allowing you to keep all regions defiled. If you lose that herdstone, you get a shard from it so you can re-defile that territory *without losing progress.* 

I mean obviously I'm just speculating and there's probably evidence against this somewhere in game that I didn't read but just putting it out there.

**Comment by Drazhir2** [comment]
This is the only thing that changed in the 4.2.0 bloodgrounds script which solves another issue so not fixed.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/8196db8b-e567-4188-a666-52da621d06e0)
