### ISSUE TITLE
Khorne regiments of renown will receive all the proper buffs, also some for khorne marauders

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#85]
![redline khorne](https://user-images.githubusercontent.com/34427023/188266396-c9fc9917-8024-43ec-a075-26e63d477f66.png)

**Comment by Harmandodelavega** [comment]
Thanks to floskan for giving me a template

**Comment by Harmandodelavega** [comment]
CA added wh3_main_kho_chaos_warriors_skullcrushers set

haven't throroughly checked the rest but pretty sure it wasn't fixed

**Comment by Harmandodelavega** [comment]
all mp_cap_unit_kho_cav_bloodcrushers_ror_0 from effect bonus value should be removed

**Comment by floskan** [comment]
> all mp_cap_unit_kho_cav_bloodcrushers_ror_0 from effect bonus value should be removed

https://github.com/chadvandy/cbfm_wh3/pull/1350 you meant like this i assume?

**Comment by floskan** [comment]
I'm curious as to why the marauder RoR isn't showing up on the tooltip for this tech.. Because it should work right?

**Comment by Harmandodelavega** [comment]
They have rage by default

**Comment by floskan** [comment]
I don't see why it wouldn't work even if there's no tooltip but didn't have time to try! Might just be that unit tooltips are excluded from the charge effect
