### ISSUE TITLE
Nagarythe missing Lileath's Blessing stance

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#852]
**Describe the bug**
High Elves, known for their super strong magics, in TWW3 have a great army stance for gaining WoMagic called Lileath's Blessing.
However Alith Anar's faction is missing this army stance - actually it has NO stance for creating Winds of Magic at all!
This is crippling because HElves greatly rely on the use of WoM (and even have units that get bonuses based on WoM). 
Also lore-wise it makes no sense that the most magic capable race on the planet has no WOM channeling stance.

**Expected behavior**
Alith Anar faction having access to High Elf army stance for gaining Winds of Magic.

**To Reproduce**
1. Play as Alith Anar
2. Notice that all your armies are missing any stance for generating WoMagic

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/217172499-6ece24f6-7d91-4544-9080-d828758aac83.png)

**Comment by mfvreeland** [comment]
Was this the case in WH2?

**Comment by Bogdanov89** [comment]
Channeling stance was MUCH different in WH2, it only granting a bit of WOM power reserve and miscast base chance.
It was in no way needed for the casters of a WH2 magic-dependent race to function, and frankly wasnt that useful due to massive movement cost/penalty.
Hence Alith Anar did not have it, either due to having too many stances already or due to balance concerns.

In total warhammer 3 the "channeling" stances are VASTLY more important since they can increase your available WOM several times over.
In my humble opinion this is beyond a doubt just a case of CA forgetting/neglecting to spread the new channeling stance to each lord of a magic-oriented race.

**Comment by mfvreeland** [comment]
@Bogdanov89 I see your point, but unless there is some sort of confirmation from CA that this wasn't intended, I would file this under out of scope for CBFM. Others may disagree, but I would leave this for now.

**Comment by Bogdanov89** [comment]
https://forums.totalwar.com/discussion/328452/alith-anar-nagarythe-missing-the-womagic-army-channeling-stance
CA responded on this topic with the following reply and added KNOWN ISSUE to the topic:
Perhaps Bug FIx mod could fix this issue before CA, pretty please :)

![image](https://user-images.githubusercontent.com/55892027/220346111-1145e121-4bcf-4e45-a1d8-07ad1378b9a8.png)

**Comment by mfvreeland** [comment]
CA evidently fixed this in 3.0, but they decided to remove raiding stance for Alith Anar to compensate.
