### ISSUE TITLE
Skaven Technology practiced goaders has no effect description

### ISSUE THREAD

**Issue by Pop000100** [chadvandy/cbfm_wh3#859]
**Describe the bug**
Skaven Technology practiced goaders has no effect description

**Expected behavior**
It doesn't mention that it gives packmasters recruit rank.

**To Reproduce**
Hover over practiced goaders in the skaven tech tree

**Screenshots**
wasn't able to take a picture of the tooltip
![goaders](https://user-images.githubusercontent.com/20156032/219434097-b7c94af3-6457-456c-acdd-b72b42e4afee.png)
but that is the problematic technology

**Additional context**
I don't have the DLC that unlocks Packmasters.

**Comment by Harmandodelavega** [comment]
think @floskan got this
