### ISSUE TITLE
IMRIK´S UNIQUE DRAGON MOUNT MINAITHNIR MISSING. HE IS MOUNTING A GENERIC STAR DRAGON VARIANT.

### ISSUE THREAD

**Issue by AdrianKarrantza** [chadvandy/cbfm_wh3#86]
Imrik is using a generic star dragon as mount instead of Minaithnir both in campaign map and battle. Apparently, there should be a unique variant for Minaithnir (Imrik´s unique mount), but the Variant filename has been reverted to just the generic dragon type. Here is the link to CA´s official Support Forum where I have reported the bug with pictures [LINK](https://forums.totalwar.com/discussion/320146/bug-imrik-s-unique-dragon-mount-minaithnir-missing-he-is-mounting-a-generic-star-dragon-variant#latest)

**Comment by mfvreeland** [comment]
The mount entity and variant is unchanged from what was in WH2. Still reads "wh2_dlc15_hef_star_dragon_minaithnir" for the variant. I think the coloring may just look a little different with the new WH3 rendering. Doesn't seem like a bug.

**Comment by AdrianKarrantza** [comment]
Thanks for answering. If you check Imrik's mount in campaign map, you will clearly see that he is mounting a generic star dragon. See the different wing pattern between the actual Minaithnir and the regular star dragon.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdrianKarrantza** [comment]
I have just checked Imrik's mount in custom battle, it is Minaithnir. However, it is not in campaign map. The first picture correspond to the actual Minaithnir in battle. The next two pictures are from the campaign map where you will see that the dragon is a regular star dragon one (see the spots of his wings, darker colour of the dragon compared to Minaithnir). All pictures are from WH3.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mfvreeland** [comment]
Ah, it's a campaign map-only bug. I didn't even look there. Will fix.
