### ISSUE TITLE
Orc warbosses and Goblin great shamans are missing their chariot mounts in the campaign skill tree.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#860]
Mod edit: They did not have them in WH2, it was an undocumented addition in WH3, CA usually doesn't do these "freebies" so I'm wary

**Describe the bug**
Orc warbosses and Goblin great shamans have chariot mounts in custom battle, but they are not available in the IE campaign (skill trees).

**Expected behavior**
Mounts available in the campaign if they are available in the custom battle.

**To Reproduce**
1. Play as any greenskin IE campaign
2. Recruit either of the two lord types mentioned above
3. Notice they lack the chariot mount options in the skill trees.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/219933297-c61d84cc-d53a-4865-8509-4c52160f64c6.png)

**Additional context**
Source:
https://www.reddit.com/r/totalwar/comments/115umz3/bug_orc_warbosses_and_goblin_great_shamans_are/

CA forum: https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/2053-known-issue-orc-warboss-and-goblin-great-shaman-lords-missing-their-chariot-mounts-in-iempires?page=1

**Comment by AmazingTriangularHairMan** [comment]
Late to the party, but can also confirm this issue and have been reporting it through Steam since patch 2.3.
Neither of these mount options are available in campaign but can be picked in multiplayer battles.

**Comment by Bogdanov89** [comment]
At last some official CA confirmation that this is a known issue & a true bug:

https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/2053-known-issue-orc-warboss-and-goblin-great-shaman-lords-missing-their-chariot-mounts-in-iempires?page=1

**Comment by mfvreeland** [comment]
@Bogdanov89:
I took a look at this. I was hoping it was simply a matter of a mount skill that wasn't active, but there are no skills providing these mounts for these units. The skill doesn't exist; the associated effects and ancillaries don't exist; the icons representing these skills don't exist. CA added these mount for custom battles only, it seems, and I believe they will have to be the ones to properly add it to campaign if they so choose. It's beyond CBFM to provide all the icons, effects, etc. to make this work right.

Thanks for the report, though!
