### ISSUE TITLE
Floating Anvil of Doom for Runelords + Runelord/Thorek Animation Regression

### ISSUE THREAD

**Issue by Mandras2** [chadvandy/cbfm_wh3#867]
#1163
### 1: Floating Anvil of Doom for Runelords ###
The four campaign variants of Dwarf Runelords use Anvil of Doom variantmeshdefinitions ported from WH2 with no changes to account for different paths/wsmodels. This results in the longbeard bearers, the shields, and the Runelord's hammer being invisible in battle. Note, the custom battle version and campaign/overworld anvil model are unaffected. 
-  Fix: copy valid slot info from "dwf_anvil_of_doom.variantmeshdefinition" into the four affected files: "dwf_anvil_of_doom_campaign_01-04.variantmeshdefinition"

### 2: Runelord/Thorek Animation Regression ###
Runelords and Thorek on Anvil of Doom use Thorgrim's animations instead of the unique Thorek animations they received in WH2, giving odd results such as their hammer being upside down and generally being less visually impressive (no lightning when striking anvil, etc). 
-  See this mod for more info + fix: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2938117522&searchtext=runelord (dead link)
Mod edit: maybe this one?https://steamcommunity.com/sharedfiles/filedetails/?id=2945364561&searchtext=runelord

### 3: Wrong Dwarf Lord Unit Card ### Mod edit: (both vanilla and this one are slight variations on one of the two, don't think mirroring a unit card counts as it being different)
Dwarf Lord campaign variant 03 uses the wrong unit card. 
-  Fix: replace "dwf_lord_campaign_03_0.png" with "dwf_lord_campaign_05_0.png" unit card.

### Screenshot ###
![runelord_dwarf_lord_fixes](https://user-images.githubusercontent.com/76390495/221414517-b56f59a7-ff7d-413e-879e-16d52510945c.jpg)

### Fixes for Issue 1 & 3: ###
[!_MOD_DWF_lord_potrait_fix+runelord_anvil_invisible_bearers_fix.zip](https://github.com/chadvandy/cbfm_wh3/files/10833821/_MOD_DWF_lord_potrait_fix%2Brunelord_anvil_invisible_bearers_fix.zip)

**Comment by mfvreeland** [comment]
Should all be fixed by #1442 when it passes testing.

**Comment by Harmandodelavega** [comment]
@mfvreeland @floskan  should we credit Mandras as well?

**Comment by floskan** [comment]
I don't know, Dux only used the mod that's up on the workshop and some older files from wh2 as far as I know

**Comment by mfvreeland** [comment]
No harm in crediting anyone who came up with a solution for these issues independently.

**Comment by floskan** [comment]
Alright, sounds good to me
