### ISSUE TITLE
Vassal income capped at 25k gold/turn per vassal

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#87]
Vassal income (for factions such as Nakai & others) are arbitrarily capped at 25k gold/turn, which is very easily reached in IE before even a tenth of the map is conquered.
This used to be a problem back in TWW2 but got changed in one of the updates to be a max of 999999 gold/turn.
Since TWW3 is based on an older version of TWW2 its likely that CA overlooked this particular old value, so it remained at 25k gold/turn instead of being updated to the 999999 gold/turn as in modern TWW2.

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2
