### ISSUE TITLE
The Elf version of Transformation of Kadon (Eagle) doesn't have its own cost reduction effect, causing the Vampire version (Varghulf) to appear in the character skill selection.

### ISSUE THREAD

**Issue by Mandras2** [chadvandy/cbfm_wh3#876]
Mod Edit: related https://github.com/chadvandy/cbfm_wh3/issues/805
**Describe the bug**
The Elf version of Transformation of Kadon (Eagle) doesn't have its own cost reduction effect when points into the skill, causing the Vampire version (Vargulf) to appear in the character skill selection alongside the Elf version. It's possible that it doesn't even reduce the winds of magic cost.

The Elf version of Transformation of Kadon in "character_skill_level_to_effects_junctions_tables":

Hero and Lord version
wh2_dlc15_skill_magic_beasts_transformation_of_kadon
wh2_dlc15_skill_magic_beasts_transformation_of_kadon_lord

have this effect:
wh2_dlc11_effect_ability_wom_cost_transformation_of_kadon_varghulf

**Solution:**
A fix would require:
1: a data core or making a completely new character skill, dummying out the original
2: making a new wom effect (basically cloning "wh2_dlc11_effect_ability_wom_cost_transformation_of_kadon_varghulf" or the original manticore version "wh_dlc03_effect_ability_wom_cost_transformation_of_kadon") for the Eagle version of this spell.

![20230308204253_1](https://user-images.githubusercontent.com/76390495/223902580-bcde22c2-01e4-4adb-b084-27d94eeb5863.jpg)

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed High Elf beasts casters having the wrong Transformation of Kadon spell when reducing the Winds of Magic cost in their skill tree."
