### ISSUE TITLE
Thorek Ironbrow can't confederate Karak Azul properly

### ISSUE THREAD

**Issue by trgeiger** [chadvandy/cbfm_wh3#877]
**Describe the bug**

Thorek should be given an early dillema to confederate Karak Azul. Currently, this only triggers after you perform one other confederation first. Some discussion of the issue: https://www.reddit.com/r/totalwar/comments/zwm5kb/thorek_is_unable_to_confederate_karak_azul/

**Expected behavior**
The dilemma should appear as usual without requiring a different confederation first.

**To Reproduce**
1. Play as Thorek Ironbrow
2. Look in diplomacy with Karak Azul and see there's no confederation option, since you normally confederate them through the bugged confederation dilemma.

**Comment by Harmandodelavega** [comment]
gonna lazily assume the patch notes mean what they say
