### ISSUE TITLE
The Vault of Nagash for the Vampire Coast is not buildable

### ISSUE THREAD

**Issue by xXAlduin99** [chadvandy/cbfm_wh3#879]
**Describe the bug**
In the Black Pyramid of Nagash settlement the Vampire Coast should be allowed to build the Vault of Nagash Landmark Building. But they can't, if they conquer it nothing special landmark-wise and be build.

**Expected behavior**
Activate the Landmark building of the Vault of Nagash for the Vampire Coast factions in the Black Pyramid of Nagash.

**To Reproduce**
1. Conquer the Black Pyramid of Nagash as the Vampire Coast
2. Look at the building options.

**Comment by Harmandodelavega** [comment]
#432

**Comment by mfvreeland** [comment]
PR merged.

**Comment by floskan** [comment]
CA added this back but they gave Vcoast the non-vampire faction variant of this building. Can the landmark availability be changed without datacoring?

**Comment by floskan** [comment]
"This is not intended and it should be using their own version. This is getting looked into."  from CA

**Comment by floskan** [comment]
Yep, the only problem is both will be buildable but not a big deal
