### ISSUE TITLE
Clan Angrund faction effect doesn't mention lords suffer an additional 100% upkeep penalty

### ISSUE THREAD

**Issue by sgproductions87** [chadvandy/cbfm_wh3#881]
Clan Angrund is supposed to apply an additional 50% upkeep penalty to all units and characters until Karak Eight Peaks is rightfully returned to their possession. This happens - on the units - but not on the lords. On the lords, it's much more.

The base upkeep on a Dwarf lord or Runelord is 250. This means that Angrund's base lord upkeep should be 375. However, on turn 1 (so no supply lines penalty is applied for this test), if the player swaps Belegar out for another lord, that lord's upkeep is 625. That's an additional 250.

This result is coming from a formula of (base*1.5)+base.

Belegar himself is costing 750 in upkeep! This makes playing this faction very painful.

**Comment by chadvandy** [comment]
Maybe there's a double-tap happening here? Where lords are hit twice with the upkeep penalty. I don't know if that makes sense mathematically, I'm a child.

**Comment by sgproductions87** [comment]
> Maybe there's a double-tap happening here? Where lords are hit twice with the upkeep penalty. I don't know if that makes sense mathematically, I'm a child.

I tried looking in RPFM myself for the tables which cause the Angrund upkeep effect but couldn't find. Anyway, I hope you guys can fix this or tell me exactly where I need to look so I can do it :)

**Comment by Harmandodelavega** [comment]
wh_dlc06_belegar_karak_owned_false_first should be this, will need to look into it more

**Comment by sgproductions87** [comment]
I'm going to try to alter "wh_main_effect_upkeep_increase_lords_hidden" to "0". Will then report.

**Comment by sgproductions87** [comment]
Can confirm, altering to 0 had desired effect. I don't have the knowledge to add this fix to the CBFM but was able to alter to 0 locally using RPFM modifying CA's packfile.

**Comment by Harmandodelavega** [comment]
they removed the effect
