### ISSUE TITLE
Blessed Chameleon Skink skin is naked compared to counterpart (Obsidian)

### ISSUE THREAD

**Issue by aimop95** [chadvandy/cbfm_wh3#885]
**Describe the bug**
Current Vanilla game displays the Blessed Chameleon Skink as completely naked compared to their counterparts, who have neat frog hats.

**Expected behavior**
Blessed Chameleon Skinks should have blue frog hats, instead of nothing.

**To Reproduce**
1. Play as any Lizardman faction
2. Obtain Blessed Chameleon Skinks and a regular unit to compare
3. Go into a battle map and see the difference between the two

I have a fix here, thanks to [Obsidian](https://steamcommunity.com/sharedfiles/filedetails/?id=2940793412) who made the Lustria Rises mod.
[!obsidian_lustria_rises_Just_Blessed_Chamelon_Skink_fix.zip](https://github.com/chadvandy/cbfm_wh3/files/11012833/obsidian_lustria_rises_Just_Blessed_Chamelon_Skink_fix.zip)

**Comment by mfvreeland** [comment]
Chameleon Skinks have hats? I never noticed.

**Comment by Drazhir2** [comment]
Is a lizard without a hat actually naked? (not fixed in 4.1.1)
