### ISSUE TITLE
Karl Franz Greatsword upkeep reduction not working for Carroburg Greatswords

### ISSUE THREAD

**Issue by kevakanin** [chadvandy/cbfm_wh3#889]
The 25% lord upkeep reduction ability and 15% skill point ability upkeep reduction for Karl Franz for greatswords doesn't work for Carroburg Greatswords (Lord Elector State Troops) in Karl Franz army. Maybe a 'feature' as the upkeep reduction for state troops from confederating elector counts these could effectively become free upkeep at a later stage in the campaign?

**Comment by Harmandodelavega** [comment]
Special Greatswords cost 275 instead of 225, on top of that Karl Gelt and Volkmar have a hidden 75% increase for elector count units, if you take this into account the numbers should make sense
