### ISSUE TITLE
Bretonnia Free Upkeep Vow Bug

### ISSUE THREAD

**Issue by bingo12345** [chadvandy/cbfm_wh3#89]
https://forums.totalwar.com/discussion/318806/this-is-how-to-fix-bretonnia-0-upkeep-bug#latest

detail there.

**Comment by Harmandodelavega** [comment]
https://trello.com/c/b90ESJXA/55-brt-vow-troth-bug?search_id=508e6d6e-3f71-418c-87cd-f650317ca4aa

**Comment by mfvreeland** [comment]
CA made changes to the script in 2.3 to fix this, although their fix is different from the one I submitted. I think theirs is probably better, but it needs testing to verify it is fixed.

**Comment by mfvreeland** [comment]
Apparently broken again
