### ISSUE TITLE
Knights of the Everlasting Light have incorrect mass.

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#890]
**Describe the bug**
Every heavy cavalry in the game has about 1150 mass, from the basic Empire Knights to the ultra heavy Necropolis Knights, Blood Knights and Demigryph Knights.
However the Knights of the Everlasting Light (Empire Knights) have a colossal mass of 1800 !!!
To put it into perspective the Stone Trolls have a mass of 1300 and the heavy Chaos Chariot has a mass of 1880.
Considering the Knights of the Everlasting Light are just an Empire Knight variant and have 45 models this vast mass of 1800 is surely unintended.

**Expected behavior**
Knights of the Everlasting Light should have a regular mass just like every other Empire Knight.

**To Reproduce**
1. Check mass in game for this unit.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/227719460-2b65753c-faad-40fe-8172-1a2ce51acd98.png)

**Comment by Cataph** [comment]
They're in line with the rest now so nothing to do here, we didn't have a fix in release, right?

**Comment by mfvreeland** [comment]
@Cataph They changed Knights of the Blazing Sun, but Knights of the Everlasting Light still seem to have jacked up mass on account of their riders registering as 800 mass, which is 700 more than standard for a man-sized rider.

**Comment by Cataph** [comment]
Mass on the tooltip is 1000 for all of those and in the 3.1 patch notes CA specified that mass shouldn't sum all the entities in the model but only use one as a governing mass.

**Comment by mfvreeland** [comment]
You are right; somehow I missed that note in the patch notes. Someone should tell whoever runs twwstats, as the 3.1 mass values over there are still using the old logic.
