### ISSUE TITLE
Bretonnian Lords in campaign broken colours

### ISSUE THREAD

**Issue by Maharaja-of-Punjab** [chadvandy/cbfm_wh3#899]
Bretonnian lords in campgian are all balck and red and are unable to be saved to multiplayer games they also have no preditrmed colour and are always randomized.

**Expected behavior**
I expected them to have intresting coulor and to load them into multiplayer battles.

**To Reproduce**
1. Play as Any Bretonnian faction
2. Recurit a lord
3. Save it
4. Load him in custom or mutiplayer battles and crash

**Additional context**
They are red and blue when unmounted.

**Comment by Harmandodelavega** [comment]
merging in #1290
