### ISSUE TITLE
Vampire Coast siege towers are replaced by Vampire Count towers

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#9]
https://discord.com/channels/373745291289034763/581350140942483456/1012077817313374300

**Comment by chadvandy** [comment]
zzz_cbfm_fix_cst_siege_items

**Comment by mfvreeland** [comment]
@chadvandy Thanks for adding this fix. Taking a look, I can see that the way you did it is better than the way I did it in the pack file I linked to on Discord, seeing as you didn't need to overwrite a whole db. I'm fairly new to modding, but I'd like to contribute more to this project, so if you get a chance to explain how the effects and effects-bundles-to-effects-junctions stuff factors in here, I'd love to learn more.  I knew the way I did it wasn't ideal, but I couldn't figure out how to do it any other way without ending up with both types of siege tower (V. Coast and V. Counts) as available options.

**Comment by chadvandy** [comment]
Hey! Essentially, what I did was:
I checked to see where that effect was used which grants the vampire siege towers, and saw it was only used in an invisible effect bundle, and it itself had no text or icons to the effect. That means it's trivial to disconnect the effect - in effect bundles to effects, I set the value of the bugged effect to 0, which means it's doing nothing at all.

Then, I just made a new effect, with the key CBFM_etc so it's easy to find later, and hooked it up with the proper functionality and connected it to the right effect bundle

**Comment by mfvreeland** [comment]
That makes sense. Unfortunately, I tried loading up the cbfm_wh3 pack, and this fix didn't seem to work. I still get the Vamp. Counts tower, although based on how the effect _should_ be working, I'm not sure how that's possible. Maybe it's not possible to remove a siege effect after it's been added?

**Comment by chadvandy** [comment]
Did you test it on a new campaign or an existing save?

**Comment by mfvreeland** [comment]
New campaign. Noctilus is the easiest to test with; he can reliably lay siege to a major settlement (Vaul's Anvil on Ulthuan) on turn 2. Results are the same with an existing campaign, though.

**Comment by mfvreeland** [comment]
I did some more testing today and discovered that the "wh2_dlc11_bundle_force_siege_equipment_cst" effect bundle wasn't really doing anything. I dug a little deeper and found that all of these "force_siege_equipment" effect bundles are only used for rebel and rogue armies (ref: wh_campaign_setup.lua); the normal factions get their siege equipment setup via the cultural trait system, which is evidently tied to the faction trait effect bundles (in this particular case, it's "wh2_dlc11_faction_trait_vampire_coast"). Unfortunately, while I could remove the incorrect siege towers by adding a new effect junction tied to this bundle, it doesn't seem the new one can be added this way. 

One thing I'd like to try is creating an entirely new effect bundle, which removes the wrong siege towers and adds the correct ones, that could the be manually applied via script. I couldn't figure out how to do this, though. My first attempt at scripting just ended with crashing.

**Comment by chadvandy** [comment]
fuck this shit

**Comment by chadvandy** [comment]
fixed through script by @mfvreeland as of #24

**Comment by mfvreeland** [comment]
Fixed in 2.2 (to my pleasant surprise!), should be removed

**Comment by chadvandy** [comment]
removed from CBFM
