### ISSUE TITLE
Hawk riders not getting vanguard deployment anymore

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#90]
https://forums.totalwar.com/discussion/320081/hawk-riders-do-not-have-vanguard-deploy

And here's a mod that fixes this among other things https://steamcommunity.com/sharedfiles/filedetails/?id=2857068576

**Comment by mfvreeland** [comment]
Without clarification from CA, we can't know if the removal of default vanguard deployment for Hawk Riders was intentional or not. Either way, there's a bug here -- either Hawk Riders should have vanguard deployment by default, or the Sisters' vanguard deployment skill should also apply to them -- but we don't know which one should be fixed.

**Comment by floskan** [comment]
> Without clarification from CA, we can't know if the removal of default vanguard deployment for Hawk Riders was intentional or not. Either way, there's a bug here -- either Hawk Riders should have vanguard deployment by default, or the Sisters' vanguard deployment skill should also apply to them -- but we don't know which one should be fixed.

I agree, what does @chadvandy think?

**Comment by Bogdanov89** [comment]
The other flying missile cav units from TWW2 still have vanguard deployment (DElf, LMen).
Hawk Riders are also more expensive than all of them.
To me this looks like a mistake by CA (similar to how Tretch Craventail got Kislevite blood attribute).

**Comment by mfvreeland** [comment]
I like to think the Tretch thing was trolling. It's too funny to be an accident. I do think you're probably right about this, although I would still want confirmation before making a change here.

**Comment by pigwithsnoot** [comment]
As of October 18, 2022, CA has fixed this with patch 2.2.
