### ISSUE TITLE
Karak Kadrin's Journey's End still not fully functional (even with this mod)

### ISSUE THREAD

**Issue by sgproductions87** [chadvandy/cbfm_wh3#901]
**Describe the bug**
Karak Kadrin faction's Slayers can still lose models when above 6480 health (6480 is 75% of Slayer health of 8640) when using CBFM despite prior fix to this issue.

**Expected behavior**
Karak Kadrin faction's Slayers should not lose models when above 75% health under any circumstances.

**To Reproduce**
1. Play as Kadrin Dwarfs
2. Attack starting enemy army
3. Charge Slayers into Goblins and attempt friendly fire or for enemy lord to fight the Slayers
4. Slayers may lose models if fired upon by Trollhammer Torpedo or if they fight the enemy lord

**Additional context**
It seems that when the Slayers fight in melee vs the Goblins without any other interference the ability works perfectly well. Firstly the JE ability wasn't working at all with this mod on with a bunch of other Dwarf mods so I disabled everything except CBFM and started testing. That was how I found the CBFM fix mostly, not completely, works.

**Comment by allenhu0912** [comment]
I suspect that it works in a similar way to Grimgor's Immortulz Banner where if entities get ragdolled they can "die". In that particular case they don't actually die, they'll come back after the battle, but I think they bug out during the current battle.

**Comment by sgproductions87** [comment]
Is that something that can be modded out?

**Comment by Harmandodelavega** [comment]
merging with #253

**Comment by mfvreeland** [comment]
> Is that something that can be modded out?

If it's like the Immortulz Banner, then no, unfortunately we can't fix it via mod (or at least no one has figured out a way to yet).
