### ISSUE TITLE
Confederating armies that are sieging deletes them

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#902]
![20230406212244_1](https://user-images.githubusercontent.com/54481962/230528403-7b1619d0-c6f0-47e2-a3f0-9f8af4e24ac7.jpg)
![20230406212322_1](https://user-images.githubusercontent.com/54481962/230528416-714e1cca-d2f3-4f9d-b8ac-5a20ff2e90a8.jpg)

As you can see Orion is besieging Massif Orcal when the confederation request goes through. He is instantly wounded and the rest of his army deleted from existence. Another of his armies does not vanish on the spot. Don't know if this is related but the confederation succeeded before I finished the mission that gives me the option to confederate him.

**Comment by Harmandodelavega** [comment]
Been an issue since at least warhammer 2 don't think it's fixable
