### ISSUE TITLE
Gobling Wolf Chariot ROR don't have fire whilst moving

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#905]
**Describe the bug**

> GOBLIN WOLF CHARIOTS & REGIMENT OF RENOWN
> 
> Attribute Added: Fire Whilst Moving (we missed adding the Fire While Moving attribute onto the RoR; this will be corrected for Patch 3.1 – apologies!)
From the 3.0 patch notes

Simply added that attribute in the teef robbers' attribute group.
[https://discord.com/channels/373745291289034763/581350140942483456/1096322586037727362](https://discord.com/channels/373745291289034763/581350140942483456/1096322586037727362)

**Comment by mfvreeland** [comment]
PR merged
