### ISSUE TITLE
Daemonsmith Sorcerer's (Metal) skill Careful Casting applies -10 wom cost instead of -10%

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#906]
**Describe the bug**
[A clear and concise description of what the bug is.](https://www.reddit.com/r/totalwar/comments/12l8sox/daemonsmith_sorcerer_can_get_spells_for_free/)
Daemonsmith Sorcerers, skill Careful Casting, applies -10 wom cost instead of -10%. 

There is one such skill per different magic lore they have, the metal one uses `wh2_dlc15_effect_magic_metal_reduce_wom_cost_all` when it should be using `wh2_dlc11_effect_ability_wom_cost_pct_metal_spells`. 

Fixing it by changing it to -1. I could zero out and add the correct % effect but it looks dirtier for pretty much the same result.

[https://discord.com/channels/373745291289034763/581350140942483456/1096334362812895312](https://discord.com/channels/373745291289034763/581350140942483456/1096334362812895312)

**Comment by Cataph** [comment]
looks to be fixed in 3.1

**Comment by mfvreeland** [comment]
CA fix verified, removed from main branch.
