### ISSUE TITLE
K'daai domination convoy trait not working (Only the armor portion)

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#909]
![Skärmbild 2023-04-14 135846](https://user-images.githubusercontent.com/34427023/232038023-bd6b825b-be7a-4a9d-9bd6-f77d369baa7c.png)
![Skärmbild 2023-04-14 135908](https://user-images.githubusercontent.com/34427023/232038037-7ae46741-55a9-42f2-b657-f8ef5728756b.png)
![Skärmbild 2023-04-14 135901](https://user-images.githubusercontent.com/34427023/232038038-4f18c10e-df01-4a3b-9e51-0c52ae4fdb29.png)

**Comment by Harmandodelavega** [comment]
they added a set just for fireborn, needs to change our to one just for destroyers
