### ISSUE TITLE
Impossible to get Exalted daemons with CoC factions since required tech isn't in the game since 3.0

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#911]
https://preview.redd.it/q1a8ov0xmuta1.png?width=712&format=png&auto=webp&v=enabled&s=0ae926e59b7c7f2e89ccb067fdc12462fec2139a

Normally that tech is unlocked by default

**Comment by pigwithsnoot** [comment]
Yeah, I was going to report this as well but it looks like you beat me to it. I can also confirm that this bug exists for what its worth.
