### ISSUE TITLE
Caravan System Traits And Reward Bugs

### ISSUE THREAD

**Issue by CathayZhao** [chadvandy/cbfm_wh3#915]
Describe the bug
1. Cathay faction can't get Von Caesten Blade after a caravan travelling to Castle Drakenhof.
2. Cathay caravan masters with the trait Clandestine still get rank 0 units instead of veteran units. 
3. Chaos Dwarf convoy overseer with the trait Retired Daemonsmith won't have Bull Centaur Taur'ruk in his army.

To fix them:
1. In the `wh3_campaign_caravans_core` script, Castle Drakenhof is using the wrong incidents in `region_to_incident  `.
2. To make the compatibility better I changed all of them from rank 2~4 to rank 3 and added a listener to add experience to units when a caravan is recruited.
3. `wh3_dlc23_chd_cha_bull_centaur_taurruk` is missing from `wh3_dlc23_skill_innate_chd_convoy_overseer_retired_daemonsmither`'s `traits_to_units ` in the `wh3_campaign_caravans_core` script.

https://discord.com/channels/373745291289034763/581350140942483456/1096593454974382100

**Comment by mfvreeland** [comment]
Partially fixed in 4.0 (only the Von Carstein Blade part)

**Comment by mfvreeland** [comment]
Potentially fully fixed in 4.1:

"Fixed the Clandestine trait for Cathay Caravan Masters not applying the ranks/experience to units when recruiting the character."

**Comment by mfvreeland** [comment]
As of 4.1, this issue still only partially fixed. CA did fix Clandestine as stated in the notes, but the Bull Centaur Taur'ruk is still missing from the Retired Daemonsmither.
