### ISSUE TITLE
"Monster Commander" Chorf caravan trait not working

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#919]
![Skärmbild 2023-04-15 193401](https://user-images.githubusercontent.com/34427023/232247601-1718aaa8-a363-4acc-bd46-11f3db99669b.png)
![Skärmbild 2023-04-15 193443](https://user-images.githubusercontent.com/34427023/232247602-16e70104-6841-4265-9bc8-67047434310f.png)
![Skärmbild 2023-04-15 193434](https://user-images.githubusercontent.com/34427023/232247603-45ee1c72-9935-4f7d-a295-ed0564d78562.png)

**Comment by mfvreeland** [comment]
Confirmed fixed by CA in 3.1
