### ISSUE TITLE
Bordeleaux's Manann Shrine is only available to Bretonnia

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#921]
**Describe the bug**
Shrine of Manann in Bord' is theoretically a chain (`wh2_dlc12_special_bordeleaux_manann_shrine`) allowed to a bunch of cultures, but it only has one line in culture_variants (`wh2_dlc12_special_bordeleaux_manann_shrine_1`) and it's hard limited to bretonnia with those old-fashioned culture *and* subculture keys.

This to me screams that those filters should be entirely removed and the loc fixed accordingly but eh.

**Comment by Harmandodelavega** [comment]
For whatever it's worth it does have a foot squire garrison/enable foot squire recruitment so it wouldn't be of much use for other cultures except for the untainted

**Comment by Autumnchain** [comment]
I'm very sure that it's entirely intentional and is there to represent the unique relationship that the Bordeleaux Bretonnians have with Manaan.
