### ISSUE TITLE
Wh2 races have their rites available from turn 1

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#923]
https://www.reddit.com/r/totalwar/comments/12n5qju/hey_ca_is_this_a_bug_or_a_feature/

**Comment by Cataph** [comment]
Fixed in 3.1, don't think we had a fix for this so nothing to remove, right?

**Comment by floskan** [comment]
> 

Yep, we didn't touch this

**Comment by mfvreeland** [comment]
Fixed by CA, no need to do anything
