### ISSUE TITLE
Beastmen Chaos Warhounds have wrong abilities

### ISSUE THREAD

**Issue by skullboyteh13** [chadvandy/cbfm_wh3#931]
This is a bug affecting this mod and not the vanilla game.

Chaos warhounds (and poison ones too) for the beastmen are missing hide in forest and strider, they have encourge instead. 

This does not affect Warriors of Chaos or Norsca warhounds, but it does affect Norsca ice wolves.

**Comment by floskan** [comment]
The mod hasn't been updated for 3.0 yet.
