### ISSUE TITLE
Cult of sotek starting enemy Clan Skrat not appearing

### ISSUE THREAD

**Issue by Pure-Fox** [chadvandy/cbfm_wh3#945]
**Describe the bug**
Apparently Clan Skrat have their faction leader deleted and replaced with a character called "Metastorm" with no army.

**Expected behavior**
Clan Skart should have Poxtooth as faction leader and have an army with 10 unit in it at the start of the game.

**To Reproduce**
1. Play as Cult of Sotek
2. Start the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/52764769/232910522-5fc7741c-eb46-426d-bc5c-eb9b446fbed7.png)
![image](https://user-images.githubusercontent.com/52764769/232910564-d11571fe-f743-4dc7-adea-37fd12033ab0.png)

**Comment by Harmandodelavega** [comment]
probably what formerdeveloper said
