### ISSUE TITLE
Chaos Dwarf Lord Trait "Considered" +1 hero recruit rank factionwide bonus does not work

### ISSUE THREAD

**Issue by k340** [chadvandy/cbfm_wh3#946]
https://github.com/floskan/cbfm_wh3/commit/e73f1546bb319379c0a788cdef7ac373e6af0a9a

**Comment by wjrogers** [comment]
Is there something broken with Chaos Dwarf hero recruit rank bonuses in general? I noticed the gold resource building is supposed to give hero recruit rank but doesn't work, either.

**Comment by sgproductions87** [comment]
Does the diplomatic relations buff work?
