### ISSUE TITLE
Tomb of Khengai Khan landmark has borked values when damaged

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#947]
specifically the Greenskin version, wh3_dlc23_special_the_volary_tomb_of_khengai_khan_grn. Goes from +5 ap damage to +100.

[https://www.reddit.com/r/totalwar/comments/12ri6dp/weird_interaction_with_new_greenskin_landmark/](https://www.reddit.com/r/totalwar/comments/12ri6dp/weird_interaction_with_new_greenskin_landmark/)

[https://discord.com/channels/373745291289034763/581350140942483456/1098156909061742642](https://discord.com/channels/373745291289034763/581350140942483456/1098156909061742642)

**Comment by mfvreeland** [comment]
Verified fixed in 3.1. Looks like they used our exact values.
