### ISSUE TITLE
Helmann Ghorst : "Master of the Dead" buff do not apply properly or at all. 

### ISSUE THREAD

**Issue by kisscool1234** [chadvandy/cbfm_wh3#948]
**Describe the bug**
Helmann Ghorst :
"Master of the Dead" level 2 skill do not apply properly or at all. 
* the target range +200% increase does not apply properly (summon a unit of grave guard stay stuck at about 50m, no increase to 150m, verified in battle), 
* the +50% effect range of the passive ability Master of the Dead does not apply properly : the effect range stay stuck at 35m in the text description, instead of about 50m

**Expected behavior**
With Master of the Dead" level 2 skill : 
 * summoning a unit of grave guard range should be 150m (awaken from the grave),
 * passive ability Master of the Dead range effect should be 50m not 35m in text description (idk range effect in battle)

**To Reproduce**
1. Play as Helmann Ghorst
2. level up to lvl6 while choosing "awaken from the grave" spells and level 2 of master of the dead skill
4. in battle, summon a unit of grave guards
5. range is limited to about 50m, not 150m as it should

**Comment by Harmandodelavega** [comment]
#631
