### ISSUE TITLE
Diplomatic offers to break treaties do not work at all

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#963]
Offer to break a treaty in a diplomatic deal, AI might pay you for it. The deal goes through, but the treaty is still there. Similarly you can demand the AI break treaties but it will do absolutely nothing.

**Comment by Harmandodelavega** [comment]
"breaking military access(also alone while being allies) + mil alliance/or nap cancels neither(not even trade) but can be traded for x in diplo(not if you ask for just money)"

**Comment by allenhu0912** [comment]
I haven't had this occur after 3.0 came out. I think it may have been a 2.4 issue that CA quietly fixed.
