### ISSUE TITLE
Chorf Rune of Immunity (spell resistance) for missile infantry no worky

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#972]
**Describe the bug**
Rune of Immunity upgrade for missile infantry should apply spell resistance. `wh3_dlc23_effect_force_stat_magic_resist_chd_missile_inf` has no unit set junction so it does absolutely nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/54819130/235234776-5d0f4cf8-e808-43e4-82b9-87991fe937de.png)
![image](https://user-images.githubusercontent.com/54819130/235234791-4371a70a-0a50-43a9-9547-83746396cd34.png)

Added the effect to `wh3_dlc23_chd_category_chaos_dwarf_missile_infantry` unit set used by similar upgrades.
[https://discord.com/channels/373745291289034763/581350140942483456/1101589077821751327](https://discord.com/channels/373745291289034763/581350140942483456/1101589077821751327)

**Comment by Cataph** [comment]
fixed in 3.1, can be retired

**Comment by mfvreeland** [comment]
CA fix verified, removed from main branch.
