### ISSUE TITLE
Ariel has no items when spawned by an AI faction

### ISSUE THREAD

**Issue by wrongweektoquitglue** [chadvandy/cbfm_wh3#977]

**Comment by bluetardis** [comment]
Still an issue as of July 8

If Ariel is spawned by AI then confederated she will not have her items.

 _(if someone can add the code)_ 
She will not have her unique items, so to get them you need the following five commands:
```
item wh2_dlc16_anc_enchanted_item_acorns_of_the_oak_of_ages
item wh2_dlc16_anc_armour_heartstone_of_athel_loren
item wh2_dlc16_anc_arcane_item_wand_of_wych_elm
item wh2_dlc16_anc_talisman_berry_wine
item wh2_dlc16_anc_weapon_dart_of_doom

```

**Comment by Drazhir2** [comment]
The UniqueAgentSpawned listener that assigns the ancillaries triggers on surname. Ariel (and Coeddil) have the surname of Alarielle in the script.

With the proper surname Ariel now spawns with her items:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/2da762dd-1df2-4820-bf39-28ba34852142)

Here is the fix (rename to .pack)
[zzz_cbfm_ariel_items.patch](https://github.com/chadvandy/cbfm_wh3/files/12051688/zzz_cbfm_ariel_items.patch)
