### ISSUE TITLE
Shadow Liche priest on horse labeled as Nehekhara on unit card

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#980]
The icon is correct, it's just that the text says Liche Priest (Nehekhara) for my Shadows caster.

**Comment by Harmandodelavega** [comment]
Old bug fixed in WH2 and reintroduced in WH3 (clap clap) https://trello.com/c/M1DvntDX/1060-shadow-liche-priest-labeled-as-nehekhara https://www.youtube.com/watch?v=YDKCaeLn8e4&t=1094s
