### ISSUE TITLE
Channeller extra winds capacity does not seem to work

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#982]
![20230505015352_1](https://user-images.githubusercontent.com/54481962/236394284-a3dd3e37-49eb-42a1-83cd-9ba62ec42550.jpg)
![20230505015336_1](https://user-images.githubusercontent.com/54481962/236394288-ab53f50c-a9f6-497a-bf7e-1f114f664a18.jpg)

Liche Priest has both Magical Capacity and Channeller, but winds capacity is only 105.

**Comment by floskan** [comment]
> ![20230505015352_1](https://user-images.githubusercontent.com/54481962/236394284-a3dd3e37-49eb-42a1-83cd-9ba62ec42550.jpg) ![20230505015336_1](https://user-images.githubusercontent.com/54481962/236394288-ab53f50c-a9f6-497a-bf7e-1f114f664a18.jpg)
> 
> Liche Priest has both Magical Capacity and Channeller, but winds capacity is only 105.



[lichepriestchanneller.zip](https://github.com/chadvandy/cbfm_wh3/files/11415112/lichepriestchanneller.zip)
Does it work with this?
