### ISSUE TITLE
Heroes with Multiple embed abilities automatically switch skills

### ISSUE THREAD

**Issue by Dom-925** [chadvandy/cbfm_wh3#983]
Some Legendary heroes have more than one ability they should apply to a Lord's army when they are embedded. For example, Kroak has Training and Replenish Troops. When you embed him in an army, it gives an option of which bonus you would like to choose. If you choose Replenish Troops, it works at first, but later the bonus applied to the army will change to Training.

I would expect that either both bonuses are applied while the lord is embedded, or the game would maintain the original choice until it is switched by the player.

I have seen this occur with other heroes in the past, but to reproduce with Kroak:
1. Play as Gor-Rok, Itza
2. Embed Kroak in Gor-Rok's army and select Replenish Troops. (You should now see Replenish troops as a status affecting the army)
3. Fight battles until Kroak levels up.
4. Add the skill point to his Replenish Troops ability. 
5. The army will now be affected by the Training status instead of Replenish Troops.

**Comment by Harmandodelavega** [comment]
#933
