### ISSUE TITLE
Regular Desynchs in Coop Multiplayer under Last Community Bug Fix Mod Update [May 5 at 6:01 AM]

### ISSUE THREAD

**Issue by KIaxons** [chadvandy/cbfm_wh3#985]
**Describe the bug**
We tried to skip first turn in new IE campaign but every time got desynched at about 64 faction. It starts to happen right after last Community Bug Fix Mod update and the only way to prevent it is to turn off the mod. We had no such problem with similar campaigns with this mod On before last update.

**Expected behavior**
Turn should be pass on correctly.

**To Reproduce**
1. Play as Boris Bokha (Kislev) and Miao Ying (Grand Cathay) in coop IE campaign
2. Skip first turn

**Additional context**
No matter what we do, the problem are the same. Loading autosave before skip don't help.

**Comment by mfvreeland** [comment]
@KIaxons 
Try running with this version. It will disable the event feed fix for multiplayer games, which is the only thing that I can think of that could be causing a problem:
[cbfm_wh3_mp_test.zip](https://github.com/chadvandy/cbfm_wh3/files/11422752/cbfm_wh3_mp_test.zip)

**Comment by mfvreeland** [comment]
@KIaxons 
Glad to hear it. I am not sure how the event feed fix could have been causing your desyncs, but it seems it was somehow the culprit. I will keep investigating this, but in the meantime, feel free to keep using the version I dropped here.

**Comment by KIaxons** [comment]
> @KIaxons Glad to hear it. I am not sure how the event feed fix could have been causing your desyncs, but it seems it was somehow the culprit. I will keep investigating this, but in the meantime, feel free to keep using the version I dropped here.

May it cause any troubles with todays 3.0.1?

**Comment by mfvreeland** [comment]
> May it cause any troubles with todays 3.0.1?
It shouldn't, no. The changes they made in 3.0.1 all seem to be on the hardware performance front. Mod compatibility doesn't seem to be affected at all.
