### ISSUE TITLE
Kurgan armies sometimes fail to spawn on IME when attacking the Great Bastion

### ISSUE THREAD

**Issue by Frodo45127** [chadvandy/cbfm_wh3#99]
Me forgot to read the readme before making the PR, so here's the issue for it.

While debugging another mod, I found out that a few of the Kurgan spawn positions on the Great bastion on IME caused armies to fail to spawn due to them being in the middle of inpassable terrain. I suspect this is also the culprit of a rare glitch that sometimes causes the Bastion menace level to drop from 100 to 0 in one turn without any army attacking, but haven't been able to confirm it.

The broken coordinates are:
`
{1156, 670},
{1185, 676},
{1170, 691}
{1243, 695},
{1235, 694}
{1199, 695},
{1292, 679}
`

**Comment by Frodo45127** [comment]
PR with the clean fix here: #95

**Comment by Harmandodelavega** [comment]
https://github.com/chadvandy/cbfm_wh3/commit/9a0f72d7d1cff55f2069fe69e97d733265dc197b

**Comment by mfvreeland** [comment]
Possibly fixed in 4.1:

"Fixed Kurgan Warband armies sometimes spawning in impassable terrain in Immortal Empires."

**Comment by mfvreeland** [comment]
Confirmed fixed in 4.1. CA changed all of the same values that Frodo did (and none he did not), but they made slight alterations to their final values, presumably to claim *some* originality.
