### ISSUE TITLE
AI Welves spawn Ariel when you're playing non Drycha Welves

### ISSUE THREAD

**Issue by Hosenlurch** [chadvandy/cbfm_wh3#990]
Either Durthu oder Orion got Ariel automatically at the beginning of turn 20, when playing as the Twilight Sisters. There is no way that one can finish the Ritual of Rebirth before turn 20. Ariel also spawns everytime without items.

Tried it with 3 different campaigns. It does not seem to have any specific requirement for the AI faction to spawn her.
Also I noticed that Gotrek also spawns automatically at turn 10 at a non-specific possible faction, don't know if this is normal, but it could be related to this bug.
![Screenshot 2023-05-09 153148](https://github.com/chadvandy/cbfm_wh3/assets/133018000/c769ec53-d298-48e1-a394-29b004d24607)

**Comment by Harmandodelavega** [comment]
AI has different requirements to unlock many things, it's not a bug even though it may seem unfair

**Comment by Harmandodelavega** [comment]
My bad, didn't catch that you were playing Wood Elves

**Comment by Harmandodelavega** [comment]
adding this report https://forums.totalwar.com/discussion/330813/ariel-not-spawning-when-completing-the-first-ritual-of-rebirth#latest

**Comment by Drazhir2** [comment]
Found the culprit for Ariel, could not reproduce Harald.

It's one missing keyword that causes the game to create the AI listener even when a player is playing one of the welves (the angry shrubbery doesn't count):
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/9afef6b2-ecdd-4aca-8c95-fa7f14de8c2d)

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d9a95167-d668-417f-916b-52369ecd4401)

I'm afraid there's no other fix than to overwrite the whole script.

**Comment by Drazhir2** [comment]
Here is the fix, as usual rename to .pack
[zzz_cbfm_ariel_ai_spawn.patch](https://github.com/chadvandy/cbfm_wh3/files/12045515/zzz_cbfm_ariel_ai_spawn.patch)
