### ISSUE TITLE
Characters getting stuck into each other

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#993]
"Rarely, when a character moves next to another, they will clip into the same character and be at the exact same location in the game. So you'll have 2 characters with the exact same coordinates, so they cannot move until one of them is removed."

**Comment by Bogdanov89** [comment]
I think this issue was originally mentioned in https://github.com/chadvandy/cbfm_wh3/issues/452

Where characters can also get stuck into cities and prevent any further interaction.

**Comment by Harmandodelavega** [comment]
also related to this mby https://trello.com/c/DB2qNNwd/764-heroes-respawning-on-top-of-armies-settlements-after-their-faction-re-emerges-prevent-interaction-with-both-indefinitely
