### ISSUE TITLE
Notifications for "Building upgrade available" is partially not working

### ISSUE THREAD

**Issue by poehud** [chadvandy/cbfm_wh3#999]
**Describe the bug**
The game wants to end the turn despite having building upgrades available and the resources to build them.

**Expected behavior**
Showing me every building upgrade option i am able to afford, like in the last games.

**To Reproduce**
1. Play as whatever
2. Attack region whatever
3. Build whatever
4. Experience the bug

**Screenshots**
![cey5t5sobb2r](https://github.com/chadvandy/cbfm_wh3/assets/67976764/5100c583-f734-4c45-9e08-1f13f50a3041)

**Additional context**
Not really hard to reproduce and im actually confused that even after over a year no one seems to be bothered with that. CA at it finest, as always.

**Comment by Harmandodelavega** [comment]
#57
